typescript-eslint/typescript-eslint

- .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
- .github/ISSUE_TEMPLATE/typescript-estree.md
without metadata issue templates are not going to work
demo: https://github.com/armano2/typescript-eslint/issues/new/choose
> chore: add missing metadata to issues templates

- packages/typescript-eslint-parser/package.json
- packages/typescript-eslint-parser/src/analyze-scope.ts
- packages/typescript-eslint-parser/src/typings.d.ts
- packages/typescript-eslint-parser/tests/lib/basics.ts
- packages/typescript-eslint-parser/tests/lib/scope-analysis.ts
- yarn.lock
Not all of types are resolved a lot of properties has type any
@types/estree should be replaced with definition from `typescript-estree`, but i didn't finish it yet there
> refactor(eslint-parser): add definition for eslint-scope

- package.json
- packages/eslint-plugin-tslint/package.json
- packages/typescript-eslint-parser/package.json
- packages/typescript-estree/package.json
- yarn.lock
i did some testing, and looks like on windows build is not possible now
rm command is not available in windows env
> refactor: fix issue with building project under windows

- README.md
<a href="https://travis-ci.com/typescript-eslint/typescript-eslint"><img src="https://img.shields.io/travis/com/typescript-eslint/typescript-eslint.svg?style=flat-square" alt="Travis"/></a> <a href="http://commitizen.github.io/cz-cli/"><img src="https://img.shields.io/badge/commitizen-friendly-brightgreen.svg?style=flat-square" alt="Commitizen friendly" /></a>
instead of
<a href="https://travis-ci.org/typescript-eslint/typescript-eslint"><img src="https://img.shields.io/travis/typescript-eslint/typescript-eslint.svg?style=flat-square" alt="Travis"/></a> <a href="http://commitizen.github.io/cz-cli/"><img src="https://img.shields.io/badge/commitizen-friendly-brightgreen.svg" alt="Commitizen friendly" /></a>
> chore: fix shields in readme

- .github/ISSUE_TEMPLATE/eslint-plugin-tslint.md
- .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
- .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
- .github/ISSUE_TEMPLATE/typescript-estree.md
> chore: update issue templates with labels

- README.md
✨ **[Preview README](https://github.com/typescript-eslint/typescript-eslint/blob/readme-links/README.md)** ✨
> docs: link to the packages in the repo from the README

- packages/eslint-plugin-typescript/lib/rules/class-name-casing.js
- packages/eslint-plugin-typescript/lib/rules/indent.js
- packages/eslint-plugin-typescript/tests/lib/eslint-rules/no-shadow.js
- packages/eslint-plugin-typescript/tests/lib/eslint-rules/no-undef.js
- packages/eslint-plugin-typescript/tests/lib/rules/indent.js
- packages/typescript-eslint-parser/src/analyze-scope.ts
- packages/typescript-eslint-parser/src/visitor-keys.ts
- packages/typescript-eslint-parser/tests/lib/__snapshots__/scope-analysis.ts.snap
- packages/typescript-eslint-parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/typescript-estree/src/ast-node-types.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/tests/ast-alignment/utils.ts
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
This PR changes `TSAbstractClassDeclaration` to `ClassDeclaration`
fixes: #20
> feat: update abstract class node

- packages/eslint-plugin-typescript/ROADMAP.md
- update partial support emoji
- add totals for each emoji
- format
> docs(plugin-typescript): update roadmap

- packages/eslint-plugin/lib/configs/recommended.json
- packages/eslint-plugin/lib/util.js
- packages/eslint-plugin/tools/update-recommended.js
> fix(eslint-plugin): update remaining parser refs

- packages/eslint-plugin/README.md
- packages/eslint-plugin/lib/util.js
- packages/eslint-plugin/tests/lib/rules/restrict-plus-operands.js
- packages/parser/README.md
fixes https://github.com/typescript-eslint/typescript-eslint/issues/130
> fix(eslint-plugin): make parser services error clearer

- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/shared-fixtures/fixtures/typescript/errorRecovery/decorator-on-variable.src.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
> test(ts-estree): add regression test for decorators on variables

- packages/eslint-plugin/ROADMAP.md
Replace white spaces with `<br>` html tags
#192 #194 #178 #155
> docs(eslint-plugin): replace white-spaces with <br> tag

- .vscode/launch.json
> chore: removed unnecessary path prefix from .vscode/launch.json

- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/typedefs.ts
- packages/typescript-estree/tests/ast-alignment/utils.ts
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
- fix range of FunctionExpression and typeParameters
- fix regression: move typeParameters from Property back to FunctionExpression
fixes: https://github.com/prettier/prettier/issues/5817
> feat(ts-estree): fix issues with typeParams in FunctionExpression

- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/shared-fixtures/fixtures/typescript/decorators/parameter-decorators/parameter-array-pattern-decorator.src.ts
- packages/shared-fixtures/fixtures/typescript/decorators/parameter-decorators/parameter-object-pattern-decorator.src.ts
- packages/shared-fixtures/fixtures/typescript/decorators/parameter-decorators/parameter-rest-element-decorator.src.ts
- packages/shared-fixtures/fixtures/typescript/errorRecovery/decorator-on-function.src.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/typedefs.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
- improve definition of parameters
- add missing tests for decorators
> refactor(ts-estree): improve definition of parameters

- README.md
Removed repeated 'the' in line 61.
> docs(*): Fixed typo in README.md

- packages/eslint-plugin/tests/rules/no-parameter-properties.test.ts
- packages/eslint-plugin/tests/rules/no-type-alias.test.ts
> test(eslint-plugin): add missing tests for no-type-alias and no-parameter-properties

- packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
- packages/eslint-plugin/tests/rules/array-type.test.ts
- packages/eslint-plugin/tests/rules/type-annotation-spacing.test.ts
This PR adds some missing test cases for rules
>  test(eslint-plugin): add missing test cases for rules

- packages/parser/tests/lib/__snapshots__/tsx.ts.snap
- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/shared-fixtures/fixtures/tsx/generic-jsx-opening-element.src.tsx
- packages/shared-fixtures/fixtures/typescript/errorRecovery/interface-method-readonly.src.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/node-utils.ts
- packages/typescript-estree/src/semantic-errors.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/tsx.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
This PR aims to improve coverage in ts-estree project
>  test(ts-estree): add missing test cases

- package.json
- yarn.lock
> deps(*): Update jest

- tsconfig.base.json
> chore(*): add lib to tsconfig.base.json

- packages/parser/src/visitor-keys.ts
> fix(parser): Make eslint traverse enum id

- packages/eslint-plugin/docs/rules/ban-types.md
a tiny change for example docs.
> fix: fix example grammar

- packages/eslint-plugin/package.json
- packages/parser/package.json
- packages/typescript-estree/package.json
See: https://github.com/facebook/create-react-app/issues/6834
> chore: remove peerDep on typescript

- README.md
I wrote this all in one slog, so there will be typos or opportunities for better phrasing. I will look with fresh eyes tomorrow!
> docs: intro readme

- .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
Updated some of the information to attempt to get people to submit more info with bugs
> chore: Update plugin issue template

- packages/eslint-plugin/src/configs/README.md
Just wanted to clearly document the reasoning behind the recommended config so I don't have to copy paste comments around the place...
> docs(eslint-plugin): add recommended config readme

- packages/eslint-plugin/src/index.ts
> fix(eslint-plugin): Fix exported name of eslint-recommended

- packages/experimental-utils/README.md
> docs(experimental-utils): fix table links

- package.json
> chore: removed lint and typecheck tasks from pre-push

- packages/eslint-plugin/README.md
> Add eslint:recommended to a usage example

- README.md
> docs: Fix grammar in README.md

- packages/eslint-plugin/ROADMAP.md
https://palantir.github.io/tslint/rules/no-async-without-await/
> docs(eslint-plugin) Add `no-async-without-await` to ROADMAP

- packages/eslint-plugin/src/rules/prefer-readonly.ts
- packages/eslint-plugin/tests/rules/prefer-readonly.test.ts
> fix(eslint-plugin): [prefer-readonly] TypeError when having computed member expression

- packages/eslint-plugin/docs/rules/indent.md
> docs:  invalid selectors link

- packages/eslint-plugin/package.json
Fixes #858
We forgot to unpin this version with the 2.0.0 release!
> chore(eslint-plugin): fix peer dependency

- packages/parser/README.md
> docs(parser): clarify usage with project references

- packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
> fix(eslint-plugin): [no-unnec-type-arg] undefined symbol crash

- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/shared-fixtures/fixtures/typescript/basics/class-with-optional-properties.src.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
> fix(typescript-estree): handle optional computed prop w/o type

- packages/eslint-plugin/src/rules/explicit-function-return-type.ts
- packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
> fix(eslint-plugin): [efrt] support constructor arguments

- README.md
Related: https://github.com/typescript-eslint/typescript-eslint/issues/1065.
> docs: clarify which versions of ESLint are supported

- packages/typescript-estree/src/create-program/createWatchProgram.ts
- tests/integration/fixtures/vue-sfc/.eslintrc.yml
- tests/integration/fixtures/vue-sfc/World.vue
- tests/integration/fixtures/vue-sfc/test.js.snap
- tests/integration/fixtures/vue-sfc/test.sh
- tests/integration/fixtures/vue-sfc/tsconfig.json
fix #883, vuejs/eslint-plugin-vue#970, vuejs/eslint-plugin-vue#944, mysticatea/vue-eslint-parser#55
> fix(typescript-estree): parsing error for vue sfc

- packages/eslint-plugin/src/rules/indent.ts
- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/shared-fixtures/fixtures/typescript/basics/abstract-class-with-declare-properties.src.ts
- packages/shared-fixtures/fixtures/typescript/basics/class-with-declare-properties.src.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/ts-estree/ts-estree.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/semanticInfo.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Fixes #1086 
I went with the same AST that we use for `declare const variable`.
> feat(typescript-estree): add support for declare class properties

- packages/typescript-estree/src/create-program/createDefaultProgram.ts
- packages/typescript-estree/src/create-program/createIsolatedProgram.ts
- packages/typescript-estree/src/create-program/createSourceFile.ts
- packages/typescript-estree/src/create-program/createWatchProgram.ts
- packages/typescript-estree/src/create-program/shared.ts
> fix(typescript-estree): don't use typescript's synthetic default

- packages/eslint-plugin/README.md
This makes the package name more visible.
> docs: mark package name as code

- packages/typescript-estree/src/create-program/createWatchProgram.ts
> fix(typescript-estree): hash code to reduce update frequency

- packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
> fix(eslint-plugin): [no-unnec-type-arg] throwing on call/new expr

- packages/eslint-plugin/src/rules/no-untyped-public-signature.ts
- packages/eslint-plugin/tests/rules/no-untyped-public-signature.test.ts
> fix(eslint-plugin): [no-untyped-pub-sig] constructor return

- packages/eslint-plugin/src/rules/no-dynamic-delete.ts
- packages/eslint-plugin/tests/rules/no-dynamic-delete.test.ts
> fix(eslint-plugin): [no-dynamic-delete] prevent fixing to identifiers

- packages/eslint-plugin/docs/rules/restrict-plus-operands.md
- packages/eslint-plugin/src/rules/restrict-plus-operands.ts
- packages/eslint-plugin/tests/rules/restrict-plus-operands.test.ts
> feat(eslint-plugin): [restrict-plus-operands] check +=

- .eslintrc.js
- packages/eslint-plugin-tslint/src/rules/config.ts
- packages/eslint-plugin/src/rules/array-type.ts
- packages/eslint-plugin/src/rules/camelcase.ts
- packages/eslint-plugin/src/rules/consistent-type-definitions.ts
- packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
- packages/eslint-plugin/src/rules/func-call-spacing.ts
- packages/eslint-plugin/src/rules/member-delimiter-style.ts
- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
- packages/eslint-plugin/src/rules/no-unused-vars-experimental.ts
- packages/eslint-plugin/src/rules/space-before-function-paren.ts
- packages/eslint-plugin/src/rules/type-annotation-spacing.ts
- packages/eslint-plugin/src/rules/unified-signatures.ts
- packages/eslint-plugin/src/util/types.ts
- packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
- packages/parser/src/analyze-scope.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/create-program/createWatchProgram.ts
- packages/typescript-estree/src/simple-traverse.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
> chore: turn on prefer-nullish-coalescing locally

- packages/eslint-plugin/src/rules/no-untyped-public-signature.ts
- packages/eslint-plugin/tests/rules/no-untyped-public-signature.test.ts
> fix(eslint-plugin): [no-untyped-pub-sig] ignore set return

- packages/experimental-utils/src/ts-eslint/SourceCode.ts
https://github.com/eslint/eslint/pull/12519
> feat(experimental-utils): add isSpaceBetween declaration to SourceCode

- packages/eslint-plugin/src/rules/return-await.ts
- packages/eslint-plugin/tests/rules/return-await.test.ts
> fix(eslint-plugin): [return-await] allow Any and Unknown

- packages/eslint-plugin/src/rules/no-unused-expressions.ts
- packages/eslint-plugin/tests/rules/no-unused-expressions.test.ts
- packages/typescript-estree/src/ts-estree/ts-estree.ts
> fix(eslint-plugin): [no-unused-expressions] ignore directives

- packages/eslint-plugin/src/rules/type-annotation-spacing.ts
Very minor, so didn't bother raising an issue
> fix(eslint-plugin): [type-annotation-spacing] typo in messages

- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/shared-fixtures/fixtures/typescript/basics/abstract-class-with-abstract-static-constructor.src.ts
- packages/shared-fixtures/fixtures/typescript/basics/interface-with-all-property-types.src.ts
- packages/shared-fixtures/fixtures/typescript/errorRecovery/interface-with-optional-index-signature.src.ts
- packages/shared-fixtures/fixtures/typescript/types/mapped-untypped.src.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
- packages/typescript-estree/tests/lib/convert.ts
This PR adds few test cases for uncovered code in ts-estree,
> test(typescript-estree): add test cases for uncovered syntax

- packages/typescript-estree/tests/lib/__snapshots__/parse.ts.snap
- packages/typescript-estree/tests/lib/parse.ts
This is follow up PR that adds test cases for changes introduced in #963
> test(typescript-estree): add test cases for extraFileExtensions

- packages/eslint-plugin/src/configs/eslint-recommended.ts
There's an eslint rule for that...
> chore(eslint-plugin): add space in comment

- packages/eslint-plugin/docs/rules/explicit-member-accessibility.md
> docs(eslint-plugin): explicit-member-accessibility

- packages/typescript-estree/tests/lib/persistentParse.ts
Tests for #1394
Also adjusted the nested tests so that they join the path instead of using hardcoded slashes, just to make sure the tests work on windows.
> test(typescript-estree): add more persistentParse tests

- packages/eslint-plugin/docs/rules/naming-convention.md
> docs(eslint-plugin): Fix misspelled [naming-convention] rule name

- azure-pipelines.yml
This PR adds execution of tests for node 12
> test: update azure pipelines to run tests on node 12

- packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
> fix(eslint-plugin): fix property access on undefined error

- CONTRIBUTING.md
> docs: extra 'a' in CONTRIBUTING.md

- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/tests/lib/convert.ts
This PR fixes regression for prettier introduced in #1525
unblocks prettier/prettier#7463
> fix(typescript-estree): fix regression introduced in #1525

- packages/eslint-plugin-internal/jest.config.js
- packages/eslint-plugin-tslint/jest.config.js
- packages/eslint-plugin/jest.config.js
- packages/experimental-utils/jest.config.js
- packages/parser/jest.config.js
- packages/typescript-estree/jest.config.js
> test: enable `isolatedModules` for tests

- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
> fix(eslint-plugin): [embt] ignore JSX callbacks

- packages/eslint-plugin/docs/rules/consistent-type-assertions.md
Resolves https://github.com/typescript-eslint/typescript-eslint/issues/1629
> docs(eslint-plugin): [consistent-type-assertion] improve docs

- packages/eslint-plugin/docs/rules/typedef.md
- packages/eslint-plugin/src/rules/typedef.ts
- packages/eslint-plugin/tests/rules/typedef.test.ts
> feat(eslint-plugin): [typedef] add variable-declaration-ignore-function

- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/shared-fixtures/fixtures/typescript/basics/export-star-as-ns-from.src.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/ts-estree/ts-estree.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/ast-alignment/utils.ts
- packages/typescript-estree/tests/lib/__snapshots__/javascript.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
~~The ESTree representation is approved, but not yet merged.~~
It's now merged :D
https://github.com/estree/estree/pull/205
> feat(typescript-estree): support 3.8 `export * as ns`

- packages/typescript-estree/src/parser-options.ts
First introduced in https://github.com/typescript-eslint/typescript-eslint/commit/25092fdc5bd9d1bd90cf3cb8d37e420b6c2efef3#diff-77692ea88ea59620ee45bd60f573b4bcR150
> chore(typescript-estree): remove unfinished comment

- README.md
See https://github.com/typescript-eslint/typescript-eslint/issues/552#issuecomment-602818681 for context
> docs: title wording in root readme

- packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md
> docs(eslint-plugin): [prefer-readonly-parameter-types] fix invalid example

- package.json
- packages/eslint-plugin-tslint/package.json
- yarn.lock
> feat(eslint-plugin-tslint): support tslint 6

- packages/eslint-plugin/src/rules/no-unsafe-call.ts
- packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
> fix(eslint-plugin): [no-unsafe-call] fix incorrect selector

- packages/typescript-estree/src/create-program/WatchCompilerHostOfConfigFile.ts
- packages/typescript-estree/src/create-program/createWatchProgram.ts
> fix(typescript-estree): add support for extra file extensions

- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/eslint-plugin/tests/rules/unbound-method.test.ts
> fix(eslint-plugin): [unbound-method] false positive on property function initializer

- packages/eslint-plugin/src/rules/dot-notation.ts
also minor perf improvement
Fixes #1945
> fix(eslint-plugin): [dot-notation] handle missing declarations

- packages/eslint-plugin/src/configs/eslint-recommended.ts
> feat(eslint-plugin): update `eslint-recommended` set

- CHANGELOG.md
- packages/eslint-plugin-internal/CHANGELOG.md
- packages/eslint-plugin-tslint/CHANGELOG.md
- packages/eslint-plugin/CHANGELOG.md
- packages/experimental-utils/CHANGELOG.md
- packages/parser/CHANGELOG.md
- packages/shared-fixtures/CHANGELOG.md
- packages/typescript-estree/CHANGELOG.md
> chore: link GH release in changelogs

- README.md
https://github.com/typescript-eslint/typescript-eslint/pull/2057
> docs: update supported TS version in readme

- docs/getting-started/linting/FAQ.md
- docs/getting-started/linting/MONOREPO.md
- docs/getting-started/linting/README.md
- docs/getting-started/linting/TYPED_LINTING.md
- packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
- packages/eslint-plugin/docs/rules/naming-convention.md
- packages/eslint-plugin/src/configs/README.md
Closes #2069
Closes #2065
Closes #2064
Closes #2062
> docs: various updates based on v3 feedback

- packages/eslint-plugin/docs/rules/naming-convention.md
> docs(eslint-plugin): [naming-convention] improve comment text regarding ESLint's camelCase

- .github/ISSUE_TEMPLATE/config.yml
- docs/getting-started/linting/FAQ.md
- docs/getting-started/linting/TYPED_LINTING.md
Fixes #280
Fixes #561
Fixes #2112
> docs: update FAQ and add issue template config

- packages/eslint-plugin/src/rules/no-var-requires.ts
- packages/eslint-plugin/tests/rules/no-var-requires.test.ts
> fix(eslint-plugin): [no-var-requires] false negative for TSAsExpression and MemberExpression

- README.md
link to Node's releases document about node version support
> docs: add note about node support

- packages/eslint-plugin/src/rules/no-throw-literal.ts
- packages/eslint-plugin/tests/rules/no-throw-literal.test.ts
> fix(eslint-plugin): [no-throw-literal] support type assertions

- packages/eslint-plugin-tslint/package.json
Do not include all files into npm
> chore(eslint-plugin-tslint): reduce files included in npm publish

- docs/getting-started/linting/README.md
So it conforms with https://www.npmjs.com/package/eslint-config-prettier#example-configuration
> docs: adjust prettier snippet

- packages/eslint-plugin/docs/rules/no-unsafe-member-access.md
Fix good variable name : 
nestedAny --> properlyType in the correct code section
> docs(eslint-plugin): [no-unsafe-member-access] update variable naming

- packages/eslint-plugin/docs/rules/consistent-type-definitions.md
- packages/eslint-plugin/docs/rules/dot-notation.md
- packages/eslint-plugin/docs/rules/init-declarations.md
- packages/eslint-plugin/docs/rules/keyword-spacing.md
- packages/eslint-plugin/docs/rules/lines-between-class-members.md
- packages/eslint-plugin/docs/rules/no-empty-function.md
- packages/eslint-plugin/docs/rules/no-implied-eval.md
- packages/eslint-plugin/docs/rules/no-invalid-this.md
- packages/eslint-plugin/docs/rules/no-loop-func.md
- packages/eslint-plugin/docs/rules/no-throw-literal.md
- packages/eslint-plugin/src/configs/README.md
> docs(eslint-plugin): missing info how to use sections, cjson -> jsonc

- packages/eslint-plugin/docs/rules/explicit-member-accessibility.md
Hi there. Added an example because I had a bit of trouble with it.
> docs(eslint-plugin): [explicit-member-accessibility] Add an example

- packages/eslint-plugin/src/rules/no-throw-literal.ts
- packages/eslint-plugin/tests/rules/no-throw-literal.test.ts
> fix(eslint-plugin): [no-throw-literal] false positive with logical expressions

- packages/parser/src/index.ts
- packages/parser/src/parser-options.ts
- packages/parser/tests/lib/services.ts
- packages/parser/tests/tools/test-utils.ts
Hi there, I've tried to minor refine the codebase.
> chore(parser): clean up some unused code

- packages/eslint-plugin/src/rules/no-misused-promises.ts
- packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
> fix(eslint-plugin): [no-misused-promises] False negative in LogicalExpression

- packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
- packages/eslint-plugin/tests/rules/prefer-string-starts-ends-with.test.ts
> fix(eslint-plugin): [prefer-string-starts-ends-with] Check negative indices in the second position for slice

- packages/eslint-plugin/tests/eslint-rules/prefer-const.test.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
- packages/scope-manager/src/referencer/Referencer.ts
- packages/scope-manager/tests/fixtures/type-assertion/assignment/angle-bracket-assignment.ts
- packages/scope-manager/tests/fixtures/type-assertion/assignment/angle-bracket-assignment.ts.shot
- packages/scope-manager/tests/fixtures/type-assertion/assignment/as-assignment.ts
- packages/scope-manager/tests/fixtures/type-assertion/assignment/as-assignment.ts.shot
- packages/scope-manager/tests/fixtures/type-assertion/assignment/non-null-assignment.ts
- packages/scope-manager/tests/fixtures/type-assertion/assignment/non-null-assignment.ts.shot
> fix(scope-manager): fix assertion assignments not being marked as write references

- packages/scope-manager/jest.config.js
- packages/types/jest.config.js
- packages/typescript-estree/jest.config.js
- packages/visitor-keys/jest.config.js
testRegex is wrong in some packages on windows. Similar to this https://github.com/facebook/jest/issues/7914.
> test: fix jest config on windows

- packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts
- packages/eslint-plugin/tests/rules/non-nullable-type-assertion-style.test.ts
> fix(eslint-plugin): [non-nullable-type-assertion-style] handle const assertion

- packages/parser/README.md
> docs(parser): clarify `ecmaVersion` usage

- packages/shared-fixtures/fixtures/typescript/basics/union-intersection.src.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
- packages/typescript-estree/tests/snapshots/typescript/basics/union-intersection.src.ts.shot
add missing test for union and intersection with leading character
> test(typescript-estree): add missing test for union and intersection

- package.json
- packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
- packages/eslint-plugin/src/rules/naming-convention-utils/format.ts
- packages/eslint-plugin/src/rules/semi.ts
- packages/eslint-plugin/src/util/index.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
- packages/eslint-plugin/tests/rules/no-empty-function.test.ts
- packages/experimental-utils/src/ts-eslint/Rule.ts
- yarn.lock
manual update as #3028 is failing
> chore: bump prettier from 2.1.1 to 2.2.1

- .all-contributorsrc
- CONTRIBUTORS.md
This PR includes changes generated by `npm run generate:contributors` which updates `CONTRIBUTORS.md`
> docs: update contributors

- .codecov.yml
- .github/workflows/ci.yml
Update codecov to not wait for all ci to report its status, this should fix issue with 
> Expected — Waiting for status to be reported
> chore: update codecov configuration

- packages/eslint-plugin/src/rules/no-implied-eval.ts
- packages/eslint-plugin/tests/rules/no-implied-eval.test.ts
> fix(eslint-plugin): [no-implied-eval] handle conditional expression

- packages/typescript-estree/src/parser.ts
Ref: https://github.com/typescript-eslint/typescript-eslint/pull/3112#issuecomment-788200742
> fix(typescript-estree): update TS version range

- .huskyrc
> chore: remove husky 4 config

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
> fix(eslint-plugin): [no-unnecessary-type-assertion] correct bad fix for angle bracket assertion

- .github/workflows/generate-contributors.yml
related to https://github.com/typescript-eslint/typescript-eslint/pull/3064#pullrequestreview-591578479
> ci: generate contributors automatically monthly

- .eslintrc.js
- packages/typescript-estree/tests/ast-alignment/parse.ts
- packages/typescript-estree/tests/ast-alignment/utils.ts
> chore: enable restrict-plus-operands internally

- packages/eslint-plugin/docs/rules/prefer-regexp-exec.md
> docs(eslint-plugin): update justification for `prefer-regexp-exec`

- README.md
- package.json
- packages/eslint-plugin/src/rules/dot-notation.ts
- packages/typescript-estree/package.json
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tests/ast-alignment/utils.ts
- packages/typescript-estree/tests/lib/__snapshots__/convert.test.ts.snap
- packages/typescript-estree/tests/lib/convert.test.ts
- packages/typescript-estree/tests/snapshots/jsx/namespace-this-name.src.js.shot
- packages/typescript-estree/tests/snapshots/typescript/errorRecovery/enum-with-keywords.src.ts.shot
- yarn.lock
> chore: update typescript to 4.3-rc

- packages/typescript-estree/tests/ast-alignment/utils.ts
> test(typescript-estree): fix alignment tests

- packages/typescript-estree/package.json
- packages/typescript-estree/tests/ast-alignment/utils.ts
- yarn.lock
https://github.com/babel/babel/pull/13354 has been released
> test(typescript-estree): remove transform for TSTypePredicate

- package.json
- yarn.lock
Update to TypeScript 4.3.2 (not rc!)
> chore: update to typescript 4.3

- packages/scope-manager/src/lib/dom.iterable.ts
- packages/scope-manager/src/lib/dom.ts
- packages/scope-manager/src/lib/es2021.full.ts
- packages/scope-manager/src/lib/es2021.promise.ts
- packages/scope-manager/src/lib/es2021.string.ts
- packages/scope-manager/src/lib/es2021.ts
- packages/scope-manager/src/lib/es2021.weakref.ts
- packages/scope-manager/src/lib/index.ts
- packages/scope-manager/src/lib/webworker.ts
- packages/types/src/lib.ts
- packages/typescript-estree/src/node-utils.ts
Forgot to regenerate these.
Fixes #3449
> fix: generate library types for TypeScript v4.3

- packages/eslint-plugin/src/util/createRule.ts
> fix(eslint-plugin): fix doc url generation

- packages/experimental-utils/src/ast-utils/eslint-utils/predicates.ts
Extracted the `IsPunctuatorTokenWithValueFunction` generic to get rid of all duplicates
> refactor(experimental-utils): simplify `eslint-utils`' predicate types in `ast-utils`

- packages/experimental-utils/src/ast-utils/eslint-utils/scopeAnalysis.ts
https://eslint-utils.mysticatea.dev/api/scope-utils.html#findvariable
> fix(experimental-utils): simplify `eslint-utils`' `findVariable`'s signature in `ast-utils`

- packages/experimental-utils/src/ts-eslint/Rule.ts
These were left over from #3560
> chore(experimental-utils): remove commented out `RuleListener`s

- .github/workflows/ci.yml
@JamesHenry - IIRC this will need your intervention to ensure the first release actually pushes.
> chore: add auto-canary release for v5

- packages/visitor-keys/src/visitor-keys.ts
~~*This PR is for version 5.*~~
I noticed that didn't have StaticBlock visitor keys so I added it.
> fix(visitor-keys): add key to StaticBlock

- packages/eslint-plugin/src/rules/prefer-reduce-type-parameter.ts
- packages/eslint-plugin/tests/rules/prefer-reduce-type-parameter.test.ts
> fix(eslint-plugin): [prefer-reduce-type-parameter] handle already existing type params

- packages/typescript-estree/README.md
> docs(typescript-estree): fix plural name for parserOptions.programs option

- packages/eslint-plugin/src/rules/no-meaningless-void-operator.ts
- packages/eslint-plugin/src/rules/padding-line-between-statements.ts
Fixes CI
https://github.com/typescript-eslint/typescript-eslint/runs/3508798755
> fix(eslint-plugin): update new rules from master

- packages/eslint-plugin/src/rules/no-var-requires.ts
- packages/eslint-plugin/tests/rules/no-var-requires.test.ts
> fix(eslint-plugin): [no-var-requires] report problems within `NewExpression`

- packages/eslint-plugin/docs/rules/no-misused-promises.md
> docs(eslint-plugin): [no-misused-promises] improve examples

- packages/eslint-plugin/src/rules/prefer-return-this-type.ts
- packages/eslint-plugin/tests/rules/prefer-return-this-type.test.ts
> fix(eslint-plugin): [prefer-return-this-type] handle generics properly in fixer

- packages/website/README.md
> chore(website): update deployment section of README

- packages/eslint-plugin/docs/rules/padding-line-between-statements.md
-   [x] Addresses an existing issue: fixes #4091 
Added a note clarifying that some ESLint options are renamed.
> docs(eslint-plugin): [padding-line-between-statements] clarify accepted options

- package.json
disable website build after each `yarn i`
> chore: disable website build after install

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation-request.md
- .github/ISSUE_TEMPLATE/eslint-plugin-tslint.md
- .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
- .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
- .github/ISSUE_TEMPLATE/typescript-eslint-scope-manager.md
- .github/ISSUE_TEMPLATE/typescript-eslint-utils.md
- .github/ISSUE_TEMPLATE/typescript-estree.md
- CONTRIBUTING.md
- packages/eslint-plugin/README.md
- packages/parser/README.md
- packages/scope-manager/README.md
- packages/typescript-estree/README.md
> docs: fix links

- packages/scope-manager/src/ScopeManager.ts
- packages/scope-manager/src/scope/ClassStaticBlockScope.ts
- packages/scope-manager/src/scope/Scope.ts
- packages/scope-manager/src/scope/ScopeBase.ts
- packages/scope-manager/src/scope/ScopeType.ts
-   [x] Addresses an existing issue: fixes #4120
Created a new Scope Type and added it to the ScopeManager
> fix(scope-manager): support static class blocks

- packages/eslint-plugin/src/rules/prefer-for-of.ts
- packages/eslint-plugin/tests/rules/prefer-for-of.test.ts
-   [x] Addresses an existing issue: fixes #4175
> fix(eslint-plugin): [prefer-for-of] do nor error when iterating over this

- commitlint.config.js
- package.json
- yarn.lock
-   [ ] ~Addresses an existing issue: fixes #000~
-   [ ] ~That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)~
Use `workspace.json` as source of truth for commitlint scopes
> chore: simplify commitlint config and remove unused package

- packages/eslint-plugin/src/rules/semi.ts
- packages/eslint-plugin/tests/rules/semi.test.ts
-   [x] Addresses an existing issue: fixes #4317
fixes #4317
> fix(eslint-plugin): handle method overloading in `semi`

- packages/experimental-utils/package.json
-   [ ] Addresses an existing issue
makes it work with npm install -strict-peer-deps=true
> chore(experimental-utils): sync peer eslint dependency with eslint-plugin

- docs/development/CUSTOM_RULES.md
-   [ ] ~Addresses an existing issue: fixes #000~
-   [ ] ~That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)~
Fix missing comma in the testing custom rule code example.
> docs(website): add comma in testing custom rule

- docs/development/architecture/ASTS.md
- packages/eslint-plugin/docs/rules/README.md
- packages/eslint-plugin/docs/rules/naming-convention.md
- packages/eslint-plugin/docs/rules/prefer-readonly.md
- packages/eslint-plugin/docs/rules/unbound-method.md
-   [ ] Addresses an existing issue: fixes #0
Make the TOC more consistent and easier to navigate
> docs(website): fix heading level inconsistencies

- packages/website/package.json
- packages/website/src/components/config/ConfigEditor.tsx
- yarn.lock
use json5 library to parse config in playground
this allows users to provide js like structures that are not fully complaint with JSON
> docs(website): use json5 library to parse config in playground

- packages/website/src/components/ASTViewerTS.tsx
- packages/website/src/components/ast/ASTViewer.tsx
- packages/website/src/components/ast/Elements.tsx
- packages/website/src/components/ast/SimpleItem.tsx
- packages/website/src/components/ast/serializer/serializer.ts
- packages/website/src/components/ast/serializer/serializerTS.ts
- packages/website/src/components/ast/types.ts
correct potential infinite loop in ts ast viewer when used with rule that requires type information
[before fix](https://typescript-eslint.io/play/#ts=4.5.2&sourceType=module&showAST=ts&code=C4TwDgpgBAsiAq4IB54D4oF4rwNwFgAoIA&rules=N4IgAgLgngDgpgZwMYCcCWMIFpEBs0B2EA9DCnAGZwpbkCGAJgPYG5RYx0p0C2cE1LNHgIQALhDUUTFCAC+QA&tsConfig=N4XyA) 
[after fix](https://deploy-preview-4354--typescript-eslint.netlify.app/play/#ts=4.5.2&sourceType=module&showAST=ts&code=C4TwDg …
> docs(website): correct potential infinite loop in ts ast viewer

- docs/linting/TROUBLESHOOTING.md
-   [x] Addresses an existing issue: fixes #2611
Adds a mention of the performance issues with `**` with a link to the issue.
> docs: mention deep globs in ESLint options in troubleshooting

- CONTRIBUTING.md
-   [x] Addresses an existing issue: fixes #4363
Mentions the very nice `.vscode/launch.json` tasks already checked in.
> docs: mention VS Code debugging tasks in CONTRIBUTING.md

- README.md
In particular, this falls under
> With the exception of extremely minor documentation typos, only send pull requests that resolve open issues.
This fixes a typo in the license section in `README.md`.
> docs: fix typo in license section in README.md

- package.json
- packages/website/data/sponsors.json
- packages/website/src/components/FinancialContributors.module.css
- packages/website/src/components/FinancialContributors.tsx
- packages/website/src/pages/index.tsx
- packages/website/src/pages/styles.module.css
- tools/generate-contributors.ts
- tools/generate-sponsors.ts
- tools/generate-website-dts.ts
- yarn.lock
-   [x] Addresses an existing issue: fixes #4370
* Adds explicit `h3`s with paragraph descriptions for each of the tiers
* Mostly clarifies the terminology: "financial contributor" is split into "sponsors" and "supporters".
* Increases the size of sponsors and gives them a text title
<table>
<thead>
<tr>
<th>500px width</th>
<th>1000px width</th>
<th>1500px width</th>
</tr>
</thead>
<tbody>
<tr>
<td><img alt="Mobile screenshot showing a narrow column of sections" …
> docs: re-ran generate-sponsors and expanded homepage listing

- .github/ISSUE_TEMPLATE/typescript-eslint-type-utils.md
-   [x] Addresses an existing issue: fixes #4424
Removes the duplicate line.
Thanks for pointing this out @RebeccaStevens 😄
> docs(type-utils): remove duplicate line from issue template

- packages/eslint-plugin/src/rules/no-magic-numbers.ts
- packages/eslint-plugin/tests/rules/no-magic-numbers.test.ts
> fix(eslint-plugin): [no-magic-numbers] handle bigint in class props

- packages/type-utils/tests/isTypeReadonly.test.ts
This PR fixes tests that failed due to conflicts.
> test(type-utils): fix incorrect utils import

- .github/workflows/update-sponsors.yml
-   [x] Addresses an existing issue: fixes #4370
Adds a daily cron job on in GHA on the `main` branch that runs `generate-sponsors` and commits changes if they exist.
> chore(website): added cron job to update sponsors data daily

- .github/pull_request_template.md
-   [x] Addresses an existing issue: fixes #4010
Makes the PR template _very clear_ that you _must_ have an associated issue.
> docs: explicitly ask for PR template checklist being true and checked

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/generate-contributors.yml
- .github/workflows/update-sponsors.yml
I also added it to the @dependabot config, so the repo will get automatic PRs for it too.
> chore: update workflow actions

- .eslintignore
- .gitignore
- nx.json
- package.json
- packages/types/package.json
- packages/types/src/index.ts
- packages/types/src/ts-estree.ts
- packages/types/tools/copy-ast-spec.ts
- packages/typescript-estree/src/convert.ts
> chore: refactor nx target graph to better include ast-spec copy

- packages/website/data/sponsors.json
> chore: update sponsors

- .github/workflows/update-sponsors.yml
https://crontab.guru/#0_0_*_*_1
> chore: change update-sponsors.yml to weekly

- docs/README.md
Removed an obsolete "the" from the readme/start page.
> docs: remove duplicate "the"

- docs/development/CUSTOM_RULES.md
-   [x] Addresses an existing issue: fixes #4721 
> docs: use valid rule config in the custom rule example

- packages/shared-fixtures/fixtures/typescript/basics/never-type-param.src.ts
- packages/shared-fixtures/fixtures/typescript/types/constructor-abstract.src.ts
- packages/shared-fixtures/fixtures/typescript/types/constructor-empty.src.ts
- packages/typescript-estree/package.json
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/ast-alignment/utils.ts
- packages/typescript-estree/tests/snapshots/typescript/basics/never-type-param.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/types/constructor-abstract.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/types/constructor-empty.src.ts.shot
- yarn.lock
this change is required for merge of #4692
> test: update babel alignment tests to latest version

- packages/eslint-plugin/CHANGELOG.md
- packages/eslint-plugin/docs/rules/consistent-type-exports.md
-   [v] Addresses an existing issue: fixes #4769 
-   [v] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [v] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken
I remove duplicate exports in the "correct" example for fixMixedExportsWithInlineTypeSpecifier. and I add about 'isolatedModules' to "When Not To Use It".
I wish reviewers check to see if it has been modified to fit the context.
> docs(eslint-plugin):improve docs [consistent-type-exports]

- packages/website/src/components/editor/useSandboxServices.ts
-   [x] Addresses an existing open issue: fixes #4869
> docs(website): correct theme color blink when playground is initialized

- packages/eslint-plugin/docs/rules/member-ordering.md
> docs(member-ordering): Rename no-non-null-assertion to member-ordering

- .markdownlint.json
- docs/linting/README.md
-   [x] Addresses an existing open issue: fixes #4902
This is, AFAICT, all the required changes to make ESLint work out-of-the-box on most projects.
> docs: improve linting getting started guide

- packages/eslint-plugin/docs/rules/parameter-properties.md
-   [x] Addresses an existing open issue: fixes #4878
Continue correcting the document according to #4878, #4879.
- `allows` => `allow`
- `parameter-properties` => `parameter-property`
> docs(eslint-plugin): [parameter-properties] improve docs

- .eslintrc.js
- packages/eslint-plugin/src/rules/no-unsafe-argument.ts
- packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/scope-manager/src/ScopeManager.ts
- packages/scope-manager/src/scope/ScopeBase.ts
- packages/scope-manager/src/scope/WithScope.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/node-utils.ts
- packages/typescript-estree/tests/ast-alignment/utils.ts
More concise syntax, dogfooding of the rule, and occasionally use `.forEach`/`.find` over for loops.
> chore: enable prefer-for-of rule internally

- .github/workflows/lock.yml
-   [x] Addresses an existing open issue: fixes #000
change missed while upgrading package, #4643, 
see https://github.com/dessant/lock-threads/blob/master/CHANGELOG.md#300-2021-09-27
https://github.com/typescript-eslint/typescript-eslint/actions/runs/2364718121
> chore: fix lock workflow after update

- packages/website/data/sponsors.json
- packages/website/src/components/FinancialContributors/Sponsors/styles.module.css
- tools/generate-sponsors.ts
-   [x] Addresses an existing open issue: fixes #4758 _(again)_
Puts a minimum on the two lower tiers that `totalDonations` must be at least two donations worth at the tier. Also blocks one more site we're pretty sure is spamming.
Further step on top of #4757.
> chore(website): require two donations at lower tiers

- .github/ISSUE_TEMPLATE/6-bug-report-other.yaml
- .github/ISSUE_TEMPLATE/7-enhancement-other.yaml
> chore: add website as an "other" package for issue forms

- package.json
- packages/typescript-estree/src/parser.ts
- yarn.lock
-   [x] Addresses an existing open issue: fixes #4800 
TS 4.7 has been released :tada:
https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/
> feat: bump dependency ranges to TypeScript 4.7

- .github/actions/prepare-install/action.yml
- .github/workflows/ci.yml
-   [x] Addresses an existing open issue: fix #4739
> test: fix Cypress test flakes

- packages/website/package.json
- yarn.lock
This upgrade will also fix the bug mentioned in https://github.com/typescript-eslint/typescript-eslint/pull/5085#discussion_r883286088, so that workaround is not necessary.
> chore: upgrade Docusaurus

- packages/website-eslint/package.json
- packages/website-eslint/rollup.config.js
- packages/website/webpack.plugin.js
- yarn.lock
-   [x] Addresses an existing open issue: fixes #5077
> chore(website): ship source maps for playground

- .github/ISSUE_TEMPLATE/1-bug-report-plugin.yaml
- .github/ISSUE_TEMPLATE/6-bug-report-other.yaml
-   [x] Addresses an existing open issue: fixes #5122
> chore: add note about minimal configs to bug report forms

- docs/linting/troubleshooting/FORMATTING.md
-   [x] Addresses an existing open issue: fixes #5383
Mentions and suggests using [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier).
Borrows a bit of phrasing from https://github.com/typescript-eslint/tslint-to-eslint-config/blob/a42a0874a09c0f156f10ea2ffd8b15f87ca712ea/docs/FAQs.md?plain=1#L40.
> chore(website): mention eslint-config-prettier in FORMATTING.md

- packages/website/src/components/ErrorsViewer.tsx
- packages/website/src/components/Playground.tsx
- packages/website/src/components/editor/LoadedEditor.tsx
- packages/website/src/components/editor/types.ts
> chore(website): surface internal errors in playground

- tools/generate-sponsors.ts
Per discussion following #5440.
> chore(website): add a 'good conscience' exclusion list to sponsors

- packages/eslint-plugin/docs/rules/no-duplicate-enum-values.md
Fix syntax error on second enum example
> docs: no-duplicate-enum-values missing comma

- .prettierignore
- package.json
- packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
- packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
- packages/scope-manager/tests/fixtures/instantiation-expressions/type-arguments1.ts
- tests/integration/fixtures/vue-sfc/Hello.vue
- tests/integration/tests/__snapshots__/vue-sfc.test.ts.snap
- yarn.lock
- ~[ ] Addresses an existing open issue: fixes #000~
- ~[ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)~
Splitting changes out of #5377.
Co-authored-by: @Josh-Cena
> chore: bump Prettier to 2.7

- docs/linting/TYPED_LINTING.md
Fixed typo in TYPED_LINTING.md 
Changed
`Some typescript-eslint rules tap utilize the awesome power`
to
`Some typescript-eslint rules utilize the awesome power`
> fix(eslint-plugin) : Typo in TYPED_LINTING.md

- packages/website/plugins/generated-rule-docs.ts
Adds a `## Resources` section at the bottom of each rule page. This mirrors the ESLint core website's rules sections (example: https://eslint.org/docs/latest/rules/array-callback-return#resources).
> chore(website): generated rule Resources with source links

- packages/website/sidebars/sidebar.base.js
- packages/website/sidebars/sidebar.rules.js
> feat(docs): always expanding collapsible sidebar menus under docs

- .github/replies.yml
Adds a first auto-reply based on https://github.com/typescript-eslint/typescript-eslint/issues/5538#issuecomment-1226118930.
> chore: add .github/replies.yml

- docs/development/CUSTOM_RULES.md
Updates the rule example to use `createRule` the way the rest of the file does.
fyi @vkarpov15
> chore(website): update outdated custom rule example

- docs/linting/typed-linting/MONOREPOS.md
- add description of resolution order of parserOptions.project
> docs: add description of resolution order of parserOptions.project

- packages/parser/tsconfig.build.json
- packages/parser/tsconfig.json
> chore: remove erroneous project reference from parser to utils

- packages/website/package.json
- yarn.lock
#5743 bumped this but for some reason the netlify build didn't fail... 🤔
unbump it to fix the build
> chore: downgrade `@docusaurus/plugin-pwa` to match the current `@docusaurus/core` version

- .github/SPONSORSHIPS.md
- packages/website/src/components/FinancialContributors/index.tsx
- packages/website/src/components/FinancialContributors/styles.module.css
Adds a `SPONSORSHIPS.md` that:
* Advertises why one would want to sponsor us
* Explains our guidelines for inclusion, per #5504
Also links to it on typescript-eslint.io.
> docs: add .github/SPONSORSHIPS.md

- packages/website/src/components/FinancialContributors/index.tsx
_Sigh_ I renamed the file without editing the link href.
> chore(website): fix renamed Sponsorship docs link

- packages/parser/src/parser.ts
- packages/parser/tests/lib/parser.ts
- packages/scope-manager/README.md
- packages/scope-manager/src/ScopeManager.ts
- packages/scope-manager/src/analyze.ts
- packages/scope-manager/src/referencer/Referencer.ts
- packages/scope-manager/tests/eslint-scope/get-declared-variables.test.ts
- packages/scope-manager/tests/eslint-scope/implied-strict.test.ts
- packages/scope-manager/tests/eslint-scope/map-ecma-version.test.ts
- packages/scope-manager/tests/fixtures.test.ts
- packages/website/src/components/linter/WebLinter.ts
Reverts typescript-eslint/typescript-eslint#5881
> Revert "feat(scope-manager): ignore ECMA version"

- packages/website/.eslintrc.js
> fix(eslint-plugin): enable react/jsx-curly-brace-presence lint rule in website package

- packages/eslint-plugin/docs/rules/consistent-type-imports.md
Makes a note about the required config in the rule's docs so that it's clearer for users.
> docs(eslint-plugin): [consistent-type-imports] make a note about `parserOptions.emitDecoratorMetadata`

- packages/eslint-plugin/docs/rules/naming-convention.md
This pr alphabetizes inline lists for naming convention rules
> docs(naming-conventions): Alphabetizing inline lists

- .github/workflows/lock.yml
Reduces the period of time before resolved issues & PRs are locked from 30 days to 7.
_Seven days!_ 😱
> chore: reduce issue+pr lock delay to 7 days

- packages/eslint-plugin/docs/rules/no-shadow.md
High time I documented this - I kept on forgetting to add it.
> docs(eslint-plugin): [no-shadow] add FAQ about enum members

- packages/eslint-plugin/docs/rules/consistent-indexed-object-style.md
> chore(eslint-plugin): fix odd consistent-indexed-object-style docs phrasing

- docs/development/architecture/PACKAGES.md
Reverts typescript-eslint/typescript-eslint#5976
> chore(website): revert "chore(website): fix TSLint.md link casing in PACKAGES.md"

- packages/ast-spec/project.json
_ignore the first few commits as I make them - I'm reporting bugs to Nx ;)_
> chore(ast-spec): fix Nx build caching

- DEVELOPMENT.md
- README.md
Mentions our canary release 
Also fixes a URL typo I'd left in in `DEVELOPMENT.md`.
> docs: mention main/canary url in README.md

- packages/eslint-plugin/src/configs/eslint-recommended.ts
Fix incorrect TS error codes in comments.
> chore(eslint-plugin): valid typescript error code in eslint-recommended

- docs/maintenance/ISSUES.md
- docs/maintenance/issues/Rule_Deprecations.md
- packages/website/sidebars/sidebar.base.js
Summarizes how to describe motivations for deprecating a rule & timelines to do so. Uses #6036 as a reference.
> docs: add Rule Deprecations page

- packages/website/src/components/FinancialContributors/index.tsx
Small grammar mistake from https://github.com/typescript-eslint/typescript-eslint/pull/6147/files#diff-1a40b97aa6d629b888e9e63da0897f2ae174abf155ba27e20818c8b713a4ae22
> docs: fix contributors spelling

- docs/linting/CONFIGURATIONS.mdx
- Unnecessary, IMO.  I'm happy to open one if y'all would like.
- N/A: no issue opened
- There aren't exactly steps in there.  I skimmed/read the CoC.
I fixed a typo.
Before:
After:
(I edited my browser HTML for this screenshot.  I don't know if the docs are backed by a server, or built in CI, or if I need to run a manual build.)
> fix(website): fix typo

- packages/typescript-estree/src/create-program/createProjectProgram.ts
- packages/typescript-estree/tests/lib/__snapshots__/parse.test.ts.snap
Fixes a minor typo of `##` in FAQ link to `#`
> fix(typescript-estree): fix typo in FAQ link

- packages/website/src/pages/index.tsx
> chore(website): fix invalid markup

- packages/eslint-plugin/README.md
Bad copypasta on my part in #6138...
> docs(eslint-plugin): corrected eslint-plugin README.md getting started link

- docs/architecture/Parser.mdx
- docs/linting/Typed_Linting.md
Explains the option per https://github.com/typescript-eslint/typescript-eslint/pull/6084#discussion_r1046597067.
> docs: explained tsconfigRootDir in website

- .cspell.json
- docs/contributing/Discussions.md
- docs/maintenance/ISSUES.md
- packages/website/sidebars/sidebar.base.js
Explains when & why to use discussions - and why not.
> docs: added Contributing > Discussions page

- docs/contributing/Issues.mdx
- docs/contributing/Pull_Requests.mdx
Mentions 3 months of blockage as an exception to our _don't ping_ rule.
> chore(website): mention 3 months SLA for issue and PR questions

- .github/workflows/ci.yml
Switches `ci.yml` to use `matrix.node-version`, as suggested in https://github.com/typescript-eslint/typescript-eslint/issues/6396#issuecomment-1410354653.
Co-authored-by: @bradzacher
> chore: test on Node 14

- packages/website/src/components/ErrorsViewer.tsx
- packages/website/src/components/FinancialContributors/Sponsor.tsx
- packages/website/src/components/ast/PropertyName.tsx
- packages/website/src/theme/MDXComponents/RuleAttributes.tsx
- packages/website/src/theme/MDXComponents/TryInPlayground.tsx
Using `<Link>` allows us to check for broken links during production build.
> chore(website): use Docusaurus Link component, fix broken link

- .gitignore
- packages/typescript-estree/src/clear-caches.ts
- packages/typescript-estree/src/index.ts
- packages/typescript-estree/src/parseSettings/createParseSettings.ts
- packages/typescript-estree/src/parseSettings/resolveProjectList.ts
Previously we exposed two separate functions and there were a few caches that weren't covered.
This PR exposes a single cache clear function that wraps up all our cache clearers for easy nuking.
> feat(typescript-estree): expose a wrapper cache clearing function for advanced usecases

- packages/website/src/components/Playground.tsx
- packages/website/src/components/editor/LoadedEditor.tsx
- packages/website/src/components/editor/types.ts
- packages/website/src/components/editor/useSandboxServices.ts
> fix(website): correct crash when switching to dark/light mode in playground

- packages/website/src/components/config/utils.ts
use default import for json5 package
> chore(website): correct build compilation warning

- packages/website/src/components/EditorTabs.tsx
- packages/website/src/components/ErrorsViewer.module.css
- packages/website/src/components/Playground.module.css
- packages/website/src/components/Playground.tsx
- packages/website/src/components/ast/ASTViewer.module.css
> chore(website): correct issues with scrollbars in playground

- packages/eslint-plugin/docs/rules/no-empty-interface.md
> docs(eslint-plugin): [no-empty-interface] correct typo in example

- .eslintrc.js
- package.json
- packages/eslint-plugin/src/rules/no-explicit-any.ts
- packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
- packages/eslint-plugin/src/rules/prefer-function-type.ts
- packages/type-utils/src/containsAllTypesByName.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tools/test-utils.ts
- yarn.lock
> chore: enable `unicorn/no-typeof-undefined` rule

- packages/utils/src/eslint-utils/rule-tester/RuleTester.ts
> chore: simplify `noFormat`

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
> feat(eslint-plugin): [no-unnecessary-cond] check logical assignments

- packages/website/blog/2023-03-13-announcing-typescript-eslint-v6-beta.md
I'd neglected to update these while the post was in PR review. But most of what it referenced as pending is now merged!
> chore(website): fixed up hourglass annotations on v6 beta announcement

- packages/eslint-plugin/src/rules/no-misused-promises.ts
- packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
Dunno how this existed for so long!
> fix(eslint-plugin): [no-misused-promises] fix incorrect detection of void functions in JSX attributes

- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/type-utils/package.json
- yarn.lock
> chore: bump ts-api-utils to v0.0.44

- .github/ISSUE_TEMPLATE/07-enhancement-other.yaml
> chore: add type-utils to "Another Package" issue template

- packages/website/.stylelintrc.json
- packages/website/package.json
- packages/website/src/components/ESQueryFilter.module.css
- packages/website/src/components/Playground.module.css
- packages/website/src/components/RulesTable/styles.module.css
- packages/website/src/components/SplitPane/SplitPane.module.css
- packages/website/src/components/config/ConfigEditor.module.css
- packages/website/src/components/inputs/Tooltip.module.css
- packages/website/src/components/layout/Expander.module.css
- packages/website/src/components/layout/Loader.module.css
- packages/website/src/css/custom.css
- packages/website/src/css/prism.css
- packages/website/src/pages/styles.module.css
- packages/website/src/theme/CodeBlock/Content/styles.module.css
- packages/website/src/theme/MDXComponents/Feature.module.css
- yarn.lock
add stylelint and apply fixes to all css files
> chore(website): add stylelint and fix css issues

- packages/ast-spec/src/type/TSMappedType/fixtures/_error_/looks-like-mapped-type-but-with-members/fixture.ts
- packages/ast-spec/src/type/TSMappedType/fixtures/_error_/looks-like-mapped-type-but-with-members/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/type/TSMappedType/fixtures/_error_/looks-like-mapped-type-but-with-members/snapshots/2-Babel-Error.shot
- packages/ast-spec/src/type/TSMappedType/fixtures/_error_/looks-like-mapped-type-but-with-members/snapshots/3-Alignment-Error.shot
- packages/ast-spec/src/type/TSMappedType/fixtures/_error_/with-member/fixture.ts
- packages/ast-spec/src/type/TSMappedType/fixtures/_error_/with-member/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/type/TSMappedType/fixtures/_error_/with-member/snapshots/2-Babel-Error.shot
- packages/ast-spec/src/type/TSMappedType/fixtures/_error_/with-member/snapshots/3-Alignment-Error.shot
- packages/typescript-estree/src/convert.ts
Ref: https://github.com/prettier/prettier/issues/14635
> feat(typescript-estree): forbid members in Mapped Type

- netlify.toml
> chore(website): correct website redirects from docs/* to /*

- .github/workflows/ci.yml
Add stylelint job in ci.yml workflow file.
PD: I was dubious whether to add fix (stylint:fix) into a matrix in the job. Let me know if I should add it and I'll make the work!
> chore(website): add stylelint job in ci

- .github/workflows/ci.yml
> chore: correct v6 stylelint action error

- packages/typescript-estree/src/convert-comments.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/node-utils.ts
> chore: simplify `getLocFor`

- docs/linting/typed-linting/Monorepos.mdx
Fix typo and make it more accessible. Not sure if I worded it correctly. Let me know and I can change it to better suit the intention. Thank you!
> docs: update monorepos typo 

- packages/eslint-plugin/docs/rules/naming-convention.md
Alphabetize lists of names in naming-convention docs page
> docs: alphabetize lists of names in naming-convention

- docs/linting/Typed_Linting.mdx
Completes sentence in https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/Typed_Linting.mdx documentation on how to turn parserOptions.project on with the suggestion from https://github.com/typescript-eslint/typescript-eslint/issues/6992.
> docs: complete sentence documenting turning on parserOptions.project 

- .cspell.json
- packages/eslint-plugin/docs/rules/restrict-template-expressions.md
> docs: be more explicit about what restrict-template-expressions restricts

- packages/eslint-plugin/package.json
This file was not included - leading to a type error.
> fix(eslint-plugin): include the rules types in the package

- .github/ISSUE_TEMPLATE/06-bug-report-other.yaml
> chore: add rule-tester package to issue report

- .github/workflows/ci.yml
- README.md
- docs/linting/Configurations.mdx
- packages/website/blog/2023-03-13-announcing-typescript-eslint-v6-beta.md
- packages/website/blog/2023-07-09-announcing-typescript-eslint-v6.md
> docs: remove v6 from docs and ci.yml

- packages/website/cypress.json
Cypress is no longer used, so removing leftover config file from repo
> chore: cypress is no longer used, remove config file

- docs/contributing/Issues.mdx
Links to one of my favorite blog posts, courtesy of https://github.com/microsoft/TypeScript/blob/a6df6c04d5dd16ecb031aba0d7499f6e9be940b6/CONTRIBUTING.md#issue-claiming.
> docs: mention lack of issue claiming system

- docs/linting/Troubleshooting.mdx
Fixes a typo in the docs ("severiy" → "severity") under Troubleshooting and FAQs > "How do I turn on a @typescript-eslint rule?"
> docs: fix typo

- packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md
Fixes the misleading documentation
> docs: fix incorrect prefer-nullish-coercing documentation

- .github/workflows/pr-review-requested.yml
Uses [`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) so that it can run on forks.
Inspired by https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/312 -> https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/632.
> chore: add pr-review-requested.yml workflow

- packages/utils/src/ts-eslint/ESLint.ts
Found these two incorrect types whilst consuming the codebase at work.
> fix(utils): [ts-eslint] small type fixes

- .eslintrc.js
- packages/eslint-plugin/src/rules/consistent-type-imports.ts
- packages/eslint-plugin/src/rules/unified-signatures.ts
- packages/rule-tester/src/utils/config-validator.ts
- packages/scope-manager/src/referencer/ClassVisitor.ts
- packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
- packages/website/src/components/config/ConfigTypeScript.tsx
Enables logical-assignment-operators rule and fixes all violations
> chore: enable logical-assignment-operators rule internally

- .github/workflows/prettier-update.yml
I tested it locally, it works fine :)
> chore: use yarn v3 syntax in prettier-update workflow

- docs/developers/Custom_Rules.mdx
The package has been renamed in the meantime - this was brought up with @JoshuaKGoldberg  over in https://github.com/JoshuaKGoldberg/ts-api-utils/issues/277
> docs: `ts-api-tools` -> `ts-api-utils`

- docs/packages/Rule_Tester.mdx
Copies @bradzacher's comments, which I have tried out locally and found to be exactly enough.
Co-authored-by: @bradzacher
> docs: explain globals in `RuleTester` for Mocha and Vitest

- packages/eslint-plugin/src/rules/no-unsafe-enum-comparison.ts
> chore(eslint-plugin): refactor getTypeFromNode to parserServices.getTypeAtLocation

- CONTRIBUTORS.md
- packages/repo-tools/src/generate-contributors.ts
https://github.com/typescript-eslint/typescript-eslint/pull/7587#discussion_r1328012160
Co-authored-by: @rubiesonthesky
> chore: fix generate-contributors path

- .cspell.json
- docs/linting/Typed_Linting.mdx
A link anchor was borken
Just fix a link
> docs: fix broken anchor in Typed_Linting.mdx

- docs/developers/Custom_Rules.mdx
> docs(website): mention how rule options should be handled

- packages/eslint-plugin/src/rules/no-unused-expressions.ts
- packages/eslint-plugin/tests/rules/no-unused-expressions.test.ts
> fix(eslint-plugin): [no-unused-expressions] handle TSInstantiationExpression expression

- packages/repo-tools/src/generate-sponsors.ts
- packages/website/data/sponsors.json
Gets the task able to run again, and runs it.
> chore: fix generate-sponsors.ts and update sponsors.json

- packages/eslint-plugin/src/util/collectUnusedVariables.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
> fix(eslint-plugin): [no-unused-vars] handle logical assignment

- packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-qualifier.test.ts
> fix(eslint-plugin): [no-unnecessary-qualifier] handle nested namespace id

- .yarnrc.yml
- package.json
Applied the suggested changes from https://yarnpkg.com/configuration/yarnrc#nmHoistingLimits
> chore: replace nohoist configuration with hoisting limits

- .github/workflows/ci.yml
> chore: reenable nx cloud

- .github/workflows/ci.yml
- packages/rule-tester/tests/RuleTester.test.ts
- packages/typescript-estree/tests/lib/describeFilePath.test.ts
> chore: add windows ci

- docs/Getting_Started.mdx
Added pnpm option for running eslint command in `getting_started.mdx` page
> docs: add `getting_started.mdx` pnpm command

- packages/typescript-estree/src/create-program/createDefaultProgram.ts
- packages/typescript-estree/src/create-program/createProjectService.ts
- packages/typescript-estree/src/create-program/createSourceFile.ts
- packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
@fisker made me realise that we hadn't wired this new option up to every possible spot.
This PR ensures that all locations that we create a program or source file have the new option set to improve our perf.
> feat(typescript-estree): pass jsDocParsingMode everywhere

- packages/eslint-plugin/docs/rules/no-misused-promises.md
This PR updates a sentence in the `no-misused-promises` doc to use active voice in order to make the sentence a little more concise.
---
Sending ❤️ to the team (and hey, I did read https://typescript-eslint.io/contributing/pull-requests/ 😄).
> docs(eslint-plugin): simplify a sentence in no-misused-promises.md

- packages/eslint-plugin/docs/rules/no-shadow.md
I got very confused when I was reading this page, and I'm surprised to see an issue lying around for a year and a half!
> docs: fix example for no-shadow

- docs/linting/Troubleshooting.mdx
> docs: add FAQ about incorrect types

- packages/eslint-plugin/docs/rules/no-for-in-array.md
- packages/eslint-plugin/src/rules/no-for-in-array.ts
> docs: add more rationale for no-for-in-array

- packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md
> docs(eslint-plugin): [prefer-readonly-parameter-types] fix broken code samples

- packages/eslint-plugin/tests/rules/prefer-readonly.test.ts
Manually formats the failing snippets.
> chore: fix test formatting in prefer-readonly.test.ts

- packages/website/blog/2022-12-05-asts-and-typescript-eslint.md
- packages/website/blog/2023-02-24-consistent-type-exports-and-imports-why-and-how.md
- packages/website/docusaurusConfig.ts
Expands posts to show all, and adds a `` with a bit of rewording to the older blog post.
> docs: show all articles in sidebar, and a missing truncate

- .github/ISSUE_TEMPLATE/02-enhancement-rule-option.yaml
- .github/ISSUE_TEMPLATE/03-enhancement-new-rule.yaml
- .github/ISSUE_TEMPLATE/04-enhancement-new-base-rule-extension.yaml
- .github/ISSUE_TEMPLATE/07-enhancement-other.yaml
- .github/replies.yml
I didn't open an issue since it's just some outdated links and didn't require much thought.
I read through the contributing guidelines and ran `yarn check-spelling`.
Updates some broken and outdated links.
👋
> chore: fix broken and outdated links

- packages/ast-spec/src/element/MethodDefinition/fixtures/_error_/duplicated-accessibility-modifiers/fixture.ts
- packages/ast-spec/src/element/MethodDefinition/fixtures/_error_/duplicated-accessibility-modifiers/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/element/MethodDefinition/fixtures/_error_/duplicated-accessibility-modifiers/snapshots/2-Babel-Error.shot
- packages/ast-spec/src/element/MethodDefinition/fixtures/_error_/duplicated-accessibility-modifiers/snapshots/3-Alignment-Error.shot
- packages/ast-spec/src/element/MethodDefinition/fixtures/_error_/mixed-accessibility-modifiers/fixture.ts
- packages/ast-spec/src/element/MethodDefinition/fixtures/_error_/mixed-accessibility-modifiers/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/element/MethodDefinition/fixtures/_error_/mixed-accessibility-modifiers/snapshots/2-Babel-Error.shot
- packages/ast-spec/src/element/MethodDefinition/fixtures/_error_/mixed-accessibility-modifiers/snapshots/3-Alignment-Error.shot
- packages/ast-spec/src/element/PropertyDefinition/fixtures/_error_/duplicated-accessibility-modifiers/fixture.ts
- packages/ast-spec/src/element/PropertyDefinition/fixtures/_error_/duplicated-accessibility-modifiers/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/element/PropertyDefinition/fixtures/_error_/duplicated-accessibility-modifiers/snapshots/2-Babel-Error.shot
- packages/ast-spec/src/element/PropertyDefinition/fixtures/_error_/duplicated-accessibility-modifiers/snapshots/3-Alignment-Error.shot
- packages/ast-spec/src/element/PropertyDefinition/fixtures/_error_/mixed-accessibility-modifiers/fixture.ts
- packages/ast-spec/src/element/PropertyDefinition/fixtures/_error_/mixed-accessibility-modifiers/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/element/PropertyDefinition/fixtures/_error_/mixed-accessibility-modifiers/snapshots/2-Babel-Error.shot
- packages/ast-spec/src/element/PropertyDefinition/fixtures/_error_/mixed-accessibility-modifiers/snapshots/3-Alignment-Error.shot
- packages/typescript-estree/src/convert.ts
> feat(typescript-estree): forbid duplicated accessibility modifiers

- packages/eslint-plugin/docs/rules/no-explicit-any.md
Mentions the preferred strategies: `interface` or `type` for known data shapes; `unknown` for unknown data shapes.
> docs(eslint-plugin): mention alternatives in no-explicit-any

- docs/linting/Typed_Linting.mdx
> docs: fix missing bracket in Typed_Linting.mdx

- packages/eslint-plugin/docs/rules/no-inferrable-types.md
> docs: small typo in no-inferrable-types.md

- packages/website/src/components/team/TeamBioList.module.css
> chore(website): add line breaks for the bios on the Team page

- docs/troubleshooting/Formatting.mdx
Fixing doc example to not generate an error.
> docs: fixing prettier config example

- packages/eslint-plugin/docs/rules/no-unsafe-unary-minus.md
`` seems missing in `no-unsafe-unary-minus.md`
> docs: add tabs in no-unsafe-unary-minus.md

- packages/website/src/theme/CodeBlock/Content/String.tsx
- packages/website/src/theme/MDXComponents/TryInPlayground.tsx
> chore(website): include file extension to "Open in Playground" URLs

- packages/eslint-plugin/src/rules/consistent-type-imports.ts
Alphabetized the options and default options in said file. Verified this when running local.
> docs: alphabetize consistent-type-imports options for consistent type imports

- docs/getting-started/typed-linting/Monorepos.mdx
> docs: fix monorepos config example syntax error

- packages/website/src/components/team/TeamBio.module.css
- packages/website/src/components/team/TeamBio.tsx
- packages/website/src/css/custom.css
- packages/website/static/img/www.svg
apply icon dark mode using global icon class
> docs(website): icons not being visible in dark mode

- packages/eslint-plugin/docs/rules/prefer-optional-chain.md
fix typo ("will not" -> "will")
filed https://github.com/typescript-eslint/typescript-eslint/issues/8659 for some more complicated changes
> docs: [prefer-optional-chain] fix boolean option being specified incorrectly

- docs/maintenance/Pull_Requests.mdx
Merge issue from me merging Docusaurus v3 (#7872) and the PR maintenance guide (#8549).
> chore(website): fix build break from {} for Docusaurus v3

- packages/website/plugins/generated-rule-docs/insertions/insertFormattingNotice.ts
- packages/website/src/theme/MDXComponents/index.tsx
> chore(website): fix broken deprecated warning

- packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
> feat(eslint-plugin): [no-unnecessary-type-arguments] handle tagged templates

- packages/website/blog/2022-12-05-asts-and-typescript-eslint.md
Fixed link to @typescript-eslint/parser package page.
> docs: fix broken link in parser page

- .github/ISSUE_TEMPLATE/06-bug-report-other.yaml
- .github/ISSUE_TEMPLATE/07-enhancement-other.yaml
i add all packages in select list except `eslint-plugin`. but i don't know all package is need in select section.
> chore: add selectable packages in issue template

- packages/integration-tests/tests/__snapshots__/flat-config-types.test.ts.snap
> chore: update failing flat-config-types integration test snapshot

- packages/eslint-plugin/tests/rules/prefer-optional-chain/prefer-optional-chain.test.ts
- packages/typescript-estree/src/create-program/createProjectService.ts
> chore: resolve lint issues on main branch

- packages/utils/src/eslint-utils/index.ts
> fix(utils): export ESLint backwards-compat functions

- packages/type-utils/src/requiresQuoting.ts
- packages/type-utils/tests/requiresQuoting.test.ts
add Testcase in requiresQuoting Function
> test(type-utils): add unit tests for requiresQuoting

- README.md
> docs: add eslint v9 tracking issue to main README

- packages/rule-tester/tests/RuleTester.test.ts
> test(rule-tester): update test config snapshots to include new disallowAutomaticSingleRunInference option

- README.md
Followup to https://github.com/typescript-eslint/typescript-eslint/pull/8998
> docs: remove eslint v9 tracking issue from main readme for v8

- packages/integration-tests/tests/__snapshots__/flat-config-types.test.ts.snap
- packages/integration-tests/tests/__snapshots__/recommended-does-not-require-program.test.ts.snap
The main branch CI is failing. It updates the test snapshots.
> test: update integration test snapshot

- packages/eslint-plugin/tests/docs.test.ts
> docs: correct its/it's spelling

- packages/eslint-plugin/docs/rules/consistent-type-imports.mdx
- packages/eslint-plugin/docs/rules/lines-between-class-members.mdx
- packages/eslint-plugin/docs/rules/no-import-type-side-effects.mdx
- packages/eslint-plugin/docs/rules/unbound-method.mdx
I just ran `lychee docs packages/eslint-plugin/docs packages/website/blog`
*[lychee](https://lychee.cli.rs/)*
> docs(eslint-plugin): fix several 404 URLs

- packages/eslint-plugin/docs/rules/no-floating-promises.mdx
> docs: [no-floating-promises] fix capitalization typo

- yarn.lock
Reverts typescript-eslint/typescript-eslint#9176
> chore: revert "chore(deps): update dependency knip to v5.17.1"

- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/tests/rules/member-ordering.test.ts
Added two invalid tests that were false-negativing on main
> fix(eslint-plugin): [member-ordering] also TSMethodSignature can be get/set

- packages/parser/src/parser.ts
- packages/types/src/parser-options.ts
I updated the type and refactored the code to prevent the same situation from happening again.
> fix(types): correct typing ParserOptions

- eslint.config.mjs
We don't have any existing violations of it. Yay, us!
💖
> chore: enable prefer-string-starts-ends-with internally

- docs/maintenance/Releases.mdx
- packages/website/blog/2024-05-27-announcing-typescript-eslint-v8-beta.mdx
Adds a mention to the blog post.
Also updates the Releases.mdx steps to mention the proper title.
💖
> docs: mention TSEnumBody breaking change in v8 beta post

- docs/contributing/Local_Development.mdx
- docs/contributing/Pull_Requests.mdx
Lumps the two issues in together since they both touch the same page.
💖
> docs: mention testing changes and keeping PRs up-to-date in PR docs

- packages/eslint-plugin/docs/rules/no-base-to-string.mdx
- packages/eslint-plugin/docs/rules/restrict-template-expressions.mdx
- packages/eslint-plugin/src/rules/no-base-to-string.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-base-to-string.shot
> fix(eslint-plugin): [no-base-to-string] make error message more nuanced

- .yarn/patches/eslint-plugin-eslint-plugin-npm-5.5.1-4206c2506d.patch
- eslint.config.mjs
- package.json
- packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
- packages/eslint-plugin/src/rules/class-literal-property-style.ts
- packages/eslint-plugin/src/rules/default-param-last.ts
- packages/eslint-plugin/src/rules/indent.ts
- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/src/rules/no-extraneous-class.ts
- packages/eslint-plugin/src/rules/no-inferrable-types.ts
- packages/eslint-plugin/src/rules/no-misused-new.ts
- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/src/rules/no-useless-constructor.ts
- packages/eslint-plugin/src/rules/padding-line-between-statements.ts
- packages/eslint-plugin/src/rules/prefer-as-const.ts
- packages/eslint-plugin/src/rules/prefer-destructuring.ts
- yarn.lock
Adds in a bugfix patch for https://github.com/eslint-community/eslint-plugin-eslint-plugin/issues/482. 
💖
> chore: enable eslint-plugin/no-property-in-node internally

- packages/website/src/components/editor/LoadedEditor.tsx
- packages/website/src/components/linter/bridge.ts
- packages/website/src/components/linter/createLinter.ts
- packages/website/src/components/linter/createParser.ts
- packages/website/src/components/linter/utils.ts
Reverts typescript-eslint/typescript-eslint#9271
> Revert "chore(website): align file names to RuleTester requirements"

- .yarn/patches/nx-npm-19.3.0-canary.20240611-1600875-bd96520563.patch
- nx.json
- package.json
- yarn.lock
Tested `yarn release` and `nx apply-canary-version repo-tools` to ensure it is working
> chore: fix changelog renderer patch

- packages/eslint-plugin/docs/rules/return-await.mdx
- packages/eslint-plugin/src/rules/return-await.ts
> docs: improve return-await description about motivation

- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/src/util/collectUnusedVariables.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
- packages/eslint-plugin/tests/schema-snapshots/no-unused-vars.shot
- packages/scope-manager/src/referencer/Referencer.ts
- packages/scope-manager/src/variable/index.ts
- packages/scope-manager/tests/fixtures/ts-enum/external-ref.ts.shot
- packages/scope-manager/tests/fixtures/ts-enum/literal-member-ref.ts.shot
- packages/scope-manager/tests/fixtures/ts-enum/literal-member.ts.shot
- packages/scope-manager/tests/fixtures/ts-enum/member-ref.ts.shot
- packages/scope-manager/tests/fixtures/ts-enum/scope.ts.shot
- packages/scope-manager/tests/fixtures/ts-enum/self-ref.ts.shot
- packages/scope-manager/tests/fixtures/type-declaration/signatures/method-computed-name2.ts.shot
- packages/scope-manager/tests/fixtures/type-declaration/signatures/property-computed-name2.ts.shot
- packages/utils/src/ts-eslint/Scope.ts
This was added upstream in https://github.com/eslint/eslint/pull/17662
This syncs the changes to our implementation.
> feat(eslint-plugin): [no-unused-vars] add `reportUnusedIgnorePattern` option

- packages/eslint-plugin/src/util/collectUnusedVariables.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts
Syncs https://github.com/eslint/eslint/pull/15868, https://github.com/eslint/eslint/pull/14928 and https://github.com/eslint/eslint/pull/14354 from upstream
NOTE: stacked on top of #9325 - retarget to `v8` before merging
> feat(eslint-plugin): [no-unused-vars] handle comma operator for assignments, treat for-of the same as for-in

- packages/utils/package.json
- packages/website-eslint/build.ts
> fix(utils): clean outdated `RuleTester` export

- docs/users/Releases.mdx
> docs: fix grammatical error in Releases.mdx

- docs/troubleshooting/typed-linting/index.mdx
Adds the FAQ with a mention of the root cause and common symptoms.
💖
> docs: mention out-of-date editor type information FAQ

- packages/eslint-plugin/src/rules/no-shadow.ts
- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/src/rules/no-use-before-define.ts
- packages/eslint-plugin/src/util/collectUnusedVariables.ts
- packages/eslint-plugin/src/util/isTypeImport.ts
- packages/eslint-plugin/src/util/referenceContainsTypeQuery.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
- packages/utils/src/ts-eslint/Linter.ts
- packages/utils/src/ts-eslint/RuleTester.ts
- packages/utils/src/ts-eslint/SourceCode.ts
- packages/utils/src/ts-eslint/eslint/FlatESLint.ts
- packages/utils/src/ts-eslint/eslint/LegacyESLint.ts
> feat(eslint-plugin): [no-unused-vars] report if var used only in typeof

- docs/troubleshooting/typed-linting/Performance.mdx
Adds some preliminary type performance debugging tips, mostly linking to the TypeScript wiki.
💖
> docs: add Performance FAQ about slow TypeScript types

- .github/workflows/ci.yml
I've also updated our `CODECOV_TOKEN` secret. Hopefully this upgrade and the refreshed token will fix our uploads? 🤞
> chore: help fix Codecov uploads by bumping to v4.5.0

- packages/eslint-plugin/src/configs/disable-type-checked.ts
- packages/repo-tools/src/generate-configs.mts
- packages/typescript-eslint/src/configs/disable-type-checked.ts
> fix: disable `EXPERIMENTAL_useProjectService` in `disabled-type-checked` shared config

- packages/eslint-plugin/src/configs/disable-type-checked.ts
- packages/repo-tools/src/generate-configs.mts
- packages/typescript-eslint/src/configs/disable-type-checked.ts
> fix: disable `projectService` in `disabled-type-checked` shared config

- docs/developers/Custom_Rules.mdx
> docs: use correct types for node in "Explicity node types" documentation

- .github/workflows/close-v8-issues.yml
> chore: add necessary permissions to the `v8` issues autocloser workflow

- .github/workflows/close-v8-issues.yml
> chore: change the `v8` issue autocloser trigger to `pull_request_target`

- docs/contributing/Pull_Requests.mdx
- Added "AST Testing" and "Updating Snapshots" sections to the [Pull Requests doc](https://typescript-eslint.io/contributing/pull-requests)
- Fixed heading levels
🌱
> docs: add snapshot-related info sections to the Pull Requests documentation

- .github/workflows/semantic-breaking-change-pr.yml
> chore: don't install dependencies in "Semantic breaking change PR" workflow

- .github/workflows/semantic-breaking-change-pr.yml
Oops :grimacing: This PR reverts my previous PR https://github.com/typescript-eslint/typescript-eslint/pull/9533
See https://github.com/typescript-eslint/typescript-eslint/pull/9530#issuecomment-2221003234
> chore: revert "chore: don't install dependencies in "Semantic breaking change PR" workflow (#9533)"

- packages/ast-spec/src/element/TSEnumMember/spec.ts
- packages/ast-spec/src/special/TSEnumBody/spec.ts
- packages/eslint-plugin-internal/src/rules/no-typescript-default-import.ts
- packages/eslint-plugin/src/rules/class-literal-property-style.ts
- packages/eslint-plugin/src/rules/class-methods-use-this.ts
- packages/eslint-plugin/src/rules/method-signature-style.ts
- packages/eslint-plugin/src/rules/no-extraneous-class.ts
- packages/eslint-plugin/src/rules/no-misused-new.ts
- packages/eslint-plugin/src/rules/no-restricted-imports.ts
- packages/eslint-plugin/src/rules/no-unnecessary-qualifier.ts
- packages/eslint-plugin/src/rules/no-unsafe-enum-comparison.ts
- packages/eslint-plugin/src/rules/no-useless-constructor.ts
- packages/types/src/ts-estree.ts
Adds all the parent types specified in #6225 and fixes the resulting type and linting errors.
Pretty straightforward here!
> feat: stricter parent types for the AST

- eslint.config.mjs
- packages/website-eslint/src/mock/path.js
Enable `prefer-rest-params` ([docs](https://eslint.org/docs/latest/rules/prefer-rest-params))
> chore: enable prefer-rest-params

- packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
CI is broken on main (https://github.com/typescript-eslint/typescript-eslint/commit/2d81d1a4686fe43ef8f2941ed2c48a9863e83c3d, https://github.com/typescript-eslint/typescript-eslint/actions/runs/9963500743), since https://github.com/typescript-eslint/typescript-eslint/pull/9043 wasn't fully up to date.
This fixes that!
> chore: [no-floating-promises] add missing suggestions on main

- docs/maintenance/Releases.mdx
Adds a process step to also create a pinned issue for _plugins_, not just _end users_, based on #9501.
💖
> docs: mention trying major version betas on plugins

- eslint.config.mjs
- packages/rule-schema-to-typescript-types/src/index.ts
Enable `operator-assignment` ([docs](https://eslint.org/docs/latest/rules/operator-assignment))
Completely autofixable
> chore: enable operator-assignment

- packages/eslint-plugin/docs/rules/sort-type-constituents.mdx
Hi, we have made a new website and moved to a new domain.
> docs: update perfectionist domain

- packages/eslint-plugin/docs/rules/no-unsafe-function-type.mdx
- packages/eslint-plugin/docs/rules/no-wrapper-object-types.mdx
The linked rules exist in v7. See https://github.com/typescript-eslint/typescript-eslint/pull/9507
> docs: remove unnecessary v8 links

- packages/eslint-plugin/docs/rules/no-unnecessary-type-parameters.mdx
For your consideration @JoshuaKGoldberg
> docs(eslint-plugin): [no-unnecessary-type-parameters] add admonition about rule's potential for subtlety

- docs/packages/Rule_Tester.mdx
Updates the docs to use the new RuleTester configuration.
> docs: update RuleTester example to use FlatConfig configuration

- packages/integration-tests/fixtures/flat-config-types-@types__eslint-v8/package.json
- packages/integration-tests/fixtures/flat-config-types-@types__eslint-v9/package.json
- packages/integration-tests/tests/flat-config-types-@types__eslint-v8.test.ts
- packages/integration-tests/tests/flat-config-types-@types__eslint-v9.test.ts
- packages/utils/src/ts-eslint/Config.ts
> fix(utils): correct types to align with @types/eslint v9

- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
- Enable "add await" suggestion.
> feat(eslint-plugin): [no-floating-promises] enable "add await" suggestion if ignoreVoid is true

- packages/eslint-plugin/docs/rules/ban-types.md
- packages/eslint-plugin/docs/rules/block-spacing.md
- packages/eslint-plugin/docs/rules/brace-style.md
- packages/eslint-plugin/docs/rules/camelcase.md
- packages/eslint-plugin/docs/rules/comma-dangle.md
- packages/eslint-plugin/docs/rules/comma-spacing.md
- packages/eslint-plugin/docs/rules/func-call-spacing.md
- packages/eslint-plugin/docs/rules/indent.md
- packages/eslint-plugin/docs/rules/key-spacing.md
- packages/eslint-plugin/docs/rules/keyword-spacing.md
- packages/eslint-plugin/docs/rules/lines-around-comment.md
- packages/eslint-plugin/docs/rules/lines-between-class-members.md
- packages/eslint-plugin/docs/rules/member-delimiter-style.md
- packages/eslint-plugin/docs/rules/no-duplicate-imports.mdx
- packages/eslint-plugin/docs/rules/no-extra-parens.md
- packages/eslint-plugin/docs/rules/no-extra-semi.md
- packages/eslint-plugin/docs/rules/no-parameter-properties.mdx
- packages/eslint-plugin/docs/rules/no-useless-template-literals.mdx
- packages/eslint-plugin/docs/rules/object-curly-spacing.md
- packages/eslint-plugin/docs/rules/padding-line-between-statements.md
- packages/eslint-plugin/docs/rules/quotes.md
- packages/eslint-plugin/docs/rules/semi.md
- packages/eslint-plugin/docs/rules/sort-type-union-intersection-members.mdx
- packages/eslint-plugin/docs/rules/space-before-blocks.md
- packages/eslint-plugin/docs/rules/space-before-function-paren.md
- packages/eslint-plugin/docs/rules/space-infix-ops.md
- packages/eslint-plugin/docs/rules/type-annotation-spacing.md
- packages/website/sidebars/sidebar.rules.js
Fixed the sidebar to display on tombstone pages.
ex: camelcase
> docs(website): display sidebar rules on tombstone pages

- packages/rule-tester/tests/RuleTester.test.ts
> chore(rule-tester): make unit tests pass

- packages/website/src/components/hooks/useHashState.ts
Set default values in tsconfig instead of blank.
> fix(website): tsconfig is blank

- packages/eslint-plugin/tests/rules/no-unsafe-enum-comparison.test.ts
Fixes a typo in the tests for the rule.
> fix(eslint-plugin): [no-unsafe-enum-comparison] typo in test

- packages/eslint-plugin/src/rules/prefer-optional-chain-utils/analyzeChain.ts
- packages/eslint-plugin/src/rules/prefer-optional-chain.ts
- packages/eslint-plugin/src/util/getFixOrSuggest.ts
- packages/eslint-plugin/src/util/index.ts
- packages/eslint-plugin/tests/rules/prefer-optional-chain/prefer-optional-chain.test.ts
> fix(eslint-plugin): [prefer-optional-chain] wrong parenthesis fix output

- packages/eslint-plugin/docs/rules/no-unsafe-return.mdx
- packages/eslint-plugin/docs/rules/no-use-before-define.mdx
- packages/eslint-plugin/src/rules/init-declarations.ts
- packages/scope-manager/src/referencer/Referencer.ts
- packages/typescript-estree/src/semantic-or-syntactic-errors.ts
> chore: remove repetitive words

- docs/troubleshooting/faqs/General.mdx
Made changes to the next page navigation on the Genera page.
> docs: next page navigation link pointing to current page

- docs/troubleshooting/typed-linting/index.mdx
Recreation of #9256. I love merge mishaps. _sigh_
💖
> docs: again correct tsconfig.eslint.json link to be permalink

- packages/utils/src/ts-eslint/Config.ts
Fixes up a few comments that were put in an incorrect new location in #9698. Thanks @FloEdelmann for catching them!
💖 
Co-authored-by: @FloEdelmann
> chore: correct a few comment placements in utils

- docs/troubleshooting/faqs/TypeScript.mdx
Adds a nice little FAQ with links to more linting.
💖
> docs: add FAQs > TypeScript entry on comment directives

- packages/eslint-plugin/docs/rules/restrict-template-expressions.mdx
Adds a brief summary of reasoning as stated in #9311. Also copy & pastes one-liner descriptions for the rest of the options while I was in the area.
💖
> docs(eslint-plugin): [restrict-template-expressions] add explanation for allowNumber

- packages/website/blog/2024-07-31-announcing-typescript-eslint-v8.md
> docs: fix typo in v8 blog post

- docs/contributing/local-development/Local_Linking.mdx
Adds an FAQ for rebuilding if a rule or parent config isn't found/updated.
Also adds explicit mentions of building earlier in the document.
💖
> docs: add 'Rule Not Found' FAQ for Local Linking

- docs/troubleshooting/faqs/General.mdx
Adds most of the examples from #5863. I kept it to the ones that were either commonly confusing/useful or TypeScript-specific.
💖
> docs: added more no-restricted-syntax FAQ examples

- docs/troubleshooting/faqs/ESLint.mdx
- packages/eslint-plugin/docs/rules/no-namespace.mdx
Adds similar examples to what's in the docs issue, along with suggested remediations, tips on disable comments, and a link to the two issues.
💖
> docs: add global variable rule disabling FAQ for ESLint

- packages/website-eslint/README.md
- packages/website/README.md
This package hasn't been asked about much in the year and a half since I filed the docs request. I think just having a basic README.md that mentions the rough build flow & usage of it should be enough. Unless anybody has specific topics, which I'd love to know & add in here?
💖
> docs: add website-eslint README.md

- eslint.config.mjs
- package.json
- packages/website/src/components/ast/utils.ts
- yarn.lock
Enable `unicorn/no-length-as-slice-end` ([docs](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v55.0.0/docs/rules/no-length-as-slice-end.md)). 100% autofixabl
> chore: enable `unicorn/no-length-as-slice-end`

- eslint.config.mjs
- package.json
- packages/types/tools/copy-ast-spec.ts
- yarn.lock
Enable `unicorn/no-single-promise-in-promise-methods` ([docs](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v55.0.0/docs/rules/no-single-promise-in-promise-methods.md)). 100% autofixable
The one instance has been in the codebase since #2911
> chore: enable `unicorn/no-single-promise-in-promise-methods`

- .github/workflows/ci.yml
Adds `rule-tester` to the list of tested packages in CI.
💖
> chore: also test rule-tester in CI

- packages/eslint-plugin/docs/rules/no-floating-promises.mdx
> docs: [no-floating-promises] add MDN link regarding void operator

- docs/developers/Custom_Rules.mdx
- docs/packages/Rule_Tester.mdx
> docs: clean up remaining allowDefaultProject(ForFiles) vestiges

- .github/ISSUE_TEMPLATE/06-bug-report-other.yaml
- .github/ISSUE_TEMPLATE/07-enhancement-other.yaml
> chore: allow selecting eslint-plugin in 'Another Package' issues

- packages/eslint-plugin/TSLINT_RULE_ALTERNATIVES.md
Run Prettier to fix CI failure on `main`, introduced in #10018.
> chore: run prettier to fix CI failure on `main`

- packages/eslint-plugin/src/rules/no-misused-promises.ts
- packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
> fix(eslint-plugin): [no-misused-promises] check contextual type

- .cspell.json
- docs/getting-started/Typed_Linting.mdx
- packages/website/blog/2024-09-30-typed-linting.md
Adds a ~10 minute read explaining:
1. What typed linting is
2. Common uses for it
3. Enabling it
4. Drawbacks
I'm planning on using this as a springboard for our more in-depth, rule-specific blog posts soon (#6415, #8517, #9103).
💖
> docs: add 'Typed Linting' blog post

- packages/eslint-plugin/docs/rules/no-unsafe-call.mdx
Followup to https://github.com/typescript-eslint/typescript-eslint/issues/9108#issuecomment-2373995560
cc @controversial feel free to chime in with your thoughts!
Co-authored-by: @controversial
> docs: [no-unsafe-call] clarify that you can never safely narrow Function

- packages/visitor-keys/src/visitor-keys.ts
> fix(visitor-keys): reorder `TSSatisfiesExpression` and `TSTypeAssertion`

- packages/type-utils/tests/getDeclaration.test.ts
Added tests for getDeclaration function.
> test(type-utils): add tests for getDeclaration

- package.json
- yarn.lock
> chore: upgrade cspell

- packages/website/src/components/RulesTable/index.tsx
- packages/website/src/components/ast/utils.ts
- packages/website/src/components/lib/jsonSchema.ts
- packages/website/src/components/lib/shallowEqual.ts
- packages/website/tsconfig.json
`website/tsconfig.json` incorrectly had `noImplicitAny: true` since the creation of the website (#4105). This PR removes that option.
> fix(website): enable `noImplicitAny`

- packages/website/plugins/generated-rule-docs/addESLintHashToCodeBlocksMeta.ts
- packages/website/plugins/generated-rule-docs/insertions/insertBaseRuleReferences.ts
- packages/website/plugins/generated-rule-docs/insertions/insertNewRuleReferences.ts
- packages/website/plugins/utils/rules.ts
Added the `Flat Config`/`Legacy Config` tabs to the configuration examples on the rule pages.
📕
> docs: update configuration examples on individual rule pages to use flat config

- packages/eslint-plugin/src/configs/eslint-recommended-raw.ts
> feat(eslint-plugin): disable `no-class-assign` rule in `eslint-recommended` config

- packages/website/plugins/generated-rule-docs/insertions/insertWhenNotToUseIt.ts
> chore: fix typo

- packages/eslint-plugin/src/rules/no-deprecated.ts
- packages/eslint-plugin/tests/rules/no-deprecated.test.ts
> fix(eslint-plugin): [no-deprecated] report on deprecated variables used inside dynamic imports

- packages/eslint-plugin/src/rules/no-deprecated.ts
- packages/eslint-plugin/tests/rules/no-deprecated.test.ts
> fix(eslint-plugin): [no-deprecated] report when exported class implements/extends deprecated entity

- docs/packages/type-utils/TypeOrValueSpecifier.mdx
- packages/eslint-plugin/docs/rules/only-throw-error.mdx
- packages/eslint-plugin/src/rules/only-throw-error.ts
- packages/eslint-plugin/tests/fixtures/errors.ts
- packages/eslint-plugin/tests/fixtures/tsconfig.json
- packages/eslint-plugin/tests/rules/only-throw-error.test.ts
- packages/eslint-plugin/tests/schema-snapshots/only-throw-error.shot
> feat(eslint-plugin): [only-throw-error] add allow option

- packages/eslint-plugin/tests/eslint-rules/prefer-const.test.ts
- packages/scope-manager/src/referencer/Referencer.ts
- packages/scope-manager/tests/fixtures/type-assertion/increment/angle-bracket-increment.ts
- packages/scope-manager/tests/fixtures/type-assertion/increment/angle-bracket-increment.ts.shot
- packages/scope-manager/tests/fixtures/type-assertion/increment/as-increment.ts
- packages/scope-manager/tests/fixtures/type-assertion/increment/as-increment.ts.shot
- packages/scope-manager/tests/fixtures/type-assertion/increment/non-null-increment.ts
- packages/scope-manager/tests/fixtures/type-assertion/increment/non-null-increment.ts.shot
This PR is analogous to #2809, but addresses increment operators.
> fix(scope-manager): fix asserted increments not being marked as write references

- packages/integration-tests/fixtures/flat-config-types-@types__eslint-v8/eslint.config.js
- packages/integration-tests/fixtures/flat-config-types-@types__eslint-v9/eslint.config.js
- packages/integration-tests/tests/__snapshots__/flat-config-types-@types__eslint-v8.test.ts.snap
- packages/integration-tests/tests/__snapshots__/flat-config-types-@types__eslint-v9.test.ts.snap
> test: fix jest plugin usage in integration test

- packages/type-utils/package.json
- packages/typescript-eslint/package.json
- packages/utils/package.json
- yarn.lock
Ensure all transitive peer dependencies are properly listed. This fixes peer-requirements warnings thrown by yarn.
> fix: add missing peer dependencies

- CONTRIBUTORS.md
- tools/scripts/generate-contributors.mts
This hasn't been updated in over 8 months.
Fixes the script so it does pagination properly.
This likely still won't work as our CI job because we make un-authenticated requests and the rate limit for that is 60/hour.
We'll have to figure out a way around that at some point.
For now I just used a personal token to bypass the limit so we can update this.
> chore: update contributors

- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/node-utils.ts
- packages/website/src/components/ast/PropertyValue.tsx
- packages/website/src/components/ast/selectedRange.ts
- packages/website/src/components/ast/utils.ts
- tools/scripts/generate-lib.mts
> [!CAUTION]
> Caution there is no associated issue but [CI is failing](https://github.com/typescript-eslint/typescript-eslint/actions/runs/11979317330/job/33401412936)
I just merged `main` in #10343 and I got some lint errors in CI.
This PR fixes them.
> chore: correct lint errors in CI

- packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
- packages/typescript-estree/tests/lib/tsVersionRangeSync.test.ts
As mentioned in #10385 - adds a test to ensure we don't fall out of sync again
> test(typescript-estree): add test to ensure TS version range matches root version

- packages/website/src/theme/MDXComponents/RuleAttributes.tsx
Fix the condition for determining recommended.
🚀
> docs: return-await doc page should say the rule is in the strict-type-checked ruleset, not recommended

- packages/eslint-plugin/docs/rules/prefer-promise-reject-errors.mdx
- packages/eslint-plugin/src/rules/prefer-promise-reject-errors.ts
- packages/eslint-plugin/tests/rules/prefer-promise-reject-errors.test.ts
- packages/eslint-plugin/tests/schema-snapshots/prefer-promise-reject-errors.shot
> feat(eslint-plugin): [prefer-promise-reject-errors] options to allow any and unknown

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
> fix(eslint-plugin): handle string like index type

- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
- packages/scope-manager/src/referencer/ClassVisitor.ts
- packages/scope-manager/tests/fixtures/decorators/parameter-property.ts.shot
- packages/scope-manager/tests/fixtures/decorators/parameter.ts
- packages/scope-manager/tests/fixtures/decorators/parameter.ts.shot
> fix(scope-manager): visit params decorator before nest scope

- packages/website/src/components/editor/loadSandbox.ts
This CDN moved a while ago, but the old one has kept working. It may not in the future, so the website should really use the new one.
> docs: switch playground to new CDN

- packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
> fix(eslint-plugin): [no-unnecessary-type-arguments] handle type/value context

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
> fix(eslint-plugin): [no-unnecessary-condition] handle noUncheckedIndexedAccess true

- packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.mdx
***
Somehow this is a repeat issue 🤔 https://github.com/typescript-eslint/typescript-eslint/pull/10033
> docs: [prefer-nullish-coalescing] fix admonition

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Reverts typescript-eslint/typescript-eslint#10523
> fix: revert "fix(eslint-plugin): [no-unnecessary-type-assertion] handle literal types"

- docs/maintenance/Contributor_Tiers.mdx
- docs/maintenance/Pull_Requests.mdx
> chore: update maintenance docs around team member expectations

- docs/maintenance/Contributor_Tiers.mdx
fix accidental omission in https://github.com/typescript-eslint/typescript-eslint/pull/10589
> docs: use consistent verbiage around authoring pull requests in contributor tiers docs

- packages/eslint-plugin/docs/rules/no-duplicate-enum-values.mdx
- packages/eslint-plugin/src/rules/no-duplicate-enum-values.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-duplicate-enum-values.shot
- packages/eslint-plugin/tests/rules/no-duplicate-enum-values.test.ts
> fix(eslint-plugin): [no-duplicate-enum-values] handle template literal

- packages/website/blog/2025-01-21-avoiding-anys.mdx
> docs: fix typo in latest blog post

- packages/eslint-plugin/src/rules/no-extraneous-class.ts
- packages/eslint-plugin/tests/rules/no-extraneous-class.test.ts
> fix(eslint-plugin): [no-extraneous-class] handle accessor keyword

- .markdownlintignore
Also alphabetizes the file while I'm in the area. 🤘
💖
> chore: ignore generated docs in markdownlint

- .gitattributes
Addresses https://github.com/typescript-eslint/typescript-eslint/pull/10679#discussion_r1932655766
> chore: add line endings for `.mts` and `.cts` files in `.gitattributes`

- packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
- packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
> fix(eslint-plugin): [prefer-nullish-coalescing] fix missing return

- packages/eslint-plugin/docs/rules/no-unnecessary-boolean-literal-compare.mdx
- packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
- packages/eslint-plugin/tests/docs.test.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-boolean-literal-compare.test.ts
- packages/eslint-plugin/tests/schema-snapshots/no-unnecessary-boolean-literal-compare.shot
> feat(eslint-plugin): [no-unnecessary-boolean-literal-compare] enforce strictNullChecks

- packages/eslint-plugin/src/rules/no-inferrable-types.ts
- packages/eslint-plugin/tests/rules/no-inferrable-types.test.ts
> fix(eslint-plugin): [no-inferrable-types] handle accessor

- packages/eslint-plugin/docs/rules/prefer-optional-chain.mdx
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/prefer-optional-chain.shot
Fixed examples for checkAny, checkUnknown, checkString, checkNumber, checkBoolean, checkBigInt, and requireNullish
> docs: [prefer-optional-chain] fix examples

- .gitattributes
- Coming over from https://discord.com/channels/1026804805894672454/1337869927041732670/1338395779764715540
> chore: make line endings more consistent

- packages/eslint-plugin/src/rules/unified-signatures.ts
- packages/eslint-plugin/tests/rules/unified-signatures.test.ts
> fix(eslint-plugin): [unified-signatures] handle getter-setter

- packages/eslint-plugin/src/rules/no-deprecated.ts
- packages/eslint-plugin/tests/rules/no-deprecated.test.ts
This PR addresses #10838 and adds checks around private identifiers.
> fix(eslint-plugin): [no-deprecated] report usage of deprecated private identifiers

- packages/eslint-plugin/docs/rules/consistent-type-definitions.mdx
Adds FAQs with a comparison table explaining where they differ or are the same. I intentionally put the same number of ✅s for each side in the comparison table to try to convey that they're both fine to use, as long as a codebase remains consistent.
💖
> docs(eslint-plugin): [consistent-type-definitions] add FAQs

- packages/integration-tests/tests/__snapshots__/vue-sfc.test.ts.snap
> chore: update vue-sfc.test.ts snapshot

- packages/eslint-plugin-internal/src/rules/no-relative-paths-to-internal-packages.ts
- packages/eslint-plugin-internal/tests/rules/no-relative-paths-to-internal-packages.test.ts
- packages/typescript-estree/tests/lib/tsVersionRangeSync.test.ts
- packages/website/src/components/editor/useSandboxServices.ts
> chore(eslint-plugin-internal): [no-relative-paths-to-internal-packages] allow relative imports of the root package.json (#10817)

- packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
- packages/integration-tests/fixtures/flat-config-types-@types__eslint-v8/eslint.config.js
- packages/integration-tests/fixtures/flat-config-types-@types__eslint-v8/package.json
- packages/integration-tests/fixtures/flat-config-types-@types__eslint-v9/eslint.config.js
- packages/integration-tests/fixtures/flat-config-types-@types__eslint-v9/package.json
- packages/integration-tests/tests/__snapshots__/flat-config-types-@types__eslint-v8.test.ts.snap
- packages/integration-tests/tests/__snapshots__/flat-config-types-@types__eslint-v9.test.ts.snap
Fixes failing integration-tests.
> chore: fix integration-tests

- project.json
Small tweak to make sure that the files owned by the root get typechecked. (can be tested with `yarn typecheck`).
Discussion at https://discord.com/channels/1026804805894672454/1316761403603812414/1345851507253448838
> chore: validate root TS

- packages/types/tsconfig.tools.json
> chore(types): fix `outDir` in `tsconfig.tools.json`

- packages/eslint-plugin/src/rules/no-deprecated.ts
- packages/eslint-plugin/tests/rules/no-deprecated.test.ts
This PR addresses #10828 and adjusts the rule to also check the alias chain for a possible deprecation.
> fix(eslint-plugin): [no-deprecated] report on deprecated imported variable used as property

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
> fix(eslint-plugin): [no-unnecessary-condition] downgrade fix to suggestion

- packages/ast-spec/tsconfig.spec.json
- packages/eslint-plugin-internal/tsconfig.spec.json
- packages/eslint-plugin/tsconfig.spec.json
- packages/integration-tests/tsconfig.spec.json
- packages/parser/tsconfig.spec.json
- packages/rule-schema-to-typescript-types/tsconfig.spec.json
- packages/rule-tester/tsconfig.spec.json
- packages/scope-manager/tsconfig.spec.json
- packages/type-utils/tsconfig.spec.json
- packages/types/tsconfig.spec.json
- packages/typescript-eslint/tsconfig.spec.json
- packages/typescript-estree/tsconfig.spec.json
- packages/utils/tsconfig.build.json
- packages/utils/tsconfig.spec.json
- packages/visitor-keys/tsconfig.spec.json
- tsconfig.repo-config-files.json
> chore: revert `vitest` related changes in `tsconfig` files

- package.json
- yarn.lock
Reverts typescript-eslint/typescript-eslint#11149. Fixes #11169.
> Revert "chore(deps): update dependency eslint-plugin-perfectionist to v4"

- vitest.config.base.mts
> chore: switch `vitest`'s reporter from `verbose` to `default`

- packages/eslint-plugin/src/rules/no-unnecessary-type-conversion.ts
> fix(eslint-plugin): [no-unnecessary-type-conversion] shouldn't have fixable property

- docs/troubleshooting/typed-linting/Performance.mdx
This setting has improved the performance of typed linting of our biggest app (~2.5 million LoC) by a factor of 2x.
> docs: add note about `max-semi-size` to performance section

- packages/project-service/package.json
- packages/tsconfig-utils/package.json
- [] ~Addresses an existing open issue: fixes #000~ quick chore
This way the packages will be able to publish.
💖
> chore: add publishConfig.access: public to project-service, tsconfig-utils

- packages/project-service/package.json
- yarn.lock
> fix(project-service): add missing `typescript` peer dependency

- packages/eslint-plugin/src/rules/prefer-optional-chain.ts
minor mistake in https://github.com/typescript-eslint/typescript-eslint/commit/3f02687d964c1e7888e5db62256d56cd72c4f281#diff-0930f8c99afdfa35e603494b985d53e7aa8a06eeec2f84df75bebccccba91e40L110
> chore(eslint-plugin): [prefer-optional-chain] fix comment placement

- packages/rule-tester/tests/RuleTester.test.ts
Modified the test as suggested in https://github.com/typescript-eslint/typescript-eslint/issues/11285#issuecomment-2999038528
> chore(rule-tester): correct typo in test

- packages/ast-spec/src/legacy-fixtures/basics/fixtures/typed-this/snapshots/2-TSESTree-Tokens.shot
- packages/ast-spec/src/legacy-fixtures/basics/fixtures/typed-this/snapshots/6-AST-Alignment-Tokens.shot
- packages/ast-spec/src/legacy-fixtures/types/fixtures/function-with-this/snapshots/2-TSESTree-Tokens.shot
- packages/ast-spec/src/legacy-fixtures/types/fixtures/function-with-this/snapshots/6-AST-Alignment-Tokens.shot
- packages/ast-spec/src/legacy-fixtures/types/fixtures/this-type-expanded/snapshots/2-TSESTree-Tokens.shot
- packages/ast-spec/src/legacy-fixtures/types/fixtures/this-type-expanded/snapshots/6-AST-Alignment-Tokens.shot
- packages/ast-spec/src/legacy-fixtures/types/fixtures/typeof-this/snapshots/2-TSESTree-Tokens.shot
- packages/ast-spec/src/legacy-fixtures/types/fixtures/typeof-this/snapshots/6-AST-Alignment-Tokens.shot
> chore: update AST snapshots

- packages/typescript-estree/src/convert.ts
> chore(typescript-estree): simplify `convertImportAttributes`

- packages/typescript-estree/src/convert.ts
> chore(typescript-estree): add `Converter#convertChildren()`

- packages/typescript-estree/src/check-modifiers.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/node-utils.ts
> chore(typescript-estree): extract modifier check logic into a separate file
