- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/tests/fixtures/javascript/directives/first-expression.src.js
- packages/typescript-estree/tests/fixtures/javascript/directives/non-unique-directive.src.js
- packages/typescript-estree/tests/lib/__snapshots__/javascript.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
This PR fixes detection of directives:
- all leading string expressions in block should be marked as such unless there is expression of different type in between them
- directives does not have to be unique http://es5.github.io/#x14.1
> A Directive Prologue may contain more than one Use Strict Directive. However, an implementation may issue a warning if this occurs.
> fix: mark only leading string expressions as directives

- .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
- package.json
Thought this could yield useful information up front so that maintainers have to spend less time chasing down this info if it's relevant.
> chore: ask for lib/Node/npm versions in parser issue template

- .travis.yml
- packages/typescript-eslint-parser/package.json
- packages/typescript-eslint-parser/tests/lib/__snapshots__/javascript.ts.snap
- packages/typescript-eslint-parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/typescript-estree/package.json
- yarn.lock
Start of the "proper" monorepo!
I've verified this works with local rebuilds, make a change in typescript-estree, rebuild and it retriggers the test watcher of tyepscript-eslint-parser, for example.
> feat(parser): use monorepo typescript-estree

- .travis.yml
We will still move to azure pipelines, but this is a good speed up in the interim
> build: separate job for integration tests

- packages/eslint-plugin/lib/rules/no-unused-vars.js
- packages/eslint-plugin/tests/lib/rules/no-unused-vars.js
This PR fixes issue with heritage clause in classes and interfaces, it also reduces possible false possitives from class heritage when used as MemberExpression 
fixes: #45
> fix(eslint-plugin): improve detection of used vars in heritage

- packages/eslint-plugin/lib/rules/no-unused-vars.js
- packages/eslint-plugin/tests/lib/rules/no-unused-vars.js
> fix(eslint-plugin): don’t mark `declare class` as unused

- .gitignore
- .vscode/extensions.json
- .vscode/launch.json
- .vscode/settings.json
- add a launch config for debugging the plugin: runs the test for the currently opened file.
- add shared config to make sure everyone's eslint plugin works correctly, and to correctly setup the typescript env
- add extension config to help tell users about what extensions work well with this codebase:
- recommend plugins:
- eslint
- editorconfig
- prettier
- advise against:
- beautify
- jshint
> chore: add vscode shared config files

- packages/parser/tests/lib/__snapshots__/javascript.ts.snap
- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/shared-fixtures/fixtures/javascript/modules/export-async-named-function.src.js
- packages/shared-fixtures/fixtures/javascript/modules/export-const.src.js
- packages/shared-fixtures/fixtures/javascript/modules/export-default-async-named-function.src.js
- packages/shared-fixtures/fixtures/javascript/modules/export-let.src.js
- packages/typescript-estree/src/node-utils.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/javascript.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
This PR fixes range of exported nodes with modifiers, 
`async` keyword was not included into range of `FunctionExpression`
```ts
export async function bar() {}
```
>  fix(ts-estree): include modifiers in exported node range

- packages/eslint-plugin/package.json
- yarn.lock
Managed to forget to add `tsutils` as a true dependency to `eslint-plugin` in #157.
> chore(eslint-plugin): add tsutils as dependency

- packages/eslint-plugin/lib/rules/array-type.js
- packages/eslint-plugin/tests/lib/rules/array-type.js
This PR adds missing brackets for infer in array-type rule
fixes: #172
> fix(eslint-plugin): use bracket for infer in array-type rule

- packages/eslint-plugin/tests/lib/eslint-rules/arrow-parens.js
Regression test for eslint `arrow-parens` rule.
fixes: #14
> test(eslint-plugin): add test case for eslint arrow-parens

- packages/eslint-plugin/lib/util.js
I have found the `metaDocsUrl` is wrong while creating an online playground. This PR fixes it.
> fix(eslint-plugin): fix wrong URL

- packages/eslint-plugin/ROADMAP.md
Update the URL from `https://github.com/bradzacher/@typescript-eslint/eslint-plugin/blob/master/docs/rules` to `https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules`.
Fix https://github.com/typescript-eslint/typescript-eslint/issues/188
> docs(eslint-plugin): fix rule URLs still point to the old repository

- packages/parser/tests/lib/__snapshots__/jsx.ts.snap
- packages/shared-fixtures/fixtures/jsx/tag-names-with-multi-dots-multi.src.js
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/jsx.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
`<a.b.c.d.e.f>` is not correctly parsed, this is test scenario to be fixed
only first 3 namespaces are correctly converted due to https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/typescript-estree/src/convert.ts#L1597
> test(ts-estree): add test for parsing nested jsx tag names

- packages/eslint-plugin/ROADMAP.md
- Add [@typescript-eslint/restrict-plus-operands](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/restrict-plus-operands.md) to the roadmap. It used to be `N/A` even though the rule was already implemented.
- Remove the duplicated `function-name` row ([here](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md#miscellaneous)) from the roadmap.
> docs(eslint-plugin): add missing rule and remove duplicate rule

- packages/parser/tests/lib/__snapshots__/jsx.ts.snap
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/convert.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/jsx.ts.snap
- packages/typescript-estree/tests/lib/convert.ts
Changes:
- fix issue with nested jsx tag names `<a.b.c.d.e.f.g>`
- simplify conversion and determining if node is jsx tag name
- make sure that jsx tag names are added to `tsNodeToESTreeNodeMap` and `esTreeNodeToTSNodeMap`
>  fix(ts-estree): fix issue with nested jsx tag names

- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tests/lib/__snapshots__/convert.ts.snap
- packages/typescript-estree/tests/lib/convert.ts
- packages/typescript-estree/tests/lib/parse.ts
This PR adds missing test cases for converter and parse in ts-estree
> test(ts-estree): add missing test cases for parser options

- package.json
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- yarn.lock
babel 7.3.2 got released yesterday, and this pr upgrades changes in alignment tests.
babel reports now error on invalid usage of identifiers/keywords in strict mode, 
typescript has `TS1100: "Invalid use of '{0}' in strict mode."`, but i'm unsure if we want to error on this code.
> test(ts-estree): upgrade babel to 7.3.2

- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
- packages/typescript-estree/tests/lib/comments.ts
- packages/typescript-estree/tests/lib/semantic-diagnostics-enabled.ts
- packages/typescript-estree/tests/lib/tsx.ts
- packages/typescript-estree/tests/lib/typescript.ts
- packages/typescript-estree/tools/test-utils.ts
files with js, jsx, tsx extensions should be parsed as "JSX" in semantic-diagnostics tests
> test(ts-estree): correct jsx for semantic-diagnostics tests

- packages/eslint-plugin/lib/rules/adjacent-overload-signatures.js
- packages/eslint-plugin/tests/lib/rules/adjacent-overload-signatures.js
`adjacent-overload-signatures` rule won't distinguish between static and instance methods, despite they're different. So when they have the same name, they'll be treated as the same thing, which can cause a false positive result.
Fix https://github.com/typescript-eslint/typescript-eslint/issues/169
> fix(eslint-plugin): fix false positive from adjacent-overload-signatures

- packages/eslint-plugin/ROADMAP.md
As discussed, they are too awkward to manually maintain when multiple plugin PRs are open at the same time.
We can revisit and look at a way to autogenerate.
> docs(eslint-plugin): removed counts from ROADMAP

- packages/eslint-plugin/lib/rules/prefer-function-type.js
Got confused by the rule name change and forgot to leave this part unchanged.
> docs(eslint-plugin): fix metadata for prefer-function-type

- packages/eslint-plugin/ROADMAP.md
Some links were broken in the roadmap for various reasons:
- `@typescript-eslint/promise-function-async` didn't have a
reference link at the bottom to refer to.
- `@typescript-eslint/no-unnecessary-qualifier` had an extra
`[no-unnecessary-qualifier]` reference at the end, like it
was both an ESLint rule *and* a typescript-eslint rule, which
isn't correct. This broke parsing of the link.
This docs update/fix can be easily verified as correct by visiting my fork with the
[corrected roadmap](https://github.com/dbpiper/typescript-eslint/blob/fix-broken-roadmap-links/packages/eslint-plugin/ROADMAP.md)
> docs(eslint-plugin): fix broken links in the roadmap

- packages/eslint-plugin/docs/rules/no-type-alias.md
allowsLiterals -> allowLiterals
> docs(eslint-plugin): no-type-alias: Fix Typo

- packages/eslint-plugin/src/util/createRule.ts
The docs URL was missing a "v" before the version number and I put it there. 
I think it got lost in [the previous PR](https://github.com/typescript-eslint/typescript-eslint/pull/71).
> docs(typescript-eslint): correct version typo in documentation url

- .eslintrc.json
- packages/eslint-plugin-tslint/src/custom-linter.ts
- packages/eslint-plugin-tslint/src/index.ts
- packages/eslint-plugin-tslint/tests/index.spec.ts
This PR adds missing regression tests for eslint-plugin-tslint and enables linting of tests files in plugin
> test(plugin-tslint): missing test cases for eslint-plugin-tslint

- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/tests/rules/member-ordering.test.ts
Fixes Cannot read property 'replace' of undefined error when
unknown node types are used in the source code.
Also adds TODO comments for missing node types.
---
**Some background information:**
There are several node types that are not implemented yet, like:
- TSCallSignatureDeclaration
- TSIndexSignature
- TSAbstractClassProperty
- TSAbstractMethodDefinition
- ...?
In that case, the current implementation returns `Number.MAX_SAFE_INTEGER` to increase the order ranking. In `getLowestRank`, however, this number is used as index for `order` which will obviously fail in some cases.
In my case, the `rank` in `getLowestRank` was an array that looked like this `[ 3, 3, 16, 9007199254740991 ]`. This threw:
```
TypeError: Cannot read property 'replace' of undefined
at getLowestRank …
```
> fix(eslint-plugin): out-of-bounds access in member-ordering rule

- packages/eslint-plugin/docs/rules/no-useless-constructor.md
it should be the plugin rule name, than eslint core rule name.
> docs(eslint-plugin): fix no-useless-constructor examples

- packages/eslint-plugin/src/rules/interface-name-prefix.ts
- packages/eslint-plugin/tests/rules/interface-name-prefix.test.ts
interface-name-prefix currenlty provides 'Interface name must not be
prefixed with "I".' but when in always mode it should give an error
message that matches the intent, added 'Interface name must be prefixed
with "I".' for when "always" is enabled
> fix: 🐛 When using always have a different error message

- packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
- packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
- packages/eslint-plugin/src/rules/member-naming.ts
- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/src/util/misc.ts
- packages/eslint-plugin/tests/rules/adjacent-overload-signatures.test.ts
- packages/eslint-plugin/typings/ts-eslint.d.ts
- packages/typescript-estree/src/ts-estree/ts-estree.ts
Currently, the name of a method definition or a class property is always assumed to be a literal or an identifier. However, this fails to account for computed property names.
In those cases, we currently sometimes give the name for a method definition with a computed name as `undefined`, which as a result causes methods with differing computed property names to be marked as overloads of each other. In this PR, we slice the text of the computed property name out to handle these cases.
> fix(eslint-plugin): fix false positives for adjacent-overload-signatures regarding computed property names

- packages/eslint-plugin/docs/rules/member-ordering.md
- packages/eslint-plugin/src/rules/member-ordering.ts
Part of the [PR to enforce an alphabetic order for members](https://github.com/typescript-eslint/typescript-eslint/pull/2639) is to rewrite the existing docs to better document the current behavior of `member-ordering`. As this touches almost any line in the rule documentation, I thought it makes sense to open a separate PR for that.
In this PR, I've reworked the entire rule documentation to make it (hopefully) more clear how this rule works. The examples are mostly taken from the current rule documentation - some with little adaptations.
Besides that, I've changed a few names and added some comments in the rule implementation to make it more understandable (basically the points I didn't understand immediately while trying to understand the current implementation to better describe the …
> docs(eslint-plugin): rewrite member-ordering docs

- .eslintrc.json
- packages/typescript-estree/src/tsconfig-parser.ts
Addressing #243 
Currently we are creating a new `ts.Program` for every subsequent file linted after the first in a given run with the `project` object given.
Here we cut down the number of times this happens by ensuring we only tell the TS API that a file has changed when we lint a file for a second time (thereby implying a `--fix` mode or "watch" mode).
> fix(typescript-estree): only call watch callback on new files

- packages/eslint-plugin/src/rules/camelcase.ts
- packages/eslint-plugin/src/rules/no-object-literal-type-assertion.ts
It causes incorrect document address in VS Code
> fix(eslint-plugin): fix incorrect rule name

- packages/eslint-plugin/docs/rules/member-naming.md
- packages/eslint-plugin/src/rules/member-naming.ts
- packages/eslint-plugin/tests/rules/member-naming.test.ts
updating rule prevent applying naming conventtions to constructor methods, fixes #359
> fix(eslint-plugin): member-naming

- packages/typescript-estree/src/ts-estree/ts-estree.ts
I have this example:
https://astexplorer.net/#/gist/2c50aae34bea149fc9863a2dd0e7a6f5/69d563ee31f1bc01d3cf71c005bb92dd24c3910e
Notice how
```
export default class Foo {}
```
Is transformed to:
```
{
"type": "ExportDefaultDeclaration",
"declaration": {
"type": "ClassDeclaration",
"id": {
"type": "Identifier",
"name": "Foo",
"range": [
580,
583
],
"loc": {
"start": {
"line": 30,
"column": 21
},
"end": {
"line": 30,
"column": 24
}
}
},
"body": {
"type": "ClassBody",
"body": [],
"range": [
584,
586
],
"loc": {
"start": {
"line": 30,
"column": 25
},
"end": {
"line": 30,
"column": 27
}
}
},
"superClass": null,
"range": [
574,
586
],
"loc": {
"start": {
"line": 30,
"column": 15
},
"end": {
"line": 30,
"column": 27
}
}
},
"range": [
559,
586
],
"loc": {
"start": {
"line": 30,
"column": 0
},
"end": …
```
> fix(typescript-estree): add ExportDefaultDeclaration to union DeclarationStatement

- packages/eslint-plugin/src/rules/no-type-alias.ts
- packages/eslint-plugin/tests/rules/no-type-alias.test.ts
I was running into an issue with the rule crashing on code like
```
type Foo =
| typeof Bar
| typeof Baz;
```
I thought it was because of the `|` being first, but when I added that test it passed. Seems like it's actually because the `TSTypeQuery` node type is never handled. I'm not sure if this is the right fix, though.
Also kind of relates to #270. Potential crash isn't caught in compile because of non-null assertion on line 216 in rules/no-type-alias.ts, but that seems like a bigger change.
> fix(eslint-plugin): no-type-alias: fix typeof alias erroring

- packages/eslint-plugin/docs/rules/explicit-function-return-type.md
- packages/eslint-plugin/src/rules/explicit-function-return-type.ts
- packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Fixes #387 
Also add documentation for the `allowTypedFunctionExpressions` which I forgot in my previous PR on this rule.
> fix(eslint-plugin): Fix `allowExpressions` false positives in explicit-function-return-type and incorrect documentation

- packages/typescript-estree/src/tsconfig-parser.ts
- packages/typescript-estree/tests/lib/semanticInfo.ts
Per conversation in #361 with @uniqueiniquity, I've pulled these small improvements out of the work there as they're likely worth merging on their own, whereas the rest of that PR likely isn't.
It's notable that the caching test now passes on master, as it didn't when I first wrote it; further confirmation that the change in #367 matches the improvements of #361 (but with much less code change 😄).
> chore: add some tests and refactor tsconfig path resolution

- packages/eslint-plugin/docs/rules/no-object-literal-type-assertion.md
This doc change was overlooked when the feature was added in #390.
> docs(eslint-plugin): `as const` with no-object-literal-type-assertion

- .huskyrc
- azure-pipelines.yml
- package.json
Closes #259 
We have too many tests to run at commit time now.
I would also say that there are too many to run at push time, as well.
Our CI will run all of the tests (incl integration tests), so there's no need to force contributors to wait through a full test cycle every commit/push.
- change pre-commit hook to only run prettier.
- commit hooks are used regularly, so we want it to be as lightweight as possible.
- add pre-push hook which runs lint + typecheck + format.
- these are all much heavier (total i find takes ~30-40s), but I think it's good to try and block pushes because of these - some of the most common errors I see are lint problems or unformatted files.
---
My question (for @JamesHenry, who I think added it?), is do we need commitizen? It's just admins that can push to …
> chore: simplify git hooks

- packages/eslint-plugin/docs/rules/explicit-function-return-type.md
- packages/eslint-plugin/src/rules/explicit-function-return-type.ts
- packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Fixes #408
Adds support for 3 cases:
```ts
let asTyped = (() => '') as () => string;
interface ObjectType {
foo(): number;
}
let objectProp: ObjectType = {
foo: () => 1,
};
interface ObjectType {
foo(): number;
}
let asObjectProp = {
foo: () => 1,
} as ObjectType;
```
> fix(eslint-plugin): support object types and as expressions [explicit-func-return-type]

- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/eslint-plugin/tests/rules/unbound-method.test.ts
Fixes #451 
added given example as positive test and switch-statement to `isSafeUse`.
> fix(eslint-plugin): support switch statement [unbound-method]

- package.json
- packages/eslint-plugin-tslint/tests/index.spec.ts
- packages/parser/tests/lib/__snapshots__/scope-analysis.ts.snap
- yarn.lock
Fixes #486 
I ran `yarn upgrade` ~~and added node-gyp to resolve for versions ^4.0.0~~
> fix: yarn audit

- packages/eslint-plugin/ROADMAP.md
There was a typo in the ESLint rule name. The link is correct, though.
> docs: rename no-unused-expression to no-unused-expressions

- packages/typescript-estree/README.md
- packages/typescript-estree/src/ast-converter.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/parser-options.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tests/lib/convert.ts
- packages/typescript-estree/tests/lib/parse.ts
I have been working on converting some user-land custom TSLint rules to ESLint and this feature has come from that work.
- In many cases, I am discovering migrating custom TSLint rules to ESLint is _far_ easier if you first migrate the "infrastructure" over (all the rule and RuleTester config), but keep the rule logic largely the same. (With the idea that you can truly migrate the implementation at some point later).
- Naturally, this is only possible if you have access to the two-way AST node maps that _may_ be preserved during conversion.
- Preserving the AST node maps is currently only possible if using the `project` option. This is a good start, but as we know the `project` feature is expensive because of its requirement to create full TypeScript Programs.
- If a custom TSLint rule …
> feat(ts-estree): add preserveNodeMaps option

- packages/typescript-estree/src/tsconfig-parser.ts
Fixes #498 
When getting the updated program from the TS watch program, it doesn't automatically set parent pointers in the contained source files (which we then traverse as ASTs). By getting the type checker, it triggers a side effect to set those parent pointers.
> fix(typescript-estree): ensure parents are defined

- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/eslint-plugin/tests/rules/unbound-method.test.ts
> fix(eslint-plugin): [unbound-method] Work around class prototype bug

- packages/eslint-plugin/docs/rules/explicit-function-return-type.md
- packages/eslint-plugin/src/rules/explicit-function-return-type.ts
- packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Fixes #484 
- Also cleaned up the docs
- Also added handling for angle bracket casts
> fix(eslint-plugin): [explicit-function-return-type] Add handling for class properties

- packages/eslint-plugin-tslint/package.json
- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/rules/no-extra-parens.ts
- packages/eslint-plugin/tests/RuleTester.ts
- packages/eslint-plugin/tests/rules/no-extra-parens.test.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
- packages/eslint-plugin/typings/ts-eslint.d.ts
- packages/parser/package.json
- packages/typescript-estree/package.json
- packages/typescript-estree/src/ts-estree/ts-estree.ts
Fixes #460
- Added a format command to each package, because I was annoyed with having to `cd ../..` up to format when I was in the eslint-plugin folder. Also means that it narrows down the number of files formatted which makes it a smidge faster.
- Added a new test util which auto splits batched single line test cases which:
- provides nicer test output messages during testing because it separates them into multiple tests automatically (see below)
- makes it easier to define test with the same options.
- handles the types automatically.
I'll look into migrating existing tests to it after this PR is merged.
```ts
batchedSingleLineTests({
code: `
one
two
three
`,
options: ['opt']
errors: [
{ line: 2, message: 'err one' },
{ line: 3, message: 'err two' },
{ line: 4, message: 'err three' }, …
```
> fix(eslint-plugin): Support more nodes [no-extra-parens]

- packages/experimental-utils/src/ts-eslint/RuleTester.ts
The `end{Line,Column}` are nice to verify ranges of error messages.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2194a1ac8b3e83a882b07257a8dfdc94b5fe2b72/types/eslint/index.d.ts#L565-L574
https://github.com/typescript-eslint/typescript-eslint/blob/89c87cc607172c5cd3f49a563ac283441632fbff/packages/experimental-utils/src/ts-eslint/Linter.ts#L95-L96
Couldn't find anywhere where its omission was discussed
---
Thanks so much for publishing these! Will be converting `eslint-plugin-jest` to use them.
> fix(experimental-utils): add `endLine` and `endColumn`

- packages/eslint-plugin/src/configs/eslint-recommended.ts
This disables the `no-dupe-class-members` rule in `eslint-recommended`. The rule is already checked by Typescript.
Since the rules are less strict, this shouldn't be a breaking change. However, I'm unsure whether this counts as a patch or a feature release.
> fix(eslint-plugin): Remove `no-dupe-class-members` from eslint-recommended

- packages/eslint-plugin-tslint/package.json
- packages/eslint-plugin/package.json
- packages/experimental-utils/package.json
- packages/parser/package.json
- packages/typescript-estree/package.json
Documentation: https://docs.npmjs.com/files/package.json#repository.
Hopefully this will fix the broken links in
https://www.npmjs.com/package/@typescript-eslint/eslint-plugin#supported-rules.
> chore: Add repository.directory to all package.json

- packages/eslint-plugin/docs/rules/no-extraneous-class.md
Docs for `no-extraneous-class` list the following options:
- `constructorOnly`
- `allowEmpty`
- `staticOnly`
However in the rule source, these options are actually named:
- `allowContructorOnly`
- `allowEmpty`
- `allowStaticOnly`
This PR updates the docs to match the rule schema.
> docs(eslint-plugin): [no-extraneous-class] fix option keys

- packages/eslint-plugin/tests/rules/promise-function-async.test.ts
It seems like the rule is already smart enough to not check special methods (`get`, `set`, and `constructor` kinds), so i just added regression tests for them. As these kinds of methods cannot be marked `async`, the rule shouldn't check them in the first place.
refs #553
> test(eslint-plugin): [promise-function-async] Add regression tests for invalid async modifiers

- packages/eslint-plugin/docs/rules/explicit-function-return-type.md
- packages/eslint-plugin/src/rules/explicit-function-return-type.ts
- packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
The last comment of #193 said that you were _Accepting PRs from the community (we love new contributors!!)_, and I really wanted #193 implemented, so... I gave it a shot, and... it _seems_ to work? All the existing tests and the 3 new ones I wrote for this seems to run fine at least? 🤔 🎉
Fixes #193
> feat(eslint-plugin): [explicit-function-return-type] allowHigherOrderFunctions (#193)

- packages/experimental-utils/src/index.ts
See: https://github.com/typescript-eslint/typescript-eslint/pull/425#issuecomment-498162293
> fix(experimental-utils): Avoid typescript import at runtime

- .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
Minor, but caught my eye as I submitted an issue
> chore: Change config default for eslint-plugin-typescript issue to use correct prefix

- packages/typescript-estree/src/ts-estree/ts-estree.ts
Currently `ExportDefaultDeclaration` is locked down to only `ExportDeclaration`, but expressions are also valid. For example:
```ts
export default new Foo();
export default 123;
export default bar;
```
> fix(typescript-estree): allow expressions in ExportDefaultDeclaration

- packages/eslint-plugin/src/rules/no-type-alias.ts
- packages/eslint-plugin/tests/rules/no-type-alias.test.ts
Fixes #575
It was going to be annoying to insert `if`s all over the place so I refactored the logic to make it cleaner.
> fix(eslint-plugin): [no-type-alias] Fix parenthesized type handling

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/src/util/types.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Fixes #529
Strict mode doesn't let you assign a null to an undefined.
This fixes the check to make sure the two types share a nullable type.
> fix(eslint-plugin): [no-unnecessary-type-assertion] false positive for null assign to undefined

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/src/util/types.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Fixes #532
The example in the issue works fine as long as all the required declarations are attached.
If something is missing, then it breaks because the code was assuming valid typescript.
>  fix(eslint-plugin): [no-unnecessary-type-assertion] handle missing declarations

- packages/eslint-plugin/package.json
Fixes https://github.com/typescript-eslint/typescript-eslint/issues/601
Needed because of https://github.com/lerna/lerna/pull/1187
> fix(eslint-plugin): peerDep should specify semver major range

- packages/experimental-utils/src/ts-eslint/RuleTester.ts
The definition of `RunTests` is duplicated...
Is there any reason for that?
> fix(eslint-plugin): Remove duplicated code

- packages/eslint-plugin/docs/rules/no-explicit-any.md
- packages/eslint-plugin/src/rules/no-explicit-any.ts
- packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
> feat(eslint-plugin): [no-explicit-any] ignoreRestArgs

- packages/eslint-plugin/docs/rules/no-magic-numbers.md
- packages/eslint-plugin/src/rules/no-magic-numbers.ts
- packages/eslint-plugin/tests/rules/no-magic-numbers.test.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
Fixes #573.
Currently, the following code will fail to lint using the default no-magic-numbers configuration
```
enum foo {
SECOND = 1000,
NUM = '0123456789',
}
```
One could make the argument that perhaps we instead want to define it in some other way, perhaps using constants and referring to them such as:
```
const MS_SECONDS = 1000;
enum foo {
SECOND = MS_SECONDS,
NUM = '0123456789',
}
```
However, this will result in a compiler error `Computed values are not permitted in an enum with string valued members.ts(2553)`.
I made these changes to resolve that problem. I tried to follow the existing code pattern as much as possible, however, I am open to changes. I also assumed updating the documentation would be unnecessary for this fix, let me know if we would like a change there and I'll …
> fix(eslint-plugin): [no-magic-numbers] add support for enums

- packages/eslint-plugin/docs/rules/no-explicit-any.md
Remove stray word from doc
on-behalf-of: @wmde <software@wikimedia.de>
> docs(eslint-plugin): [no-explicit-any] correct docs

- packages/eslint-plugin/docs/rules/promise-function-async.md
- packages/eslint-plugin/src/rules/promise-function-async.ts
- packages/eslint-plugin/src/util/types.ts
- packages/eslint-plugin/tests/rules/promise-function-async.test.ts
refs #369 
i guess it could be improved, but it solves the most obvious issues.
> feat(eslint-plugin): [promise-function-async] Allow any and unknown as return values

- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/shared-fixtures/fixtures/typescript/basics/keyword-variables.src.ts
- packages/typescript-estree/src/node-utils.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Fixes #678
The `async` keyword wasn't correctly handled in the parser with respect to variable names, so the token it created was typed as `Keyword` instead of `Identifier`
> fix(typescript-estree): fix `async` identifier token typed as `Keyword`

- packages/eslint-plugin/docs/rules/explicit-function-return-type.md
- packages/eslint-plugin/src/rules/explicit-function-return-type.ts
- packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Fixes #679 
This wasn't ever added to the implementation for some reason.
> feat(eslint-plugin): [explicit-function-return-type] add handling for usage as arguments

- packages/eslint-plugin-tslint/package.json
- packages/eslint-plugin/package.json
- packages/experimental-utils/package.json
As per https://github.com/typescript-eslint/typescript-eslint/issues/36#issuecomment-508748273
The dependencies weren't declare correctly.
> fix: Correct `@types/json-schema` dependency

- packages/eslint-plugin/src/rules/prefer-readonly.ts
- packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
- packages/eslint-plugin/src/rules/triple-slash-reference.ts
> fix(eslint-plugin): remove imports from typescript-estree

- packages/experimental-utils/src/ts-eslint/RuleTester.ts
As briefly discussed in #425.
Background is that I want to use these utils for authoring eslint rules, but I want the tests to run using the default parser as the rules do not need type info
> fix(utils): RuleTester should not require a parser

- packages/eslint-plugin/docs/rules/semi.md
Both are related to semicolons, so let’s help looking for member-delimiter-style by linking it here.
---
Follow-up for #714, where I misunderstood what the semi rule is for.
> docs(eslint-plugin): mention member-delimiter-style in semi

- packages/eslint-plugin/docs/rules/no-magic-numbers.md
typo in docs
```
Error: .eslintrc.yml:
Configuration for rule "@typescript-eslint/no-magic-numbers" is invalid:
Value {"ignoreEnum":true,"ignoreNumericLiteralTypes":true,"detectObjects":false,"enforceConst":false,"ignoreArrayIndexes":false} should NOT have additional properties.
```
> docs(eslint-plugin): correct `no-magic-number` docs

- packages/eslint-plugin/docs/rules/no-misused-promises.md
the link was quoted, which does not work
> docs: fix typo in no-misused-promises related links

- packages/experimental-utils/package.json
Done in https://github.com/typescript-eslint/typescript-eslint/pull/535/files#diff-5c11193544492a7547f43d5531701d83 so hopefully fine on its own as well 🙂 
This makes sure we don't get a peer dep warning if an eslint plugin depends on the utils to author the rules but do not need TS when running
> fix(utils): move `typescript` from peer dep to dev dep

- package.json
- yarn.lock
It turns out installing with `yarn --frozen-lockfile` is not enough to catch all lockfile mutations because some of them can occur in child packages via lerna bootstrap.
This happened in https://github.com/typescript-eslint/typescript-eslint/pull/712 and it therefore broke master when it got merged because it breaks the release process (both canary and latest).
Added a git diff based validation to ensure CI fails if lock file updates are missed in future.
**This initial commit should fail**, will add the fix once we have verified it does.
> chore: add check for dirty workspace post-install

- azure-pipelines.yml
- package.json
- packages/eslint-plugin-tslint/package.json
- packages/eslint-plugin-tslint/tests/index.spec.ts
- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/rules/array-type.ts
- packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
- packages/eslint-plugin/tests/RuleTester.ts
- packages/eslint-plugin/tests/eslint-rules/no-redeclare.test.ts
- packages/eslint-plugin/tests/rules/array-type.test.ts
- packages/eslint-plugin/tests/rules/ban-ts-ignore.test.ts
- packages/eslint-plugin/tests/rules/no-triple-slash-reference.test.ts
- packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
- packages/eslint-plugin/tests/rules/type-annotation-spacing.test.ts
- packages/eslint-plugin/typings/eslint-ast-util.d.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
- packages/experimental-utils/src/ts-eslint/RuleTester.ts
- packages/parser/package.json
- packages/typescript-estree/tests/ast-alignment/utils.ts
- yarn.lock
There was some weirdness around now requiring absolute paths for parser in test, but otherwise seemed to "just work"
BREAKING: dropped support for node 6
Fixes #644
Fixes #564
> feat: Support eslint@6

- packages/eslint-plugin/docs/rules/promise-function-async.md
- packages/eslint-plugin/src/rules/promise-function-async.ts
- packages/eslint-plugin/tests/rules/promise-function-async.test.ts
BREAKING CHANGE: changing default rule config
Having functions that return `any` be considered async is weird. I left the option in just in case someone wants this functinoality.
https://github.com/typescript-eslint/typescript-eslint/issues/501#issuecomment-498160270
> feat(eslint-plugin)!: [promise-function-async] make allowAny default true

- azure-pipelines.yml
The automated canary is not picking up on the 2.x and so is publishing 1.x versions on merge to master. Disabling for now until 2.x hits stable
> chore: disable automated canary during 2.x prerelease

- packages/experimental-utils/src/ts-eslint/ParserOptions.ts
See https://eslint.org/docs/user-guide/configuring#specifying-parser-options
> fix(utils): add ES2019 as valid `ecmaVersion`

- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/shared-fixtures/fixtures/typescript/basics/keyword-variables.src.ts
- packages/typescript-estree/src/node-utils.ts
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Fixes #749 
As in #681 (and quoting from that PR), the `is` keyword wasn't correctly handled in the parser with respect to variable names, so the token it created was typed as Keyword instead of Identifier.
I suppose there are other such keywords that are also valid identifiers, but I'm not sure where to find the complete list.
> fix(typescript-estree): fix `is` identifier token typed as `Keyword`

- packages/eslint-plugin/src/rules/no-var-requires.ts
- packages/eslint-plugin/tests/rules/no-var-requires.test.ts
Throwing error if the parent is CallExpression in no-var-requires plugin
Closes: #665
> fix(eslint-plugin): [no-var-requires] error if parent is CallExpression

- packages/eslint-plugin/docs/rules/strict-boolean-expressions.md
- packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
- packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Adds an ignoreRhs option, to match the equivalent option in the tslint version of this rule.
This is a particularly good option to have for react code where [stuff like this is idiomatic](https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator):
```tsx
function MyComponent() {
const shouldRenderFoo: boolean = /*...*/;
return (<div>
{shouldRenderFoo && <span>Foo</span>}
<span>Bar</span>
</div>);
}
```
Fixes #691
> feat(eslint-plugin): [strict-boolean-expressions] add ignoreRhs option

- package.json
- packages/eslint-plugin-tslint/src/rules/config.ts
- tests/integration/docker-compose.yml
- tests/integration/fixtures/typescript-and-tslint-plugins-together/test.js.snap
- tests/integration/fixtures/vue-sfc/.eslintrc.yml
- tests/integration/fixtures/vue-sfc/Dockerfile
- tests/integration/fixtures/vue-sfc/Hello.vue
- tests/integration/fixtures/vue-sfc/test.js.snap
- tests/integration/fixtures/vue-sfc/test.sh
- tests/integration/fixtures/vue-sfc/tsconfig.json
- tests/integration/run-all-tests.sh
Note the first commit should hopefully cause the CI build to fail
The integration tests have been failing for a while but weren't causing CI to fail, this PR addresses that and adds an integration test for a Vue SFC as a follow up to https://github.com/typescript-eslint/typescript-eslint/pull/760
> test: ensure integration tests can fail, add vue-sfc

- packages/eslint-plugin/docs/rules/explicit-function-return-type.md
> docs: fix typo in documentation for explicit-function-return-type

- packages/eslint-plugin/docs/rules/no-explicit-any.md
- packages/eslint-plugin/src/rules/no-explicit-any.ts
- packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
> fix(eslint-plugin): [no-explicit-any] Fix ignoreRestArgs for interfaces

- packages/eslint-plugin/docs/rules/prefer-readonly.md
The "(prefer-readonly)" part wasn't in the title.
> docs(prefer-readonly): add rule name to title

- packages/eslint-plugin/src/rules/typedef.ts
- packages/eslint-plugin/tests/rules/typedef.test.ts
Fixes https://github.com/typescript-eslint/typescript-eslint/issues/784
> fix(eslint-plugin): [@typescript-eslint/typedef] support default value for parameter

- packages/eslint-plugin/src/rules/typedef.ts
- packages/eslint-plugin/tests/rules/typedef.test.ts
> fix(eslint-plugin): [typedef] support "for..in", "for..of"

- packages/eslint-plugin/ROADMAP.md
It seems like the rule already has been [implemented](#373) but some parts of ROADMAP.md hasn't updated. Am I right?(first time here...)
> docs(eslint-plugin): update [no-magic-numbers] on ROADMAP.md

- packages/parser/tests/lib/__snapshots__/comments.ts.snap
- packages/shared-fixtures/fixtures/comments/jsx-tag-comment-after-prop.src.js
- packages/typescript-estree/src/convert-comments.ts
- packages/typescript-estree/tests/lib/__snapshots__/comments.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
Fixes #643
Fixes #648
Fixes #703
The problem is that with the fix performed in https://github.com/typescript-eslint/typescript-eslint/pull/607, when you have something like this:
```
const pure = () => {
return (
<Foo
// one
foo={123}
// two
bar="woof"
/>
);
}
```
We currently perform `reScanJsxToken()` on the closing brace for the `foo` attribute value.
This results in a `SyntaxKind.JsxText` token like this:
```
"}\n        // two\n        bar="woof"\n      />\n  );\n}\n"
```
So the `// two` never gets correctly identified. If we hadn't performed the `reScanJsxToken()` on the `}` closing brace for the JSX expression, the `// two` would have been tokenized correctly.
I have fixed this by changing the rescan call added in the PR referenced earlier to only apply if the JSX expression is …
> fix(typescript-estree): jsx comment parsing

- packages/eslint-plugin/README.md
Spotted a small typo in eslint-plugin.
Let me know if there's other small things I can contribute on.
- JB
> fix(eslint-plugin): readme typo

- .gitattributes
The Git commit hook always fails on Windows because the EOL character is not what Prettier expects it to be.
> chore: eliminate spurious Prettier warnings on Windows

- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
- packages/eslint-plugin/tests/rules/restrict-plus-operands.test.ts
- packages/parser/README.md
- packages/typescript-estree/jest.config.js
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/src/tsconfig-parser.ts
- packages/typescript-estree/tests/fixtures/invalidFileErrors/js/included.js
- packages/typescript-estree/tests/fixtures/invalidFileErrors/js/included.jsx
- packages/typescript-estree/tests/fixtures/invalidFileErrors/js/notIncluded.js
- packages/typescript-estree/tests/fixtures/invalidFileErrors/js/notIncluded.jsx
- packages/typescript-estree/tests/fixtures/invalidFileErrors/other/included.vue
- packages/typescript-estree/tests/fixtures/invalidFileErrors/other/notIncluded.vue
- packages/typescript-estree/tests/fixtures/invalidFileErrors/other/unknownFileType.unknown
- packages/typescript-estree/tests/fixtures/invalidFileErrors/ts/included.ts
- packages/typescript-estree/tests/fixtures/invalidFileErrors/ts/included.tsx
- packages/typescript-estree/tests/fixtures/invalidFileErrors/ts/notIncluded.ts
- packages/typescript-estree/tests/fixtures/invalidFileErrors/ts/notIncluded.tsx
- packages/typescript-estree/tests/fixtures/invalidFileErrors/tsconfig.json
- packages/typescript-estree/tests/lib/__snapshots__/parse.ts.snap
- packages/typescript-estree/tests/lib/parse.ts
- packages/typescript-estree/tests/lib/semanticInfo.ts
- packages/typescript-estree/tsconfig.json
Fixes #853
People were having some problems because we now throw errors if files aren't included in the tsconfig.
This PR:
- Improves the error messages so that required steps to fix the issue are clearer
- Ensures that `allowJs`/`checkJs` are forced on, so that users don't ever have to manually turn it on in their configs.
- This helps the system to "just work" without any real downside.
- Added tests to make sure the errors occur as expected.
- Improved documentation for the parser to clarify the setup for mixed js/ts codebases.
>  fix(typescript-estree): improve error messaging around project files

- packages/eslint-plugin/docs/rules/explicit-member-accessibility.md
Hi,
I found some nitpicks in code examples in the `explicit-member-accessibility` rule document, so I opened this PR to fix them.
If I was doing something wrong, please close this PR.
> docs(eslint-plugin): fix errors in explicit-member-accessibility examples

- packages/parser/package.json
I was wondering why WebStorm was completely ignoring my import:
```
import { parse } from '@typescript-eslint/parser';
```
Turns out it doesn't use `.d.ts` files for packages if they're not included via `types`/`typings`.
`eslint-plugin` also doesn't have this property, but there's not really a reason to import that.
It'd be great if this could be backported to v1, as `eslint-plugin-jest` is still supporting Node 6.
It's not a showstopper by any means, but would be very much appreciated :)
> chore(parser): add `types` field to `package.json`

- packages/eslint-plugin/docs/rules/no-var-requires.md
Fixes #899 
Adds an example to the documentation for replacing `require` with ES6 modules. Since this isn't going to work on everyone's system, I'm happy to also add a comment on this line stating the restrictions if the maintainers of this think it would be appropriate.
> docs(eslint-plugin): no-var-requires: Add example for ES6 modules

- packages/eslint-plugin/src/rules/no-inferrable-types.ts
- packages/eslint-plugin/tests/rules/no-inferrable-types.test.ts
Fixes #902 
> Technically in this case, it is actually a bug in no-inferrable-types.
> foo?: string = 'str' is not inferrable, as the property is optional.
> fix(eslint-plugin): [no-inferrable-types] ignore optional properties

- packages/eslint-plugin/src/rules/typedef.ts
- packages/eslint-plugin/tests/rules/typedef.test.ts
This is a potential fix for #921.
The node with the `TSParameterProperty` type can contains the node with the `AssignmentPattern` type. In this case, we should check type annotations for the node with `AssignmentPattern`  type.
```ts
class Something {
// Works fine without `= {}`
constructor(private readonly _options: Options = {}) {
//         ^                 ^ AssignmentPattern
//         | TSParameterProperty
//                                               
}
}
```
> fix(eslint-plugin): [typedef] handle AssignmentPattern inside TSParameterProperty

- packages/eslint-plugin/src/rules/explicit-function-return-type.ts
- packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
> fix(eslint-plugin): [explicit-function-return-type] make error location smaller

- packages/eslint-plugin/docs/rules/explicit-function-return-type.md
- packages/eslint-plugin/docs/rules/explicit-member-accessibility.md
As per #906 - add a section to the readme for these two rules as they both will not work on JS code.
> docs(eslint-plugin): document mixed codebase usage for efrt/ema

- README.md
Update the docs to match the change in #916 (i.e. support up to  <3.7.0)
> docs(readme): Update supported TypeScript version range

- packages/eslint-plugin/src/rules/triple-slash-reference.ts
- packages/typescript-estree/src/ts-estree/ts-estree.ts
According to [the spec](https://github.com/estree/estree/blob/master/es2015.md#importdeclaration), `ImportDeclaration.source` should have type `Literal`
> fix(typescript-estree): ImportDeclaration.specifier to Literal

- packages/eslint-plugin/docs/rules/typedef.md
Updated rule name, typedef to @typescript-eslint/typedef
> docs(eslint-plugin): fix typo in typedef docs

- packages/eslint-plugin/src/rules/promise-function-async.ts
- packages/eslint-plugin/tests/rules/promise-function-async.test.ts
In #820, support was added for getters/setters that return async functions, e.g.
```ts
const someObject = {
get asyncGetterFunc() {
return async () => new Promise<void>();
},
set asyncGetterFunc(p: () => Promise<void>) {
return p;
}
}
```
Unfortunately, the previous fix only handles getters/setters on objects (the implementation specifically checks for `node.parent.type === 'Property'`).
As it turns out, getter/setters on classes have `node.parent.type === 'MethodDeclaration'`, so the following code still generates warnings:
```ts
class SomeClass = {
get asyncGetterFunc() {
return async () => new Promise<void>();
},
set asyncGetterFunc(p: () => Promise<void>) {
return p;
}
}
```
This PR addresses the class getter/setter case, by checking if `node.parent.type === 'Property' || …
> fix(eslint-plugin): [pfa] Allow async getter/setter in classes

- packages/eslint-plugin/src/rules/consistent-type-assertions.ts
- packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
> fix(eslint-plugin): [cons-type-assns] handle namespaced types

- packages/eslint-plugin/ROADMAP.md
Link to `@typescript-eslint/strict-boolean-expressions` is currently missing from [ROADMAP.md].
[ROADMAP.md]:https://github.com/typescript-eslint/typescript-eslint/blob/90b36ddac2f6de006fd59f2a9234df1eb2d1606e/packages/eslint-plugin/ROADMAP.md
> docs(eslint-plugin): add missing ROADMAP link

- packages/eslint-plugin/src/rules/indent.ts
- packages/typescript-estree/src/ts-estree/ts-estree.ts
According to [the spec](https://github.com/estree/estree/blob/master/es2015.md#classes), `ClassDeclarationBase.id` and `ClassDeclarationBase.superClass` are always present and nullable
> fix(typescript-estree): correct ClassDeclarationBase type

- packages/experimental-utils/src/ts-eslint/Rule.ts
`Rule.meta.extraDescription` is [not documented](https://eslint.org/docs/developer-guide/working-with-rules#rule-basics) and never used, so it might be confusing for consumers of `experimental-utils` package
> fix(experimental-utils): remove Rule.meta.extraDescription

- packages/eslint-plugin/src/rules/class-name-casing.ts
- packages/eslint-plugin/tests/rules/class-name-casing.test.ts
> fix(eslint-plugin): [class-name-casing] allow unicode letters

- packages/typescript-estree/README.md
- packages/typescript-estree/package.json
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/src/tsconfig-parser.ts
- yarn.lock
Fixes #1080
I followed typescript's lead here, and fall back to polling if `chokidar` throws an error when attempting to use fs watchers.
I also added support for reusing watchers, to attempt to conserve resources, and reduce the total number of watchers that we setup.
I also decided it was time to setup some logging to help with debugging.
The logging can be shown via `DEBUG=typescript-eslint:* yarn lint`
> fix(typescript-estree): handle running out of fs watchers

- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tests/lib/warn-on-unsupported-ts.ts
Not sure if this is fine. I got this warning and ran `npm ls typescript-estree` in my project but that didn't return any results. Turns out that it was missing the scope of the package.
> chore(typescript-estree): fix package name in warning message

- package.json
- packages/typescript-estree/src/parser.ts
- yarn.lock
It wasn't matching 3.6.4 as valid because I missed the pipe.
> fix(typescript-estree): correct semver check range

- packages/eslint-plugin/docs/rules/no-unnecessary-condition.md
> docs(eslint-plugin): typo in no-unnecessary-condition.md

- packages/typescript-estree/src/create-program/createWatchProgram.ts
- packages/typescript-estree/src/create-program/shared.ts
- packages/typescript-estree/tests/lib/persistentParse.ts
- packages/typescript-estree/tests/lib/semanticInfo.ts
Whilst investigating #1110, I found that there are some cases where typescript will give us their "canonical path" instead of the actual path.
This is a problem on unix because the canonical path is all lower case, which means we can fail to fire directory updates, because the watcher path doesn't match.
This PR adds a pseudo-nominal type (waiting for the day typescript adds it for real) which ensures (at typecheck time) that the canonical path passed in where required.
> fix(typescript-estree): better handle canonical paths

- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tests/lib/warn-on-unsupported-ts.ts
Currently the Warning regarding the versions mismatch breaks other tools, like ALE for vim.
Since some tools depend on the output to the stdout to be a well formatted json.
This fixes the issue by allowing tools to use the parser without getting the warning, but still displaying the warning if the user triggers the command from the terminal. 
Fixes #1060
> fix(typescript-estree): check TTY before version mismatch warning

- packages/typescript-estree/src/create-program/shared.ts
Fixes #1126
Windows paths can come in with forward or back slashes.
Need to normalize the paths so they have the same slashes.
NGL switching from mac to windows to do this was so painful.
> fix(typescript-estree): normalize paths to fix cache miss on windows

- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/shared-fixtures/fixtures/typescript/basics/optional-chain-call-with-parens.src.ts
- packages/shared-fixtures/fixtures/typescript/basics/optional-chain-call.src.ts
- packages/shared-fixtures/fixtures/typescript/basics/optional-chain-element-access-with-parens.src.ts
- packages/shared-fixtures/fixtures/typescript/basics/optional-chain-with-parens.src.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/create-program/shared.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
Fixes #1139
Also fixes the package not working in the browser (`ts.sys === undefined` in the browser).
The snapshots are getting pretty ugly now.
I think we need a new system for them (#1142).
I tested this via a local build of ASTExplorer.
Sidebar - we should really maintain our own version of it (#1143).
> fix(typescript-estree): correct parenthesized optional chain AST

- packages/eslint-plugin/docs/rules/no-unnecessary-condition.md
- packages/eslint-plugin/docs/rules/strict-boolean-expressions.md
Fixes #1016.
Removes "looser/stricter" wording in favor of "more opinionated, less opinionated" and clarifies in what way `no-unnecessary-condition` is less opinionated.
> docs(eslint-plugin): [no-unnecessary-condition] tweak wording

- packages/eslint-plugin/src/rules/array-type.ts
- packages/eslint-plugin/tests/rules/array-type.test.ts
> fix(eslint-plugin): crash fixing readonly arrays to generic

- packages/typescript-estree/src/convert-comments.ts
> If you don't need everything offered by this package, you can select what should be imported.
-- from https://www.npmjs.com/package/tsutils
> fix(typescript-estree): reduce bundle footprint of tsutils

- packages/eslint-plugin/docs/rules/no-type-alias.md
- packages/eslint-plugin/src/rules/no-type-alias.ts
- packages/eslint-plugin/tests/rules/no-type-alias.test.ts
> fix(eslint-plugin): [no-type-alias] handle constructor aliases

- packages/eslint-plugin/ROADMAP.md
It seems that the `eslint` core brace-style could replace the one-line `tslint` rule. See https://github.com/eslint/eslint/issues/12559#issuecomment-553213226
(maybe letting prettier do the work is also a good solution)
> docs(eslint-plugin): brace-style as a replacement for one-line

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Discovered that conditions involving a naked type param were being incorrectly considered "unnecessary":
```ts
function test<T>(t: T) {
// raised an error here
return t ? 'yes' : 'no'
}
```
> fix(eslint-plugin): [no-unnecessary-cond] fix naked type param

- packages/eslint-plugin/src/rules/indent.ts
- packages/eslint-plugin/tests/rules/indent/indent.test.ts
> fix(eslint-plugin): [indent] handle empty generic declarations

- README.md
"comprised of" is incorrect, since "comprise" means "to include" and refers to the whole, not the parts. Change "comprised of" to "composed of". See https://www.dictionary.com/e/comprise-vs-compose/ for an explanation.
> docs: tweak grammar

- packages/eslint-plugin/src/rules/require-await.ts
- packages/eslint-plugin/tests/rules/require-await.test.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
Fixes #1226
There wasn't a test case for a non-async function that returned a promise.
> fix(eslint-plugin): [req-await] crash on nonasync promise return

- packages/typescript-estree/src/visitor-keys.ts
The generated `.d.ts` file would be something like
```
import * as eslintVisitorKeys from 'eslint-visitor-keys';
```
Which require the user to turn on `allowSyntheticDefaultImports` in tsconfig
otherwise they will see
```
node_modules/@typescript-eslint/typescript-estree/dist/visitor-keys.d.ts:1:8 - error TS1192: Module '"//tools/eslint/eslint-plugin-ts/node_modules/@types/eslint-visitor-keys/index"' has no default export.
1 import eslintVisitorKeys from 'eslint-visitor-keys';
~~~~~~~~~~~~~~~~~
Found 1 error.
```
> fix(typescript-estree): fix synthetic default import

- package.json
- packages/eslint-plugin/src/rules/no-explicit-any.ts
- packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
- packages/experimental-utils/src/ts-eslint/Rule.ts
- packages/experimental-utils/src/ts-eslint/RuleTester.ts
- tests/integration/README.md
- tests/integration/fixtures/markdown/test.js.snap
- tests/integration/fixtures/vue-jsx/test.js.snap
- tests/integration/fixtures/vue-sfc/test.js.snap
- yarn.lock
Fixes #1249
I wanted to add an example usage at the same time.
`no-explicit-any` seemed like a good candidate because it's not possible to explicitly fix to this.
Suggestions are the perfect use case for it!
> feat: suggestion types, suggestions for no-explicit-any

- packages/eslint-plugin/src/rules/prefer-optional-chain.ts
- packages/eslint-plugin/src/util/index.ts
- packages/eslint-plugin/src/util/misc.ts
- packages/eslint-plugin/src/util/nullThrows.ts
- packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
I imported my implementation to the fb codebase and ran it (because I figured this rule isn't actually TS specific), and I found a few cases that I missed in the original implementation.
To better handle the cases, I significantly reduced the "allowed" scope of the rule by only allowing certain AST structures (see the `isValidChainTarget` function).
1) no longer false-positives on chains where the first variable name is a substring of the next in the chain:
- `foo && fooBar.baz`
1) now can detect chains with some optionals already:
- `foo && foo.bar?.baz`
1) no longer detcets arbitrarily "complex" computed cases, such as:
`foo && foo[bar as string] && foo[bar as string].baz`, or
`foo && foo[1 + 2] && foo[1 + 2].baz`.
- I realised that in order to "normalise" the text for comparison, the …
> fix(eslint-plugin): [prefer-optional-chain] handle more cases

- packages/eslint-plugin/docs/rules/no-empty-function.md
- packages/eslint-plugin/src/rules/no-empty-function.ts
- packages/eslint-plugin/tests/rules/no-empty-function.test.ts
> feat(eslint-plugin): [no-empty-func] private/protected construct

- .eslintrc.js
- packages/eslint-plugin/src/rules/no-empty-function.ts
https://github.com/eslint/eslint/blob/master/lib/rules/no-empty-function.js#L159
> fix(eslint-plugin): [no-empty-function] add missed node types

- packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
- packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
This rule shouldn't actually touch them, but it never checked the operator, so it does right now..
> fix(eslint-plugin): [strict-bool-expr] allow nullish coalescing

- packages/typescript-estree/src/ts-estree/ts-estree.ts
This is half of #734:
> I didn't realise it, but in #156, it added handling to convert function declarations with no body into TSFunctionDeclaration (https://github.com/typescript-eslint/typescript-eslint/pull/156/files#diff-68b2b0b0d2d0ff1846b1114472008332R674)
>
> So it looks like there's no case now that a FunctionDeclaration can have no body?
> fix(typescript-estree): make FunctionDeclaration.body non-null

- packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md
- packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
- packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
Fixes #1265
Adding an option to force the rule to only use suggestions.
This should help with users migrating existing codebases.
> feat(eslint-plugin): [prefer-null-coal] opt for suggestion fixer

- packages/eslint-plugin/src/rules/no-non-null-assertion.ts
- packages/eslint-plugin/src/util/astUtils.ts
- packages/eslint-plugin/tests/rules/no-non-null-assertion.test.ts
- packages/experimental-utils/src/ts-eslint/Rule.ts
- packages/experimental-utils/src/ts-eslint/RuleTester.ts
Always wanted a fixer for this. A normal fixer won't work because it will cause type errors.
Seems like an awesome opportunity to create a suggestion fixer.
> feat(eslint-plugin): [no-non-null-assert] add suggestion fixer

- packages/eslint-plugin/src/configs/README.md
Removed an additional more in the sentence.
> docs(eslint-plugin): typo in the configs README

- packages/eslint-plugin/docs/rules/space-before-function-paren.md
This lint is about the space after `function` but in the example both versions do have one.
The eslint page has it like this
```js
function withoutSpace(x) { // <-- NO space
// ...
}
function withSpace (x) { // <-- space
// ...
}
var anonymousWithoutSpace = function() {};
var anonymousWithSpace = function () {};
```
> docs(eslint-plugin): typo in space-before-function-paren docs

- packages/eslint-plugin/src/rules/brace-style.ts
- packages/eslint-plugin/src/util/astUtils.ts
- packages/eslint-plugin/tests/rules/brace-style.test.ts
> fix(eslint-plugin): [brace-style] handle enum declarations

- packages/eslint-plugin/ROADMAP.md
The functionality of `no-redundant-jsdoc` from TSLint was already introduced in `jsdoc/no-types` rule. I updated the ROADMAP accordingly.
> docs(eslint-plugin): ROADMAP note some jsdoc rules

- packages/parser/package.json
Since `@typescript-eslint/typescript-estree` has an [optional peer dependency](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/typescript-estree/package.json#L70) on TS, `@typescript-eslint/parser` should too.
> chore(parser): mark TS as optional peer dependency

- packages/eslint-plugin/src/rules/quotes.ts
- packages/eslint-plugin/tests/rules/quotes.test.ts
> fix(eslint-plugin): [quotes] ignore `backticks` for interface properties

- packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
- packages/eslint-plugin/src/util/astUtils.ts
- packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
> fix(eslint-plugin): [prefer-null-coal] fixer w/ mixed logicals

- packages/eslint-plugin-tslint/src/rules/config.ts
- packages/eslint-plugin-tslint/tests/fixture-project/4.ts
- packages/eslint-plugin-tslint/tests/index.spec.ts
- tests/integration/fixtures/typescript-and-tslint-plugins-together/test.js.snap
Fixes: https://github.com/typescript-eslint/typescript-eslint/issues/1340
Add a fixer for the tslint config rule.
This was easier than expected - maybe I'm missing something? I'm not convinced this is tested enough, please give me any suggestions you have. I could maybe add an additional test for the `prefer-const` rule, which has a tslint fixer.
> feat(eslint-plugin-tslint): add fixer for config rule

- docs/getting-started/linting/README.md
The link is to `eslint-plugin-import` but the text on the link is `eslint-plugin-eslint-comments`.
> docs: fix typo in getting started doc

- packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
- packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
- packages/eslint-plugin/src/rules/member-naming.ts
- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/src/util/misc.ts
- packages/typescript-estree/src/ts-estree/ts-estree.ts
Whilst working on #1318, I noticed that the types for both property names and destructuring were wrong.
property names assumed that only `Identifier | Literal` were valid, when in fact any expression is valid, if and only if the name is computed: `{ [1 + 2]: 1 }`.
Part of me thinks we should probably split the types to make this nicer (I've raised #1345)
The destructuring types were also inconsistent, so I corrected them.
> feat(typescript-estree): tighten prop name and destructure types

- azure-pipelines.yml
The js uploader keeps on timing out which causes coverage to not report, causing PR status to get stuck in pending.
The bash reporter has a retry mechanism, so it is supposed to be be more resilient.
> test: use codecov bash uploader instead of js uploader

- packages/eslint-plugin/docs/rules/no-unnecessary-type-arguments.md
It's still somewhat ambiguous given it's actually for generics only, but now it's grammatically correct 🤷‍♂
> docs(eslint-plugin): [no-unnec-type-arg] correct doc title

- packages/typescript-estree/src/ts-estree/ts-estree.ts
This is follow up PR of #1349 that fixes recently introduced invalid key type for base properties
```ts
export type PropertyName = PropertyNameComputed | PropertyNameNonComputed;
```
in some places type was defined as `PropertyNameComputed | PropertyNameComputed`
> fix(typescript-estree): correct type of key for base nodes

- packages/eslint-plugin/src/rules/require-array-sort-compare.ts
- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/eslint-plugin/tests/rules/require-array-sort-compare.test.ts
- packages/eslint-plugin/tests/rules/unbound-method.test.ts
See #1051
This finishes off the "easy" rules
> feat(eslint-plugin): more optional chain support in rules

- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/ast-alignment/utils.ts
This PR enables alignment tests that between babel and ts-estree
> test(typescript-estree): reenable alignment tests

- packages/eslint-plugin/src/rules/explicit-function-return-type.ts
- packages/eslint-plugin/src/rules/no-extra-parens.ts
- packages/eslint-plugin/src/util/astUtils.ts
While working on a new rule, I noticed that there were a few places that we didn't check for both angle bracket and as assertions.
This introduces a utility function which does that, and uses it everywhere.
> fix(eslint-plugin): add isTypeAssertion utility function

- packages/eslint-plugin/src/rules/no-extra-parens.ts
- packages/eslint-plugin/tests/rules/no-extra-parens.test.ts
This PR adds test cases for type assertion in rule `no-extra-parens` and fixes issue with incorrectly reported parens in binary expressions for type assertions
```
((a as any) | 0) - 1
```
test cases covers changes added in #1369
closes #742
fixes #807
> fix(eslint-plugin): type assertion in rule no-extra-parens

- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/shared-fixtures/fixtures/typescript/expressions/optional-call-expression-type-arguments.src.ts
- packages/typescript-estree/src/create-program/createDefaultProgram.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/src/visitor-keys.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
allow to visit typeParameters in OptionalCallExpression
- add missing test case for type parameters in optional call expression
> fix(parser): allow to visit typeParameters in OptionalCallExpression

- packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
- packages/typescript-estree/src/convert.ts
This PR does no change how rule will work
- register TSTypeParameterInstantiation in ast tree node maps
- add missing test cases for extends and implements
- refactor `no-unnecessary-type-arguments` rule
> refactor: TypeParameter parsing and no-unnecessary-type-arguments rule

- packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
This PR contains fix for regression introduced in #1381
fixes #1400
> fix(eslint-plugin): crash in no-unnecessary-type-arguments

- packages/eslint-plugin/src/rules/class-name-casing.ts
- packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
- packages/eslint-plugin/src/rules/no-array-constructor.ts
- packages/eslint-plugin/src/rules/no-empty-interface.ts
- packages/eslint-plugin/src/rules/no-misused-new.ts
- packages/eslint-plugin/src/rules/no-type-alias.ts
- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/fixtures/class.ts
- packages/eslint-plugin/tests/rules/array-type.test.ts
- packages/eslint-plugin/tests/rules/class-name-casing.test.ts
- packages/eslint-plugin/tests/rules/explicit-member-accessibility.test.ts
- packages/eslint-plugin/tests/rules/no-misused-new.test.ts
- packages/eslint-plugin/tests/rules/no-throw-literal.test.ts
- packages/eslint-plugin/tests/rules/no-type-alias.test.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
- packages/eslint-plugin/tests/rules/prefer-for-of.test.ts
- packages/eslint-plugin/tests/rules/prefer-readonly.test.ts
- packages/eslint-plugin/tests/rules/triple-slash-reference.test.ts
This PR adds some edge cases for uncovered syntax that is actually validated by rules.
each commit represents changes to tests for one rule
- there is few minor changes to code (redundant conditions)
i was unable to get coverage for all rules that i checked up to 100% (some of code paths can't be triggered)
affected tests for rules:
- array-type
- no-empty-interface
- prefer-for-of
- no-type-alias
- triple-slash-reference
- no-unnecessary-type-assertion
- class-name-casing
- no-misused-new
- no-throw-literal
- explicit-member-accessibility
> test(eslint-plugin): add missing test cases for rules

- packages/typescript-estree/src/create-program/shared.ts
Windows and Linux/Mac uses different path separator.
currently some of tests do not pass on windows machines because of that
this is used by persisted parse and may be related to #1394
> fix(typescript-estree): correct persisted parse for windows

- packages/typescript-estree/src/create-program/createWatchProgram.ts
- packages/typescript-estree/tests/lib/persistentParse.ts
Currently `**` is resolved only as directory, it means that for `./**/*` paths `/src/test.ts`, `/test.ts` is going to work but `/src/test/test.ts` will not.
This is edge case and happens when you setup includes with `**`.
```json5
// tsconfig.extend.json
{
"include": ["src"],
}
```
```json5
// tsconfig.json
{
"extends": "./tsconfig.extend.json",
"include": ["./**/*"],
}
```
fixes #1394
> fix(typescript-estree): parsing of deeply nested new files in new folder

- packages/eslint-plugin/src/rules/no-magic-numbers.ts
- packages/eslint-plugin/tests/rules/no-magic-numbers.test.ts
Fixes #1414
Also fixes a consistency issue wherein our extension would include the `+` when reporting, but the base rule doesn't.
Also reformatted the code a bit:
- moved utility functions outside of create
- used optional chaining
> fix(eslint-plugin): [no-magic-numbers] handle UnaryExpression for enums

- packages/eslint-plugin/src/rules/no-throw-literal.ts
- packages/eslint-plugin/tests/rules/no-throw-literal.test.ts
> fix(eslint-plugin): handle error classes using generics

- packages/eslint-plugin-tslint/package.json
- packages/eslint-plugin-tslint/src/rules/config.ts
- packages/typescript-estree/package.json
- packages/typescript-estree/src/node-utils.ts
- yarn.lock
This PR migrates our usages of `lodash.*` standalone per method packages to single module.
Why?
Other projects started moving out of `standalone per method packages` in favor of single module (eg. babel)
> However, use of these packages is discouraged and they will be removed in v5.
https://lodash.com/per-method-packages
fixes #1399
> chore: migrate lodash from function packages

- packages/eslint-plugin/src/configs/all.json
- packages/eslint-plugin/tools/generate-configs.ts
Forgot to list the rule as an extension rule
> fix(eslint-plugin): set default-param-last as an extension rule

- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
I just switched over to the new `naming-convention` rule (which is pretty awesome), I was getting an exception `TypeError: Cannot read property 'type' of null`, here is a quick repo:
```ts
const match = 'test'.match(/test/);
const [, key, value] = match;
```
With the minimum configuration of
```js
{
selector: 'default',
format: ['camelCase'],
}
```
This is the case because the `AST_NODE_TYPES.ArrayPattern` was returning an array of elements in which the first element is `null`, then, when we recursively step back into `getIdentifiersFromPattern`, we're immediately evaluating `null.type`. 
The solution I'm proposing is just filtering out those `null` elements in the loop prior to recursion. I added a regression test as well.
Thank you!
> fix(eslint-plugin): naming-convention null pattern

- packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
- packages/typescript-estree/src/ts-estree/ts-estree.ts
#1450 pointed out that the type is incorrect. The parser assigns `null` if the element in the pattern is empty, but the types were non-nullable.
> fix(typescript-estree): correct type of `ArrayPattern.elements`

- packages/eslint-plugin-tslint/src/rules/config.ts
- packages/eslint-plugin-tslint/tests/index.spec.ts
- packages/eslint-plugin/src/util/index.ts
- packages/experimental-utils/src/eslint-utils/getParserServices.ts
- packages/experimental-utils/src/eslint-utils/index.ts
- tests/integration/docker-compose.yml
- tests/integration/fixtures/markdown/test.sh
- tests/integration/fixtures/recommended-does-not-require-program/test.sh
- tests/integration/fixtures/typescript-and-tslint-plugins-together/test.sh
- tests/integration/fixtures/vue-jsx/test.sh
- tests/integration/fixtures/vue-sfc/test.sh
This change got extracted from #716 as non breaking feature
> feat(experimental-utils): expose getParserServices from utils

- packages/eslint-plugin/docs/rules/naming-convention.md
- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
Fixes #1453
Also fixes empty options breaking, because I'm a dingus and didn't ever test this case.
> feat(eslint-plugin): [naming-convention] allow not check format

- packages/eslint-plugin/docs/rules/no-extra-non-null-assertion.md
- packages/eslint-plugin/src/rules/no-extra-non-null-assertion.ts
- packages/eslint-plugin/tests/rules/no-extra-non-null-assertion.test.ts
> feat(eslint-plugin): [no-extra-!-assert] flag ?. after !-assert

- packages/eslint-plugin/docs/rules/default-param-last.md
ref: #1407 #1418 
The following code is a correct example.
``` typescript
function f(a: number, b = 0, c?: number) {}
```
> docs(eslint-plugin): fix examples of default-param-last rule

- packages/eslint-plugin/docs/rules/naming-convention.md
> docs(eslint-plugin): correct `naming-convention` example

- package.json
- yarn.lock
This PR upgrades commitlint packages to latest versions 
- `travis-cli` integration gets dropped as is no longer in use (and its left over from before monorepo)
- `config-lerna-scopes` adds validation (that we currently follow) that scope of commit message, if present must be a name of package from project.
> chore: upgrade commitlint and add config-lerna-scopes

- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/shared-fixtures/fixtures/typescript/basics/keyword-variables.src.ts
- packages/typescript-estree/src/node-utils.ts
- packages/typescript-estree/tests/lib/__snapshots__/javascript.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/jsx.ts.snap
- packages/typescript-estree/tests/lib/__snapshots__/typescript.ts.snap
As in #681 and #750, the `of` keyword wasn't correctly handled in the parser with respect to variable names, so the token it created was typed as Keyword instead of Identifier.
Fixes https://github.com/lydell/eslint-plugin-simple-import-sort/issues/33
> fix(typescript-estree): fix identifier tokens typed as `Keyword`

- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Functions or classes nested, but not returned from inside an exported function should not be required to have an explicit type signature.
Fixes #1486
> fix(eslint-plugin): [explicit-module-boundary-types] fix false positives

- yarn.lock
This makes [coverage](https://github.com/wycats/handlebars.js/issues/1636) happy [again](https://github.com/wycats/handlebars.js/pull/1633).
> chore: update `istanbul-reports` to make tests quiet

- packages/eslint-plugin/tests/rules/no-dynamic-delete.test.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-qualifier.test.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
- packages/eslint-plugin/tests/rules/prefer-includes.test.ts
- packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
- packages/eslint-plugin/tests/rules/prefer-regexp-exec.test.ts
- packages/eslint-plugin/tests/rules/prefer-string-starts-ends-with.test.ts
- packages/eslint-plugin/tests/rules/require-array-sort-compare.test.ts
- packages/eslint-plugin/tests/rules/restrict-plus-operands.test.ts
- packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
- packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
- packages/eslint-plugin/tests/rules/unbound-method.test.ts
Noticed that there were some tests that weren't using the utility function.
> chore(eslint-plugin): use getFixturesRootDir in tests

- packages/eslint-plugin/docs/rules/naming-convention.md
- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
Fixes #1478
I had the logic just slightly wrong
> fix(eslint-plugin): [naming-convention] fix filter option

- packages/experimental-utils/src/ts-eslint/Rule.ts
Currently attempting to access `context.settings['<property>']` nets me
> TS7053: Element implicitly has an 'any' type because expression of type '"local/configs"' can't be used to index type '{}'.
>   Property 'local/configs' does not exist on type '{}'.
> fix(experimental-utils): widen type of `settings` property

- azure-pipelines.yml
Bash uploader used for sending coverage reports to codecov currently is broken for azure pipelines.
This fixes missing pr in query sent to codecov by providing it as parameter
Codecov bash script https://codecov.io/bash
> -P pr
> Specify the pull request number
Pipelines docs https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
> System.PullRequest.PullRequestNumber
> The number of the pull request that caused this build. This variable is populated for pull requests from GitHub which have a different pull request ID and pull request number.
-------------------
https://codecov.io/gh/typescript-eslint/typescript-eslint/pull/1528/commits
https://dev.azure.com/typescript-eslint/TypeScript%20ESLint/_build/results?buildId=3139&view=logs&jobId=18ce2c …
> test: fix coverage reports from codecov

- .vscode/launch.json
> test: fix vscode launch configuration for windows

- packages/eslint-plugin/docs/rules/naming-convention.md
- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
> feat(eslint-plugin): support negative matches for `filter`

- packages/typescript-estree/jest.config.js
This PR fixes `isolatedModules` for typescript-estree package 
#1546
> test(typescript-estree): fix issue in jest config

- packages/eslint-plugin/src/rules/require-await.ts
- packages/eslint-plugin/tests/rules/require-await.test.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
Figured that we didn't need to:
- check return statements in a function that isn't async.
- check return statement if the function already has an as await.
- check body-less arrow function value if it's an await expression.
This will saves many unneeded type checks across a codebase.
This has the unfortunate maintenance downside of bringing the entire codebase in, but the old extension did something unstable anyways, so I don't think it matters.
> fix(eslint-plugin): [require-await] improve performance

- packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Fixes #1552
I also updated the docs whilst I was at it, and added a few more tests
> fix(eslint-plugin): [embt] fix allowTypedFunctionExpressions

- packages/typescript-estree/src/create-program/createDefaultProgram.ts
- packages/typescript-estree/src/create-program/createIsolatedProgram.ts
- packages/typescript-estree/src/create-program/createWatchProgram.ts
- packages/typescript-estree/tests/lib/persistentParse.ts
This PR fixes issue when persisted parse is called with module option set to "none",
fixes #1502
> fix(typescript-estree): persisted parse and module none

- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/eslint-plugin/tests/rules/unbound-method.test.ts
#1526 Added a whitelist of member expressions which are bound by default .
But of the ~100 methods in the list, ~15 aren't actually bound (for whatever reason).
This just adds a blacklist alongside the whitelist so we don't false-negative.
I highly doubt anyone will ever actually do `const x = Promise.all` in their code, but we might as well be correct.
> fix(eslint-plugin): [unbound-method] blacklist a few unbound natives

- packages/typescript-estree/src/create-program/createProjectProgram.ts
> fix(typescript-estree): ts returning wrong file with project references

- packages/parser/README.md
It was not clear that relative paths rely on the cwd. For example, a valid alternative interpretation could be that relative paths rely on the location of the eslintconfig file.
This change clarifies how the `parserOptions.project` relative paths are interpreted, and ties it in nicely with the existing recommendation to look at the `tsconfigRootDir` setting.
> docs(parser): mention that relative paths rely on cwd

- packages/eslint-plugin/ROADMAP.md
This resolves #1223 and updates link to deprecation plugin rule.
> docs(eslint-plugin): update link to deprecation rule in roadmap

- packages/typescript-estree/src/parser.ts
This happens in Prettier's browser bundle.
> fix(typescript-estree): process.stdout can be undefined

- packages/eslint-plugin/docs/rules/typedef.md
- packages/eslint-plugin/src/rules/typedef.ts
- packages/eslint-plugin/tests/rules/typedef.test.ts
> fix(eslint-plugin): [typedef] allow array/object destructuring in for/of

- packages/eslint-plugin/docs/rules/no-floating-promises.md
- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
> fix(eslint-plugin): [no-floating-promises] handle finally callback

- packages/eslint-plugin/README.md
- packages/eslint-plugin/src/rules/return-await.ts
- packages/eslint-plugin/src/util/astUtils.ts
- packages/eslint-plugin/tests/rules/return-await.test.ts
This adds `--fix` support for the [require-await](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/require-await.md) rule.
> feat(eslint-plugin): [require-await] add --fix support

- packages/eslint-plugin/ROADMAP.md
We can be sure this is the last of the core rules to be added, because TSLint is deprecated now :smile:.
Fixes #1034.
Edit: also fixes #1627.
> docs(eslint-plugin): added missing TSLint 5.20 rules to ROADMAP.md

- packages/eslint-plugin/docs/rules/default-param-last.md
- packages/eslint-plugin/src/rules/default-param-last.ts
- packages/eslint-plugin/tests/rules/default-param-last.test.ts
> fix(eslint-plugin): [default-param-last] handle param props

- packages/eslint-plugin/src/rules/no-implied-eval.ts
- packages/eslint-plugin/tests/rules/no-implied-eval.test.ts
Fixes #1642 
Tested this against 3.7.5 and 3.8.2 and it works in both.
The changes in the tests were just whitespace changes and changing ``{ code: `...` }`` to be inline.
> fix(eslint-plugin): [no-implied-eval] correct logic for ts3.8

- packages/eslint-plugin/docs/rules/no-base-to-string.md
> docs(eslint-plugin): [no-base-to-string] fix typo

- packages/eslint-plugin/src/rules/type-annotation-spacing.ts
- packages/eslint-plugin/src/util/astUtils.ts
- packages/eslint-plugin/tests/rules/type-annotation-spacing.test.ts
> fix(eslint-plugin): [type-annotation-spacing] handle constructor types

- packages/eslint-plugin/src/util/isTypeReadonly.ts
- packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
Fixes #1665
Also did a small refactor to use an enum instead of `boolean | null`, because it's cleaner.
> fix(eslint-plugin): [prefer-readonly-parameter-types] handle recursive types

- packages/eslint-plugin/docs/rules/no-namespace.md
This PR fixes the default value for the `no-namespace` rule option `allowDefinitionFiles`.
See the default in the code:
https://github.com/typescript-eslint/typescript-eslint/blob/e5db36f140b6463965858ad4ed77f71a9a00c5a7/packages/eslint-plugin/src/rules/no-namespace.ts#L47
> docs(eslint-plugin): [no-namespace] fix typo

- packages/eslint-plugin/src/rules/ban-ts-comment.ts
- packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts
Noticed this while working on a few new rules for `ts-expect-error`.
Also kicking myself slightly for using `comment` instead of `comments` :(
> fix(eslint-plugin): fix placeholder in `ban-ts-comment`

- packages/eslint-plugin/docs/rules/no-unsafe-member-access.md
Fix a very minor little typo in the docs for the `no-unsafe-member-access` rule in the plugin.
> docs(eslint-plugin): Typo in no-unsafe-member-access

- .github/ISSUE_TEMPLATE/eslint-plugin-tslint.md
- .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
- .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
- .github/ISSUE_TEMPLATE/typescript-eslint-utils.md
- .github/ISSUE_TEMPLATE/typescript-estree.md
I've been getting annoyed as people use the wrong template, and then miss information, because it's not in that template.
This just standardises the templates, so that they all have the same basic structure and comments.
> chore: standardise issue templates

- packages/typescript-estree/src/convert.ts
Fixes #1746
133f622f / #1698 introduced a regression.
This was a case I didn't think about in the original implementation.
It's a hole in the types due to the fact that the SyntaxKind enum member, ofc always exists in 3.8.x.
Tested this via:
- change the resolved typescript version in the root package.json to `3.7.5`
- `yarn lint` - no parsing errors
> fix(typescript-estree): export * regression from 133f622f

- packages/eslint-plugin/src/rules/no-base-to-string.ts
`({}).toString() === "[object Object]"`
> fix(eslint-plugin): fix message of no-base-to-string

- packages/eslint-plugin/src/rules/quotes.ts
- packages/eslint-plugin/tests/rules/quotes.test.ts
> fix(eslint-plugin): [quotes] false positive with backtick in import equals statement

- packages/eslint-plugin/src/rules/no-unsafe-call.ts
- packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
> fix(eslint-plugin): [no-unsafe-call] allow import expressions

- packages/experimental-utils/src/ts-eslint/ParserOptions.ts
- packages/parser/README.md
- packages/typescript-estree/README.md
- packages/typescript-estree/src/parser-options.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tests/fixtures/projectFolderIgnoreList/ignoreme/file.ts
- packages/typescript-estree/tests/fixtures/projectFolderIgnoreList/ignoreme/tsconfig.json
- packages/typescript-estree/tests/fixtures/projectFolderIgnoreList/includeme/file.ts
- packages/typescript-estree/tests/fixtures/projectFolderIgnoreList/includeme/tsconfig.json
- packages/typescript-estree/tests/lib/parse.ts
- tsconfig.eslint.json
Resolves #1771 
I didn't realise, but there's a lot of packages that are published to npm with tsconfigs, and even .ts source files.
If you provide a wide glob like `./**/tsconfig.json`, then it'll match those node modules, which means our parser will parse them, leading to wasted memory, and wasted parse time.
This PR adds an option for users to configure ignored folders. By default it just ignores `node_modules`.
I ran a test against our repo by changing the glob in our config to `./packages/**/tsconfig.json` (added an extra *), and the following logs were output, doubly showing it's working
```
typescript-eslint:typescript-estree:parser parserOptions.project matched projects: [
'./tsconfig.eslint.json',
'./packages/eslint-plugin-internal/node_modules/@typescript-eslint/experimental-util …
```
> feat(typescript-estree): add option to ignore certain folders from glob resolution

- packages/eslint-plugin/src/util/types.ts
Fixes #1807
tested by installing TS@3.6.2 and running the tests.
They passed.
> fix(eslint-plugin): [no-unsafe-return] error with <TS3.7

- .cspell.json
- .github/workflows/ci.yml
If linting/formatting/spelling fails, it should not block running the tests.
If they do block, they can increase the iteration time for contributors, because they will have to fix them before they can see the status of their tests.
By not blocking, a contributor will be able to submit a PR, and come back ~5min later knowing they will be able to see if their code passes linting _and_ tests.
This should also knock ~40-60s off of the perceived runtime, as it parallelises some of the work.
> chore: separate linting checks to their own step

- packages/eslint-plugin/ROADMAP.md
> docs(eslint-plugin): add missing invalid-void link to ROADMAP.md

- .prettierrc.json
- packages/eslint-plugin-internal/package.json
- packages/eslint-plugin-internal/src/rules/index.ts
- packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
- packages/eslint-plugin-internal/tests/rules/plugin-test-formatting.test.ts
- packages/eslint-plugin/tests/RuleTester.ts
- packages/eslint-plugin/tools/generate-configs.ts
The strings that are used for eslint plugins will not be checked for formatting.
This can lead to diff noise as one contributor adjusts formatting, uses different quotes, etc.
This rule just enforces the following:
- all code samples are formatted with prettier
- all single line tests do not use backticks
- all multiline tests have:
- no code on the first line
- no code on the last line
- the closing backtick indentation === property indentation
- one of the following indentations:
- no indentation at all
- indentation of 1 + object indent
examples of enforced style:
```ts
ruleTester.run('foo', rule, {
valid: [
'const a = 1;',
`
const a = 1;
`,
`
const a = 1;
`,
{
code: 'const a = 1;',
},
{
code: `
const a = 1;
`,
},
{
code: `
const a = 1;
`,
},
],
invalid: [
{
code: 'const a = 1;',
},
{ …
```
> feat(eslint-plugin-internal): add plugin-test-formatting rule

- packages/eslint-plugin/src/rules/require-await.ts
- packages/eslint-plugin/tests/rules/require-await.test.ts
Fixes #1691 
- added `!node.generator` before checking starts as to ignore the checks for generators
- added tests
> fix(eslint-plugin): [require-await] handle async generators

- packages/eslint-plugin/src/rules/no-throw-literal.ts
- packages/eslint-plugin/tests/rules/no-throw-literal.test.ts
> fix(eslint-plugin): [no-throw-literal] fix crash caused by getBaseTypes

- packages/eslint-plugin/docs/rules/member-ordering.md
- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/tests/rules/member-ordering.test.ts
- packages/typescript-estree/src/ts-estree/ts-estree.ts
Hi,
this PR adds a new rule to sort members in `interface`s alphabetically. A use case for such a rule would be the following:
Sorting things can have certain benefits, e.g. fewer merge conflicts or easier manual comparison of implementations.
Currently, in ESLint, multiple things can be sorted alphabetically:
- [sort-keys](https://eslint.org/docs/rules/sort-keys)
- [sort-vars](https://eslint.org/docs/rules/sort-vars)
- [sort-imports](https://eslint.org/docs/rules/sort-imports)
Additionally, it is possible to sort members using [member-ordering](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-ordering.md). Except if I didn't understand how to use the `member-ordering` rule correctly, currently, there is no option to sort members …
> feat(eslint-plugin): sort members alphabetically

- packages/eslint-plugin/docs/rules/no-type-alias.md
'mapping types is an advance technique, leaving it open can quickly become a pain point' -> 'mapping types is an advanced technique and leaving it open can quickly become a pain point'
> docs(eslint-plugin): [no-type-alias] fix typo

- packages/experimental-utils/src/ts-eslint-scope/ScopeManager.ts
- packages/experimental-utils/src/ts-eslint-scope/analyze.ts
- packages/experimental-utils/src/ts-eslint/CLIEngine.ts
- packages/experimental-utils/src/ts-eslint/Linter.ts
- packages/experimental-utils/src/ts-eslint/ParserOptions.ts
- packages/experimental-utils/src/ts-eslint/Rule.ts
- packages/experimental-utils/src/ts-eslint/RuleTester.ts
went through the history on the definitely typed types to update our copies.
I need to pay a bit more attention to ESLint releases so that I don't miss this stuff.
> feat(experimental-utils): update eslint types to match v6.8

- packages/eslint-plugin/ROADMAP.md
Available since v2.27.0: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/method-signature-style.md
> docs: Add @typescript-eslint/method-signature-style to the migration guide / roadmap 🎉

- packages/eslint-plugin/src/rules/method-signature-style.ts
- packages/eslint-plugin/tests/rules/method-signature-style.test.ts
Fixes #1857
Whilst I was there, I also added support for preserving the delimiter, because why not
> fix(eslint-plugin): [method-signature-style] handle multiline params

- packages/eslint-plugin/src/rules/no-empty-interface.ts
- packages/eslint-plugin/tests/rules/no-empty-interface.test.ts
Ensures TypeParams are copied in autofix action for `no-empty-interface`
- Ensures type params are included in the autofix output
- Adds test case derived from **1864**
Resolves: #1864
> fix(eslint-plugin): no-empty-interface autofix

- packages/eslint-plugin/docs/rules/no-unsafe-assignment.md
Minor typo update to documentation for recent `no-unsafe-assignment` feature
> docs(eslint-plugin): fix typos in no-unsafe-assign

- packages/eslint-plugin/src/rules/no-empty-interface.ts
- packages/eslint-plugin/tests/rules/no-empty-interface.test.ts
Uses a suggested fix (instead of auto-fix) when an empty interface is found inside an ambient declaration.
Resolves: #1875
> fix(eslint-plugin): [no-empty-interface] use suggestion fixer for ambient contexts

- packages/eslint-plugin/docs/rules/explicit-function-return-type.md
- packages/eslint-plugin/src/rules/explicit-function-return-type.ts
- packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
This is an option to complement [the `no-void` base rule allowing the use of `void` in the same conditions](https://github.com/eslint/eslint/issues/13020).
Since that issue is still being evaluated, I've not made any reference to it, but the use-case is still valid even if the team decide against it.
The idea is to not require you to double up `void`:
```
const log = (message: string): void => void console.log(message);
```
This change means that an option can be enabled that allows you to drop the `void` return type:
```
const log = (message: string) => void console.log(message);
```
This is only allowed when the option is enabled *and*: the arrow function is concise, and starts with the `void` operator.
-----
I'm completely open to bikeshedding on the name & such - I just didn't feel it …
> feat(eslint-plugin): [explicit-function-return-type] add option to allow concise arrows that start with void

- packages/eslint-plugin/src/rules/no-for-in-array.ts
- packages/eslint-plugin/src/rules/no-unsafe-call.ts
- packages/eslint-plugin/src/rules/no-unsafe-return.ts
- packages/eslint-plugin/src/rules/require-array-sort-compare.ts
- packages/eslint-plugin/src/rules/restrict-plus-operands.ts
- packages/eslint-plugin/src/rules/restrict-template-expressions.ts
- packages/eslint-plugin/src/util/types.ts
- packages/eslint-plugin/tests/rules/no-for-in-array.test.ts
- packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
- packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
Based on discussion [here](https://github.com/typescript-eslint/typescript-eslint/pull/1707#discussion_r389402779), which was broken out into #1721.
I've not yet checked the rest of the rules for possible refactoring.
> fix(eslint-plugin): use `isTypeArrayTypeOrUnionOfArrayTypes` util for checking if type is array

- packages/eslint-plugin/docs/rules/ban-ts-comment.md
- packages/eslint-plugin/src/rules/ban-ts-comment.ts
- packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts
This one should be safe to merge without TS3.9 being released - it'll just meant the docs are a bit confusing for a few months, which we should solve by putting a note on them about "feature not being released".
I've made the default `true`, as I think `ts-expect-error` is safer, and it's possible to restrict a thing too much :)
closes #1709
> feat(eslint-plugin): [ban-ts-comment] support `ts-expect-error`

- packages/eslint-plugin/docs/rules/no-base-to-string.md
- packages/eslint-plugin/src/rules/no-base-to-string.ts
- packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
ref: #1914
This "soft" removes the `ignoreTaggedTemplateExpressions` option, treating it as always true.
In the next breaking change, 3.0, we can remove this option altogether ☺️ 
Let me know if you want to approach this in another way, this is my first PR here, happy to learn!
> fix(eslint-plugin): [no-base-to-string] soft remove `ignoreTaggedTemplateExpressions` option

- .github/workflows/lock.yml
As per our [contributing guidelines](https://github.com/typescript-eslint/typescript-eslint/blob/master/CONTRIBUTING.md#commenting), we prefer if users raise new issues instead of commenting on old, closed ones.
This adds a github action to automatically lock issues and PRs after they've been closed for 30 days.
Fixes #1767
I found this action because I got a notification on an old closed issue I had followed (`https://github.com/prettier/prettier-vscode/issues/763`).
It'll probably take a day or two to run over our entire repo, [as it only processes 50 items per run](https://github.com/dessant/lock-threads#why-are-only-some-issues-and-pull-requests-processed). I'll check back in a week and change the schedule to be daily instead of hourly.
> chore: add gh action to lock old issues and PRs

- packages/eslint-plugin/docs/rules/explicit-function-return-type.md
Added a missing "s" into the property "allowConciseArrowFunctionExpression`s`StartingWithVoid".
> docs(eslint-plugin): [explicit-function-return-type] fix typo

- packages/experimental-utils/src/eslint-utils/RuleCreator.ts
- packages/experimental-utils/src/eslint-utils/applyDefault.ts
* Change `createRule`'s `TOptions` to a _readonly_ generic constraint ...
* ... and make it mutable exactly where it's necessary: within `applyDefault()` (after cloning it, the mutation happens in line 26 & 28)
=> This allows to create a rule this way: 
```ts
ESLintUtils.RuleCreator(name => name)<readonly [{ readonly prop: string }],
"defaultMessage">({
name: "name", meta: { /* ... */ },
create(context, options) {
// This is now a compile error ("Cannot assign to '0' because it
//  is a read-only property"), which is gooodd:
options[0] = { prop: "x" };
return {};
},
});
```
> feat(experimental-utils): allow rule options to be a readonly tuple

- packages/eslint-plugin/docs/rules/no-extraneous-class.md
It's just a spelling mistake in the docs.
> chore(eslint-plugin): correct grammatical mistake

- packages/eslint-plugin/src/rules/consistent-type-definitions.ts
- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
- packages/eslint-plugin/src/rules/no-unsafe-call.ts
- packages/eslint-plugin/src/rules/no-unsafe-member-access.ts
- packages/eslint-plugin/src/rules/no-unsafe-return.ts
- packages/eslint-plugin/src/rules/no-untyped-public-signature.ts
- packages/eslint-plugin/src/rules/no-unused-vars-experimental.ts
- packages/eslint-plugin/src/rules/prefer-as-const.ts
- packages/eslint-plugin/src/rules/prefer-for-of.ts
- packages/eslint-plugin/src/rules/prefer-readonly-parameter-types.ts
- packages/eslint-plugin/src/rules/return-await.ts
- packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
- packages/eslint-plugin/src/rules/typedef.ts
**Current situation:** The majority of error messages in rules end with a period, and almost all error messages start with an uppercase character.
This PR standardizes this, with one exception being messages that end with a colon followed by a template literal like this: `Name must match one of the following formats: {{formats}}`
> chore(eslint-plugin): standardise sentences in rule messages

- packages/eslint-plugin/docs/rules/no-base-to-string.md
- packages/eslint-plugin/src/rules/no-base-to-string.ts
- packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Fixes #1655
Feat: add option ignoreTypeNames
> fix(eslint-plugin): fix no-base-to-string boolean literal check

- packages/eslint-plugin-internal/tests/RuleTester.ts
- packages/eslint-plugin/tests/RuleTester.ts
- packages/experimental-utils/src/eslint-utils/RuleTester.ts
- packages/experimental-utils/src/eslint-utils/index.ts
There are a few things we've built in (like automatically adding a filename) that others might find value in.
Plus I want to use it in the internal plugin.
> feat(experimental-utils): expose our RuleTester extension

- .github/workflows/lock.yml
- package.json
it appears a newer version of yarn is running on the CI, which is more strict about the noop install that bootstrap does.
> chore: fix CI

- packages/eslint-plugin/docs/rules/naming-convention.md
An example in this documentation used `type` when the schema for the object in the example requires the key to be `types`.
> docs(eslint-plugin): [naming-convention] correct typo in example

- packages/eslint-plugin/src/rules/return-await.ts
- packages/eslint-plugin/tests/rules/return-await.test.ts
I added checking async keyword in rule of return-await.
Fixes https://github.com/typescript-eslint/typescript-eslint/issues/1930
> fix(eslint-plugin): [return-await] await in a normal function

- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/eslint-plugin/tests/rules/unbound-method.test.ts
Fixes #1934. 
Added an extra check to `isSafeUse` to deal with the case when an unbound method is made truthy/falsy (and therefore safe to reference) through the use of the `!` operator.
> fix(eslint-plugin): [unbound-method] false positives for unary expressions

- packages/eslint-plugin/docs/rules/no-base-to-string.md
- packages/eslint-plugin/src/rules/no-base-to-string.ts
- packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
docs typofix
fix boolean expression detect
> fix(eslint-plugin): no-base-to-string boolean expression detect

- packages/eslint-plugin/docs/rules/method-signature-style.md
- packages/eslint-plugin/src/rules/method-signature-style.ts
- packages/eslint-plugin/tests/rules/method-signature-style.test.ts
> fix(eslint-plugin): [method-signature-style] fix overloaded methods to an intersection type

- packages/eslint-plugin/docs/rules/prefer-optional-chain.md
- packages/eslint-plugin/src/rules/prefer-optional-chain.ts
- packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
Fixes #1820
Added the option `suggestInsteadOfAutofix` which converts the rule into a suggestion fixer when set to `true`.
> feat(eslint-plugin): [prefer-optional-chain] added option to convert to suggestion fixer

- packages/eslint-plugin/src/rules/no-unused-expressions.ts
I'm not sure what changed in ESLint 7 that means this is now an error as it was working up until now and nothing else seems to be broken.
I've checked & tested all the other base rules and they either do this or have their own `messages`, so I don't think it's worth creating an internal rule over (but am happy to do so if it becomes a regular thing - feel free to `@` me if so 🙂 )
This works in both eslint 6 & 7, so 🤷
> fix(eslint-plugin): [no-unused-expressions] inherit `messages` from base rule

- .markdownlint.json
- packages/eslint-plugin/docs/rules/ban-types.md
- packages/eslint-plugin/src/rules/ban-types.ts
- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/src/util/index.ts
- packages/eslint-plugin/src/util/objectIterators.ts
- packages/eslint-plugin/tests/rules/ban-types.test.ts
- packages/experimental-utils/src/eslint-utils/applyDefault.ts
- packages/experimental-utils/src/ts-eslint-scope/analyze.ts
- packages/parser/tests/lib/services.ts
- packages/typescript-estree/src/parser-options.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tests/lib/parse.ts
Updated the config based on feedback:
- Removed fixer from `object` and `Object`
- Updated the messages to be much clearer.
- Added `{}`
- Added `Function`
```ts
{
// ... config for lower case primitives ...
Function: {
message: [
'The `Function` type accepts any function-like value.',
'It provides no type-safety when calling the function, which can be a common source of bugs.',
'It also accepts things like class declarations, which will throw at runtime as they will not be called with `new`.',
'If you are expecting the function to accept certain arguments, you should explicitly define function shape.',
].join('\n'),
},
Object: {
message: [
'The `Object` type actually means "any non-nullish value", so it is marginally better than `unknown`.',
'- If you want a type meaning …
```
> feat(eslint-plugin): [ban-types] rework default options

- packages/eslint-plugin/docs/rules/no-floating-promises.md
- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
https://github.com/eslint/eslint/pull/12613 was released in eslint v7, so it's now possible and easy to use this within the ecosystem.
I think this makes sense as a way to consume top-level promises, so changing it to `true`.
> feat(eslint-plugin): [no-floating-promises] ignore void operator by default

- packages/eslint-plugin/docs/rules/restrict-template-expressions.md
- packages/eslint-plugin/src/rules/restrict-template-expressions.ts
- packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
I forgot this as part of the recommended config changes
> feat(eslint-plugin): [restrict-template-expressions] `allowNumber: true` by default

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Fixes #1591 .  
This is a pretty minimal "handles exactly the case raised in the issue" fix.  While looking into this on the issue tracker, I also found [Typescript#32627](https://github.com/microsoft/TypeScript/issues/32627) which is another case that TS won't catch.  Might be worth trying to "beef up" this logic to handle this more generally.
> feat(eslint-plugin): [no-unnecessary-condition] report when non-nullish is compared to `null`/`undefined`

- packages/eslint-plugin/docs/rules/restrict-template-expressions.md
- packages/eslint-plugin/src/rules/restrict-template-expressions.ts
- packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
> feat(eslint-plugin): [restrict-template-expressions] rename `allowNullable` to `allowNullish`

- packages/eslint-plugin/src/rules/no-type-alias.ts
- packages/eslint-plugin/tests/rules/no-type-alias.test.ts
> fix(eslint-plugin): [no-type-alias] handle readonly types in aliases

- packages/experimental-utils/src/json-schema.ts
> fix(experimental-utils): remove accidental dep on json-schema

- .eslintrc.js
- README.md
- package.json
- packages/typescript-estree/README.md
- packages/typescript-estree/src/parser.ts
- yarn.lock
> feat: bump minimum required TS version

- .github/workflows/ci.yml
Lerna is a bit of a pain in the CI.
You just see a single "test" step, so you can't tell how far done it is, nor can you tell what failed when it fails.
If it fails, you have to open up the logs and parse them yourself, which isn't easy due to the line prefixing.
> chore: provide more granularity in the CI logs

- packages/eslint-plugin/docs/rules/explicit-function-return-type.md
Not sure if the default is correct; feel free to fix.
> docs(eslint-plugin): [explicit-function-return-type] add missing default

- packages/eslint-plugin-internal/src/rules/no-poorly-typed-ts-props.ts
- packages/eslint-plugin/src/rules/no-empty-interface.ts
- packages/eslint-plugin/src/rules/no-explicit-any.ts
- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/eslint-plugin/src/rules/no-non-null-asserted-optional-chain.ts
- packages/eslint-plugin/src/rules/no-non-null-assertion.ts
- packages/eslint-plugin/src/rules/prefer-as-const.ts
- packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
- packages/eslint-plugin/src/rules/prefer-optional-chain.ts
- packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
- packages/experimental-utils/src/ts-eslint/Rule.ts
This property doesn't seem to be used for anything by ESLint (suggestions still work without it), but it's in [the docs](https://eslint.org/docs/developer-guide/working-with-rules#rule-basics), and would let us plugin devs check if our rules have suggestions for documentation generation tooling.
> feat(experimental-utils): add `suggestion` property for rule  modules

- packages/typescript-estree/src/ast-converter.ts
if I pass the options with  
{
comment: true,
loc: false,
range: false,
}
when parsing, I expect it should remove loc & range both
> fix(typescript-estree): fix handling of range/loc removal

- packages/eslint-plugin/src/rules/dot-notation.ts
> fix(eslint-plugin): [dot-notation] fix typo in schema

- docs/getting-started/linting/FAQ.md
On https://eslint.org/docs/user-guide/getting-started there is information that ESLint should be installed locally: "It is also possible to install ESLint globally rather than locally (using npm install eslint --global). However, this is not recommended, and any plugins or shareable configs that you use must be installed locally in either case."
But, I have not found anywhere information that TypeScript must be installed locally for ESLint to work. It took me several hours to figure it out. Such information would be very user friendly especially for novices.
See https://github.com/typescript-eslint/typescript-eslint/issues/2041
> docs: Adding FAQ entry saying TypeScript should be installed locally

- packages/eslint-plugin/docs/rules/no-unnecessary-condition.md
This was removed from the actual code in this PR:
https://github.com/typescript-eslint/typescript-eslint/pull/1163
> docs(eslint-plugin): remove `ignoreRHS` from `no-unnecessary-condition`

- packages/eslint-plugin/README.md
> docs(eslint-plugin): remove mention of `eslint-recommended`

- packages/typescript-estree/src/parser.ts
3.8 isn't truly supported yet (#1436), but it will work fine - just can't lint private fields.
We _want_ people to upgrade as 3.9 is much better and faster!
So this increases the version range so 3.8 and 3.9 will stop logging the unsupported warning.
#1436 is pinned in our issues, so that's about as good as we can do.
> fix(typescript-estree): mark TS 3.8 and 3.9 as "supported"

- packages/eslint-plugin/docs/rules/naming-convention.md
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
> docs(eslint-plugin): [naming-convention] document ignoring quoted properties

- packages/experimental-utils/src/ts-eslint/index.ts
I can't find any reason why they're not exported already, but I could have missed something.
> fix(experimental-utils): export `CLIEngine` & `ESLint`

- packages/eslint-plugin/src/rules/unbound-method.ts
When Node.js is compiled with the "--with-intl=none" option ( https://nodejs.org/api/intl.html#intl_options_for_building_node_js ) it will not have the Intl global. This rule however does expect all SUPPORTED_GLOBALS including Intl to always exist. As a result, any attempt to run eslint would result in an error like:
```
TypeError: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.js': Cannot convert undefined or null to object
Referenced from: /home/dev/web/.eslintrc.js
at Function.getOwnPropertyNames (<anonymous>)
at /home/dev/web/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unbound-method.js:91:19
```
We can silently ignore missing globals as a workaround.
> fix(eslint-plugin): [unbound-method] fix crash due to missing `Intl`

- packages/eslint-plugin/src/rules/no-throw-literal.ts
- packages/eslint-plugin/tests/rules/no-throw-literal.test.ts
> fix(eslint-plugin): [no-throw-literal] handle intersection and union types

- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
> fix(eslint-plugin): [naming-convention] handle no options correctly

- README.md
presently, on https://github.com/typescript-eslint/typescript-eslint#contributing-guide if you click `Contributing Guide` in the table of contents at the top, it's broken because in https://github.com/typescript-eslint/typescript-eslint/commit/2b16019426b8f97b97796c6cd4ea3a20fd44ebb9#diff-04c6e90faac2675aa89e2176d2eec7d8L300 it was changed from `Contributing Guide` to `Contributing` without the TOC link being updated.
Corrected demo (from this PR) here https://github.com/typescript-eslint/typescript-eslint/blob/309a423e41b0c1f72d00c48f6d33f27a8940e04b/README.md#contributing-guide
> docs: broken markdown link in Contributing Guide in main README

- packages/eslint-plugin/ROADMAP.md
The migration guide suggested migrating from TSLint's `no-void-expression` rule to ESLint's `no-void` rule despite the rules being unrelated (while having confusingly similar names.) This removes the link to `no-void` and fixes #1871.
> docs(eslint-plugin): remove `no-void` from roadmap

- docs/getting-started/linting/README.md
This PR adds NPM commands for installing and running typescript-eslint with the NPM package manager.
> docs: include npm install instructions in getting started

- packages/eslint-plugin/src/rules/no-unused-expressions.ts
- packages/eslint-plugin/tests/rules/no-unused-expressions.test.ts
- packages/typescript-estree/src/ts-estree/ts-estree.ts
> fix(eslint-plugin): [no-unused-expressions] ignore import expressions

- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Version 3.0.0 of the plugin enabled `explicit-module-boundary-types` by default. Unfortunately it doesn't currently handle the case where the parent function has a type signature. The following correct code produces an error. 
```ts
export const foo = (a: string): (n: number) => string => {
return (n) => String(n)
}
```
This fixes the problem by checking the parent nodes of exported declarations to see if they are already typed. If they are typed it doesn't show the error for child functions.
Fixes #1845
> fix(eslint-plugin): [explicit-module-boundary-types] don't check returned functions if parent function has return type

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
, unknown and nullish values (closes #2113)
> fix(eslint-plugin): [no-unnecessary-condition] handle comparison of any, unknown and loose comparisons with nullish values

- .gitignore
- package.json
- packages/eslint-plugin-internal/package.json
- packages/eslint-plugin-tslint/package.json
- packages/eslint-plugin/package.json
- packages/experimental-utils/package.json
- packages/parser/package.json
- packages/shared-fixtures/package.json
- packages/typescript-estree/package.json
- yarn.lock
Fixes #2114
Use `downlevel-dts` to do it.
I thought about just removing the private fields, but I think this is better for ensuring we don't cause regressions going forward.
Also it sets a precedence that I will leverage as part of #1939.
> fix(experimental-utils): downlevel type declarations for versions older than 3.8

- .vscode/launch.json
- packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
- packages/experimental-utils/src/ts-eslint/Scope.ts
This is a large refactor of the code so that it only checks the functions that should be checked.
Fixes #2134
Also added an option `allowArgumentsExplicitlyTypedAsAny`  in case for some reason users want to allow explicit `any`s for argument types
Fixes #2119
Finally, this soft removes the `shouldTrackReferences` option. There's no reason you wouldn't want this set to true, because otherwise there are just a lot of cases it will miss.
> feat(eslint-plugin): [explicit-module-boundary-types] improve accuracy and coverage

- packages/eslint-plugin/docs/rules/ban-types.md
- packages/eslint-plugin/src/rules/ban-types.ts
- packages/eslint-plugin/tests/rules/ban-types.test.ts
Following #2115 @bradzacher guidelines, I've added a way to selectively disable a default type rule for ban-types. Currently if you want to keep every banned-types defaults except one, you have to manually inline the remaining types.
This allow a simpler API:
```js
{
types: {
'{}': false,
},
extendDefaults: true,
}
```
> feat(eslint-plugin): [ban-types] allow selective disable of default options with `false` value

- packages/eslint-plugin-tslint/src/rules/config.ts
- packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
- packages/eslint-plugin/src/rules/array-type.ts
- packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
- packages/eslint-plugin/src/rules/no-empty-function.ts
- packages/eslint-plugin/src/rules/no-use-before-define.ts
- packages/eslint-plugin/src/rules/prefer-optional-chain.ts
- packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
- packages/experimental-utils/src/eslint-utils/RuleTester.ts
- packages/parser/src/analyze-scope.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/create-program/createWatchProgram.ts
There is a false negative when member expression comes first.
```ts
foo.bar && foo.bar.baz;  // no error
```
> fix(eslint-plugin): [prefer-optional-chain] handling first member expression

- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
> fix(eslint-plugin): [explicit-module-boundary-types] dont report return type errors on constructor overloads

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Follow-up for https://github.com/typescript-eslint/typescript-eslint/pull/2123#discussion_r433443841
> fix(eslint-plugin): [no-unnecessary-conditionals] Handle comparison of generics and loose comparisons with undefined values

- packages/eslint-plugin/src/rules/no-extra-non-null-assertion.ts
- packages/eslint-plugin/tests/rules/no-extra-non-null-assertion.test.ts
> fix(eslint-plugin): [no-extra-non-null-assertion] dont report for assertions not followed by the optional chain

- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
> fix(eslint-plugin): [explicit-module-boundary-types] handle nested functions and functions expressions in a typed variable declaration

- packages/eslint-plugin/ROADMAP.md
This PR removes the description about the following repealed rule and replaces it with a replacement rule.
- `@typescript-eslint/ban-ts-ignore` to `@typescript-eslint/ban-ts-comment`
- `@typescript-eslint/class-name-casing` to `@typescript-eslint/naming-convention`
> docs(eslint-plugin): update roadmap

- packages/eslint-plugin/src/rules/return-await.ts
- packages/eslint-plugin/tests/rules/return-await.test.ts
> fix(eslint-plugin): [return-await] correct handling of ternaries

- packages/eslint-plugin/src/rules/naming-convention.ts
> feat(eslint-plugin): [naming-convention] put identifiers in quotes in error messages

- packages/eslint-plugin/docs/rules/no-non-null-assertion.md
Previous example
```typescript
const includesBaz: boolean = foo.bar && foo.bar.includes('baz');
```
does not compile with `--strictNullChecks` because type of `foo.bar && foo.bar.includes('baz')` is `boolean | undefined`. Instead, using null coalescing operator and optional chaining is better example for safer and idiomatic TypeScript code.
```typescript
const includesBaz: boolean = foo.bar?.includes('baz') ?? false;
```
> docs(eslint-plugin): [no-non-null-assertion] correct example

- packages/eslint-plugin/docs/rules/naming-convention.md
- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
* Make error message more clear about trimming.
* Docs: add a note about prefix being trimmed before format is validated to make it more noticeable.
Addresses #2187
Here's the current error message:
Proposed error message:
> Variable name `isStore` trimmed as `Store` must match one of the following formats: UPPER_CASE, camelCase
Better wording can be considered, I tried to keep it short and informative.
> feat(eslint-plugin): [naming-convention] better error message and docs for prefix/suffix

- packages/eslint-plugin/src/rules/no-unused-expressions.ts
- packages/eslint-plugin/tests/rules/no-unused-expressions.test.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
> fix(eslint-plugin): [no-unused-expressions] handle ternary and short-circuit options

- packages/eslint-plugin/src/rules/no-base-to-string.ts
- packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Fixes #2162 [no-base-to-string] complains about intersection types
> fix(eslint-plugin): [no-base-to-string] handle intersection types

- .eslintrc.js
- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/rules/await-thenable.ts
- packages/eslint-plugin/src/rules/no-throw-literal.ts
- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/src/rules/restrict-template-expressions.ts
- packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
- packages/eslint-plugin/src/util/types.ts
- packages/eslint-plugin/typings/typescript.d.ts
This is just to help us investigate bugs that people report.
Sometimes the type fails to resolve, causing it to be reported as an `any`.
TS also adds a property to these `any`s - `intrinsicName: "error"` (example: https://ts-ast-viewer.com/#code/C4TwDgpgBAGlC8UCuA7A1ig9gdxaSA3EA)
Being able to see what's an `any` can often help in debugging issues - if it's an "error `any`", then it's not a bug in our code, but instead a problem with the user's setup.
I used to manually patch node_modules on repro repos to log it out, but it's probably better if it's just built into the plugin instead.
> chore(eslint-plugin): add a debug log when a type is an "error" any to help with investigations

- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/eslint-plugin/tests/rules/unbound-method.test.ts
> fix(eslint-plugin): [unbound-method] handling destructuring

- packages/experimental-utils/src/eslint-utils/getParserServices.ts
> fix(experimental-utils): getParserServices takes a readonly context

- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
**Add support for unicode regular expressions.**
[The rule docs](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md) present the example below, saying *"You can use the filter option to ignore names that require quoting"*:
```ts
{
"@typescript-eslint/naming-convention": [
"error",
{
"selector": "property",
"format": ["strictCamelCase"],
"filter": {
// you can expand this regex as you find more cases that require quoting that you want to allow
"regex": "[- ]",
"match": false
}
}
]
}
```
(Aside: Ideally there should be a selector for detecting quoted names, since quotes can be a useful shorthand for bypassing lint rules.  But let's ignore that for now.  Instead we will follow the above example's premise, of substituting …
> fix(eslint-plugin): [naming-convention] support unicode in regex

- packages/typescript-estree/src/node-utils.ts
This changes `typescript-estree` to use TypeScript API's for some of the functionality in `node-utils.ts` so that it will be forward compatible with TypeScript 4.0's support for ES2020's `||=`, `&&=`, and `??=` compound assignment operators.
> fix(typescript-estree): forward compat for new compound assignment operators

- docs/getting-started/linting/FAQ.md
There have been a few issues asked about this, so explicitly note this in the FAQ.
> docs: add FAQ about typescript errors not being included in lint output

- packages/eslint-plugin/src/rules/space-before-function-paren.ts
- packages/eslint-plugin/tests/rules/space-before-function-paren.test.ts
> fix(eslint-plugin): [space-before-function-paren] incorrect handling of abstract methods

- packages/eslint-plugin/src/rules/prefer-literal-enum-member.ts
- packages/eslint-plugin/tests/rules/prefer-literal-enum-member.test.ts
> fix(eslint-plugin): [prefer-literal-enum-member] allow negative numbers

- packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
- packages/eslint-plugin/tests/rules/switch-exhaustiveness-check.test.ts
> fix(eslint-plugin): [switch-exhaustiveness-check] handle special characters in enum keys

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
> fix(eslint-plugin): [no-unnecessary-condition] handle computed member access

- packages/parser/tests/lib/__snapshots__/typescript.ts.snap
- packages/shared-fixtures/fixtures/typescript/basics/catch-clause-with-annotation.src.ts
- packages/shared-fixtures/fixtures/typescript/basics/catch-clause-with-invalid-annotation.src.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/semantic-or-syntactic-errors.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
- packages/typescript-estree/tests/snapshots/typescript/basics/catch-clause-with-annotation.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/basics/catch-clause-with-invalid-annotation.src.ts.shot
reference #2260
Split these changes out of #2202 to better focus the PR
> feat(typescript-estree): support type annotations on catch clauses

- packages/eslint-plugin/docs/rules/no-empty-function.md
- packages/eslint-plugin/src/rules/no-empty-function.ts
- packages/eslint-plugin/tests/rules/no-empty-function.test.ts
- packages/types/src/ts-estree.ts
> feat(eslint-plugin): [no-empty-function] add `decoratedFunctions` option

- packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
- packages/eslint-plugin/tests/rules/adjacent-overload-signatures.test.ts
Fixes #2312
This false positive occurred because `CallSignature` and normal methods named `call` were treated identically.
So I've fixed how to decide two methods are same or not.
> fix(eslint-plugin): [adjacent-overload-signatures] fix false positive on call signatures and a method named `call`

- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/node-utils.ts
- packages/typescript-estree/src/version-check.ts
Reference: https://github.com/prettier/prettier/pull/8805
I had a major brainfart when implementing #2305 and didn't think about the fact that changes should be backwards compatible.
When handling the null type change introduced by `4.0`, I deleted the old branches instead of gating them behind a version check. This PR just gates the old logic for `< 4.0`.
We don't have automated testing against old TS versions yet (#1752) so I tested this by hand by doing the following:
- `yarn build` to build against `4.0.0-beta`.
- change the [resolved ts version](https://github.com/typescript-eslint/typescript-eslint/blob/30fafb09422b3aca881f4785d89b0536092d4952/package.json#L104) to `3.9.7`
- `yarn install --ignore-scripts` (the automatic rebuild after the install would fail due to incorrect types)
- …
> fix(typescript-estree): correct AST regression introduced by TS4.0 upgrade

- packages/eslint-plugin/src/rules/no-extra-parens.ts
- packages/eslint-plugin/tests/rules/no-extra-parens.test.ts
> fix(eslint-plugin): [no-extra-parens] stop reporting on calling generic functions with one argument and type parameters containing parentheses

- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
> fix(eslint-plugin): [no-unused-vars] handle TSCallSignature

- packages/eslint-plugin/docs/rules/ban-ts-comment.md
- packages/eslint-plugin/src/rules/ban-ts-comment.ts
Fixes #2146
Default rule options is a breaking change.
> feat(eslint-plugin): [ban-ts-comment] change default for `ts-expect-error` to `allow-with-description`

- packages/eslint-plugin/docs/rules/typedef.md
- packages/eslint-plugin/src/rules/typedef.ts
- packages/eslint-plugin/tests/rules/typedef.test.ts
Removes all default options from `typedef`. Users will have to specifically opt-in to all options them selves.
This is intentional friction being introduced to setup the rule to help discourage it as it's not recommended for use.  
This also ensures this rule cannot conflict with any other rules (or even do anything) in the `all` config.
Fixes #2075
> feat(eslint-plugin): [typedef] remove all defaults

- packages/eslint-plugin/src/rules/no-shadow.ts
- packages/eslint-plugin/tests/rules/no-shadow.test.ts
> fix(eslint-plugin): [no-shadow] fix false-positive on enum declaration

- packages/eslint-plugin/src/rules/no-empty-function.ts
- packages/eslint-plugin/src/rules/no-unused-vars-experimental.ts
- packages/eslint-plugin/tests/rules/no-empty-function.test.ts
- packages/eslint-plugin/tests/rules/no-unused-vars-experimental.test.ts
- packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
- packages/types/package.json
- packages/types/src/ast-node-types.ts
- packages/types/src/ts-estree.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
- packages/typescript-estree/tests/snapshots/typescript/errorRecovery/decorator-on-enum-declaration.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/errorRecovery/decorator-on-function.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/errorRecovery/decorator-on-interface-declaration.src.ts.shot
- packages/visitor-keys/package.json
- packages/visitor-keys/src/visitor-keys.ts
Fixes #2369
- Removed `decorators` property from several `Node`s that could never semantically have them (`FunctionDeclaration`, `TSEnumDeclaration`, and `TSInterfaceDeclaration`)
- Removed `AST_NODE_TYPES.Import`. This is a minor breaking change as the node type that used this was removed ages ago.
---
This was an interesting bug to fix!
We had a bug in our visitor keys here - they didn't declare the `decorators` key for `AssignmentPattern`, this meant that when ESLint traversed the tree, it wouldn't traverse assignment pattern's decorators, so it wouldn't add the `parent` property.
So when `no-unused-vars` attempted to get the `parent` of the `Optional` `Identifier` for the decorator, it wouldn't find one, and hence it would crash.
This PR:
- adds the missing visitor …
> fix: correct decorator traversal for AssignmentPattern

- packages/eslint-plugin/docs/rules/no-empty-function.md
This PR adds missing pieces of the `no-empty-function` documentation, where the TS-specific `allow` entries were completely omitted. It adds both a general overview of the extended `Options` object (as  pseudo-code), and per entry descriptions with examples (taken directly from test cases).
> docs: document additional allow options in no-empty-function

- packages/eslint-plugin/src/rules/no-non-null-asserted-optional-chain.ts
- packages/eslint-plugin/src/rules/prefer-optional-chain.ts
- packages/eslint-plugin/tests/rules/no-non-null-asserted-optional-chain.test.ts
- packages/types/src/ts-estree.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/node-utils.ts
- packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/snapshots/typescript/basics/optional-chain-call-with-non-null-assertion.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/basics/optional-chain-call-with-parens.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/basics/optional-chain-element-access-with-non-null-assertion.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/basics/optional-chain-with-non-null-assertion.src.ts.shot
I did some alignment testing against babel and found they handled some things differently. I decided their way was better, so updating the representation to match.
Previously:
- we emitted a different AST for pre-3.9 and post-3.9
- we treated `TSNonNullExpression` as a breakage in the chain, meaning that the `ChainExpression` would not move up through them.
Now:
- we emit the same AST regardless of TS version
- we treat `TSNonNullExpression` as a `ChainElement`, so the `ChainExpression` always moves past them in the tree
> fix(typescript-estree): correct ChainExpression interaction with parentheses and non-nulls

- packages/eslint-plugin/docs/rules/no-unsafe-assignment.md
- packages/eslint-plugin/docs/rules/no-unsafe-return.md
- packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
- packages/eslint-plugin/src/rules/no-unsafe-return.ts
- packages/eslint-plugin/src/util/types.ts
- packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
- packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
- packages/eslint-plugin/tests/util/isUnsafeAssignment.test.ts
Fixes #2325 
This PR looks to relax restrictions to allow any => unknown assignment for `no-unsafe-assignment` and `no-unsafe-return`.
Initially we are checking for `Any` or `AnyArray` as `senderType`, if found we used to stop processing with the relevant message.
Now we additionally check if the `recieverType` is `Unknown` or `Unknown` array. If yes - then we do not treat this as an error case.
I would like you to specifically look at the coding style, so that we don't adversely affect future contributors. I have tried to align with the existing style. Feel free to point out where we could align more.
**Checklist**
> feat(eslint-plugin): [no-unsafe-assignment/return] allow assigning any => unknown

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
> fix(eslint-plugin): [no-unnecessary-condition] fix false positive with nullish coalescing

- packages/eslint-plugin/src/rules/prefer-includes.ts
- packages/eslint-plugin/tests/rules/prefer-includes.test.ts
Fixes #2349 
* Related Rule: prefer-includes
* add the code of checking argument type of `test` method. 
Please let me know if there are any required changes.
> fix(eslint-plugin): [prefer-includes] don't auto fix when `test` method's argument type doesn't have an 'includes' method

- packages/eslint-plugin/docs/rules/type-annotation-spacing.md
Fix @typescript-eslint/type-annotation-spacing examples with 'allow'
> docs(eslint-plugin): [type-annotation-spacing] typo

- .github/ISSUE_TEMPLATE/eslint-plugin-tslint.md
- .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
- .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
- .github/ISSUE_TEMPLATE/typescript-eslint-utils.md
- .github/ISSUE_TEMPLATE/typescript-estree.md
I didn't want to add another comment to the template, as there's already enough that I don't think people read anyways.
So I've added a simple checklist to every template (for the first 3).
A few common problems people have when filing issues:
1) **people don't ever restart their IDE.**
Often times they've done git rebases, yarn installs/removals, added and deleted folders, and just generally caused things to get into a weird state.
Restarting the IDE almost always fixes the issue.
2) **people are running an old version of the package.**
In some cases people have filed issues using a 3+ month old versions of the tooling.
Updating ensures that they have all the latest fixes.
3) **people haven't read the FAQ.**
I've tried to keep it up-to-date with concise and helpful information, but some …
> chore: update issue templates

- docs/getting-started/linting/FAQ.md
Very minor fix to the FAQ. The link to prettier currently just sends you to https://www.npmjs.com/package, rather than https://www.npmjs.com/package/prettier.
> docs: fix incorrect link to prettier package

- packages/typescript-estree/src/ts-estree/ts-nodes.ts
with updated workaround from <https://github.com/typescript-eslint/typescript-eslint/issues/2388#issuecomment-676540952>, following suggestions by @bradzacher & @ExE-Boss, *tested* with <https://github.com/prettier/prettier/pull/8759>
If this can be integrated and published soon, we should be able to remove the ugly workaround from <https://github.com/prettier/prettier/pull/8759>.
resolves #2388
> fix(typescript-estree): ts.NamedTupleMember workaround for <TS4.0

- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
> fix(eslint-plugin): [explicit-module-boundary-types] ignore abstract setters

- README.md
- package.json
- packages/typescript-estree/src/parser.ts
- yarn.lock
TS v4.0 is released, we can now bump our range to allow it, as we have full support for it.
> feat(typescript-estree): update allowed TS version range

- packages/parser/README.md
- packages/typescript-estree/README.md
- packages/typescript-estree/package.json
- packages/typescript-estree/src/parser-options.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tests/lib/parse.test.ts
- yarn.lock
Fixes #2398
If the user has a particularly large node_modules folder and uses globs for `parserOption.project`, then the `glob` library can spend a decent chunk of time searching the `node_modules` folder.
In some cases, this can be on the order of hundreds to thousands of milliseconds.
This wouldn't be a problem, but for safety and correctness during a persistent parse, we have to do this check for every call to the parser (i.e. every file that's being linted).
Over a whole project, this can easily add up to many, many seconds wasted.
Previously, we:
- applied the project globs, one by one
- then manually excluded `tsconfig`s from the list.
This meant that we are always slow. I remember I did this because I had issues getting `glob`'s `ignore` option to work at all.
`globby` is a better …
> feat(typescript-estree): switch to globby

- packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
- packages/scope-manager/src/referencer/Referencer.ts
- packages/scope-manager/tests/fixtures/class/declaration/abstract-property.ts
- packages/scope-manager/tests/fixtures/class/declaration/abstract-property.ts.shot
> fix(scope-manager): correct analysis of abstract class properties

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
> fix(eslint-plugin): [no-unnecessary-condition] correct regression with unary negations

- packages/eslint-plugin/package.json
Fixes #2444
I'm pretty sure we've forgotten do bump this range every single release...
> fix(eslint-plugin): update parser dependency range

- package.json
- packages/eslint-plugin/docs/rules/no-shadow.md
- packages/eslint-plugin/src/rules/no-shadow.ts
- packages/eslint-plugin/tests/rules/no-shadow.test.ts
Fixes #2447
Technically this is backwards incompatible, because I'm adding the option true by default, but I believe that the case it protects against is so rare that it's a substantially better experience this way, and it's what people expect
> feat(eslint-plugin): [no-shadow] add option `ignoreFunctionTypeParameterNameValueShadow`

- packages/scope-manager/src/analyze.ts
- packages/scope-manager/tests/eslint-scope/map-ecma-version.test.ts
> fix(scope-manager): fallback to lib 'esnext' or 'es5' when ecma version is unsupported

- docs/getting-started/linting/FAQ.md
I'm assuming people are not reading the FAQ when filing issues because the first question is super long.
This just moves that question to the end, and promotes the extension rule question to be first (as it's one that is most appropriate right now)
> docs: reorder FAQ

- CHANGELOG.md
- package.json
- packages/eslint-plugin-internal/CHANGELOG.md
- packages/eslint-plugin-tslint/CHANGELOG.md
- packages/eslint-plugin/CHANGELOG.md
- packages/experimental-utils/CHANGELOG.md
- packages/parser/CHANGELOG.md
- packages/scope-manager/CHANGELOG.md
- packages/shared-fixtures/CHANGELOG.md
- packages/types/CHANGELOG.md
Some users use CHANGELOG.md as the source of truth for releases and don't check the github releases page.
We should probably delete these files and just have everything in the GH releases page.
This adds a link to the  v4 releases page and adds a disclaimer to the top of the file pointing at the releases page.
> docs: add link to v4 release notes to the changelogs

- packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
- packages/scope-manager/src/referencer/TypeVisitor.ts
- packages/scope-manager/tests/fixtures/type-declaration/function/params/array-pattern.ts
- packages/scope-manager/tests/fixtures/type-declaration/function/params/array-pattern.ts.shot
- packages/scope-manager/tests/fixtures/type-declaration/function/params/object-pattern.ts
- packages/scope-manager/tests/fixtures/type-declaration/function/params/object-pattern.ts.shot
- packages/scope-manager/tests/fixtures/type-declaration/function/params/rest-element.ts
- packages/scope-manager/tests/fixtures/type-declaration/function/params/rest-element.ts.shot
> fix(scope-manager): support rest function type parameters

- packages/eslint-plugin/tests/eslint-rules/no-undef.test.ts
- packages/scope-manager/src/referencer/TypeVisitor.ts
- packages/scope-manager/tests/fixtures/functions/arrow/type-predicate-asserts1.ts
- packages/scope-manager/tests/fixtures/functions/arrow/type-predicate-asserts1.ts.shot
- packages/scope-manager/tests/fixtures/functions/arrow/type-predicate-asserts2.ts
- packages/scope-manager/tests/fixtures/functions/arrow/type-predicate-asserts2.ts.shot
- packages/scope-manager/tests/fixtures/functions/arrow/type-predicate1.ts
- packages/scope-manager/tests/fixtures/functions/arrow/type-predicate1.ts.shot
- packages/scope-manager/tests/fixtures/functions/arrow/type-predicate2.ts
- packages/scope-manager/tests/fixtures/functions/arrow/type-predicate2.ts.shot
- packages/scope-manager/tests/fixtures/functions/function-declaration/type-predicate-asserts1.ts
- packages/scope-manager/tests/fixtures/functions/function-declaration/type-predicate-asserts1.ts.shot
- packages/scope-manager/tests/fixtures/functions/function-declaration/type-predicate-asserts2.ts
- packages/scope-manager/tests/fixtures/functions/function-declaration/type-predicate-asserts2.ts.shot
- packages/scope-manager/tests/fixtures/functions/function-declaration/type-predicate1.ts
- packages/scope-manager/tests/fixtures/functions/function-declaration/type-predicate1.ts.shot
- packages/scope-manager/tests/fixtures/functions/function-declaration/type-predicate2.ts
- packages/scope-manager/tests/fixtures/functions/function-declaration/type-predicate2.ts.shot
- packages/scope-manager/tests/fixtures/functions/function-expression/type-predicate-asserts1.ts
- packages/scope-manager/tests/fixtures/functions/function-expression/type-predicate-asserts1.ts.shot
- packages/scope-manager/tests/fixtures/functions/function-expression/type-predicate-asserts2.ts
- packages/scope-manager/tests/fixtures/functions/function-expression/type-predicate-asserts2.ts.shot
- packages/scope-manager/tests/fixtures/functions/function-expression/type-predicate1.ts
- packages/scope-manager/tests/fixtures/functions/function-expression/type-predicate1.ts.shot
- packages/scope-manager/tests/fixtures/functions/function-expression/type-predicate2.ts
- packages/scope-manager/tests/fixtures/functions/function-expression/type-predicate2.ts.shot
> fix(scope-manager): support type predicates

- packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
- packages/scope-manager/src/definition/ImportBindingDefinition.ts
- packages/scope-manager/tests/fixtures/import/type-default-value.ts
- packages/scope-manager/tests/fixtures/import/type-default-value.ts.shot
- packages/scope-manager/tests/fixtures/import/type-default.ts.shot
- packages/scope-manager/tests/fixtures/import/type-named-value.ts
- packages/scope-manager/tests/fixtures/import/type-named-value.ts.shot
- packages/scope-manager/tests/fixtures/import/type-named.ts.shot
- packages/scope-manager/tests/types/reference-type.test.ts
> fix(scope-manager): treat type imports as both values and types

- .cspell.json
- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
> fix(eslint-plugin): [no-unused-vars] properly handle ambient declaration exports

- packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
- packages/scope-manager/src/referencer/TypeVisitor.ts
- packages/scope-manager/tests/fixtures/type-declaration/conditional3.ts
- packages/scope-manager/tests/fixtures/type-declaration/conditional3.ts.shot
- packages/scope-manager/tests/fixtures/type-declaration/conditional4.ts
- packages/scope-manager/tests/fixtures/type-declaration/conditional4.ts.shot
- packages/scope-manager/tests/fixtures/type-declaration/conditional5.ts
- packages/scope-manager/tests/fixtures/type-declaration/conditional5.ts.shot
Fixes #2459
This was a bit tricky. Nested scopes are wack.
> fix(scope-manager): correctly handle inferred types in nested type scopes

- packages/eslint-plugin/docs/rules/no-redeclare.md
- packages/eslint-plugin/tests/rules/no-redeclare.test.ts
> docs(eslint-plugin): [no-redeclare] clearly document type/variable redeclare case

- packages/eslint-plugin/src/rules/no-use-before-define.ts
- packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
> fix(eslint-plugin): [no-use-before-define] false positive with jsx pragma reference

- packages/eslint-plugin/src/rules/typedef.ts
- packages/eslint-plugin/tests/rules/typedef.test.ts
> fix(eslint-plugin): [typedef] false positive for rest parameter with array destructuring

- packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
- packages/eslint-plugin/src/rules/indent.ts
- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
- packages/scope-manager/src/scope/ScopeBase.ts
- packages/types/src/ts-estree.ts
If a `declare module` has an `export =` in its body, then TS will only export that.
If it doesn't have an `export =`, then all things are implicitly exported.
This adds handling to correctly detect this case.
```ts
declare module 'foo' {
type T = 1; // T is unused and not exported
const x = 2;
export = x;
}
declare module 'bar' {
type T = 1;
const x = 2;
// T and x are both implicitly exported
}
```
> fix(eslint-plugin): [no-unused-vars] correct detection of unused vars in a declared module with `export =`

- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Fixes #2309
the recursive logic added by #2135 is setup to check members that are not directly exported but used by public members of an exported class, for example here `A.method` needs to be explicit return type because `A` ends up being exported:
```ts
class A {
method(){}
}
export class B{
public ref = A;
}
```
However when the class refers to itself (or any reference loop) this would cause infinite recursion.
To get around this I've just added a set of all nodes we've already visited so recursion will be bounded.
NOTE: it is very possible the `checkedFunctions` and `alreadyVisited` sets can be merged. I tried the unit tests where `checkFunctions` was removed entirely and `isExportedHigherOrderFunction` used the `alreadyVisited` set instead, all unit tests passed but it feels unsound …
> fix(eslint-plugin): [explicit-module-boundary-types] cyclical reference infinite recursion crash

- packages/eslint-plugin/ROADMAP.md
A few rule names didn't have corresponding links, so they were being formatted improperly.
> docs(eslint-plugin): added missing links to ROADMAP.md

- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
Fixes #2523
- `declare global` should never be marked as unused.
- namespaces within declared namespaces all ambiently export their children
> fix(eslint-plugin): [no-unused-vars] better handling for declared modules

- packages/eslint-plugin/src/rules/no-use-before-define.ts
- packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
- packages/experimental-utils/src/ts-eslint/Scope.ts
> fix(eslint-plugin): [no-use-before-define] false positive for function type arguments

- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
Fixes #2376 
Please let me know if there are any required changes!
> fix(eslint-plugin): [naming-convention] allow an array of selectors with types and modifiers

- packages/eslint-plugin/ROADMAP.md
Fixes #1817
https://palantir.github.io/tslint/rules/ban/
https://eslint.org/docs/rules/no-restricted-globals
https://eslint.org/docs/rules/no-restricted-properties
> docs(eslint-plugin): added missing `no-restricted-globals` to `ban` in ROADMAP.md

- packages/eslint-plugin/docs/rules/no-redeclare.md
Fixes type/variable names of the base options (possibly from `no-shadow`)
> docs(eslint-plugin): [no-redeclare] fix type/variable names of base options

- packages/eslint-plugin/tests/rules/no-shadow.test.ts
- packages/scope-manager/src/referencer/TypeVisitor.ts
- packages/scope-manager/tests/fixtures/type-declaration/conditional-nested.ts
- packages/scope-manager/tests/fixtures/type-declaration/conditional-nested.ts.shot
This fixes #2526 
In a conditional type, the inferred types are not in scope in the "if false" type.
> fix(scope-manager): correct analysis of inferred types in conditional types

- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
> _"**'Do it! Do it now!'** - Arnold Schwarzenegger"_ - Brad Zacher
Starts on #2244. Doesn't add the new rule options for more specific properties, but does ensure that object destructures _only_ match on variables -- not properties.
> fix(eslint-plugin): [naming-convention] ignore properties inside object patterns

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/src/util/index.ts
- packages/eslint-plugin/src/util/isTypeReadonly.ts
- packages/eslint-plugin/src/util/propertyTypes.ts
- packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
Fixes #2143. A quick find-all on `getTypeOfPropertyOfType` showed that the bug might also be able to pop up in `no-unnecessary-condition` as well.
> fix(eslint-plugin): added safe getTypeOfPropertyOfType wrapper

- packages/eslint-plugin/tests/rules/indent/indent.test.ts
- packages/experimental-utils/src/ts-eslint/RuleTester.ts
Similar story to https://github.com/typescript-eslint/typescript-eslint/issues/2232 and https://github.com/typescript-eslint/typescript-eslint/pull/2235
> fix(experimental-utils): treat RuleTester arrays as readonly

- packages/eslint-plugin/docs/rules/consistent-indexed-object-style.md
Fixes a small typo in the code sample supplied for `consistent-indexed-object-style`
> docs(eslint-plugin): fix plugin name in config example

- packages/eslint-plugin/docs/rules/explicit-function-return-type.md
Fixed a minor issue about `allowConciseArrowFunctionExpressionsStartingWithVoid` option value missmatch in documentation.
https://github.com/typescript-eslint/typescript-eslint/blob/ef7dfb6836f5dd95a7a716068993ba3d880e8fdc/packages/eslint-plugin/src/rules/explicit-function-return-type.ts#L65
> docs(eslint-plugin): [explicit-function-return-type] fixed default `allowConciseArrowFunctionExpressionsStartingWithVoid` option value

- packages/eslint-plugin/src/rules/no-duplicate-imports.ts
- packages/eslint-plugin/tests/rules/no-duplicate-imports.test.ts
fixes #2636
And also fixes typo - [review](https://github.com/typescript-eslint/typescript-eslint/pull/2609#discussion_r500038143). thanks @ginger-kang
> fix(eslint-plugin): [no-duplicate-imports] distinguish member, default

- packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
- packages/scope-manager/src/referencer/Referencer.ts
- packages/scope-manager/tests/fixtures/ts-module/global-augmentation.ts
- packages/scope-manager/tests/fixtures/ts-module/global-augmentation.ts.shot
> fix(scope-manager): don't create a variable for global augmentation

- packages/typescript-estree/README.md
I was curious about the differences between Babel and typescript-estree ASTs, so I tried to look into it, but I was confused because the link to the code does not exist.
This PR adds link for AST Alignment Tests to README.
> docs(typescript-estree): add the link for AST Alignment Tests

- packages/typescript-estree/README.md
I ran `npm run ast-alignment-tests` to run AST Alignment Tests, but the command does not seem to exist already.
This PR removes documentations for commands that do not already exist from README.
> docs(typescript-estree): remove defunct Build/Test Commands from README

- packages/eslint-plugin/src/rules/no-use-before-define.ts
- packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
Fixes #2572 
The `no-use-before-define` rule wasn't taking into account type reference that comes from values prefixed by the `typeof` operator.
Thank you @bradzacher for your help 🙂
> fix(eslint-plugin): [no-use-before-define] correctly handle typeof type references

- packages/eslint-plugin/docs/rules/consistent-type-assertions.md
- packages/eslint-plugin/src/rules/consistent-type-assertions.ts
- packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
> fix(eslint-plugin): [consistent-type-assertions] check type assertion in jsx props

- packages/typescript-estree/tests/ast-alignment/parse.ts
Some of the babel-parser plugins used in AST Alignment Tests are already enabled by default.
- `importMeta`: https://github.com/babel/babel/pull/11406
- `bigInt`: https://github.com/babel/babel/pull/11117
- `asyncGenerators`, `objectRestSpread`: https://github.com/babel/babel/pull/8448
- `dynamicImport`: https://github.com/babel/babel/pull/10843
- `logicalAssignment`: https://github.com/babel/babel/pull/11869
- `nullishCoalescingOperator `: https://github.com/babel/babel/pull/10819
- `optionalChaining`: https://github.com/babel/babel/pull/10817
- `numericSeparator`: https://github.com/babel/babel/pull/11863
If these are intentionally, please close this PR:smile:
> test(typescript-estree): remove babel-parser plugins that are enabled by default

- packages/eslint-plugin/src/rules/ban-types.ts
- packages/eslint-plugin/tests/rules/ban-types.test.ts
Fixes https://github.com/typescript-eslint/typescript-eslint/issues/2657.
The docs for `ban-types` claims that `ban-types` can be used with "a type name with generic parameter instantiation(s)", but this functionality never seems to have been implemented. The previous implementation only compared against the `typeName` node of the type reference, but now we also compare against the entire `TypeReference` node if there are any type parameters.
> fix(eslint-plugin): [ban-types] allow banning types with specific parameters

- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
Fixes #2595
This attempts to make `markDeclarationChildAsUsed` somewhat more targeted. 
In some cases it seems that `context.getScope().upper` is the correct scope where we should attempt to mark a variable as having been used, in order to avoid starting further down the tree and marking a variable in a child scope as used instead (`context.markVariableAsUsed` is an inside-out search, keying in on variable name only).
Tests have been added for the two cases where there appears to be a false positive (the ambient declaration of either a `function` or a `namespace` with a variable of the same name of the parent in scope)
> fix(eslint-plugin): [no-unused-vars] fix false positives for duplicated names in namespaces

- .eslintrc.js
- packages/eslint-plugin-internal/tsconfig.json
- packages/eslint-plugin-tslint/tsconfig.build.json
- packages/eslint-plugin-tslint/tsconfig.json
- packages/eslint-plugin/tsconfig.build.json
- packages/eslint-plugin/tsconfig.json
- packages/experimental-utils/tsconfig.json
- packages/parser/tsconfig.build.json
- packages/parser/tsconfig.json
- packages/scope-manager/tsconfig.json
- packages/types/src/parser-options.ts
- packages/typescript-estree/README.md
- packages/typescript-estree/src/create-program/createWatchProgram.ts
- packages/typescript-estree/src/parser-options.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tsconfig.build.json
See #2094
This is quick-and-dirty to get this out there for some users to see what sort of perf improvements this squeezes out.
Intentionally not documenting the flag as it isn't ready to be used by the wider world
<details>
<summary>With the flag turned on</summary>
```bash
bradzacher@bradzacher-mbp typescript-eslint % DEBUG=typescript-eslint:* yarn eslint ./packages/types/src/index.ts ./packages/eslint-plugin/src/index.ts
yarn run v1.22.4
$ /Users/bradzacher/github/typescript-eslint/node_modules/.bin/eslint ./packages/types/src/index.ts ./packages/eslint-plugin/src/index.ts
typescript-eslint:typescript-estree:parser parserOptions.project (excluding ignored) matched projects: [
'./tsconfig.eslint.json',
'./tests/integration/utils/jsconfig.json',
'./packages/eslint-plugin/tsconfig.json', …
```
> feat(typescript-estree): add flag EXPERIMENTAL_useSourceOfProjectReferenceRedirect

- packages/eslint-plugin/src/rules/return-await.ts
- packages/eslint-plugin/tests/rules/return-await.test.ts
Resolves #2598 
Specifically tadhgmister's solution:
> If it detected that the value is type any and make a suggestion instead of a fix would that be satisfactory? That way it still gives a warning and IDE has quick fix but the --fix command doesn't remove your await?
> fix(eslint-plugin): [return-await] do not auto-fix when type is `any`/`unknown`

- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
> fix(eslint-plugin): [naming-convention] check bodyless function parameters

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- tests/integration/fixtures/vue-sfc/.eslintrc.js
- tests/integration/fixtures/vue-sfc/Utility.vue
- tests/integration/fixtures/vue-sfc/test.js.snap
- tests/integration/fixtures/vue-sfc/test.sh
Fixes #2591 
n.b. I've kept this fix tight, because I had some whitespace artefacts using `node` vs `originalNode`. If you think I should extend it to the rest of the file, or have some guidance of dealing with how node ranges don't quite match the originalNode.end values, let me know.
> fix(eslint-plugin): [no-unnecessary-type-assertion] correct fixer for vue files

- packages/eslint-plugin/src/rules/lines-between-class-members.ts
Rename `exceptAfterOverload` type from "booleean" to "boolean"
> fix(eslint-plugin): [lines-between-class-members] fix typo in schema

- packages/eslint-plugin/src/rules/no-invalid-this.ts
- packages/eslint-plugin/tests/rules/no-invalid-this.test.ts
Fixes #491
This should fix the things mentioned in the issue. I also added some tests for the new cases.
It seemed almost too easy to fix, so please let me know if I'm missing anything.
Thanks.
> fix(eslint-plugin): [no-invalid-this] allow "this" in class property definitions

- packages/parser/src/parser.ts
Minor optimize. One `reduce` instead of `map-filter`.
Minor fix check lib regexp.
> fix(parser): minor fix regexp, map-filter to reduce

- packages/eslint-plugin/docs/rules/array-type.md
- packages/eslint-plugin/src/rules/array-type.ts
- packages/eslint-plugin/tests/rules/array-type.test.ts
> fix(eslint-plugin): [array-type] fix issues with readonly option

- packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md
- packages/eslint-plugin/src/rules/prefer-readonly-parameter-types.ts
- packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
This PR addresses part of #2079. I'm not sure whether I should mark this as `fixes`, since there's discussion of other wants. So I'll leave that determination up to the reporter and maintainers).
This introduces an `ignoreInferredTypes` option for `prefer-readonly-parameter-types`, which if `true` ignores errors on parameters with no explicit type parameter. This may be useful for cases where an external dependency specifies mutable parameter types, e.g. for parameters in callbacks.
> feat(eslint-plugin): [prefer-readonly-parameter-types] add `ignoreInferredTypes` option

- packages/eslint-plugin/README.md
- packages/eslint-plugin/docs/rules/space-infix-ops.md
- packages/eslint-plugin/src/configs/all.ts
- packages/eslint-plugin/src/rules/index.ts
- packages/eslint-plugin/src/rules/space-infix-ops.ts
- packages/eslint-plugin/tests/rules/space-infix-ops.test.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
Closes #2536
Hello! It's my first time opening a MR. I don't know if i forgot something, don't be shy i can take criticism. the only thing that bothers me it is the 
```
if (nonSpacedNode) {
report(node, nonSpacedNode);
}
```
It says "Excessive stack depth comparing types 'TSEnumMember' and 'Node'" and i dont really know what it means.
For the most part of the code it is functions for the eslint rule but applied to enum members too.
> feat(eslint-plugin): add extension rule `space-infix-ops`

- packages/eslint-plugin/src/rules/method-signature-style.ts
- packages/eslint-plugin/tests/rules/method-signature-style.test.ts
> fix(eslint-plugin): [method-signature-style] correct fixer for overloads in an object literal type

- packages/eslint-plugin/docs/rules/ban-types.md
- packages/eslint-plugin/src/rules/ban-types.ts
- packages/eslint-plugin/tests/rules/ban-types.test.ts
fix #2582
This PR only adds support for banning the empty tuple type `[]`, it does not change the default options of the `ban-types` rule. 
I think it might also be worth adding `[]` to the default banned types. As this would be a breaking change, I would do it in another PR, if the maintainers are ok with that.
> feat(eslint-plugin): [ban-types] support banning `[]`

- packages/eslint-plugin/docs/rules/consistent-type-imports.md
See https://github.com/typescript-eslint/typescript-eslint/issues/2559#issuecomment-692780580 for additional information
> docs(eslint-plugin): [consistent-type-imports] note that it can't be used for decorator metadata

- packages/eslint-plugin/docs/rules/no-shadow.md
- packages/eslint-plugin/src/rules/no-shadow.ts
- packages/eslint-plugin/tests/rules/no-shadow.test.ts
> fix(eslint-plugin): [no-shadow] ignore global module augmentation

- packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
- packages/eslint-plugin/tests/rules/consistent-indexed-object-style.test.ts
> fix(eslint-plugin): [consistent-indexed-object-style] fix wrong autofix behaviour with generics

- packages/eslint-plugin/src/rules/no-extra-non-null-assertion.ts
- packages/eslint-plugin/tests/rules/no-extra-non-null-assertion.test.ts
Fixes #2732
```
function foo(key: string | null) {
const obj = {};
return obj?.[key!];
}
function foo(key: string | null) {
const obj = {};
return obj?.[a!?.key!];
}
function foo(key: string | null) {
const obj = {};
return obj!?.[key!];
}
```
Some extra code tests that were used in [AST](https://astexplorer.net/) to check the solution
> fix(eslint-plugin): [no-extra-non-null-assertion] false positive with non-nullable computed key

- packages/eslint-plugin/src/rules/array-type.ts
- packages/eslint-plugin/tests/rules/array-type.test.ts
> fix(eslint-plugin): [array-type] parenthesize ReadonlyArray fix

- packages/typescript-estree/tests/ast-alignment/utils.ts
I've fixed the AST difference from Babel's side, so I think we can get rid of this AST transformation. See https://github.com/babel/babel/pull/12170
> test(typescript-estree): [babel alignment] remove now unnecessary AST transformation for ImportDeclaration

- packages/eslint-plugin/src/rules/no-unsafe-member-access.ts
- packages/eslint-plugin/tests/rules/no-unsafe-member-access.test.ts
Fixes #2740 
- I feel like the selector is too long to be on one line, but it wouldn't work if I split it. Any recommendations to shorten it? Or is it good to go like it is.
> fix(eslint-plugin): [no-unsafe-member-access] ignore MemberExpression's whose parents are either TSClassImplements or TSInterfaceHeritage

- packages/typescript-estree/README.md
- packages/typescript-estree/src/index.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tests/lib/__snapshots__/parse.test.ts.snap
- packages/typescript-estree/tests/lib/parse.test.ts
Ref: https://github.com/prettier/prettier/pull/9636
This allows consumers to reach into the underlying TS AST in cases where our AST doesn't quite solve the use case.
Motivating example:
We don't (currently) error for code unless TS itself throws an error.
TS is _very_ permissive, but that leads to some weird (and invalid) code we don't error for, and don't include in the AST.
For example - this is _syntactically_ valid in the TS parser, but they emit a _semantic_ error (we currently ignore semantic errors as they're expensive to calculate)
```ts
@decorator
enum Foo {
A = 1
}
```
As it's not a valid place for a decorator - we do not emit its information in the ESTree AST, but as TS treats this as a semantic error - it is parse-time valid.
This creates weird states for consumers wherein …
> feat(typescript-estree): add `parseWithNodeMaps` API

- packages/eslint-plugin/src/rules/consistent-type-definitions.ts
- packages/eslint-plugin/tests/rules/consistent-type-definitions.test.ts
> fix(eslint-plugin): [consistent-type-definitions] remove fixer when the interface is within a global module declaration

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Fix: Mark unknown and any as possibly falsy.
> fix(eslint-plugin): [no-unnecessary-condition] false positive when array predicate returns unknown

- packages/eslint-plugin/docs/rules/ban-types.md
- packages/eslint-plugin/src/rules/ban-types.ts
I recently got a `ban-types` error when specifying an empty object to be allowed (`{}`), which correctly warned me that this is not what I intended. But the message only offered alternatives for cases that didn't apply to my case in particular. After a lot of digging I found this issue (https://github.com/typescript-eslint/typescript-eslint/issues/2063) thankfully explaining the solution to my problem.
I want to save some other devs the trouble of having to look for a solution in this case (or even worse, some people probably ignoring the error, should they not find a solution). This was also suggested here https://github.com/typescript-eslint/typescript-eslint/issues/2063#issuecomment-659748424
> docs(eslint-plugin): [ban-types] add reference on how to type an empty object

- packages/eslint-plugin/src/rules/prefer-literal-enum-member.ts
- packages/eslint-plugin/tests/rules/prefer-literal-enum-member.test.ts
> fix(eslint-plugin): [prefer-literal-enum-member] allow pure template literal strings

- package.json
- packages/typescript-estree/src/ts-estree/ts-nodes.ts
- yarn.lock
> fix(typescript-estree): fix type-only regression for consumers not yet on TS 4.1

- packages/typescript-estree/package.json
- packages/typescript-estree/tests/ast-alignment/utils.ts
- yarn.lock
https://github.com/babel/babel/pull/12352 and https://github.com/babel/babel/pull/12167 remove the difference of AST. So we can remove transformation of TSTypePredicate.
> test(typescript-estree):[babel alignment] remove AST transformation of TSTypePredicate

- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/src/util/collectUnusedVariables.ts
- packages/eslint-plugin/src/util/index.ts
- packages/eslint-plugin/tests/rules/no-unused-vars.test.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
- packages/experimental-utils/src/ast-utils/predicates.ts
- packages/experimental-utils/src/eslint-utils/InferTypesFromRule.ts
- packages/experimental-utils/src/ts-eslint/Rule.ts
- packages/experimental-utils/src/ts-eslint/RuleTester.ts
- packages/experimental-utils/src/ts-eslint/Scope.ts
- packages/scope-manager/src/referencer/VisitorBase.ts
- packages/types/src/ts-estree.ts
I wanted to avoid doing this, but not doing this restricts our logic too much - it causes problems when we want to consider reporting on things that the base rule wouldn't report on.
By forking this logic - it also opens the door to using this in `naming-convention` to detect unused variables.
Fixes #2782
Fixes #2714
Fixes #2648
Closes #2679
> feat(eslint-plugin): [no-unused-vars] fork the base rule

- packages/eslint-plugin/docs/rules/naming-convention.md
- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
Fixes #1477
Closes #2802
This allows users to target different types of properties differently.
Adds the following selectors (self explanatory - just breaking the selectors up):
- `classProperty`
- `objectLiteralProperty`
- `typeProperty`
- `classMethod`
- `objectLiteralMethod`
- `typeMethod`
For backwards compatibility, also converts
- `property` to a meta selector for `classProperty`, `objectLiteralProperty`, `typeProperty`
- `method` to a meta selector for `classMethod`, `objectLiteralMethod`, `typeMethod`
> feat(eslint-plugin): [naming-convention] split `property` and `method` selectors into more granular `classXXX`, `objectLiteralXXX`, `typeXXX`

- packages/eslint-plugin/docs/rules/naming-convention.md
- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
Fixes #2239
Fixes #2512
Fixes #2318
Closes #2802
Adds the following modifiers:
- `exported` - matches anything that is exported from the module.
- `global` - matches a variable/function declared in the top-level scope.
- `destructured` - matches a variable declared via an object destructuring pattern (`const {x, z = 2}`)
> feat(eslint-plugin): [naming-convention] add modifiers `exported`, `global`, and `destructured`

- README.md
The support for TS 4.1 features was added in #2748
SUPPORTED_TYPESCRIPT_VERSIONS in parser: https://github.com/typescript-eslint/typescript-eslint/blob/a8227a6185dd24de4bfc7d766931643871155021/packages/typescript-estree/src/parser.ts#L23
> docs: update supported TS versions to include 4.1

- packages/eslint-plugin/docs/rules/naming-convention.md
- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
Fixes #1510
Leverages the infra added in #2768 to mark variables as unused
> feat(eslint-plugin): [naming-convention] add modifier `unused`

- packages/eslint-plugin/docs/rules/naming-convention.md
- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
Fixes #1712
I chose not to add an unbounded `allowMultiple` for now. I don't think that it's a commonly used pattern.
Single and double I've seen, but I don't believe I've ever seen more than that.
I'd like to avoid adding something unbounded unless there's a strong usecase for it.
> feat(eslint-plugin): [naming-convention] add `requireDouble`, `allowDouble`, `allowSingleOrDouble` options for underscores

- packages/eslint-plugin/docs/rules/naming-convention.md
- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
- packages/eslint-plugin/src/util/index.ts
- packages/eslint-plugin/src/util/requiresQuoting.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
Fixes #2761
Fixes #1483
This modifier simply matches any member name that requires quotes.
To clarify: this does not match names that have quotes - only names that ***require*** quotes.
> feat(eslint-plugin): [naming-convention] add `requiresQuotes` modifier

- packages/eslint-plugin/src/rules/consistent-type-imports.ts
- packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
> fix(eslint-plugin): [consistent-type-imports] crash when using both default and namespace in one import

- packages/eslint-plugin/src/rules/triple-slash-reference.ts
- packages/eslint-plugin/tests/rules/triple-slash-reference.test.ts
fixes #2762
https://astexplorer.net/#/gist/cde0bd7d85e03d135e604e7913a999cd/c034332f4ccf256e809629b0552578191e38b3fe
I'm not sure about the solution cuz it's weird that there was used `as TSESTree.TSExternalModuleReference` and didn't handle any other types considering that `moduleReference` has already been typed.
> fix(eslint-plugin): [triple-slash-reference] fix crash with external module reference

- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Fixes #2183 by looking for the Property value's ancestor type instead of the Property's ancestor itself.
> fix(eslint-plugin): [explicit-module-boundary-types] ignore functions exported within typed object/array literals

- packages/eslint-plugin/docs/rules/consistent-indexed-object-style.md
- packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
- packages/eslint-plugin/tests/rules/consistent-indexed-object-style.test.ts
Fixes #2797 
- ~~Update the rule to skip readonly index signature.~~
- ~~Update the rule document.~~
Update the rule to fix a readonly index signature by `Readonly<Record<key, value>>` type.
(https://github.com/typescript-eslint/typescript-eslint/pull/2798#pullrequestreview-536112524)
> fix(eslint-plugin): [consistent-indexed-object-style] convert readonly index signature to readonly record

- packages/eslint-plugin/docs/rules/unbound-method.md
- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/eslint-plugin/tests/rules/unbound-method.test.ts
Fixes #854
Despite the original issue has the `enhancement: plugin rule option` label, this looks like just a false positive to me.
Feel free to give feedbacks!
> feat(eslint-plugin): [unbound-method] add support for methods with a `this: void` parameter

- packages/typescript-estree/src/create-program/createDefaultProgram.ts
- packages/typescript-estree/src/create-program/createWatchProgram.ts
- packages/typescript-estree/src/create-program/shared.ts
- packages/typescript-estree/src/parser-options.ts
- packages/typescript-estree/src/parser.ts
In #2418 I introduced a regression - I forgot to add in the default value for `projectFolderIgnoreList`.
This means that globs have been matching `node_modules` since the v4.0 release! Oops :(
This PR fixes that.
It also hoists the tsconfig path canonicalisation up so that we can deduplicate early.
Previously if you provided a config like `projects: ['./tsconfig.json', './**/tsconfig.json']`, then we would resolve this to `./tsconfig.json` and `tsconfig.json`, then later canonicalise them.
This meant we'd check that same tsconfig twice!
By hoisting the canonicalisation, we can deduplicate this early.
Fixes #2814
> fix(typescript-estree): add default value for `parserOptions.projectFolderIgnoreList` and deduplicate resolved projects

- packages/eslint-plugin/docs/rules/no-unnecessary-boolean-literal-compare.md
Added a warning message to the rule readme since this rule can change
the behaviour of a program if `strictNullChecks` is disabled.
Fixes #2830
> docs(eslint-plugin): [no-unnecessary-boolean-literal-compare] add warning message

- packages/eslint-plugin/src/util/collectUnusedVariables.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
> fix(eslint-plugin): [no-unused-vars] false-positive with class expressions

- packages/eslint-plugin/src/rules/method-signature-style.ts
- packages/eslint-plugin/tests/rules/method-signature-style.test.ts
> fix(eslint-plugin): [method-signature-style] fix crash with methods without a return type

- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
> fix(eslint-plugin): [no-unused-vars] fix race condition between naming-convention and no-unused-vars

- packages/eslint-plugin/src/rules/naming-convention-utils/enums.ts
In https://github.com/typescript-eslint/typescript-eslint/pull/2807, the `method` selector was converted to a meta selector for `[classMethod, objectLiteralMethod, typeMethod]`, but it incorrectly includes `typeProperty` as a member in place of `typeMethod`. Similarly, the `property` meta selector includes `typeMethod` in place of `typeProperty`. This PR fixes these meta selectors.
> fix(eslint-plugin): [naming-convention] fix wrong member of `method` and `property` meta selectors

- packages/eslint-plugin/docs/rules/no-namespace.md
The typescript/no-namespace rule has a default value of `true` for
the `allowDefinitionFiles` option, but the first example showed that
the default is `false`. This commit fixes that example by showing the
correct default.
> docs(eslint-plugin): [no-namespace] correct default and example

- packages/eslint-plugin/docs/rules/strict-boolean-expressions.md
The code example is demonstrating that boolean _short-circuiting_ is allowed in certain cases, but the comment in the code block refers to this as "side effects", which is an unrelated concept. The page already refers to this correctly as "short-circuiting" in the opening paragraph.
> docs(eslint-plugin): reword misleading strict-boolean-expressions code example

- packages/eslint-plugin/src/rules/naming-convention-utils/shared.ts
- packages/eslint-plugin/src/rules/naming-convention-utils/validator.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
> fix(eslint-plugin): [naming-convention] fix precedence of method and property meta selectors

- packages/eslint-plugin/src/rules/comma-spacing.ts
- packages/eslint-plugin/tests/rules/comma-spacing.test.ts
> fix(eslint-plugin): [comma-spacing] handle empty type params

- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/rules/no-redeclare.ts
- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/src/util/astUtils.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
> fix(eslint-plugin): support eslint@5

- packages/eslint-plugin/docs/rules/sort-type-union-intersection-members.md
- packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
- packages/eslint-plugin/tests/rules/sort-type-union-intersection-members.test.ts
This adds a group called `nullish` to allow sorting `null` and `undefined` independently of the other types in the keywords group. Closes #2918
> feat(eslint-plugin): [sort-type-union-intersection-members] add nullish group

- packages/eslint-plugin/tests/eslint-rules/no-undef.test.ts
- packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
- packages/scope-manager/src/referencer/ClassVisitor.ts
- packages/scope-manager/tests/fixtures/class/declaration/method-param-default.ts
- packages/scope-manager/tests/fixtures/class/declaration/method-param-default.ts.shot
- packages/scope-manager/tests/fixtures/decorators/class-deco-with-object-param.ts
- packages/scope-manager/tests/fixtures/decorators/class-deco-with-object-param.ts.shot
Fixes #2941
Fixes #2942
This was a regression introduced by #2751
> fix(scope-manager): fix incorrect handling of class decorators and class method default params

- packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
> fix(eslint-plugin): [sort-type-union-intersection-members] consider `void` as a `nullish`

- packages/typescript-estree/package.json
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/persistentParse.test.ts
- yarn.lock
Update ast aligment tests to reflect changes to in @babel and allow persistent parse test to be executed on non posix machines
> test(typescript-estree): update ast-alignment tests

- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
- packages/scope-manager/src/referencer/ClassVisitor.ts
- packages/scope-manager/tests/fixtures/class/emit-metadata/method-return-generic.ts
- packages/scope-manager/tests/fixtures/class/emit-metadata/method-return-generic.ts.shot
> fix(scope-manager): correctly reference generic parameters when decorator metadata is enabled

- packages/eslint-plugin/src/rules/consistent-type-imports.ts
- packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
> fix(eslint-plugin): [consistent-type-imports] incorrect handling of computed property type signatures

- packages/parser/README.md
The original link was no longer accurate.
> docs: updated link to eslint parser options documenatation

- packages/eslint-plugin/src/rules/prefer-function-type.ts
- packages/eslint-plugin/tests/rules/prefer-function-type.test.ts
fix generates correct code from rule [prefer-function-type] when used with union or intersection types
fixes #3000
> fix(eslint-plugin): [prefer-function-type] generate correct code in union and intersection

- packages/typescript-estree/package.json
- packages/typescript-estree/tests/ast-alignment/utils.ts
- yarn.lock
https://github.com/babel/babel/pull/12562 has been merged and released. So AST transformation of chain elements can be removed from alignment tests.
> test(typescript-estree): remove AST transformation of chain elements

- packages/eslint-plugin/tests/eslint-rules/no-undef.test.ts
- packages/scope-manager/src/referencer/TypeVisitor.ts
- packages/scope-manager/tests/fixtures/type-declaration/import-type-with-qualifier.ts
- packages/scope-manager/tests/fixtures/type-declaration/import-type-with-qualifier.ts.shot
- packages/scope-manager/tests/fixtures/type-declaration/import-type-with-type-params.ts
- packages/scope-manager/tests/fixtures/type-declaration/import-type-with-type-params.ts.shot
- packages/scope-manager/tests/fixtures/type-declaration/import-type.ts
- packages/scope-manager/tests/fixtures/type-declaration/import-type.ts.shot
> fix(scope-manager): fix visiting of TSImportType

- packages/eslint-plugin/src/rules/no-extra-parens.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
Fixes #2986.
This works on eslint 7.19.0, but breaks on earlier versions (I'd expect). If I left in the previous version of the function (and types) with `'ForInStatement, ForOfStatement'`, it might work on those as well.
If I don't do that, I think the version of eslint in `package.json` should be bumped.
Which would you prefer?
> fix(eslint-plugin): [no-extra-parens] handle ESLint 7.19.0

- packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
1. For each option of the rule, the sentences `Examples of incorrect/correct code for this rule with ...` were wrong when the option's value had to be `false`.
2. Slight simplification of a few code examples, less confusing.
3. Fix and homogenise code examples.
> docs(eslint-plugin): [explicit-module-boundary-types] fix doc & code examples

- tests/integration/fixtures/markdown/.eslintrc.js
Integration tests are no longer working because `eslint-plugin-markdown` released new version that changed api.
https://github.com/eslint/eslint-plugin-markdown/tree/v2.0.0#migrating-from-eslint-plugin-markdown-v1
> test: correct integration tests for eslint-plugin-markdown

- packages/eslint-plugin/src/rules/no-var-requires.ts
- packages/eslint-plugin/tests/rules/no-var-requires.test.ts
This fixes issue with `no-var-requires` not reporting issues for `<Foo>require('./foo.json');`
i found this issue while doing https://github.com/typescript-eslint/typescript-eslint/pull/3005/files#r571368246
> fix(eslint-plugin): [no-var-requires] report when used in type assertion

- packages/typescript-estree/src/convert.ts
Those changes has been extracted from #3078
simplifies logic used to generate deprecated `modifiers` field in some of nodes. instead of iterating over nodes collecting results, filtering them and mapping them again we perform entire operation in first loop
this change has negligible perf improvement
> refactor(typescript-estree): simplify applyModifiersToResult

- packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
- packages/eslint-plugin/tests/rules/sort-type-union-intersection-members.test.ts
- packages/shared-fixtures/fixtures/typescript/basics/intrinsic-keyword.src.ts
- packages/types/src/ast-node-types.ts
- packages/types/src/ts-estree.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
- packages/typescript-estree/tests/snapshots/typescript/basics/intrinsic-keyword.src.ts.shot
- packages/visitor-keys/src/visitor-keys.ts
This PR adds missing AST definition for intrinsic keyword
```ts
type Uppercase<S extends string> = intrinsic;
```
fixes #3079
> fix: add missing intrinsic keyword node to AST

- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/types/src/ts-estree.ts
- packages/typescript-estree/src/convert.ts
Those changes has been extracted from #3078
fixes #2912
```ts
if (x) export {x}
if (x) import test from 'x'
// -----
for (x in foo) {
export {x}
}
// -----
function test (x: string) {
export {x}
}
```
```ts
const a = ++(await x)
```
```ts
try {} catch {}
```
good example in this case can be any proposal that has not been accepted yet 
eg. https://github.com/tc39/proposal-regexp-match-indices
```tsx
const x = /a+(?<Z>z)?/d
```
```ts
const foo = <x {...spread}></x>
```
```ts
// TSModuleDeclaration without body
module "x";
// TSModuleDeclaration -> TSModuleBlock
module x {
}
// TSModuleDeclaration -> TSModuleDeclaration **
module x.x {
}
```
> fix(typescript-estree): correct issues in AST definition

- packages/eslint-plugin/docs/rules/naming-convention.md
In the docs for naming-convention, the order that the selectors are evaluated in is correct, but the selector numbers that they refer to in the example were wrong. The order was `3`, `2`, `1`, `4` when it should have been `3`, `2`, `4`, `1`.
> docs(eslint-plugin): Corrected numbering of selector order for naming-convention

- packages/scope-manager/tests/fixtures/type-declaration/type-query-qualified.ts
- packages/scope-manager/tests/fixtures/type-declaration/type-query-qualified.ts.shot
- packages/scope-manager/tests/fixtures/type-declaration/typeof-import-type-with-qualifier.ts
- packages/scope-manager/tests/fixtures/type-declaration/typeof-import-type-with-qualifier.ts.shot
> test(scope-manager): add missing test cases for typeof import

- packages/typescript-estree/src/node-utils.ts
This PR adds few missing typeguards to node utility functions
> refactor(typescript-estree): add missing type guards to node utils

- docs/getting-started/linting/README.md
Prettier config has since been merged into one, hence `prettier/@typescript-eslint` is deprecated/removed from latest release. All you need to do is declare `prettier` now.
https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
While installing typescript-eslint for a new project, I wasted a few minutes trying to look find where is this `prettier/@typescript-eslint` to install.
> docs: FAQ: update prettier config for v8

- packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
- packages/eslint-plugin/tests/rules/consistent-indexed-object-style.test.ts
Disable reporting when interface has extends
fixes #3007
> fix(eslint-plugin): [consistent-indexed-object-style] do not autofix if interface has extends

- packages/eslint-plugin/docs/rules/unbound-method.md
- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/eslint-plugin/tests/rules/unbound-method.test.ts
This is rebased version of PR, #1925 with fixes.
fixes #1866
> fix(eslint-plugin): [unbound-method] allow `super` expressions in `this` assignments

- packages/eslint-plugin/src/rules/prefer-function-type.ts
- packages/eslint-plugin/tests/rules/prefer-function-type.test.ts
These changes fix the following cases:
```ts
interface Foo1 {
// comment
(): void;
}
// comment
type Foo1 = () => void;
// ---
interface Foo2 {
/* comment */
(): void;
}
/* comment */
type Foo2 = () => void;
// ---
interface Foo3 {
/**
* comment
*/
(): void
}
/**
* comment
*/
type Foo3 = () => void;
```
Fixed #3004
> fix(eslint-plugin): [prefer-function-type] apply existing comments to the fixed code

- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
This is workaround over bug in no-unused-vars as proper change will be a breaking change and can't be done as fix
fixes #2573
> fix(eslint-plugin): [no-unused-vars] don't report nested module declaration

- yarn.lock
fixes issue with https://github.com/typescript-eslint/typescript-eslint/runs/2008398425
> chore: yarn lock after depencency update

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/src/util/types.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
should fix #2953
This is an aggressive move, but I don't why we don't use getContextualType directly. All current tests have passed. If this is feasible, I can add more test cases.
> fix(eslint-plugin): [no-unnecessary-type-assertion] handle assignment

- packages/eslint-plugin/index.d.ts
- packages/eslint-plugin/package.json
- packages/eslint-plugin/tsconfig.json
> feat(eslint-plugin): add package type declaration

- packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
- packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
Fixes #2864
**Gist of it:**
`explicit-module-boundary-types` and `explicit-function-return-type` both have an option `allowTypedFunctionExpressions`.
It makes this code correct:
```ts
interface ObjectType {
foo(): number;
}
export const obj: ObjectType = {
foo: () => 1,
};
```
The issue is that the following code is not correct even with the option set to `true`:
```ts
interface ObjectType {
foo: { bar: () => number }; 
}
export const obj: ObjectType = {
foo: { bar: () => 1 },
};
```
My PR fixes the issue for both of these rules and adds relevant tests.
My fork can be used with npm/yarn using this, that's what I temporarily will do.
```
"@typescript-eslint/eslint-plugin": "https://gitpkg.now.sh/grumd/typescript-eslint/packages/eslint-plugin?build",
```
> fix(eslint-plugin): [explicit-module-boundary-types] fixes #2864 related to functions in nested object properties

- README.md
- packages/typescript-estree/tests/ast-alignment/utils.ts
https://github.com/babel/babel-eslint#note-babel-eslint-is-now-babeleslint-parser-and-has-moved-into-the-babel-monorepo
> docs: update babel-eslint to @babel/eslint-parser

- packages/eslint-plugin/docs/rules/naming-convention.md
Hi, I was working with naming-convention recently. I was trying to remove an object prop `___typename` from a rule. From the documentation  at the time it wasn't entirely clear (to me) what the `regex` property should take:
`let re = "/ab+c/i";` // literal notation
`let re = "ab+c"`  // something to be passed into [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp)
This is important because for example `new RegExp('/typename/') === '//typename//'` and not `"/typename/"`
Also, I think that the args that RegExp is taking changes slightly in ES6? 
I've proposed a small docs change.
Thanks!
> docs(eslint-plugin): [naming-convention] clarify literal regex notation vs. argument to RegExp

- packages/shared-fixtures/fixtures/typescript/basics/import-equal-type-declaration.src.ts
- packages/shared-fixtures/fixtures/typescript/basics/import-export-equal-type-declaration.src.ts
- packages/types/src/ts-estree.ts
- packages/typescript-estree/package.json
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
- packages/typescript-estree/tests/snapshots/typescript/basics/import-equal-type-declaration.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/basics/import-export-equal-declaration.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/basics/import-export-equal-type-declaration.src.ts.shot
- yarn.lock
typescript 4.2 introduced new missing syntax: 
```ts
import type foo = require('bar');
export import type foo = require('bar');
```
AST addition
```js
TSImportEqualsDeclaration <: Node {
importKind: 'type' | 'value';
}
```
fixes #3183, ref babel/babel#12962, microsoft/TypeScript#41573
> fix(typescript-estree): [ts 4.2] add support for import type equal declaration

- packages/eslint-plugin/src/rules/promise-function-async.ts
- packages/eslint-plugin/tests/rules/promise-function-async.test.ts
- Fixer for `public"foo"() {}` now adds a space so it doesn't become `publicasync "foo"() {}`
- Fixer for `["computed"]() {}` now inserts async in the correct position instead of `[async "computed"]() {}`
> fix(eslint-plugin): [promise-function-async] bad fixer with computed and literal methods

- packages/eslint-plugin/src/rules/object-curly-spacing.ts
- packages/eslint-plugin/tests/rules/object-curly-spacing.test.ts
The rule did support not `MappedType` (`var d: {[k in 'union']: any}`).
This PR adds tests and support.
This fixes #3175.
> feat(eslint-plugin): [object-curly-spacing] support MappedType

- packages/eslint-plugin/docs/rules/unbound-method.md
- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/eslint-plugin/tests/rules/unbound-method.test.ts
> feat(eslint-plugin): [unbound-method] improve error message

- packages/eslint-plugin/src/rules/member-delimiter-style.ts
- packages/eslint-plugin/tests/rules/member-delimiter-style.test.ts
Everything was explained here: https://github.com/typescript-eslint/typescript-eslint/issues/2982
The rule would produce invalid code when trying to fix it.
Fixes #2982
> fix(eslint-plugin): [member-delimiter-style] correct invalid fix for multiline with params on the same line

- packages/eslint-plugin/docs/rules/unbound-method.md
Relates to #2951
-------
We've not had any complaints so far 🤷
> docs(eslint-plugin): [unbound-method] reference eslint-plugin-jests extension rule

- packages/eslint-plugin/src/rules/type-annotation-spacing.ts
- packages/eslint-plugin/tests/rules/type-annotation-spacing.test.ts
Fixes type-annotation-spacing rule to give an error if there is a space between `?` and `:` in a type annotation.
Fixes #3140
> feat(eslint-plugin): [type-annotation-spacing] handle space between ? and :

- packages/eslint-plugin/src/rules/space-infix-ops.ts
- packages/eslint-plugin/tests/rules/space-infix-ops.test.ts
Hey,
I've bumped into this issue after migrating to eslint. Nice work btw! We've used whitespace rule in tslint for certain formatting and this PR will bring feature parity closer to what was there before. I know it's about whitespace, but moving to prettier is just too much for our code base and the patterns we are used to. Maybe one day :) (plenty of things gets far less readable)
Fixes #1699 
A bit later I'll also have a look at #1606
EDIT:
2nd commit fixes first part of #1606
> feat(eslint-plugin): [space-infix-ops] support for class properties and type aliases

- packages/eslint-plugin/src/rules/no-type-alias.ts
- packages/eslint-plugin/tests/rules/no-type-alias.test.ts
> fix(eslint-plugin): [no-type-alias] consider `keyof` as an alias

- packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
- packages/eslint-plugin/src/rules/no-unsafe-call.ts
- packages/eslint-plugin/src/rules/no-unsafe-member-access.ts
- packages/eslint-plugin/src/rules/no-unsafe-return.ts
- packages/eslint-plugin/src/util/getThisExpression.ts
- packages/eslint-plugin/src/util/index.ts
- packages/eslint-plugin/tests/fixtures/tsconfig.noImplicitThis.json
- packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
- packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
- packages/eslint-plugin/tests/rules/no-unsafe-member-access.test.ts
- packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
> feat(eslint-plugin): [no-unsafe-call][no-unsafe-member-access] improve report messages for `this` for `noImplicitThis`

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Fixes #3187.
Since TypeScript is smart about inferring types for variable assignments, I think it's reasonable to always exclude the right-hand-side of assignment expressions.
> fix(eslint-plugin): always ignore assignments in no-unnecessary-type-assertion

- packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
- packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Fixes #3115.
I hadn't seen this version of the code with phrases like `is('nullish', 'string')`. Very clever & readable! The code as-is does a _lot_ of loop iterations, but I guess that's fine because type unions are typically very small?
> fix(eslint-plugin): [strict-boolean-expressions] account for truthy literals

- packages/eslint-plugin/src/rules/restrict-plus-operands.ts
- packages/eslint-plugin/tests/rules/restrict-plus-operands.test.ts
> fix(eslint-plugin): [restrict-plus-operands] consider template literal types as strings

- packages/eslint-plugin/src/rules/no-unsafe-argument.ts
- packages/eslint-plugin/tests/rules/no-unsafe-argument.test.ts
@G-Rath noticed that we were false-reporting on jest expect functions.
Turns out this was because I hadn't handled tuple rest types.
It turns out that generic array rest types are reported by TS as if they were tuples.
So for `function foo<T extends any[]>(...param: T): void` - `param` will always report as a tuple.
Eg `foo(1, 2, 'a', 1 as any)` will report the type of `param` to be `[number, number, string, any]`. Which means we can't actually do a check here 😢
> fix(eslint-plugin): [no-unsafe-argument] handle tuple types on rest arguments

- .eslintrc.js
- tools/generate-contributors.ts
Starts on #3278.
This was the only rule with very few violations: only one.
> chore: enable no-floating-promises internally

- packages/experimental-utils/src/ts-eslint/Rule.ts
It's in https://eslint.org/docs/developer-guide/working-with-rules#the-context-object
> feat(experimental-utils): Include `getCwd()` in `RuleContext` type

- packages/experimental-utils/src/ast-utils/predicates.ts
`Comment` is a sub-type of `Token`
https://github.com/typescript-eslint/typescript-eslint/blob/26d71b57fbff013b9c9434c96e2ba98c6c541259/packages/types/src/ts-estree.ts#L117-L129
> chore(experimental-utils): remove useless union types `ast-utils` predicates

- packages/eslint-plugin/src/rules/no-loss-of-precision.ts
This commit fixes a typo in the name of the helper function `isSeparatedNumeric`.
> chore(eslint-plugin): [no-loss-of-precision] fix spelling of `isSeparatedNumeric`

- packages/eslint-plugin/src/rules/no-shadow.ts
- packages/eslint-plugin/tests/rules/no-shadow.test.ts
Fixes #2592
Unfortunately I think this is impossible to solve from the scope analysis side.. So I opted instead to just ignore it from the lint rule.
> fix(eslint-plugin): [no-shadow] fix static class method generics shadowing class generics

- packages/eslint-plugin/src/rules/no-unsafe-argument.ts
- packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
- packages/eslint-plugin/src/rules/no-unsafe-return.ts
- packages/eslint-plugin/src/util/types.ts
- packages/eslint-plugin/tests/rules/no-unsafe-argument.test.ts
- packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
- packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
- packages/eslint-plugin/tests/util/isUnsafeAssignment.test.ts
Fixes #2109
Sucks that it had to be this way, but oh well.
> fix(eslint-plugin): [no-unsafe-*] special case handling for the empty map constructor with no generics

- packages/eslint-plugin/docs/rules/no-unnecessary-boolean-literal-compare.md
Just a simple fix on the docs. It was using `booleanLiteral` instead of `booleanVar`
> docs(eslint-plugin): [no-unnecessary-boolean-literal-compare] fix fixer docs

- packages/eslint-plugin/ROADMAP.md
I noticed in https://github.com/typescript-eslint/tslint-to-eslint-config/pull/1068 that this is off; `no-dynamic-delete` was ported over.
> docs: updated no-delete-expression roadmap equivalent to no-dynamic-delete

- packages/eslint-plugin/ROADMAP.md
Noticed in https://github.com/typescript-eslint/tslint-to-eslint-config/issues/892: despite its name, the rule is about letting developers explicitly mark certain areas of code as specific to a browser.
> docs(eslint-plugin): corrected no-unsupported-browser-code in roadmap as unimplemented

- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/tests/rules/member-ordering.test.ts
Fixes https://github.com/typescript-eslint/typescript-eslint/issues/3037
> feat(eslint-plugin): [member-ordering] add callback as an ordering type of node

- packages/eslint-plugin/src/rules/space-infix-ops.ts
- packages/eslint-plugin/tests/rules/space-infix-ops.test.ts
Second PR so maybe i'm missing something. I added support for Union and Intersection of interface and type declarations.
There is the yarn.lock that was updated and don't understand why, i can remove it if it not support to be there
> feat(eslint-plugin): [space-infix-ops] Add support for Union and intersection of type declarations

- packages/experimental-utils/src/ast-utils/eslint-utils/predicates.ts
- packages/experimental-utils/src/ast-utils/misc.ts
`Comment` is a sub-type of `Token`
https://github.com/typescript-eslint/typescript-eslint/blob/02acc4f528c92efb4a7023ee3fa26413fd6180bb/packages/ast-spec/src/unions/Token.ts#L14-L26
---
Follow-up of #3289
> chore(experimental-utils): remove useless union types in `ast-utils`

- packages/experimental-utils/src/ts-eslint/Rule.ts
- packages/experimental-utils/src/ts-eslint/SourceCode.ts
`Comment` is a sub-type of `Token`
https://github.com/typescript-eslint/typescript-eslint/blob/02acc4f528c92efb4a7023ee3fa26413fd6180bb/packages/ast-spec/src/unions/Token.ts#L14-L26
---
Follow-up of #3289
> chore(experimental-utils): remove useless union types in `ts-eslint`

- packages/ast-spec/src/unions/LeftHandSideExpression.ts
Remove `TemplateLiteral` from `LeftHandSideExpression` as `TemplateLiteral` is a sub-type of `LiteralExpression`, which is a sub-type of `LeftHandSideExpression`
https://github.com/typescript-eslint/typescript-eslint/blob/02acc4f528c92efb4a7023ee3fa26413fd6180bb/packages/ast-spec/src/unions/LiteralExpression.ts#L4
https://github.com/typescript-eslint/typescript-eslint/blob/02acc4f528c92efb4a7023ee3fa26413fd6180bb/packages/ast-spec/src/unions/LeftHandSideExpression.ts#L23-L44
> chore(ast-spec): remove useless union type from `LeftHandSideExpression`

- packages/ast-spec/src/expression/AwaitExpression/spec.ts
`TSTypeAssertion` is a sub-type of `LeftHandSideExpression`
https://github.com/typescript-eslint/typescript-eslint/blob/02acc4f528c92efb4a7023ee3fa26413fd6180bb/packages/ast-spec/src/unions/LeftHandSideExpression.ts#L23-L44
> chore(ast-spec): remove useless union type from `AwaitExpression`'s `argument`

- packages/ast-spec/src/unions/TSUnaryExpression.ts
`TSTypeAssertion` is a sub-type of `LeftHandSideExpression`
https://github.com/typescript-eslint/typescript-eslint/blob/02acc4f528c92efb4a7023ee3fa26413fd6180bb/packages/ast-spec/src/unions/LeftHandSideExpression.ts#L23-L44
> chore(ast-spec): remove useless union type from `TSUnaryExpression`

- tests/integration/fixtures/vue-jsx/Jsx.vue
- tests/integration/fixtures/vue-jsx/test.js.snap
- tests/integration/fixtures/vue-sfc/Hello.vue
- tests/integration/fixtures/vue-sfc/World.vue
- tests/integration/fixtures/vue-sfc/test.js.snap
- tests/performance/docker-compose.yml
When working on #3419, #3420 & #3421, my IDE (WebStorm) started complaining about files that some files weren't prettified
> chore: prettify codebase

- packages/eslint-plugin/docs/rules/no-this-alias.md
ref: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/no-this-alias.ts#L49
> docs(eslint-plugin): [no-this-alias] `allowDestructuring` is `true` by default

- packages/eslint-plugin/src/rules/comma-spacing.ts
- packages/eslint-plugin/src/rules/consistent-type-imports.ts
- packages/eslint-plugin/src/rules/indent-new-do-not-use/BinarySearchTree.ts
- packages/eslint-plugin/src/rules/indent-new-do-not-use/OffsetStorage.ts
- packages/eslint-plugin/src/rules/indent-new-do-not-use/TokenInfo.ts
- packages/eslint-plugin/src/rules/indent-new-do-not-use/index.ts
- packages/eslint-plugin/src/rules/object-curly-spacing.ts
`Comment` is a sub-type of `Token`
https://github.com/typescript-eslint/typescript-eslint/blob/02acc4f528c92efb4a7023ee3fa26413fd6180bb/packages/ast-spec/src/unions/Token.ts#L14-L26
---
Follow-up of #3289
> chore(eslint-plugin): remove useless union types

- packages/eslint-plugin/src/rules/no-type-alias.ts
- packages/eslint-plugin/tests/rules/no-type-alias.test.ts
> fix(eslint-plugin): [no-type-alias] consider type imports as alias types

- packages/ast-spec/src/parameter/TSParameterProperty/spec.ts
- packages/shared-fixtures/fixtures/typescript/basics/class-with-constructor-and-parameter-property-with-modifiers.src.ts
- packages/shared-fixtures/fixtures/typescript/basics/class-with-constructor-and-parameter-proptery-with-override-modifier.src.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
- packages/typescript-estree/tests/snapshots/typescript/basics/class-with-constructor-and-parameter-property-with-modifiers.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/basics/class-with-constructor-and-parameter-proptery-with-override-modifier.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/basics/class-with-export-parameter-properties.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/basics/class-with-private-parameter-properties.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/basics/class-with-protected-parameter-properties.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/basics/class-with-public-parameter-properties.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/basics/class-with-static-parameter-properties.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/basics/interface-with-construct-signature-with-parameter-accessibility.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/namespaces-and-modules/nested-internal-module.src.ts.shot
ref: https://github.com/prettier/prettier/issues/11017
Support TS 4.3 `override` modifier for parameter properties.
[TS Playground Link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBC0G8BQ1XWAewHYQC4CcBXYXDfACgAd8NcBTEugE2nzrCexAE91sAzAJYBzAFyJoYcXnyCswgNzQARuKyEAtsrr5oAXwCUiFGj1IzSUJBgARaHQAe9LExjxkqTDgLFSFarQM9CzQGABuOrJMdKhsHFy8fFhCYhJS0DJyiipqmtq6hsZoGYSUOuReKQYKJmZmQA)
> fix(typescript-estree): support override modifier for parameter property

- packages/ast-spec/src/expression/LogicalExpression/spec.ts
Just like #3496 is doing for `PunctuatorToken`'s `value` type
> feat(ast-spec): specify `LogicalExpression`'s `operator` type

- packages/eslint-plugin/docs/rules/prefer-literal-enum-member.md
- packages/eslint-plugin/src/rules/prefer-literal-enum-member.ts
- packages/eslint-plugin/tests/rules/prefer-literal-enum-member.test.ts
Fixes https://github.com/typescript-eslint/typescript-eslint/issues/3487
> feat(eslint-plugin): [prefer-literal-enum-member] add allowBitwiseExpressions option

- packages/eslint-plugin/src/rules/no-unsafe-return.ts
- packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
Generally uses the same check that already existed for _some_ cases to make sure we don't give a complaint if the function's explicit return type matches its actual return type.
Fixes #3482.
> fix(eslint-plugin): allow explicit any for no-unsafe-return

- packages/typescript-estree/src/node-utils.ts
`SyntaxKind.LastBinaryOperator` & `SyntaxKind.LastPunctuation` have the same value (`77`)
https://github.com/microsoft/TypeScript/blob/663b19fe4a7c4d4ddaa61aedadd28da06acd27b6/lib/typescript.d.ts#L472
https://github.com/microsoft/TypeScript/blob/663b19fe4a7c4d4ddaa61aedadd28da06acd27b6/lib/typescript.d.ts#L462
> chore(typescript-estree): use `SyntaxKind.LastPunctuation` as upper bound to determine `Punctuator` token type

- package.json
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- yarn.lock
@babel/parser 7.14.6 supports override modifiers for parameter property.
I'm not sure if this is the correct diff for yarn.lock.
Ref: https://github.com/babel/babel/blob/main/CHANGELOG.md#v7146-2021-06-14
> test: update @babel/parser to update ignored fixtures

- packages/experimental-utils/src/ast-utils/eslint-utils/predicates.ts
Just like it's done with `isNotCommentToken`
https://github.com/typescript-eslint/typescript-eslint/blob/d4f077473afb04f7c4d377dd87318749632b4404/packages/experimental-utils/src/ast-utils/eslint-utils/predicates.ts#L49-L51
> fix(experimental-utils): fix `eslint-utils`' negative predicates' return types in `ast-utils`

- packages/experimental-utils/src/ast-utils/predicates.ts
Just like it's done with `ast-utils`' `isNotCommentToken`
https://github.com/typescript-eslint/typescript-eslint/blob/d4f077473afb04f7c4d377dd87318749632b4404/packages/experimental-utils/src/ast-utils/eslint-utils/predicates.ts#L49-L51
> fix(experimental-utils): fix `eslint-utils`' negative predicates' return types

- packages/experimental-utils/src/ast-utils/eslint-utils/ReferenceTracker.ts
> fix(experimental-utils): make keys for `ReferenceTracker` options optional

- packages/experimental-utils/src/ast-utils/eslint-utils/ReferenceTracker.ts
- packages/experimental-utils/typings/eslint-utils.d.ts
Fixes #3527 
ReferenceTracker.ESM seems to be undocumented, but it marks a trace map as being an ES module. It is used only once that I can see, here: https://github.com/mysticatea/eslint-utils/blob/c3b1d38328dc3a5278b208a58186a0735315f58f/src/reference-tracker.js#L181
The code only checks if the trace map has they key, and does nothing with it's value. Therefore when adding it to the TraceMapElement type, I opted to type it as always `true`, if it's present. In theory something like `any` or `unknown` would work, but that wouldn't convey that it's just a flag; a type of `boolean` might lead to confusion if users think they can do `[ReferenceTracker.ESM]: false` and expect it to be disabled.
> feat(experimental-utils): expose ReferenceTracker.ESM

- packages/experimental-utils/src/ts-eslint/RuleTester.ts
Was added in latest eslint: https://github.com/eslint/eslint/pull/14677 🎉 
(cc @SimenB in case you missed it - I'm so glad we finally have this 😍)
> feat(experimental-utils): add `only` property to `RuleTester` types

- packages/experimental-utils/src/ts-eslint/RuleTester.ts
From [the docs](https://eslint.org/docs/developer-guide/nodejs-api#ruletester):
> The RuleTester constructor accepts an optional object argument, which can be used to specify defaults for your test cases. For example, if all of your test cases use ES2015, you can set it as a default:
Have configured that this is supported & usable for e.g. setting `settings`:
```
const ruleTester = new TSESLint.RuleTester({
parser: resolveFrom(require.resolve('eslint'), 'espree'),
parserOptions: {
ecmaVersion: 2015,
},
settings: { hookNames: ['beforeAll', 'beforeEach', 'afterAll', 'afterEach'] },
});
```
> fix(experimental-utils): expand `RuleTester` config properties

- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/util/astUtils.ts
- packages/eslint-plugin/src/util/escapeRegExp.ts
It is not necessary to add a full lodash as a dependency just for escaping RegExp, right?
> chore(eslint-plugin): remove lodash from dependencies

- packages/experimental-utils/src/ts-eslint/Linter.ts
- packages/experimental-utils/src/ts-eslint/Rule.ts
- packages/experimental-utils/src/ts-eslint/RuleTester.ts
This lets us do declaration merging to define settings at the plugin level e.g.
```
interface ESLintPluginJestSettings {
describeBlocks: readonly string[];
hookNames: readonly string[];
}
declare module '@typescript-eslint/experimental-utils/dist/ts-eslint/Rule' {
export interface SharedConfigurationSettings
extends ESLintPluginJestSettings {}
}
```
> feat(experimental-utils): use mergable interface for `settings` property

- packages/ast-spec/src/token/PunctuatorToken/PunctuatorTokenToText.ts
- packages/ast-spec/tests/PunctuatorTokenToText.test.ts
Follow-up of #3496
We should somehow test that all possible values of `PunctuationSyntaxKind` are definitely included.
If not, this should error out somehow.
I first tried doing
```ts
export const PunctuatorTokenToText: Record<PunctuationSyntaxKind, string> = {
// ...
}
```
and this errored out (as expected) because `SyntaxKind.BacktickToken` isn't includes, but is included in `PunctuationSyntaxKind`.
Not including the type makes it also of type `string` again, which will fail #3461 & #3462.
This however made it a value instead of a type and had the implication that `SyntaxKind.BarBarEqualsToken`, `SyntaxKind.AmpersandAmpersandEqualsToken` & `SyntaxKind.QuestionQuestionEqualsToken` couldn't be added as they'll only be added to `PunctuationSyntaxKind` in TS 4.4 (they're currently included …
> tests(ast-spec): make `PunctuatorTokenToText` more type-safe

- packages/experimental-utils/src/ast-utils/eslint-utils/predicates.ts
Extracted the `IsNotPunctuatorTokenWithValueFunction` generic (the negative generic of what I've done in #3550) to get rid of all duplicates
> refactor(experimental-utils): simplify `eslint-utils`' predicate types in `ast-utils`

- packages/eslint-plugin/ROADMAP.md
https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/html-has-lang.md now has a notice that `html-has-lang` is largely superseded by `lang`.
> docs: remove almost-deprecated html-has-lang rule from ROADMAP.md

- packages/experimental-utils/src/ast-utils/eslint-utils/predicates.ts
Extract `IsSpecificTokenFunction` & `IsNotSpecificTokenFunction` generics to simplify `IsPunctuatorTokenWithValueFunction` & `IsNotPunctuatorTokenWithValueFunction` even more and to simplify the types of `isCommentToken` & `isNotCommentToken`
> refactor(experimental-utils): simplify `eslint-utils`' predicate types in `ast-utils` even more

- packages/eslint-plugin/docs/rules/no-redeclare.md
- packages/eslint-plugin/src/rules/no-redeclare.ts
- packages/eslint-plugin/tests/rules/no-redeclare.test.ts
> feat(eslint-plugin): [no-redeclare] ignoreDeclarationMerge of enum+namespace

- packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-boolean-literal-compare.test.ts
Fixes #3442
Before this PR no-unnecessary-boolean-literal-compare fix would change
```
if (true === var) {
...
}
```
to
```
if (true) {
...
}
```
instead of 
```
if (var) {
...
}
```
This PR intends to fix this issue.
> fix(eslint-plugin): [no-unnecessary-boolean-literal-compare] incorrect fix when condition is reversed

- packages/eslint-plugin/docs/rules/no-use-before-define.md
* https://github.com/typescript-eslint/typescript-eslint/issues/1856 has been closed since last summer
* Fix typo in `enums` configuration example
> docs(eslint-plugin): [no-use-before-define] fix typo and outdated issue

- packages/eslint-plugin/src/rules/no-implied-eval.ts
- packages/eslint-plugin/tests/rules/no-implied-eval.test.ts
Fixes https://github.com/typescript-eslint/typescript-eslint/issues/3582
> fix(eslint-plugin): [no-implied-eval] handle bind on nested member expressions

- packages/eslint-plugin/src/rules/return-await.ts
- packages/eslint-plugin/tests/rules/return-await.test.ts
> fix(eslint-plugin): [return-await] handle nested functions correctly

- .github/workflows/ci.yml
This step is failing on forks
Ref: https://github.com/MichaelDeBoey/typescript-eslint/runs/3213160896
> chore: only run CI publish step on official repo

- packages/typescript-estree/src/index.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tests/lib/semanticInfo-singleRun.test.ts
I realise this isn't the most sophisticated fix (and we can improve this further in the future by adding support for the catch-all builder program as we discussed as part of the long-term solution to `createDefaultProgram`) but for now this at least makes singleRun mode usable with `--fix` and in my basic testing locally it still yields a speed up over the same invocation without singleRun mode enabled.
Fixes #3626
> fix(typescript-estree): ensure --fix works with singleRun mode

- packages/eslint-plugin/src/rules/comma-dangle.ts
Continues #3738 by matching the rule's to the new ESLint value. Just on echange: adding an `additionalProperties: false`.
Refs: https://github.com/eslint/eslint/issues/13739, https://github.com/eslint/eslint/pull/14030
> feat(eslint-plugin): [comma-dangle] align schema with ESLint v8

- packages/experimental-utils/src/ts-eslint/SourceCode.ts
Tackles a small part of #3738: the `getComments()` API is deprecated so we generally don't want to use it.
Ref: https://github.com/eslint/eslint/issues/14744, https://github.com/eslint/eslint/pull/14769
> feat(experimental-utils): remove `getComments` from `ESLint` `SourceCode` types

- README.md
- package.json
- packages/ast-spec/src/ast-node-types.ts
- packages/ast-spec/src/element/StaticBlock/spec.ts
- packages/ast-spec/src/element/spec.ts
- packages/ast-spec/src/token/PunctuatorToken/PunctuatorTokenToText.ts
- packages/ast-spec/src/unions/ClassElement.ts
- packages/ast-spec/src/unions/Node.ts
- packages/eslint-plugin/src/rules/indent-new-do-not-use/OffsetStorage.ts
- packages/parser/tests/tools/test-utils.ts
- packages/scope-manager/tests/fixtures.test.ts
- packages/shared-fixtures/fixtures/typescript/basics/class-static-blocks.src.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/node-utils.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/src/ts-estree/estree-to-ts-node-types.ts
- packages/typescript-estree/src/ts-estree/ts-nodes.ts
- packages/typescript-estree/tests/ast-alignment/parse.ts
- packages/typescript-estree/tests/ast-alignment/utils.ts
- packages/typescript-estree/tests/ast-fixtures.test.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
- packages/typescript-estree/tests/lib/parse.test.ts
- packages/typescript-estree/tests/snapshots/jsx/invalid-mismatched-closing-tag.src.js.shot
- packages/typescript-estree/tests/snapshots/jsx/invalid-mismatched-dot-tag-name.src.js.shot
- packages/typescript-estree/tests/snapshots/jsx/invalid-mismatched-namespace-tag.src.js.shot
- packages/typescript-estree/tests/snapshots/typescript/basics/class-static-blocks.src.ts.shot
- packages/typescript-estree/tools/test-utils.ts
- packages/visitor-keys/src/visitor-keys.ts
- yarn.lock
[TypeScript 4.4 RC has been announced.](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-rc)
And it supports Stage-3 class static blocks ( https://devblogs.microsoft.com/typescript/announcing-typescript-4-4-rc/#static-blocks ).
This PR adds support for class static blocks.
> feat(typescript-estree): add support for class static blocks

- packages/eslint-plugin/src/rules/no-dupe-class-members.ts
- packages/eslint-plugin/tests/rules/no-dupe-class-members.test.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
*This PR is for version 5.*
I noticed that the `no-dupe-class-members` rule crashes with property definition that has no value due to my changes. This PR fixes it problem.
> fix(eslint-plugin): crash in no-dupe-class-members (v5)

- packages/experimental-utils/src/ts-eslint/Linter.ts
In addition to boolean values, the string values below are allowed in `globals` field of `BaseConfig`.
- "readable"
- "readonly"
- "writeable"
- "writable"
- "off"
> Globals can be disabled with the string "off". For example, in an environment where most ES2015 globals are available but Promise is unavailable, you might use this config:
> For historical reasons, the boolean value false and the string value "readable" are equivalent to "readonly". Similarly, the boolean value true and the string value "writeable" are equivalent to "writable". However, the use of older values is deprecated.
https://eslint.org/docs/user-guide/configuring/language-options#using-configuration-files-1
> feat(experimental-utils): add literal types to `global` option

- packages/eslint-plugin/src/rules/dot-notation.ts
- packages/eslint-plugin/tests/rules/dot-notation.test.ts
> fix(eslint-plugin): [dot-notation] false positive with optional chaining

- packages/eslint-plugin/docs/rules/require-array-sort-compare.md
_"noted in the"_ was repeated in the text. Please refer the changes.
> docs(eslint-plugin): fix typo

- packages/eslint-plugin/docs/rules/ban-types.md
- packages/eslint-plugin/src/rules/ban-types.ts
BREAKING CHANGE: `ban-types` no longer reports `object` by default
---
Part of #3738
Part of #3746
> feat(eslint-plugin): remove `object` from `ban-types`' default types

- packages/experimental-utils/src/ast-utils/predicates.ts
Just like I did in https://github.com/testing-library/eslint-plugin-testing-library/pull/329
> feat(experimental-utils): extract `isNodeOfType` out of `ast-utils`' `predicates`

- packages/eslint-plugin/docs/rules/restrict-template-expressions.md
- packages/eslint-plugin/src/rules/restrict-template-expressions.ts
- packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
> feat(eslint-plugin): [restrict-template-expressions] add option to allow RegExp

- packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md
- packages/eslint-plugin/src/rules/prefer-readonly-parameter-types.ts
- packages/eslint-plugin/src/util/isTypeReadonly.ts
- packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
> feat(eslint-plugin): [prefer-readonly-parameter-types] add option treatMethodsAsReadonly

- packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
- packages/eslint-plugin/src/rules/consistent-type-imports.ts
- packages/eslint-plugin/src/rules/no-confusing-non-null-assertion.ts
- packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
- packages/eslint-plugin/src/rules/no-duplicate-imports.ts
- packages/eslint-plugin/src/rules/no-implicit-any-catch.ts
- packages/eslint-plugin/src/rules/no-invalid-void-type.ts
- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/src/rules/prefer-enum-initializers.ts
- packages/eslint-plugin/src/rules/prefer-return-this-type.ts
Revisiting #1935 a year later – some rule messages are missing a period at the end, and there is one instance of a message beginning with a lowercase letter.
> chore(eslint-plugin): fix missing periods in rule messages

- packages/eslint-plugin/docs/rules/no-unnecessary-type-assertion.md
> docs(eslint-plugin): fix incorrect quote

- packages/eslint-plugin/src/rules/no-explicit-any.ts
- packages/eslint-plugin/src/rules/prefer-enum-initializers.ts
- packages/experimental-utils/src/ts-eslint/Rule.ts
> fix(utils): support immutable arrays in `ReportFixFunction`

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
This PR fixes several false-positive/negatives in no-unnecessary-condition.
- False-positive at nullish coalescing after array index access: `arr[42]?.foo ?? 0`
- False-negative at `arr[42] ?? 0` where `arr[42]` is always nullish or never.
- False-negative at `arr[0].foo?.bar` where `foo` is not nullable.
> fix(eslint-plugin): false-positive/negative with array index in no-unnecessary-condition

- package.json
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/ast-alignment/utils.ts
- yarn.lock
~~This is still draft because blocked by https://github.com/babel/babel/pull/13731.~~
Updates `@babel/parser` to latest!
> test(typescript-estree): update `@babel/parser` to 7.15.4

- .eslintrc.js
- packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
- packages/scope-manager/tests/fixtures.test.ts
- packages/scope-manager/tests/util/serializers/TSESTreeNode.ts
- packages/scope-manager/tests/util/serializers/baseSerializer.ts
> chore: enabled restrict-template-expressions internally

- packages/eslint-plugin/src/rules/padding-line-between-statements.ts
- packages/eslint-plugin/tests/rules/padding-line-between-statements.test.ts
> fix(eslint-plugin): [padding-line-between-statements] problems within namespaces not being reported

- packages/experimental-utils/src/ast-utils/eslint-utils/astUtilities.ts
> fix(experimental-utils): add missing signature for `isParenthesized`

- packages/eslint-plugin/src/rules/consistent-type-definitions.ts
- packages/eslint-plugin/tests/rules/consistent-type-definitions.test.ts
> fix(eslint-plugin): [consistent-type-definitions] correct fix for `export default`

- packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
- packages/eslint-plugin/tests/rules/explicit-member-accessibility.test.ts
> fix(eslint-plugin): [explicit-member-accessibility] report `TSAbstractPropertyDefinition` and `TSAbstractMethodDefinition` properly

- packages/parser/README.md
- packages/parser/src/parser.ts
- packages/parser/tests/lib/parser.ts
- packages/scope-manager/README.md
- packages/scope-manager/src/analyze.ts
- packages/scope-manager/tests/eslint-scope/map-ecma-version.test.ts
- packages/types/src/parser-options.ts
Done: https://github.com/typescript-eslint/typescript-eslint/issues/3857
> feat: Support `'latest'` as `ecmaVersion`

- packages/eslint-plugin/docs/rules/no-type-alias.md
- packages/eslint-plugin/src/rules/no-type-alias.ts
- packages/eslint-plugin/tests/rules/no-type-alias.test.ts
Fixes #3784
(⚠️ Note: an earlier version of this PR introduced an `allowedAliasNames: []` option which accepted an array of strings to ignore. This was later swapped to an `allowGenerics: 'always' | 'never'` option that permits/prevents _any_ `TSTypeReference` that has parameters)
This change adds an option to `no-type-alias` to allow generics to be ignored by the rule.
The new option is `allowGenerics`, and can be set to `"always"` or `"never"` (default is `"never"`), e.g.
```json
{
"@typescript-eslint/no-type-alias": ["error", { "allowGenerics": "always" }]
}
```
As discussed in #3784, the main driver for this change is to avoid a conflict when using both `consistent-indexed-object-style` and `no-type-alias` with their default options.
Specifically to allow the following code to pass …
> feat(eslint-plugin): [no-type-alias]: add allowGenerics option

- packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
- packages/eslint-plugin/tests/rules/prefer-regexp-exec.test.ts
> fix(eslint-plugin): [prefer-regexp-exec] respect flags when using `RegExp`

- packages/eslint-plugin/src/rules/no-require-imports.ts
- packages/eslint-plugin/tests/rules/no-require-imports.test.ts
> fix(eslint-plugin): [no-require-imports] report only global `require`

- packages/eslint-plugin/src/rules/no-shadow.ts
- packages/eslint-plugin/tests/rules/no-shadow.test.ts
> fix(eslint-plugin): [no-shadow] ignore type-only imports properly

- packages/eslint-plugin-internal/package.json
- packages/eslint-plugin-internal/src/rules/no-poorly-typed-ts-props.ts
- packages/eslint-plugin-internal/src/rules/prefer-ast-types-enum.ts
- packages/eslint-plugin-internal/tests/rules/no-poorly-typed-ts-props.test.ts
- packages/eslint-plugin-internal/tests/rules/prefer-ast-types-enum.test.ts
- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/src/rules/no-inferrable-types.ts
- packages/eslint-plugin/src/rules/no-shadow.ts
- packages/eslint-plugin/src/rules/no-type-alias.ts
- packages/eslint-plugin/src/rules/no-unused-vars-experimental.ts
- packages/eslint-plugin/src/rules/no-use-before-define.ts
- packages/eslint-plugin/tests/rules/ban-types.test.ts
- packages/eslint-plugin/tests/rules/naming-convention.test.ts
- packages/eslint-plugin/tests/rules/no-unused-vars-experimental.test.ts
- packages/scope-manager/src/definition/DefinitionType.ts
- packages/scope-manager/tests/eslint-scope/references.test.ts
As per discussion on https://github.com/typescript-eslint/typescript-eslint/pull/3868#issuecomment-923458462
> feat(eslint-plugin-internal): [prefer-ast-types-enum] add `DefinitionType` enum

- packages/ast-spec/src/base/NodeOrTokenData.ts
- packages/ast-spec/src/base/Position.ts
- packages/ast-spec/src/base/SourceLocation.ts
- packages/ast-spec/src/index.ts
- packages/eslint-plugin/src/util/getFunctionHeadLoc.ts
- packages/experimental-utils/src/ts-eslint/Rule.ts
- packages/experimental-utils/src/ts-eslint/SourceCode.ts
- packages/typescript-estree/src/node-utils.ts
- packages/typescript-estree/tests/ast-alignment/parse.ts
https://github.com/estree/estree/blob/master/es5.md#node-objects
https://eslint.org/docs/developer-guide/working-with-custom-parsers#the-ast-specification
---
BREAKING CHANGE: `LineAndColumnData` is renamed to `Position`
> feat(ast-spec): bring `Node` objects in line with ESTree

- .github/ISSUE_TEMPLATE/eslint-plugin-typescript.yml
The current template for the plugin is centered around bug reporting: https://github.com/typescript-eslint/typescript-eslint/issues/new?assignees=&labels=package%3A+eslint-plugin%2C+triage&template=eslint-plugin-typescript.md&title=%5Brulename%5D+issue+title
https://github.com/fregante/sandbox/issues/new?assignees=&labels=enhancement%3A+new+base+rule+extension%2Cpackage%3A+eslint-plugin%2Ctriage&template=a.yml&title=Rule+proposal%3A+
https://github.com/typescript-eslint/typescript-eslint/issues/3926
> chore: add issue template to propose new rules

- packages/experimental-utils/src/ast-utils/predicates.ts
Like #3677, but with extra conditions
> feat(experimental-utils): extract `isNodeOfTypeWithConditions` out of `ast-utils`' `predicates`

- packages/eslint-plugin/src/rules/no-shadow.ts
Context: https://github.com/typescript-eslint/typescript-eslint/pull/3871#issuecomment-923679179
> refactor(eslint-plugin): [no-shadow] use `findVariable` from utils

- packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
- packages/eslint-plugin/tests/rules/no-confusing-void-expression.test.ts
> fix(eslint-plugin): [no-confusing-void-expression] support optional chaining

- packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts
- packages/eslint-plugin/tests/rules/non-nullable-type-assertion-style.test.ts
Fixes #3938.
As suggested there, a simple array length assertion did the trick. I added two regression test cases for this check.
> fix(eslint-plugin): [non-nullable-type-assertion-style] false-positive with non-nullish `as` assertions and types

- packages/eslint-plugin/src/rules/lines-between-class-members.ts
- packages/eslint-plugin/tests/rules/lines-between-class-members.test.ts
> fix(eslint-plugin): [lines-between-class-members] fix `exceptAfterOverload` for abstract methods

- packages/eslint-plugin/src/rules/padding-line-between-statements.ts
- packages/eslint-plugin/tests/rules/padding-line-between-statements.test.ts
Updates the scope changes to include `TSModuleBlock`. This helps a `module` declaration be its own scope, thereby fixing false positives related to #3869
> fix(eslint-plugin): [padding-line-between-statements] TSModuleBlock should change scope

- packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
- packages/eslint-plugin/tests/rules/prefer-regexp-exec.test.ts
> fix(eslint-plugin): [prefer-regexp-exec] check `RegExp` without flags

- packages/eslint-plugin/src/rules/no-restricted-imports.ts
- packages/eslint-plugin/tests/rules/no-restricted-imports.test.ts
> fix(eslint-plugin): [no-restricted-imports] fix crash when no options given

- packages/experimental-utils/src/ts-eslint/Rule.ts
Fixes #3948 
Every suggestion _must_ have a fix function, it can't be left empty (nullish).
I did a similar fix in eslint's types recently. Really they should be aligned IMO but it seems they're already diverged anyway.
> fix(experimental-utils): require fix in suggestions

- CONTRIBUTING.md
-   [x] Addresses an existing issue: fixes #4010 _(-ish)_
#4066 was sent in without an attached issue. Time to make the docs more explicit?
> chore: mention needing an issue for a PR in CONTRIBUTING.md

- packages/experimental-utils/src/ts-eslint/RuleTester.ts
-   [x] Addresses an existing issue: fixes #3920
I implemented this in [ESLint](https://github.com/eslint/eslint/pull/15179).
> fix(experimental-utils): add `name` property to test case interface

- packages/eslint-plugin/docs/rules/consistent-type-definitions.md
Fix consistent-type-definitions README with correct usage of `type`, as of right now, the README conflicts with itself.
> docs(eslint-plugin): Fix `consistent-type-definitions` README with correct usage of type

- packages/experimental-utils/src/ast-utils/helpers.ts
- packages/experimental-utils/src/ast-utils/predicates.ts
#3976 needs to be merged first
> feat(experimental-utils): extract `isTokenOfTypeWithConditions` out of `ast-utils`' `predicates`

- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
-   [x] Addresses an existing issue: fixes #1740
`PrivateIdentifier` key nodes indicate it's a `#`.
> fix(eslint-plugin): ignore private identifiers in explicit-module-boundary-types

- package.json
- packages/typescript-estree/tests/ast-alignment/utils.ts
- packages/typescript-estree/tests/lib/semanticInfo-singleRun.test.ts
- yarn.lock
Update babel package to 7.16 and align tests, this change is necessary for #4099 and #3147
closes #4085
> chore: bump babel to 7.16.x and update tests

- packages/eslint-plugin/tests/rules/await-thenable.test.ts
Added tests based on #4095 to confirm that `await-thenable` supports optional chaining and continues to do in future.
> test(eslint-plugin): add optional chaining cases for `await-thenable`

- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
-   [x] Addresses an existing issue: fixes #4095
Changes `no-floating-promises` to "expand" optional chain so that it's expression is checked.
> fix(eslint-plugin): check optional chaining for floating promises

- packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
- packages/eslint-plugin/tests/rules/explicit-member-accessibility.test.ts
-   [x] Addresses an existing issue: fixes #1666
Private fields, like methods, cannot have accessibility modifiers, and so they shouldnt be required by this rule. To fix this I took the fix that was already done for private methods (#3808) and applied it to private fields too.
> fix(eslint-plugin): [explicit-member-accessibility] private fields cannot have accessibility modifiers

- packages/ast-spec/src/base/BinaryExpressionBase.ts
- packages/ast-spec/src/expression/AssignmentExpression/spec.ts
- packages/ast-spec/src/expression/BinaryExpression/spec.ts
- packages/ast-spec/src/expression/LogicalExpression/spec.ts
- packages/eslint-plugin/src/rules/no-base-to-string.ts
- packages/eslint-plugin/src/rules/no-confusing-non-null-assertion.ts
- packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
- packages/eslint-plugin/src/rules/prefer-for-of.ts
- packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
- packages/eslint-plugin/src/rules/restrict-plus-operands.ts
- packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
- packages/shared-fixtures/fixtures/typescript/basics/private-fields-in-in.src.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
- packages/typescript-estree/tests/snapshots/typescript/basics/private-fields-in-in.src.ts.shot
Adds support for `#bar in foo` syntax.(updating types and adding tests)
Based on #4073
> feat(typescript-estree): support private fields in-in syntax

- packages/experimental-utils/src/ts-eslint/Rule.ts
-   [x] Addresses an existing issue: fixes #4134
Allow `TOptions` to default to `[]` so there's less overhead in setting up rules. Related to https://github.com/typescript-eslint/typescript-eslint/pull/4124.
> feat(experimental-utils): add default [] for RuleModule TOptions generic

- packages/eslint-plugin/tests/docs.test.ts
- packages/experimental-utils/src/eslint-utils/RuleCreator.ts
- packages/experimental-utils/src/ts-eslint/Rule.ts
-   [x] Addresses an existing issue: fixes #4133
Allows this:
```ts
import { ESLintUtils } from '@typescript-eslint/experimental-utils';
const myRule = ESLintUtils.RuleCreator.withoutDocs({
create(context) {
// ...
},
meta: {
// ...
},
});
```
I'm not 100% attached to this particular API. I chose it because it forces people to import `RuleCreator` anyway and has a _"you're not documenting this"_ name.
Adds a bit of JSDoc around the two functions to help make them clear in IDEs.
> feat: add RuleCreator.withoutDocs

- packages/eslint-plugin/src/rules/no-restricted-imports.ts
- packages/eslint-plugin/src/util/collectUnusedVariables.ts
- packages/eslint-plugin/src/util/isTypeReadonly.ts
- packages/scope-manager/src/referencer/PatternVisitor.ts
-   [ ] Addresses an existing issue: fixes 
Ensure that we are not doing circular imports in code-base, this change has been extracted from #4108
> fix: correct issues with circular imports

- packages/eslint-plugin/src/rules/require-await.ts
- packages/eslint-plugin/tests/rules/require-await.test.ts
-   [x] Addresses an existing issue: fixes #3507
The previous implementation specifically only checked for the `AsyncGenerator` type, however any type that has a `[Symbol.asyncIterator]` property is closer to what actually happens at runtime. This change checks for the existance of `[Symbol.asyncIterator]` on any of the types (union or intersection types are checked) and declares await as being called if one exists.
This also fixes a small related issue where `yield* <some literal>` would cause any …
> fix(eslint-plugin): [require-await] treat yield* asynciterable as an await

- package.json
- packages/typescript-estree/tests/ast-alignment/utils.ts
- yarn.lock
Sorry for creating PR without creating issue...
https://github.com/babel/babel/pull/13957 has been merged to babel/parser. So we can remove workaround for Import Assertions AST alignment tests.
> test(typescript-estree): remove workaround for import assertions

- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/tests/rules/member-ordering-alphabetically-order.test.ts
Updated the sorting algorithm to consider the raw string values of identifiers.
> fix(eslint-plugin): [member-ordering] order literal names correctly in

- packages/experimental-utils/src/ast-utils/eslint-utils/ReferenceTracker.ts
- packages/experimental-utils/src/ast-utils/eslint-utils/astUtilities.ts
-   [x] Addresses an existing issue: fixes #4159
Fixed typings for `ReferenceTracker`, `getFunctionNameWithKind` and `getPropertyName`, re-exported from `eslint-utils`.
> fix(experimental-utils): fix types for eslint-utils

- packages/visitor-keys/src/visitor-keys.ts
-   [x] Addresses an existing issue: fixes #4177
Add the missing key. This allows the rules to traverse the ImportAttribute.
> fix(visitor-keys): add missing import assertion keys

- package.json
- yarn.lock
Updates `typescript` to 4.5.2 (not RC)
> chore: update to typescript 4.5

- packages/experimental-utils/src/eslint-utils/RuleCreator.ts
-   [x] Addresses an existing issue: fixes #4198
Also exports the types used by `RuleCreator`.
> fix(experimental-utils): export RuleCreator interfaces

- packages/eslint-plugin/src/rules/no-duplicate-imports.ts
Since v5.x, `source` of `ExportNamedDeclaration`, `ExportAllDeclaration` and `ImportDeclaration` is always `StringLiteral`.
> fix(eslint-plugin): [no-duplicate-imports] remove unnecessary type checking for `node.source`

- packages/website/docusaurus.config.js
- packages/website/package.json
- packages/website/src/pages/index.tsx
- yarn.lock
-   [x] Addresses an existing issue: fixes #4165
Follows https://docusaurus.io/docs/search#using-algolia-docsearch to get Algolia search on the site. 🔍 
~In my usage this doesn't change the website right now -no header search bar or `/search` page-, so keeping in draft... I don't know why it's not showing locally. The steps in https://github.com/facebook/docusaurus/issues/4975, run in both the repo root and the `packages/website` directory aren't fixing it, and I don't see any obvious typos or missing …
> docs: added Algolia search to website

- packages/eslint-plugin/src/rules/ban-types.ts
- packages/eslint-plugin/tests/rules/ban-types.test.ts
-   [x] Addresses an existing issue: fixes #4220
While comparing types exclude all white-spaces
> fix(eslint-plugin): ignore all whitespaces in comparison

- packages/eslint-plugin/src/rules/no-var-requires.ts
- packages/eslint-plugin/tests/rules/no-var-requires.test.ts
-   [x] Addresses an existing issue: fixes #4035 
Used [this](https://github.com/typescript-eslint/typescript-eslint/issues/3713) as a reference. Pretty much the same solution if I am not mistaken.
> fix(eslint-plugin): [no-var-requires] do not report require created from createRequire

- docs/development/CUSTOM_RULES.md
Correct the example in the type checking section. The type that `checker.getTypeAtLocation` accepts is a TS Node not a ES Node.
> docs(website): fix `node` to `originalNode` in type checking example

- packages/eslint-plugin/docs/rules/no-implicit-any-catch.md
-   [ ] Addresses an existing issue
https://github.com/microsoft/TypeScript/pull/41013 added `useUnknownInCatchVariables` which implies `unknown` instead of `any`, meaning this rule is actually wrong when when that's enabled (because it's no longer "implicit any catch")
> docs(eslint-plugin): Mention `useUnknownInCatchVariables` in `no-implicit-any-catch`

- docs/linting/MONOREPO.md
-   [X] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken
Use tsconfig.eslint.json instead of .eslint.js in the code snippet at /docs/linting/monorepo
The paragraph mentions a `tsconfig.eslint.json` file but the example is a javascript snippet named `.eslintrc.js`
> docs(website): fix tsconfig.eslint.json instead of .eslintrc.js in code snippet

- packages/typescript-estree/src/ts-estree/ts-nodes.ts
-   [x] Addresses an existing issue: fixes #4164
I tested with typesript `4.4` variations and got another error so I added `AssertClause` aside from mentioned issue's `AssertEntry`(Maybe I did it with wrong local setting?)
> fix(typescript-estree): type-only regression for consumers not yet on TS 4.5

- packages/eslint-plugin/ROADMAP.md
This PR adds mapping for several security rules from [tslint-microsoft-contrib](https://github.com/microsoft/tslint-microsoft-contrib) to [@microsoft/eslint-plugin-sdl](https://github.com/microsoft/eslint-plugin-sdl/tree/main/lib), plus few minor clean-ups. Might be helpful for someone who still did not migrate over from TSLint.
> docs: updates to security rules in ROADMAP.md

- .github/workflows/ci.yml
https://github.com/codecov/codecov-action#%EF%B8%8F--deprecration-of-v1
> On February 1, 2022, this version will be fully sunset and no longer function
>
> Due to the deprecation of the underlying bash uploader, the Codecov GitHub Action has released v2 which will use the new uploader. You can learn more about our deprecation plan and the new uploader on our blog.
>
> We will be restricting any updates to the v1 Action to security updates and hotfixes.
This PR also fixes coverage report sent to codecov, we should not submit again coverage for all packages
https://app.codecov.io/gh/typescript-eslint/typescript-eslint/compare/4278/tree/packages
new: 
old:
> chore: update codecov/codecov-action to v2

- packages/website/package.json
- packages/website/src/components/OptionsSelector.tsx
- packages/website/src/components/config/ConfigEslint.tsx
- packages/website/src/components/config/ConfigTypeScript.tsx
- packages/website/src/components/hooks/useHashState.ts
- packages/website/src/components/lib/shallowEqual.ts
- packages/website/src/components/modals/Modal.module.css
- packages/website/src/components/modals/Modal.tsx
Playground config editor should now not trigger config update every time when you open/close it
few accessibility issues in modal has been fixed
> docs(website): optimize playground config editor

- packages/website/docusaurus.config.js
Add links to footer, 
as for UI, I'm not sure if we should wait for https://github.com/facebook/docusaurus/issues/6101 or just swizzle this component for now
> docs(website): add community links to footer

- packages/eslint-plugin/src/rules/no-implied-eval.ts
- yarn.lock
-   [x] Addresses an existing issue: fixes #4286
Shifts the acquisition of type information in `no-implied-eval` down into the `calleeName === FUNCTION_CONSTRUCTOR` block because
- That's the only place that it is consumed
- Most nodes *won't* be function constructors (or zero will be if you're using `no-new-func` in the base eslint ruleset)
My team has been running this change (as a forked rule in our custom rules package) for a few days in CI on our fairly-large application and it's shaved ~25% off of …
> fix(eslint-plugin): [no-implied-eval] improve performance

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation-request.md
- .github/ISSUE_TEMPLATE/eslint-plugin-tslint.md
- .github/ISSUE_TEMPLATE/eslint-plugin-typescript.md
- .github/ISSUE_TEMPLATE/typescript-eslint-parser.md
- .github/ISSUE_TEMPLATE/typescript-eslint-scope-manager.md
- .github/ISSUE_TEMPLATE/typescript-eslint-utils.md
- .github/ISSUE_TEMPLATE/typescript-estree.md
- packages/eslint-plugin/README.md
- packages/parser/README.md
- packages/scope-manager/README.md
- packages/typescript-estree/README.md
-   [x] Addresses an existing issue: fixes #4316
Update links to correctly point into `troubleshooting` and `getting started` pages
> docs: update links to point to correct pages

- packages/website/docusaurus.config.js
- packages/website/src/components/ast/ASTViewer.module.css
- packages/website/src/css/custom.css
- packages/website/src/css/prism.css
This PR aligns colors used in various code blocks on website, as for palette I used colors use theme in playground
this change fixes blinking of code blocks in dark mode.
----------------------
dark mode code blocks do look different now:
new:
> docs: align colors of code block

- packages/eslint-plugin/docs/rules/no-throw-literal.md
- packages/eslint-plugin/src/rules/no-throw-literal.ts
- packages/eslint-plugin/tests/rules/no-throw-literal.test.ts
-   [x] Addresses an existing issue: fixes https://github.com/typescript-eslint/typescript-eslint/issues/4206
This PR adds the following options to `@typescript-eslint/no-throw-literal`:
```jsonc
{
"allowThrowingAny": true, // Default is to allow throwing values of type any
"allowThrowingUnknown": true // Default is to allow throwing values of type unknown
}
```
When enabled, these rules result in an error being generated from code such as:
```typescript
function fun(value: any) {
throw value;
} …
```
> feat(eslint-plugin): [no-throw-literal] add options to to disallow `any`/`unknown`

- packages/eslint-plugin/docs/rules/no-unsafe-argument.md
Just a minor typo fix to avoid confusion in terms of what the rule is doing.
> docs(eslint-plugin): fix typo in example codeFix typo in example code

- packages/eslint-plugin/src/rules/consistent-type-definitions.ts
- packages/eslint-plugin/tests/rules/consistent-type-definitions.test.ts
-   [x] Addresses an existing issue: fixes #4333
Fixer incorrectly changes declare keyword to interface
> fix(eslint-plugin): [consistent-type-definitions] correct fixer with declare keyword

- packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
- packages/eslint-plugin/tests/rules/consistent-indexed-object-style.test.ts
-   [x] Addresses an existing issue: fixes #2687
cc EvgenyOrekhov/eslint-config-hardcore#356
> fix(eslint-plugin): [consistent-indexed-object-style] do not report for circular references

- packages/eslint-plugin/src/rules/padding-line-between-statements.ts
- packages/eslint-plugin/tests/rules/padding-line-between-statements.test.ts
-   [x] Addresses an existing issue: fixes #4030
normal function overloading was not processed at all because `TSDeclareFunction` was not called at all. Cases such as below should have made error that there is a blank space expected
```
options: [{ blankLine: 'always', prev: '*', next: 'block-like' }],
function bar(arg: number): number;
function bar(arg: string | number) {
return arg;
}
```
1. make `TSDeclareFunction` is also processed.
2. I added test case for already working export function …
> fix(eslint-plugin): [padding-line-between-statements] make function overloading is also processed

- packages/eslint-plugin/src/util/createRule.ts
- packages/eslint-plugin/tests/docs.test.ts
-   [x] Addresses an existing issue: fixes #4368
Changes the link in most rules' `createRule` usage to point to the general website instead of version-specific GitHub markdown files.
> docs(eslint-plugin): change createRule usage to point to website

- docs/linting/TROUBLESHOOTING.md
-   [x] Addresses an existing issue: fixes #4102
Mentions the high-level version conflicts and links to the deeper technical explanation.
> docs: explain why there is not a "typescriptLocation" option

- docs/development/architecture/ASTS.md
- docs/development/architecture/PACKAGES.md
- docs/linting/TROUBLESHOOTING.md
-   [x] Addresses an existing issue: fixes #4353
Mentions the playground's AST option and changes links to surface with it enabled.
> docs: replace astexplorer.net links with playground

- packages/eslint-plugin/docs/rules/no-useless-constructor.md
-   [x] Addresses an existing issue: fixes #3820
Adds a `## Caveat` heading in the rule docs file.
> docs(eslint-plugin): mention constructor privacy limitation on no-useless-constructor

- docs/linting/TYPED_LINTING.md
-   [x] Addresses an existing issue: fixes #4087
See #4087
> docs: add examples of overrides without type information

- packages/eslint-plugin/project.json
- packages/types/tools/copy-ast-spec.ts
- packages/typescript-estree/project.json
-   [x] Addresses an existing issue: fixes #4335
Adds `"@typescript-eslint/types"` under `implicitDependencies` for the `eslint-plugin` package so that `npx nx build website` knows to build types and therefore copy `ast-spec.ts`.
Also adds a `console.error` in case the `copy-ast-spec` code throws for whatever reason.
> chore: added missing implicit dependency on types to eslint-plugin

- packages/eslint-plugin/docs/rules/no-restricted-imports.md
A simple doc change as the current config incorrectly turned the rule `off` instead of `error`.
> Fixes incorrect "How to Use" for `no-restricted-imports` rule.

- packages/type-utils/src/isTypeReadonly.ts
-   [x] Addresses an existing issue: fixes #4410
Use the default options as the default param.
> feat(type-utils): make isTypeReadonly's options param optional

- packages/type-utils/src/isTypeReadonly.ts
- packages/type-utils/tests/isTypeReadonly.test.ts
-   [ ] Addresses an existing issue
Add basic tests for `isTypeReadonly`.
Note: this PR is the base of #4417, #4419,#4421 and  #4429
> test(type-utils): add basic tests for isTypeReadonly

- package.json
- packages/eslint-plugin/src/rules/no-extra-semi.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
- yarn.lock
This PR modifies to call the changed method name of the `no-extra-semi` core rule.
This issue was found while working on #4448.
https://github.com/typescript-eslint/typescript-eslint/pull/4448#issuecomment-1014222118
> fix(eslint-plugin): [no-extra-semi] false negatives when used with eslint 8.3.0

- docs/development/CUSTOM_RULES.md
I think the PR title and content is self-explanatory
> docs: Add missing comma in CUSTOM_RULES.md

- packages/eslint-plugin/src/rules/no-restricted-imports.ts
- packages/eslint-plugin/tests/rules/no-restricted-imports.test.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
-   [x] Addresses an existing issue: fixes #4491 
This is in line with how the ESLint base rule is configured:
https://github.com/eslint/eslint/blob/b6f2bd8879176cd774f253ba437963f2fa1c493d/lib/rules/no-restricted-imports.js#L163
I'm surprised that we never had the `caseSensitive` option in our typedef, so I added that as well.
> fix(eslint-plugin): [no-restricted-imports] allow relative type imports with patterns configured

- packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts
- packages/eslint-plugin/tests/fixtures/tsconfig.noUncheckedIndexedAccess.json
- packages/eslint-plugin/tests/rules/non-nullable-type-assertion-style.test.ts
-   [x] Addresses an existing issue: fixes #4512
Consider the following code:
```typescript
function first<T>(array: ArrayLike<T>): T | null {
return array.length > 0 ? (array[0] as T) : null;
}
```
When compiling with `noUncheckedIndexedAccess`, the type assertion `array[0] as T` is required because the original type of `array[0]` is `T | undefined`.
However, non-nullable-type-assertion-style complains about the cast, suggesting that it should be `array[0]!` instead. This is not correct because the …
> fix(eslint-plugin): [non-nullable-type-assertion-style] fix false positive when asserting to a generic type that might be nullish

- packages/eslint-plugin/src/rules/no-magic-numbers.ts
-   [x] Addresses an existing issue: fixes #4515
`baseRule.meta.schema` is an array of object
As a result, it merges in this:
According to the approach from `no-empty-function` rule, we use `Array.isArray` and return the first element, otherwise the object
> fix(eslint-plugin): [no-magic-numbers] fix invalid schema merging

- packages/website/docusaurus.config.js
- packages/website/sidebars/sidebar.rules.js
- packages/website/src/components/FinancialContributors.module.css
-   ~~[ ] Addresses an existing issue: fixes #000~~
-   ~~[ ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)~~
1. This PR excludes TEMPLATE from the build entirely. Before it was listed in the sidebar's "deprecated" section which is definitely not correct; I think it doesn't make sense to put it anywhere in the website, so just removed it.
2. This PR removes a Webpack module warning:
```
ModuleWarning [Warning: Warning
(9:3) autoprefixer: end value has mixed support, consider using flex-end instead] undefined
[WARNING] …
```
> docs: remove TEMPLATE from website; fix CSS autoprefixer warning

- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
-   [x] Addresses an existing issue: fixes #4463
Now, it also covers the case with property definition
> feat(eslint-plugin): [explicit-module-boundary-types] add checking property definition on `allowedNames` option

- packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
-   [x] Addresses an existing issue: fixes #4489
Instead of using text to check if the type is the same, it is now checked by symbol.
If there is no symbol, it is checked by typeFlag.
Typescript doesn't provide an api for handling type relationships, does it?
> fix(eslint-plugin): [no-unnecessary-type-arguments] Use Symbol to check for the same type

- packages/eslint-plugin/src/rules/typedef.ts
- packages/eslint-plugin/tests/rules/typedef.test.ts
-   [x] Addresses an existing issue: fixes #4505
It finds if top level has object has type annotation
> fix(eslint-plugin): [typedef] support nested object destructuring with type annotation

- packages/eslint-plugin/src/rules/init-declarations.ts
- packages/eslint-plugin/tests/rules/init-declarations.test.ts
-   [x] Addresses an existing issue: fixes #4392
It doesn't error when the ancestor namespace is declared(`declare namespace myLib { }`)
> fix(eslint-plugin): [init-declarations] fix nested namespace

- .github/workflows/update-sponsors.yml
-   [x] Addresses an existing issue: fixes #4370
Turns out `schedule` (cron) in GHA doesn't support specifying the branch. https://github.com/typescript-eslint/typescript-eslint/actions/runs/1834719537
```
Error: .github#L1
Invalid type for `on`
```
Per https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule the commit SHA will be the last commit on the default branch.
> chore: remove unsupported branch argument from update-sponsors

- packages/eslint-plugin/docs/rules/member-ordering.md
Corrected member-ordering options type on the readme.
> docs(eslint-plugin): [member-ordering] correct options type

- packages/parser/README.md
-   [ ] Addresses an existing issue: fixes #000 (NO ISSUE DUE TO SIZE)
The documentation is missing a `"` and I'm trying to fix it.
Happy to file an issue if you think it's worth it, but didn't want to add more noise.
> docs: add a missing "

- packages/utils/src/ast-utils/index.ts
Currently we're using a copy of [`isNodeOfType`](https://github.com/typescript-eslint/typescript-eslint/blob/a2bd04865527cc9b172895caf380757fb214d4fb/packages/utils/src/ast-utils/helpers.ts#L6-L11) in `eslint-plugin-testing-library`.
https://github.com/testing-library/eslint-plugin-testing-library/blob/main/lib/node-utils/is-node-of-type.ts#L6-L11
As the extraction in this codebase was originally copied from `eslint-plugin-testing-library` (see #3677 & testing-library/eslint-plugin-testing-library#329), it seems logical to expose it here so other packages can use it whenever they want.
> feat(utils): expose `ast-utils`' helpers

- packages/utils/src/ast-utils/helpers.ts
- packages/utils/src/ast-utils/predicates.ts
This is the negative version of what I did in #3977
> feat(utils): extract `isNotTokenOfTypeWithConditions` out of `ast-utils`' `predicates`

- packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
- packages/eslint-plugin/tests/rules/sort-type-union-intersection-members.test.ts
-   [x] Addresses an existing issue: fixes #4581
The constructorType is now also enclosed in parentheses.
> fix(eslint-plugin): [sort-type-union-intersection-members] Wrap the constructorType in parentheses

- packages/eslint-plugin/src/rules/no-misused-promises.ts
- packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
-   [x] Addresses an existing issue: fixes #4609
Previously the rule checked for any function overload signature that had a `void`-returning function for each parameter. Those parameters were then considered unsafe for thenable-returning functions.
In an ideal world we would use the type checker's `getResolvedSignature` API to grab the specific type signature used for the call instead. However, TypeScript selects the first matching signature, causing it to select one with the `() => void`  parameter …
> fix(eslint-plugin): [no-misused-promises] factor thenable returning function overload signatures

- docs/linting/README.md
I found this in the documentation of ESLint (https://eslint.org/docs/user-guide/configuring/ignoring-code):
```
In addition to any patterns in the .eslintignore file, ESLint always follows a couple of implicit ignore rules even if the --no-ignore flag is passed. The implicit rules are as follows:
- node_modules/ is ignored.
- dot-files (except for .eslintrc.*), as well as dot-folders and their contents, are ignored.
```
Maybe it's confusing to the person reading the documentation?
I couldn't find an issue for this change, sorry.
> docs: remove node_modules from .eslintignore

- .eslintrc.js
-   [x] Addresses an existing issue: fixes #3278
I tried enabling it but there are a ton of AST-specific names such as `TSQuery` that don't match with it. We've lived this long without it and have a pretty informed maintainer team. 🤷
> chore: remove naming convention todo from eslintrc

- packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
- packages/parser/README.md
- packages/parser/src/parser.ts
- packages/types/src/parser-options.ts
-   [x] Addresses an existing issue: fixes #4608
`emitDecoratorMetadata` is added to `ParserOptions` as an optional param
The parser first try to use `compilerOptions.emitDecoratorMetadata` as it did before.
If `parserOptions.project` is set, then `parserOptions.emitDecoratorMetadata` is used.
> feat(parser): add `parserOptions.emitDecoratorMetadata`

- packages/eslint-plugin/docs/rules/README.md
Docs/Linting/Linting didn't exist. However there was a regular page called linting.
-   [X] Addresses an existing issue: fixes #4593
-   [X] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [X] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken
In Rules > Overview, in the first bullet point, "See [Linting](https://typescript-eslint.io/docs/linting/linting) for more details" has an incorrect link. This leads to a "Page Not Found" error.
I had changed the link from "https://typescript-eslint.io/docs/linting/linting" to "https://typescript-eslint.io/docs/linting" in order to fix the error.
> docs(eslint-plugin) : Fix broken link in the readme

- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/typescript-estree/src/convert-comments.ts
- packages/typescript-estree/src/create-program/shared.ts
- packages/website-eslint/src/mock/path.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> chore: replace deprecated String.prototype.substr()

- packages/scope-manager/src/referencer/Referencer.ts
- packages/scope-manager/tests/fixtures/jsx/this-jsxidentifier.tsx
- packages/scope-manager/tests/fixtures/jsx/this-jsxidentifier.tsx.shot
-   [x] Addresses an existing issue: fixes #4055
Currently when a JSX Identifier has name="this" is treated like a variable. This PR will ignore the JSXIdentifier when its name is "this" and thus not referencing it
> fix(scope-manager): incorrect reference for this within a jsx identifier

- packages/utils/src/eslint-utils/RuleTester.ts
When using RuleTester outside of a test runner,  if fails to instantiate due to `ReferenceError: afterAll is not defined`.
This PR make it possible to use TS ESLint RuleTester in simple node scripts.
> fix(utils): RuleTester: Only call afterAll if defined

- packages/eslint-plugin/src/rules/consistent-type-assertions.ts
- packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
-   [x] Addresses an existing issue: fixes #4684
- Enables the consistent-type-assertions rule enforces the assertionStyle (`as` and `angle-bracket`) for `const` too
> fix(eslint-plugin): [consistent-type-assertions] enforce assertionStyle for `const` assertions

- .github/dependabot.yml
- packages/website/package.json
- yarn.lock
Reverts typescript-eslint/typescript-eslint#4710. 😢 
@bradzacher I was so hopeful about it too..
> fix: revert "chore: Bump cypress from 8.3.0 to 9.5.2", and ignore cypress for now

- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
-   [x] Addresses an existing issue: fixes #4691
implmented `destructuredArrayIgnorePattern` options just like base rule added. (https://github.com/eslint/eslint/pull/15649)
Also applied this fix(https://github.com/eslint/eslint/commit/c4d8b0db62b859e721105d4bc0f4044ce346995e).
This fix is needed for the new test case using `destructuredArrayIgnorePattern` and `ignoreRestSiblings` options. This test case is from base rule. 
It causes error without this fix.
> feat(eslint-plugin): [no-unused-vars] add destructuredArrayIgnorePattern options

- packages/website/data/sponsors.json
- packages/website/src/components/Playground.module.css
Code container is hiding side navigation menu in a smaller window. The issue is due same z-index values for both code container and navigation menu. Now code container is pushed down by lowering the z-index value.
No issue template for creating issues for the website. So directly raising PR without opening an issue.
> fix: code container hiding navigation menu

- packages/eslint-plugin/src/rules/no-this-alias.ts
- packages/eslint-plugin/tests/rules/no-this-alias.test.ts
-   [x] Addresses an existing issue: fixes #4690 
The rule 'no-this-alias' had no logic of how to manage a reassignment of a variable already declared, it was only working in a variable declaration. This code adds an AssignmentExpression node to be handled and grabs the id of the Identifier of either AssigmentExpression or  VariableDeclarator.
> feat(eslint-plugin): [no-this-alias] report on assignment expressions

- packages/website/src/components/editor/LoadedEditor.tsx
Fix issue reported in https://github.com/typescript-eslint/typescript-eslint/pull/4765#issuecomment-1085051925
> https://typescript-eslint.io/play/#ts=4.6.2&sourceType=module&code=CYUwxgNghgTiAEAzArgOzAFwJYHtXwDcctgB5GABRhwFssBnEAClgHMAueJpgSngF4AfIWLA+AHy68BwqrQYgAPERKCePTiuABuIA&rules=N4XyA&tsConfig=N4XyA
> 
> ```
> Cannot find name 'Promise'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.(2583)
> ```
- [Test 1](https://deploy-preview-4770--typescript-eslint.netlify.app/play/#ts=4.6.2&sourceType=module&code=PQKgsAUApgzgNgSwHYBdIAJPoEQAEUCeADrAMYBOCRKAtLIqsEgPY0BmczAhisgOY0i5ZgFsEMWNgBc6ANoByKOWHl5AXQA0GLHkIkYFKrXrIUTVmJgBXCQBNBwy5JkKlK9VohYc+YmUrUdPCm5jRWSDZQ9gBuXOQw0nKKysyqapAgwJCQSFAA7ugACo7iUAAUZQCU6AC8AHzoAN7oAL6VANzowMDogDLk6C …
> fix(website): do not update lib target on every config change

- packages/website/src/css/custom.css
i noticed that dark mode colors are not workign correctly after changes done in #4362
`html:root` has higher priority than `html[data-theme='dark']` and it looks that dark mode overrides are no longer working correctly
and this should be 
-----------
before fix:
after fix:
> fix(website): correct dark mode color regression

- packages/eslint-plugin/src/rules/method-signature-style.ts
- packages/eslint-plugin/tests/rules/method-signature-style.test.ts
-   [x] Addresses an existing issue: fixes #4762
Added a check to verify that the `TSMethodSignature` node is not a getter or setter by using the `kind` property.
> fix(eslint-plugin): method-signature-style respect getter signature

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
-   [x] Addresses an existing issue: fixes #4723
Use location data from estree instead of typescript, this change fixes fixer when,
This issue is present in any parser that modifies location data of estree nodes, eg. mdx, vue
> fix(eslint-plugin): update code to use estree range instead of ts pos/end 

- .github/pull_request_template.md
-   [x] Addresses an existing issue: fixes #4010
I am again clarifying the PR template.
> docs: clarify PR template to refer to an open issue

- packages/eslint-plugin/src/rules/restrict-plus-operands.ts
- packages/eslint-plugin/tests/rules/restrict-plus-operands.test.ts
-   [x] Addresses an existing issue: extends #2506
This PR extends the functionality of #2628 to also support number intersections and bigint intersections. A real-world use case for this functionality would be the new reactivityTransfrom Vue macros: https://github.com/vuejs/eslint-plugin-vue/issues/1839
(also the code was mainly copied from PR #2628 and tweaked for numbers and bigints)
> feat(eslint-plugin): add support for valid number and bigint intersections in restrict-plus-operands rule

- packages/website-eslint/package.json
- packages/website-eslint/src/linter/linter.js
- packages/website-eslint/types/index.d.ts
- packages/website/src/components/editor/LoadedEditor.tsx
- packages/website/src/components/editor/lintCode.ts
- packages/website/src/components/editor/useSandboxServices.ts
- packages/website/src/components/types.ts
- packages/website/src/vendor/ds/createDesignSystem.d.ts
- packages/website/src/vendor/playground.d.ts
- packages/website/src/vendor/sandbox.d.ts
- packages/website/src/vendor/tsWorker.d.ts
- packages/website/src/vendor/typescript-vfs.d.ts
- tools/generate-website-dts.ts
- yarn.lock
-   [x] Addresses an existing issue: fixes #4767
Use current typescript options for eslint processing
> docs(website): propagate typescript options to eslint

- packages/eslint-plugin/docs/rules/parameter-properties.md
-   [x] Addresses an existing open issue: fixes #4878
I got this error when I first try this new rule by following the example on the document:
```
Configuration for rule "@typescript-eslint/parameter-properties" is invalid:
Value "parameter-properties" should be equal to one of the allowed values.
```
and here is my config:
```
"@typescript-eslint/parameter-properties": [
"error",
{
"prefer": "parameter-properties"
}
]
```
I checked the [source …
> docs(eslint-plugin): improve docs [parameter-properties]

- packages/ast-spec/tests/PunctuatorTokenToText.type-test.ts
- packages/ast-spec/tests/ast-node-types.type-test.ts
- tsconfig.base.json
-   [x] Addresses an existing open issue: fixes #4871
As the issue suggests, has us use the ESLint rule only.
> chore: removed noUnused(Locals|Parameters) from tsconfig.base.json

- packages/ast-spec/src/expression/AwaitExpression/spec.ts
- packages/ast-spec/src/unions/LeftHandSideExpression.ts
-   [x] Addresses an existing open issue: fixes #4877
ImportExpression is added to [LeftHandSideExpression](https://github.com/typescript-eslint/typescript-eslint/blob/f79ae9b58e82f4fddef640a34a1d7ff92b763e65/packages/ast-spec/src/unions/LeftHandSideExpression.ts#L23).
> fix(ast-spec): correct `AwaitExpression.argument` type

- packages/eslint-plugin/src/rules/no-restricted-imports.ts
- packages/eslint-plugin/tests/rules/no-restricted-imports.test.ts
-   [x] Addresses an existing open issue: fixes #4895 
- No... but it clearly is a bug, so I'm pre-emptively sending the PR :D
The problem with our current logic is that we require _every_ allowed import pattern to match a given path, but in practice, they can well be disjoint! With this change, we will be more permissive and allow type import as long as _one_ matcher matches.
This may lead to some false-negatives? For example, there are two matchers that both match a file, one with `allowTypeImports`, …
> fix(eslint-plugin): [no-restricted-imports] allow type import as long as there's one matching pattern

- packages/utils/src/ts-eslint/ESLint.ts
- packages/utils/src/ts-eslint/Rule.ts
- packages/utils/src/ts-eslint/RuleTester.ts
- packages/utils/src/ts-eslint/SourceCode.ts
This just updates eslint types to be in sync with the last few versions.
I just went through the [history on the nodejs api docs file](https://github.com/eslint/eslint/commits/f2c2d350425268efa4b78ee6e0a2df8860e0efad/docs/developer-guide/nodejs-api.md) and compared the commits to what we have.
> feat(utils): update eslint types

- packages/eslint-plugin/docs/rules/no-type-alias.md
-   [] Addresses an existing open issue: fixes #000
-   [] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
-   [] Steps in [CONTRIBUTING.md](https://github.com/typescript-eslint/typescript-eslint/blob/main/CONTRIBUTING.md) were taken
There was obviously no issue for this, but caught my eye. I assume that the correct form is "Advanced Types" instead of "Advance Types".
No change in code, only docs.
(And btw, big thanks for this comprehensive documentation)
> docs: fix typo in link

- .github/workflows/ci.yml
our integration tests started failing because one of the packages bumped its engine reqs.
let's jump to the top-end of our current range to future proof us for a while
> chore: bump primary node version for CI

- packages/eslint-plugin/src/rules/array-type.ts
- packages/eslint-plugin/tests/rules/array-type.test.ts
-   [x] Addresses an existing open issue: fixes #4756
add missing parens to fixer of rule `array-type` for `TSConstructorType` nodes
> fix(eslint-plugin): [array-type] in fixer add missing parens for constructor types #4756

- packages/eslint-plugin/docs/rules/ban-types.md
- packages/eslint-plugin/src/rules/ban-types.ts
-   [x] ~Addresses an existing open issue: fixes #000~ No issues have been created about this feature
-   [x] ~That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)~ No issues have been created about this feature
The pull request title says it all: to add `BigInt` type to the default list of banned types, given that `bigint` is a primitive type (just like `boolean`, `string`, `number`, and `symbol`).
The `ban-types` rule source code and the rule documentation have been changed.
> feat(eslint-plugin): Add BigInt object type to default ban-types list

- docs/linting/CONFIGS.md
> fix(website): missing colon before tip notes in configs.md

- packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md
This only fixes the typo error `acceceptsCallback` => `acceptsCallback` in prefer-readonly-parameter-types
> docs(eslint-plugin): fix typo in prefer-readonly-parameter-types

- packages/shared-fixtures/fixtures/typescript/types/conditional-infer-with-constraint.src.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
- packages/typescript-estree/tests/snapshots/typescript/types/conditional-infer-with-constraint.src.ts.shot
-   [x] Addresses an existing open issue: ref #4829 
Based on #4829
According to TS Compiler AST, add the `constraints` field to the `TSTypeParameter`, not the `TSInferType`. so This PR just adds tests( a87ec29081b0a8f4581ff39bcea66be155d49f89 ).
> feat(typescript-estree): `extends` constraints for `infer`

- .github/actions/prepare-install/action.yml
- .github/workflows/ci.yml
Correct issue with credentials not being setup in `publish_canary_version` action after changes to #4959
> Please note that you need to set the `registry-url` to `https://registry.npmjs.org/` in setup-node to properly configure your credentials.
https://github.com/actions/setup-node/blob/bacd6b4b3ac3127b28a1e1920c23bf1c2cadbb85/src/main.ts#L42-L46
```ts
const registryUrl: string = core.getInput('registry-url');
const alwaysAuth: string = core.getInput('always-auth');
if (registryUrl) {
auth.configAuthentication(registryUrl, alwaysAuth);
}
```
https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
> chore: allow publishing canary versions

- packages/ast-spec/src/expression/ArrayExpression/spec.ts
-   [x] Addresses an existing open issue: fixes #4963
> fix(ast-spec): add `SpreadElement` to `ArrayExpression.elements`

- packages/eslint-plugin/src/rules/member-delimiter-style.ts
- packages/eslint-plugin/tests/rules/member-delimiter-style.test.ts
-   [x] Addresses an existing open issue: fixes #5028
> fix(eslint-plugin): [member-delimiter-style] autofixer result is not as expected when comments after the delimiter with option `delimiter: 'none'`

- packages/eslint-plugin/docs/rules/triple-slash-reference.md
The [`triple-slash-reference` docs](https://typescript-eslint.io/rules/triple-slash-reference/) were missing the options schema and defaults, so I added that section from the [template](https://github.com/typescript-eslint/typescript-eslint/blob/1f60fae2a1fe06b886da92e4a3bb5ecc7df230bb/packages/eslint-plugin/docs/rules/TEMPLATE.md) based on the implementation's [schema](https://github.com/typescript-eslint/typescript-eslint/blob/1f60fae2a1fe06b886da92e …
> docs(eslint-plugin): add triple-slash-reference options schema and defaults

- packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
A small fix for https://github.com/typescript-eslint/typescript-eslint/pull/5053, where some tests where using invalid code.
> chore(eslint-plugin): fix invalid code in promise spread tests

- packages/parser/src/parser.ts
- packages/parser/tests/lib/parser.ts
- packages/types/src/parser-options.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
-   [x] Addresses an existing open issue: related to changes done in #3109 and released with 5.0.0
this option is no longer available / working since v5.0.0 release but looks that not all references has been removed for it
> fix(types): remove leftovers from removal of useJSXTextNode

- packages/eslint-plugin/docs/rules/no-type-alias.md
- packages/eslint-plugin/src/rules/no-type-alias.ts
- packages/eslint-plugin/tests/rules/no-type-alias.test.ts
> fix(eslint-plugin): [no-type-alias] handle Template Literal Types

- packages/eslint-plugin/src/rules/space-infix-ops.ts
- packages/eslint-plugin/tests/rules/space-infix-ops.test.ts
-   [x] Addresses an existing open issue: fixes #5109
correct seelcting last node of PropertyDefinition when `typeAnnotation` is present
regression fix for #5041 `/^[=|?|:]$/.test(token.value)`
> fix(eslint-plugin): [space-infix-ops] correct PropertyDefinition with typeAnnotation

- README.md
As per PR #5082, the supported TypeScript version range is updated, but it seems like README is left unchanged, this PR fixes that.
> docs: update supported TS version range

- packages/website/src/components/editor/LoadedEditor.tsx
-   [x] Addresses an existing open issue: fixes #000
This change fixes issues witch switching from and to jsx
----
with code:
```
function x() {
return <div></div>
}
```
before this change if you try to switch to jsx, playground is going to report bunch of issues
[Playground #5128](https://deploy-preview-5128--typescript-eslint.netlify.app/play/#ts=4.7.0-beta&sourceType=module&code=GYVwdgxgLglg9mABADwBQEpEG8CwAoRRAJwFMoQikAeAExgDcA+KgejqfwF98g&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2 …
> chore(website): [playground] create new model with jsx support if needed

- packages/website/src/components/lib/markdown.ts
I was wrong [when I originally told armano to remove these](https://github.com/typescript-eslint/typescript-eslint/pull/4916#discussion_r870862218).
It appears that GH uses the issue form config to power the initial link from the issue chooser, and then completely ignores the config after that 😢 
So without this param, the issue is filled without any tags at all!!!
> chore(website): include labels in the report-an-issue button

- packages/eslint-plugin/src/rules/space-infix-ops.ts
- packages/eslint-plugin/tests/rules/space-infix-ops.test.ts
-   [x] Addresses an existing open issue: fixes #5134 fixes #5133
Additional regression fix for #5041 `/^[=|?|:]$/.test(token.value)`
> fix(eslint-plugin): [space-infix-ops] regression fix for conditional types

- packages/website-eslint/rollup.config.js
Do not mangle class names in playground
this is fixing regression from adding source maps to ease debugging
> chore(website): [playground] correct scope analysis class names

- packages/eslint-plugin/src/rules/space-infix-ops.ts
- packages/eslint-plugin/tests/rules/space-infix-ops.test.ts
-   [x] Addresses an existing open issue: fixes #5137
Additional regression fix for #5041 `/^[=|?|:]$/.test(token.value)`
> fix(eslint-plugin): [space-infix-ops] regression fix for type aliases

- packages/eslint-plugin/src/rules/space-infix-ops.ts
- packages/eslint-plugin/tests/rules/space-infix-ops.test.ts
-   [x] Addresses an existing open issue: fixes #5154
Additional regression fix for #5041 `/^[=|?|:]$/.test(token.value)`
```
class Example {
optional? = false;
}
```
---------------
Optimizations:
- reduce amount of computations needed to find tokens (we can use nodes as they contain proper information's about range)
> fix(eslint-plugin): [space-infix-ops] support for optional property without type

- .prettierignore
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
- packages/scope-manager/src/referencer/TypeVisitor.ts
- packages/scope-manager/tests/fixtures.test.ts
- packages/scope-manager/tests/fixtures/type-declaration/type-query-with-parameters.ts
- packages/scope-manager/tests/fixtures/type-declaration/type-query-with-parameters.ts.shot
- packages/visitor-keys/src/visitor-keys.ts
-   [x] Addresses an existing open issue: fixes #5152
add visiting of `typeParameters` in `TSTypeQuery`
prettier is not supporting this syntax yet
missing changes for #5067
> fix: [TS4.7] allow visiting of typeParameters in TSTypeQuery

- packages/eslint-plugin/docs/rules/prefer-optional-chain.md
Fixes invalid syntax.
```js
> (((foo || {}).a || {}).b {}).c;
(((foo || {}).a || {}).b {}).c;
^
Uncaught SyntaxError: Unexpected token '{'
```
Now has become:
```js
> (((foo || {}).a || {}).b || {}).c;
undefined
```
> chore(eslint-plugin): [prefer-optional-chain] fix incorrect syntax in documentation

- packages/website/src/components/lib/markdown.ts
-   [x] Addresses an existing open issue: fixes #5056
Nice little feature so most well-isolated issue reporters won't have to manually edit the issue name.
> feat(website): open issue with rule name if only one rule is enabled

- .husky/pre-push
- package.json
-   [x] Addresses an existing open issue: fixes #5203
Per the issue, commits still run Prettier on staged->committed files. We just no longer also run Prettier on _all_ files when pushing.
> chore: removed pre-push hook

- packages/eslint-plugin/src/rules/no-base-to-string.ts
-   [x] Addresses an existing open issue: fixes #5268
It's been like this for years. Oops.
> fix(eslint-plugin): [no-base-to-string] add missing apostrophe to message

- packages/eslint-plugin/docs/rules/ban-ts-comment.md
-   [x] Addresses an existing open issue: fixes #5282
Cover-up from #5026
> docs(eslint-plugin): [ban-ts-comment] include descriptionFormat

- packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
- packages/eslint-plugin/tests/rules/consistent-indexed-object-style.test.ts
-   [x] Addresses an existing open issue: fixes #5279 
Instead of just [mapping each typeParameter node to its name](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts#L135), map it to the complete node text to avoid stripping information.
https://typescript-eslint.io/play/#ts=4.7.2&sourceType=module&code=JYOwLgpgTgZghgYwgAgGIHt0B4CCyC8ycIAngHzIDeAUMsgNoDWEJAXMgM5hSgDmAuuxwBuagF8gA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPA …
> fix(eslint-plugin): [consistent-indexed-object-style] fix record mode fixer for generics with a default value

- .prettierignore
- packages/scope-manager/src/referencer/TypeVisitor.ts
- packages/scope-manager/tests/fixtures/type-declaration/infer-type-constraint.ts
- packages/scope-manager/tests/fixtures/type-declaration/infer-type-constraint.ts.shot
-   [x] Addresses an existing open issue: fixes #5330
Add visiting of `constraint` in `infer` type
> fix(scope-manager): allow visiting of constraint in infer type

- packages/eslint-plugin/docs/rules/comma-dangle.md
The "How to Use" section of `comma-dangle` rule was incorrectly titled as "Rule Changes"
> docs(eslint-plugin): [comma-dangle] fix incorrect section heading

- packages/eslint-plugin/src/rules/no-inferrable-types.ts
- packages/eslint-plugin/tests/rules/no-inferrable-types.test.ts
-   [x] Addresses an existing open issue: fixes #5340
(I have a feeling we need more test cases, but I can't think of any edge-cases.)
> fix(eslint-plugin): [no-inferrable] fix optional param to valid code

- packages/eslint-plugin/src/rules/typedef.ts
- packages/eslint-plugin/tests/rules/typedef.test.ts
-   [x] Addresses an existing open issue: fixes #5233 
Update the typedef rule to take into consideration the type annotation of ancestor nodes when destructuring nested arrays.
> fix(eslint-plugin): [typedef] Support nested array destructuring with type annotation

- packages/website/src/components/OptionsSelector.tsx
- packages/website/src/components/editor/useSandboxServices.ts
- packages/website/src/components/inputs/Dropdown.tsx
-   [x] Addresses an existing open issue: fixes #5244
lock typescript version dropdown while playground is loading and add currently loaded ts version to dropdown
> chore(website): add current version of typescript to playground dropdown

- .prettierignore
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
- packages/scope-manager/src/referencer/Referencer.ts
- packages/scope-manager/tests/fixtures/instantiation-expressions/type-arguments1.ts
- packages/scope-manager/tests/fixtures/instantiation-expressions/type-arguments1.ts.shot
- packages/scope-manager/tests/fixtures/instantiation-expressions/type-arguments2.ts
- packages/scope-manager/tests/fixtures/instantiation-expressions/type-arguments2.ts.shot
-   [x] Addresses an existing open issue: fixes #5317
ref: https://github.com/typescript-eslint/typescript-eslint/blob/3d552895af436ef0a983a34a9b708030c9b5ebc7/packages/scope-manager/src/referencer/Referencer.ts#L383-L386
> fix(scope-manager): handle typeParameters of TSInstantiationExpression

- packages/website/plugins/generated-rule-docs.ts
1. Allows interpolating inline code
2. Reliably removes the notice; currently some rules don't have their notice removed, for some reason... (e.g. https://typescript-eslint.io/rules/comma-dangle)
> chore(website): multiple fixes to rule docs generation

- docs/README.md
Removes extraneous closing-paren in "Configuration Values" section of Readme.
> docs: remove extra paren in readme

- packages/eslint-plugin/docs/rules/member-ordering.md
Just a typo – seems like `memberTypes` is missing an `s` in documentation of `member-ordering` rule.
> docs(eslint-plugin): typo in `member-ordering` rule documentation

- packages/eslint-plugin/docs/rules/member-ordering.md
- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/tests/rules/member-ordering-alphabetically-case-insensitive-order.test.ts
- packages/eslint-plugin/tests/rules/member-ordering-alphabetically-order.test.ts
- packages/eslint-plugin/tests/rules/member-ordering.test.ts
-   [x] Addresses an existing open issue: fixes #5404
> feat(eslint-plugin): [member-ordering] support static blocks

- packages/website/sidebars/sidebar.rules.js
-   [x] Addresses an existing open issue: fixes #5400
Moves formatting and deprecated rules to sad little sub-categories at the bottom of the sidebar rules list.
> chore(website): lower formatting rules in sidebar

- packages/website/src/components/RulesTable/index.tsx
- packages/website/src/theme/MDXComponents/RuleAttributes.tsx
The lightbulb 💡 emoji is the convention for denoting rules with emojis used by the official ESLint website as well as in many popular ESLint plugins. Examples (note: I am a maintainer on these plugins and have been working to standardize the lists of rules):
* https://eslint.org/docs/latest/rules/
* https://github.com/sindresorhus/eslint-plugin-unicorn#rules
* https://github.com/ember-cli/eslint-plugin-ember#-rules
* https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin#rules
The previous hammer and wrench 🛠 emoji for suggestable rules is too similar to the wrench 🔧 emoji for fixable rules, in my opinion. The lightbulb emoji better conveys the meaning of an "idea" or "suggestion".
> Switch to lightbulb emoji to denote rule suggestions

- packages/eslint-plugin/src/rules/no-useless-constructor.ts
- packages/eslint-plugin/tests/rules/no-useless-constructor.test.ts
> fix(eslint-plugin): [no-useless-constructor] handle parameter decorator

- packages/website/data/sponsors.json
- packages/website/src/components/FinancialContributors/Sponsor.tsx
- packages/website/src/components/FinancialContributors/Sponsors/index.tsx
- packages/website/src/components/FinancialContributors/Sponsors/styles.module.css
- packages/website/src/components/FinancialContributors/index.tsx
- packages/website/src/components/FinancialContributors/styles.module.css
- tools/generate-sponsors.ts
As the issue describes:
* Removes the "monthly amount" option from the Financial Contributors list, and has it just go based on total donations
* Makes the tiers $100, $500, and $1000 (previous: $50, $150, $750)
* Adds a "see all financial contributors" link at the bottom
Re-running `yarn generate-sponsors` both applied those changes and updated sponsor amounts, since we haven't checked in an updated sponsors list in a week or so.
Gives the tiers nice rare metal based names to more clearly indicate that they're particularly money-generous sponsors.
> chore(website): simplify sponsor displays to just minimums

- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/src/rules/no-empty-interface.ts
- packages/eslint-plugin/src/rules/no-explicit-any.ts
- packages/eslint-plugin/src/rules/no-unsafe-call.ts
- packages/eslint-plugin/src/rules/return-await.ts
- packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
- yarn.lock
Upgrade to [v5.0.5](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/releases/tag/v5.0.5) of [eslint-plugin-eslint-plugin](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin).
This version fixes 4 separate bugs that we had to use disable comments for in #5453. These disable comments have now been removed. Only one disable comment related to this plugin remains.
> chore: update eslint-plugin-eslint-plugin to 5.0.5

- packages/website/src/components/RulesTable/index.tsx
- packages/website/src/components/RulesTable/styles.module.css
I actually wanted to do it when implementing the table, but didn't think deeply about it. I also took the chance to add a `title` to every table cell so people know what the little emojis mean.
> chore(website): improve rules table UX

- README.md
We have a website which is the primary port-of-call for users - we don't want people to be drawn to our github readme.
We also display financial contributors on our website, and we do so with our own logic.
The images deleted here are generated and controlled using OC's private, internal logic - meaning we're vulnerable to bad actors that we don't want to give publicity to.
> chore: remove opencollective sponsors from the root readme

- .github/workflows/ci.yml
Since node 12 isn't supported anymore, this PR changes the oldest node version to `14`. The CI will now run tests on node 14 and 18
> chore: test node v14 on ci.yml

- packages/website/docusaurusConfig.ts
Update the Algolia DocSearch credentials to leverage [the new infrastructure](https://docsearch.algolia.com/docs/migrating-from-legacy/#scraper).
The daily crawls on the legacy infra (`BH4D9OD16A`) have been stopped months ago, which make the search results outdated and not benefiting of the improvements made on our crawler since then.
> docs: use new Algolia infrastructure credentials

- packages/eslint-plugin/README.md
- packages/parser/README.md
- packages/scope-manager/README.md
- packages/typescript-estree/README.md
Update readme files to new getting started page
> docs: Fix links to getting started in README.md

- packages/shared-fixtures/fixtures/typescript/decorators/class-decorators/export-default-class-decorator.src.ts
- packages/shared-fixtures/fixtures/typescript/decorators/class-decorators/export-named-class-decorator.src.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
- packages/typescript-estree/tests/snapshots/typescript/decorators/class-decorators/export-default-class-decorator.src.ts.shot
- packages/typescript-estree/tests/snapshots/typescript/decorators/class-decorators/export-named-class-decorator.src.ts.shot
Just adding these ahead of #5551 so that it's easy to verify that we aren't introducing a regression with the parser upgrade
> test: add fixtures for exported classes with decorators

- packages/eslint-plugin/docs/rules/prefer-optional-chain.md
- packages/eslint-plugin/src/rules/prefer-optional-chain.ts
- packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
The enhancement added to the rule in #5266 unfortunately introduced a crash.
The fix will be non-trivial and require some investigation.
Given that the PR only released last week - I think it's best to revert it entirely to fix the rule for users, and rebuild the PR without crashes when it's ready
> fix(eslint-plugin): revert #5266

- package.json
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/getModifiers.ts
- patches/typescript+4.8.2.patch
- yarn.lock
#5573 will add CI tests for this, so for now you'll have to trust me that this fixes things
> fix(typescript-estree): fix decorator regression for pre TS4.8

- packages/website-eslint/rollup.config.js
- packages/website-eslint/src/mock/globby.js
- packages/website-eslint/src/mock/is-glob.js
- packages/website-eslint/src/mock/semver.js
There's a lot of unrelated changes in here - it took me a while to really nail down exactly what the problem was. I spent a chunk of time just figuring out how everything worked.
I still don't know *why* it occurred, but for some reason when we upgraded to TS4.8 the website-eslint build started including a dependency that required `os` and `stream` (nodejs modules). Because rollup can't bundle nodejs modules - it assumed they'd be provided later, which they weren't - leading to unresolved imports that (I think) monaco attempted to resolve by loading a script from the server.
Result of testing with this PR locally:
> chore(website): fix playground

- packages/shared-fixtures/fixtures/typescript/decorators/class-decorators/class-parameter-property.src.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
- packages/typescript-estree/tests/lib/__snapshots__/semantic-diagnostics-enabled.test.ts.snap
- packages/typescript-estree/tests/snapshots/typescript/decorators/class-decorators/class-parameter-property.src.ts.shot
Removes the unnecessary block that was added with the 4.8 support and adds a fixture for it
> fix(typescript-estree): don't double add decorators to a parameter property's parameter

- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
- packages/scope-manager/src/referencer/ClassVisitor.ts
- packages/scope-manager/tests/fixtures/class/declaration/static-external-ref.ts
- packages/scope-manager/tests/fixtures/class/declaration/static-external-ref.ts.shot
- packages/scope-manager/tests/fixtures/class/declaration/static-with-constructor.ts
- packages/scope-manager/tests/fixtures/class/declaration/static-with-constructor.ts.shot
I wasn't paying anywhere near enough attention when reviewing #5489.
That PR did not actually properly implement scope analysis.
It created a scope but never closed it - meaning if you had a static block it'd leave a dangling scope which breaks things.
Also it never actually visited the static block's children.
This PR closes off the scope and visits the children, fixing the problem
> fix(scope-manager): correct handling for class static blocks

- packages/website/docusaurusConfig.ts
Fixes #5213
On the TypeScript ESLint Docusaurus site, the logo's alt text ("TypeScript ESLint logo") is cluttering the logo link's accessible name for assistive technologies. When screenreader users navigate to the logo link, they're told "link, TypeScript ESLint logo TypeScript ESLint," which is too cumbersome. Additionally, voice control users would need to recite that name to trigger the link.
This pull request uses a change to Docusaurus that arrived in v2 (facebook/docusaurus#7658) to supply an empty alt text for the logo image, marking it as decorative for assistive technologies. As a result, the link's accessible name is simply "link, TypeScript ESLint."
**DevTools showing empty alt for the image, and that the image is ignored in the accessibility tree:**
_(Note that Chrome …
> chore(website): [a11y] Mark logo as decorative for assistive technologies

- docs/README.md
Fixes the link to the ESLint website in the Getting Started docs.
> docs(readme): update ESLint website link

- packages/eslint-plugin/docs/rules/no-throw-literal.md
[#5386](https://github.com/typescript-eslint/typescript-eslint/pull/5386/files#diff-9181ab0ae5422d5141e0ec2940c8730c5b367547acacbf5033ac3b3260bab8b7) changed the docs for the no-throw-literal options to show them extending from the no-shadow options. In fact, the base no-throw-literal rule does not have any options, so this PR removes the references to the base options.
> docs(eslint-plugin): fix no-throw-literal options type

- packages/website/plugins/generated-rule-docs.ts
The name of the rules from typescript-eslint and eslint may differ (for example `return-await` rule in typescript-eslint and `no-return-await` rule in eslint) and the information specified in `How to Use` and some links on the page become broken and lead to the 404 page of the eslint site.
> fix(website): Use extended base rule name from file's meta

- packages/eslint-plugin/docs/rules/no-parameter-properties.md
> docs: [no-parameter-properties] fix broken link

- packages/website/plugins/generated-rule-docs.ts
In #5621 I didn't notice that the value of extendsBaseRule could be boolean, so some rules on the site was changed to `true`.
> chore(website): correct true extendsBaseRule values

- .github/workflows/ci.yml
- .github/workflows/lock.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> chore: GitHub Workflows security hardening

- packages/website/src/css/custom.css
The thead shadow for the rules table in dark mode is much less aggressive now.
> chore(website): fix border-shadow color in dark mode

- packages/eslint-plugin/src/rules/comma-spacing.ts
> chore(eslint-plugin): comma-spacing meta.type should be layout, not suggestion

- packages/website/package.json
- packages/website/src/components/ast/utils.ts
Fixes a type error from a `@ts-expect-error`. Nice.
> chore(website): add typecheck task

- packages/website/sidebars/sidebar.rules.js
The first two sections -_TypeScript Rules_ and _Extension Rules_- are uncollapsed by default:
> chore(website): split extension rules in sidebar too

- packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
- packages/eslint-plugin/tests/rules/consistent-indexed-object-style.test.ts
> fix(eslint-plugin): [consistent-indexed-object-style] handle interface generic

- .github/dependabot.yml
Speaking with @JoshuaKGoldberg - we were thinking we wanted a way to help ensure we test against the latest stable version of our core deps.
We thought about creating a bespoke action to install the latest version and test.. then we realised we have that functionality in dependabot - though the deps were ignored in the config.
This unignores them so that we can get the auto update including a PR which runs the full CI.
> chore: unignore typescript and eslint from dependabot

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
> fix(eslint-plugin): [no-unnecessary-condition] handle void

- packages/website-eslint/rollup.config.js
Corrects the alias path for `RuleTester` in the Rollup config, as it was updated in #5750.
> chore(website): fix RuleTester alias in Rollup

- .github/renovate.json
https://docs.renovatebot.com/configuration-options/#postupdateoptions
This will cause renovate bot to run `yarn-deplicate` after it does a bump.
This should help us keep the lockfile correct and the number of versions minimal
> chore: deduplicate after renovate updates

- packages/eslint-plugin/src/rules/no-misused-promises.ts
- packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
Fixes #5807
When linting a function with a 'rest' tuple argument, we might have different numbers of arguments between signatures:
```
function foo(...args: []);
function foo(...args: [string]);
```
This PR makes no-misused-promises handle this code correctly, by ensuring that we only check an argument when we have a corresponding type parameter in the tuple type arguments.
> fix(eslint-plugin): Skip missing 'rest' tuple type arguments in no-misused-promises

- .github/replies.yml
My [refined-save-replies extension](https://github.com/JoshuaKGoldberg/refined-saved-replies) bails out on parsing replies because of this one.
> chore: fix replies.yml blank entry
