typescript-eslint/typescript-eslint

- packages/website/plugins/generated-rule-docs.ts
The auto-generated 'How to Use' code blocks are incorrect, this PR basically fixes the problem.
> chore(website): correct 'how to use' code block of rules

- packages/utils/package.json
- yarn.lock
#5750 added a dependency on `semver` to the `@typescript-eslint/utils` package. This implicitly depended on `@types/semver` which is provided by the top-level workspace package.json file but not `@typescript-eslint/utils` itself. This caused my application to break.
My application imports some types from this package:
```ts
import type { TSESLint, JSONSchema } from '@typescript-eslint/utils';
```
And the breakage occurred during:
* https://github.com/bmish/eslint-doc-generator/pull/111
* https://github.com/bmish/eslint-doc-generator/pull/113
While running:
```
> tsc
Error: node_modules/@typescript-eslint/utils/dist/eslint-utils/rule-tester/dependencyConstraints.d.ts(1,25):
error TS7016: Could not find a declaration file for module 'semver'. …
```
> fix(utils): add missing dependency on `@types/semver`

- nx.json
Per the #5382, adds the coverage directory to nx output cache for `test` commands. This should get coverage data uploaded to the cache restored in `main` branch runs.
> chore: add test coverage data to nx test caches

- .github/renovate.json5
#5797 is working on automation here, which is when we can remove `@nrwl/workspace`.
I'm adding because renovate raised #5837, #5838, #5842, #5843
> chore: don't renovate `nx` or `@nrwl/workspace` for now

- packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
Removed `forceSuggestionFixer` from the code since the rule `prefer-nullish-coalescing` is not `fixable` anymore, i.e, it won't fix automatically on someone running `--fix`. Which makes this option useless.
> chore(eslint-plugin): [prefer-nullish-coalescing] removed forceSuggestionFixer option

- packages/eslint-plugin/src/rules/no-base-to-string.ts
- packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Adds built-in types that have `toString()` overrides not mentioned by TypeScript to the default `ignoredTypeNames` object.
> fix(eslint-plugin): [no-base-to-string] ignore Error, URL, and URLSearchParams by default

- packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts
- packages/type-utils/src/isTypeReadonly.ts
- packages/type-utils/tests/isTypeReadonly.test.ts
> fix(type-utils): prevent stack overflow in `isTypeReadonly`

- packages/eslint-plugin/docs/rules/no-empty-interface.md
- packages/eslint-plugin/tests/docs.test.ts
The _Options_ heading in https://typescript-eslint.io/rules/no-empty-interface was an h3 (`###`), not h2 (`##`) as expected by `generated-rule-docs.ts`. This fixes it to be an h2 and adds a unit test for known headings.
> chore(website): fix Options heading level for no-empty-interface docs

- .github/workflows/ci.yml
Akin to #3776 but for v6, and roughly following the guide in #5874.
Things I changed from the guide based on the old PR:
* Made this branch+PR first, rather than all in one `v6`
* Added to `push: branches:` list on top of `ci.yml`
* Additions to Step 2:
* Change the name
* Change the description
* Additions to Step 3:
* Naming convention for initial commit / PR
> chore: add auto-canary release for v6

- packages/parser/README.md
- packages/typescript-estree/README.md
- packages/typescript-estree/src/create-program/createDefaultProgram.ts
- packages/typescript-estree/src/create-program/createProjectProgram.ts
- packages/typescript-estree/src/parseSettings/createParseSettings.ts
- packages/typescript-estree/src/parseSettings/index.ts
- packages/typescript-estree/src/parser-options.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tests/lib/parse.test.ts
- packages/typescript-estree/tests/lib/semanticInfo.test.ts
- packages/website/src/components/linter/config.ts
Renames a part of the public typescript-estree API
Renames `createDefaultProgram` to `deprecated__createDefaultProgram`, with associated `@deprecated` TSDoc tags and warnings.
> feat(typescript-estree): deprecate createDefaultProgram

- packages/typescript-estree/src/parseSettings/inferSingleRun.ts
- fixes https://github.com/import-js/eslint-plugin-import/issues/2496
This was an absolute doozy to debug!
`eslint-plugin-import` does its own out-of-band parsing for some of its lint rules (like `import/no-cycle` or `import/namespace`). It does this by reusing the config originally passed to ESLint for the currently linted file - namely the `parser` and `parserOptions` config items.
This parsing is always forced to be in non-type-aware mode thanks to some hard-coding I added to their tooling way way back (https://github.com/import-js/eslint-plugin-import/blob/c3d14cb920bdc6d277134973d37364db22c3a8b8/utils/parse.js#L79-L84). This was necessary for performance and because they often parse files not covered by a tsconfig (like `node_modules` files).
Back to the issue at hand. When we added …
> fix(typescript-estree): don't allow single-run unless we're in type-aware linting mode

- packages/utils/src/eslint-utils/rule-tester/RuleTester.ts
- packages/utils/src/ts-eslint/RuleTester.ts
- packages/utils/tests/eslint-utils/rule-tester/RuleTester.test.ts
As I continued working on #5573, I realised that there are some plugin rules that won't ever work on old versions of TS.
For example `consistent-type-imports` hard requires at least TS 4.1 as that was the first version where the required syntax was added.
This PR adds a new API to the rule tester that allows you to list a set of dependency constraints for all tests in the rule tester constructor. If the constraints don't pass then absolutely no tests are run.
> feat(utils): add `RuleTester` API for top-level dependency constraints

- packages/ast-spec/src/unions/TypeNode.ts
- packages/eslint-plugin/src/rules/sort-type-constituents.ts
- packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
- packages/eslint-plugin/tests/rules/sort-type-constituents.test.ts
- packages/eslint-plugin/tests/rules/sort-type-union-intersection-members.test.ts
Found this was missing whilst doing some work - oops!
> fix(ast-spec): add TSQualifiedName to TypeNode union

- packages/ast-spec/src/declaration/ExportNamedDeclaration/spec.ts
The props were the correct sets - but they didn't match the names of the interfaces.
> fix(ast-spec): correct misnamed ExportNamedDeclaration AST type

- README.md
- package.json
- packages/eslint-plugin/src/rules/no-non-null-asserted-optional-chain.ts
- packages/eslint-plugin/src/rules/no-unnecessary-type-constraint.ts
- packages/eslint-plugin/tests/rules/no-non-null-asserted-optional-chain.test.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/create-program/createWatchProgram.ts
- packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
- packages/typescript-estree/src/version-check.ts
- yarn.lock
Bumps the minimum supported range and removes handling for old versions
DT hasn't bumped to 4.2 yet, but it's only just ticked to november, so I'd expect them to do it soon - likely before we do the major release.
This PR:
- updates docs to clarify our version support windows
- bumps the ranges around the place
- removes no-longer-necessary checks for now outdated versions
> feat: bump minimum supported TS version to 4.2.4

- packages/eslint-plugin/docs/rules/consistent-type-imports.md
- packages/eslint-plugin/src/rules/consistent-type-imports.ts
- packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
-   [x] Addresses an existing open issue: fixes #4338
This PR adds a configuration option `inline-type-imports` that users can utilize to inline their type imports.
Previously, as on Typescript 3.8, we had the ability to `import type`.  This import would be elided from the build deterministically.
```
import A, { CType } from 'foo';
import type { AType } from 'foo';
import { BType } from 'foo';
```
As of 4.5, we can inline that type, making it easier to manage top level imports.
```
import A, { tye …
```
> feat(eslint-plugin): [consistent-type-imports] support fixing to inline types

- packages/utils/src/ts-eslint/Rule.ts
Removes `meta.docs.suggestion` property
`meta.docs.suggestion` was replaced by `meta.hasSuggestions` as of ESLint v8: https://github.com/eslint/eslint/pull/14573
The old property was never used for anything, while the presence of the new property is [enforced](https://eslint.org/docs/latest/user-guide/migrating-to-8.0.0#suggestions) by ESLint when a rule provides suggestions.
It's confusing to leave the old, redundant property in place, so I have removed it here.
We can remove the old type as a breaking change in the upcoming v6 release.
> feat(utils): remove obsolete `meta.docs.suggestion` rule type

- .eslintrc.js
- packages/eslint-plugin-internal/src/rules/no-poorly-typed-ts-props.ts
- packages/eslint-plugin-internal/src/rules/no-typescript-default-import.ts
- packages/eslint-plugin-internal/src/rules/no-typescript-estree-import.ts
- packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
- packages/eslint-plugin-internal/src/rules/prefer-ast-types-enum.ts
- packages/eslint-plugin-tslint/src/rules/config.ts
Enable this optional rule for rule source files internally: https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-docs-description.md
Same change in ESLint recently: https://github.com/eslint/eslint/pull/16529
> chore: enable `eslint-plugin/require-meta-docs-description` rule

- packages/eslint-plugin/docs/rules/sort-type-union-intersection-members.md
Replaces the incorrect link that currently links to the rule itself with the link to the rule that replaced it.
> docs(eslint-plugin): [sort-type-union-intersection-members] fix link to new rule

- packages/website/src/theme/MDXComponents/RuleAttributes.tsx
The typescript rules [index](https://typescript-eslint.io/rules/) uses the wrench 🔧 emoji for auto-fixable rules, as do MANY other ESLint plugins (including many that use [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator)):
* [eslint-plugin-ava](https://github.com/avajs/eslint-plugin-ava#rules)
* [eslint-plugin-ember](https://github.com/ember-cli/eslint-plugin-ember#-rules)
* [eslint-plugin-eslint-plugin](https://github.com/eslint-community/eslint-plugin-eslint-plugin#rules)
* [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import#rules)
* [eslint-plugin-jsx-a11y](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#supported-rules)
* [eslint-plugin-promise](https://github.com/eslint-community/eslint-plugin-promise#rules)
* …
> docs: use consistent auto-fixable rule emoji

- tsconfig.base.json
Updates the internal TSConfig target to ES2021.
Fixes #5980.
I didn't see any other production files to update this in. All the other `tsconfig.json` files present are test fixtures. Let me know if we should update those too.
Potential breaking change targeting v6 (#5886).
> feat: raise tsconfig target to ES2021

- packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md
This PR adds a line to the `prefer-nullish-coalescing` docs letting the reader know the rule will not work as intended if `strict-null-checks` is not enabled.
> chore(website): [prefer-nullish-coalescing] explicit notice for strictNullChecks

- packages/eslint-plugin/src/rules/keyword-spacing.ts
- packages/eslint-plugin/tests/rules/keyword-spacing.test.ts
Add a space between `type` token and `*` or `{` tokens when `after` option is true, and remove when `after` is false
> feat(eslint-plugin): [keyword-spacing] Support spacing in import-type syntax

- packages/eslint-plugin/src/rules/prefer-optional-chain.ts
- packages/eslint-plugin/tests/rules/prefer-optional-chain.test.ts
I'm not sure why the default switch case is to throw instead of ignoring the code 😢 
~The issue was not yet triaged but I opened a PR just in case~
> fix(eslint-plugin): [prefer-optional-chain] handle binary expressions in negated or

- docs/development/architecture/PACKAGES.md
Fixes the text's link casing to be the same as on disk.
> chore(website): fix TSLint.md link casing in PACKAGES.md

- packages/parser/src/parser.ts
- packages/typescript-estree/src/ast-converter.ts
- packages/typescript-estree/src/create-program/createDefaultProgram.ts
- packages/typescript-estree/src/create-program/createIsolatedProgram.ts
- packages/typescript-estree/src/create-program/createSourceFile.ts
- packages/typescript-estree/src/create-program/createWatchProgram.ts
- packages/typescript-estree/src/parseSettings/createParseSettings.ts
- packages/typescript-estree/src/parseSettings/index.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/src/source-files.ts
- packages/typescript-estree/tests/lib/source-files.test.ts
- packages/website/src/components/linter/config.ts
Changes several function parameters from `code: string` to `code: string | ts.SourceFile`. Folks should now be able to pass in a source file directly, instead of the text of a file that we then have to redundantly reparse.
Targeting the `v6` branch even though this arguably isn't really a breaking change. Since this is such a core API, I'd want it to be able to benefit from the v6 testing process too.
> feat(typescript-estree): allow providing code as a ts.SourceFile

- docs/linting/TROUBLESHOOTING.md
Adds a brief overview of caching issues, with a link to a very thorough comment.
cc @tkdodo
> docs(website): mention cross-file caching issues in FAQs

- packages/eslint-plugin/tests/rules/non-nullable-type-assertion-style.test.ts
- packages/typescript-estree/src/create-program/createWatchProgram.ts
Discovered this while working on #5916
Previously we would consider any cached program as fair game during parsing.
Most of the time this isn't a problem because users always have the same config for an entire lint run.
However if the user has a different value for `parserOptions.project` around the place, then we would behave incorrectly - we would iterate through our cached programs and return a matching program for a file even if its tsconfig wasn't included in the current `parserOptions.project`! This is really bad because it means we'll lint a file with probably incorrect types!!!
I discovered this in the above PR because I defined two separate test runs with different tsconfigs in the same file.
Because our rule tester uses the exact same filename, the parser checked the cache, …
> fix(typescript-estree): don't consider a cached program unless it's specified in the current `parserOptions.project` config

- packages/eslint-plugin/src/rules/adjacent-overload-signatures.ts
- packages/eslint-plugin/tests/rules/adjacent-overload-signatures.test.ts
Overloaded function declarations can also appear in BlockStatements and should be checked.
> feat(eslint-plugin): [adjacent-overload-signatures] check BlockStatement nodes

- .github/replies.yml
- docs/maintenance/ISSUES.md
- docs/maintenance/PULL_REQUESTS.md
- packages/website/sidebars/sidebar.base.js
Describes how we close old issues & PRs. And by _"we"_ I mean how _I_ have been doing it 😄 - would be nice to see if there's a better way!
> docs(website): pruning flow for issues and PRs

- .github/DISCUSSION_TEMPLATE/rfcs.yml
Sets up a discussion form for the RFC category. Perhaps the first public non-GitHub repo to do so in the ✨ world ✨ - and the universe!
Co-authored-by: @entcheva
> chore: add discussion template for RFCs

- packages/eslint-plugin/src/rules/no-invalid-this.ts
- packages/eslint-plugin/src/rules/no-unused-expressions.ts
- packages/eslint-plugin/src/rules/no-useless-constructor.ts
- packages/eslint-plugin/src/rules/quotes.ts
- packages/eslint-plugin/src/rules/semi.ts
I stumbled onto some more references to ESLint v6 in the codebase. I hadn't known about them. 🔪 
cc @bmish from #5968 -> #5972
> chore: removed eslint@6 fallbacks for rule messages, and a snapshot

- .prettierignore
- packages/scope-manager/src/referencer/Referencer.ts
- packages/scope-manager/tests/fixtures/type-assertion/satisfies.ts
- packages/scope-manager/tests/fixtures/type-assertion/satisfies.ts.shot
(missed as part of #5717, part of #5688)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/typescript-eslint/typescript-eslint/pull/6059).
* __->__ #6059
feat(scope-manager): add support for TS4.9 satisfies expression
> fix(scope-manager): add support for TS4.9 satisfies expression

- packages/eslint-plugin/src/rules/array-type.ts
- packages/eslint-plugin/tests/rules/array-type.test.ts
Array type with intersection that has parentheses does not retain the parens. Remove an unnecessary check since the type node doesn't include parens.
> fix(eslint-plugin) [array-type] --fix flag removes parentheses from type

- packages/eslint-plugin/src/rules/keyword-spacing.ts
Sources the `after` option from the second parameter to `create` instead of `context.options`. Turns out the latter is the raw user-provided options before `defaultOptions` are applied.
> fix(eslint-plugin): [keyword-spacing] prevent crash on no options

- .github/workflows/semantic-pr-titles.yml
- CONTRIBUTING.md
I've seen a few PRs recently that haven't had the correct titles.
I accidentally merged one that was missing the colon!
This PR adds an action that will validate the PR titles match the semantic commit spec using this action:
https://github.com/amannn/action-semantic-pull-request
> chore: add action to enforce semantic-pr titles

- packages/typescript-estree/src/ts-estree/ts-nodes.ts
Another thing we need to add to the "new syntax" contributor guide.
This union is part of the API surface for the package, so we need to ensure we don't break the build on old TS versions by "stubbing" out the new AST node types.
Also added version comments so it's easy to tell when we can remove them as we bump the minimum TS version
> fix(typescript-estree): stub out `ts.SatisfiesExpression` on old TS versions

- packages/website/playwright.config.ts
- packages/website/src/components/config/ConfigEditor.tsx
- packages/website/tests/playground.spec.ts
Adds a playground test that:
1. Types passing code & enables a rule with no issues
2. Changes the code to fail the rule
3. Autofixes the code to pass again
Also fixes an accessibility oddity with labels in the visual dropdown for rules. There's no space between rule name and description currently:
```diff
await page
.getByLabel(
-    '@typescript-eslint/array-typeRequire consistently using either `T[]` or `Array<T>` for arrays',
+    '@typescript-eslint/array-type Require consistently using either `T[]` or `Array<T>` for arrays',
)
.check();
```
> test(website): add Playwright test for Playground linting

- packages/eslint-plugin-tslint/src/rules/config.ts
This is showing up as an unchanged file annotation in #6084 [[failing action job](https://github.com/typescript-eslint/typescript-eslint/actions/runs/3545759537/jobs/5954200630)]:
```plaintext
/home/runner/work/typescript-eslint/typescript-eslint/packages/eslint-plugin-tslint/src/rules/config.ts
Error:   111:9  error  Retrieve options from create's second parameter so that defaultOptions are applied  no-restricted-syntax
```
I don't know why this wasn't caught in #6074.
> chore(eslint-plugin-tslint): take rule options from create parameter

- .github/ISSUE_TEMPLATE/01-bug-report-plugin.yaml
Sometimes we remove the `bug` tag when we mark an issue as "working as intended". So let's just remove this from the pre-filled search entirely
> chore: remove bug tag from pre-filled bug search

- packages/eslint-plugin/src/rules/no-shadow.ts
- packages/eslint-plugin/tests/rules/no-shadow/no-shadow.test.ts
Adds call signatures and method signatures to the node types that `no-shadow` will ignore when `ignoreFunctionTypeParameterNameValueShadow` is `true`.
I embarrassingly got this rule's logic wrong the first time I tried triaging the issues, so asking for more oversight here. 🥲
> fix(eslint-plugin): [no-shadow] add call and method signatures to `ignoreFunctionTypeParameterNameValueShadow`

- packages/parser/src/parser.ts
> fix(parser): remove the jsx option requirement for automatic jsx pragma resolution

- packages/eslint-plugin/src/rules/sort-type-constituents.ts
- packages/eslint-plugin/src/rules/sort-type-union-intersection-members.ts
- packages/eslint-plugin/src/util/misc.ts
- packages/eslint-plugin/tests/rules/sort-type-constituents.test.ts
- packages/eslint-plugin/tests/rules/sort-type-union-intersection-members.test.ts
`requiresParentheses` now returns `true` for union types starting with `|` and intersection types starting with `&`.
> fix(eslint-plugin): [sort-type-constituents, sort-type-union-intersection-members] handle some required parentheses cases in the fixer

- packages/eslint-plugin-tslint/src/rules/config.ts
- packages/typescript-estree/src/create-program/createProjectProgram.ts
- packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
- packages/typescript-estree/src/index.ts
- packages/typescript-estree/tests/lib/persistentParse.test.ts
- packages/typescript-estree/tests/lib/semanticInfo-singleRun.test.ts
- packages/typescript-estree/tests/lib/semanticInfo.test.ts
- packages/website-eslint/rollup.config.js
Just a small cleanup PR from an unused export I noticed in https://github.com/typescript-eslint/typescript-eslint/pull/6084/files#diff-8198ca001c396f4c9a35d64b92e18a9361516a5046f98f31cec808fe76e4fd78.
1. `createWatchProgram` is never used outside of [createWatchProgram.ts](https://github.com/typescript-eslint/typescript-eslint/pull/6084/files#diff-8198ca001c396f4c9a35d64b92e18a9361516a5046f98f31cec808fe76e4fd78)
2. That file is mostly used for its `getProgramsForProjects`, which is specifically getting _watch_ programs
3. I renamed the file and function both to `getWatchProgramsForProjects`
> chore(typescript-estree): cleaned up watch program naming internally

- .github/workflows/semantic-pr-titles.yml
@JoshuaKGoldberg asked for this and I needed it for #6118
In general we want people to do separate PRs so that changes are smaller - but sometimes it really is necessary to do everything in one PR - so might as well allow our validator to validate
> chore: allow multiple rule names in pr titles

- .github/workflows/ci.yml
- packages/ast-spec/project.json
- packages/eslint-plugin-internal/project.json
- packages/eslint-plugin-tslint/project.json
- packages/eslint-plugin/project.json
- packages/experimental-utils/project.json
- packages/parser/project.json
- packages/scope-manager/project.json
- packages/type-utils/project.json
- packages/types/project.json
- packages/typescript-estree/project.json
- packages/utils/project.json
- packages/visitor-keys/project.json
For example, allows us to write:
```sh
nx lint utils
```
instead of 
```sh
nx lint @typescript-eslint/utils
```
The names needed to match the package.json files a longgg time ago when I first set things up, but that's no longer the case so this would be a nice little QOL improvement
> chore: use short form for nx project names

- packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
- packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
Added strict-null-check and test for prefer-nullish-coalescing rule.
> feat(eslint-plugin): [prefer-nullish-coalescing] logic and test for strict null checks

- docs/linting/Troubleshooting.md
Mentions that no, you don't need to additionally run ESLint on transpiled JS code.
I couldn't find this explicitly mentioned anywhere else.
> docs: add FAQ entry about running ESLint on transpiled code

- .github/ISSUE_TEMPLATE/01-bug-report-plugin.yaml
> chore: remove versions table from simple bug report form

- packages/experimental-utils/package.json
- packages/experimental-utils/src/index.ts
- packages/experimental-utils/tests/consoleWarning.test.ts
Adds a console.warn upon importing from experimental-utils, as well as a test to verify
> feat(experimental-utils): console.warn on import of experimental-utils

- .cspell.json
- .github/actions/prepare-install/action.yml
This allows us to directly reuse out dependency installation logic in our private-workflows, and by landing it before the yarn 3 PR we can make that change in only one place and have it work everywhere (and stay in sync over time)
> chore: add working-directory input to prepare-install action

- packages/ast-spec/src/base/BaseNode.ts
- packages/types/package.json
- tools/postinstall.ts
I took another hard look at local build caching w.r.t. #6144 and #6163. I think the issue was that out-of-date files kept getting out of date, most often `packages/types/src/generated/ast-spec.ts`. This adds two layers of protection:
* For specifically the `types` package, also cleans `src/generated/` in `yarn clean`: since it's generated similar to `dist/`.
* Generally runs `yarn clean` in the postinstall script: as a backup precaution to make sure if you've pulled in build/cache changes, to wipe more things that might be out of date now. Ideally Nx should be caching them when the next line's `yarn build` runs anyway.
I moved the `BaseNode` JSDoc comments to below its `type` as a way to test this. They show up erroneously in the built output so this is a good change anyway. And, #5252 …
> chore: more aggressively clean local dev caches

- packages/eslint-plugin/docs/rules/no-non-null-assertion.md
Change "foo.property" to "example.property"
> docs: fixed typo  "foo.property"

- packages/website/src/pages/index.tsx
- packages/website/src/pages/styles.module.css
I haven't been able to figure out any kind of caching issue. So as a bandaid fix for now, this just adds a manual class to the buttons. 🤷
> chore(website): manually centered homepage buttons

- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/tests/rules/member-ordering/member-ordering-optionalMembers.test.ts
I'd flipped the order of the rule option when taking over the PR. 🤦
> fix(eslint-plugin): [member-ordering] correctly invert optionalityOrder

- packages/ast-spec/src/expression/ArrayExpression/spec.ts
- packages/ast-spec/src/expression/MemberExpression/spec.ts
- packages/ast-spec/src/unions/ObjectLiteralElement.ts
- packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
- packages/eslint-plugin/src/rules/require-array-sort-compare.ts
- packages/typescript-estree/tests/lib/semanticInfo.test.ts
These changes will be disruptive to downstream consumers but they are correct and will help expose potentially bad code.
Particularly the sparse array type fix because it's meant to include `null`, not just some other node type. They're a rarer case in code (because sparse arrays are one of the dumbest features in JS), but if encountered it will crash code that doesn't expect it.
> fix(ast-spec): correct some incorrect ast types

- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/eslint-plugin/tests/rules/unbound-method.test.ts
Specified which destructured method is unbound  and causing an error. Also added a test case for this in `unbound-method.test.ts`
> feat(eslint-plugin): specify which method is unbound and added test case

- .eslintrc.js
- packages/typescript-estree/tests/lib/parse.test.ts
When the renovate PR went in which upgraded the major version of `eslint-plugin-jest` some issues were introduced.
- `valid-expect` is triggered by some more unusual, advanced assertion we have, so we can simply ignore it
- `no-jest-import` rule was removed by the plugin, so we remove it from our config
> chore: fix repo linting

- packages/website/plugins/generated-rule-docs.ts
If `meta.docs.extendsBaseRule` is `true`, then we should just go with `file.stem`.
Corrects the link to be the right md source path. Also moves the link to be underneath the new _Resources_ section while I'm in the area. Feels like that makes more sense.
> chore(website): fix base rule source links for extended rules

- packages/eslint-plugin/docs/rules/unified-signatures.md
The invalid example for `unified-signatures`:
```ts
function f(...a: number[]): void;
function f(...b: string[]): void;
```
Is removed, and:
```ts
function f(...a: number[]): void;
function f(...a: string[]): void;
```
Is moved out of the `ignoreDifferentlyNamedParameters` part, and added comments about why the rule won't check overload signatures with different rest parameter types.
> docs(eslint-plugin): remove invalid examples for unified-signatures

- docs/maintenance/RELEASES.md
To try out the latest canary versions of typescript-eslint, install `@typescript-eslint/eslint-plugin@canary` and `@typescript-eslint/parser@canary`. Note that npm may need a `--force` to override version requirements.
> docs: describe how to install canary versions

- packages/typescript-estree/src/convert.ts
I missed this when I did #5915 - this piece of converter state is now completely unnecessary because #5915 cleaned up the last reference to it.
This PR just deletes the now unused code.
> chore(typescript-estree): remove unnecessary this.inTypeMode field

- docs/maintenance/ISSUES.md
Mostly mentions our common trends of keeping rules generally applicable to TypeScript.
> docs(website): added maintenance docs for rule feature requests

- packages/website/src/components/FinancialContributors/Sponsor.tsx
- packages/website/src/components/FinancialContributors/Sponsors/index.tsx
- packages/website/src/components/FinancialContributors/Sponsors/styles.module.css
- packages/website/src/components/FinancialContributors/index.tsx
- packages/website/src/components/FinancialContributors/styles.module.css
- packages/website/src/components/FinancialContributors/types.ts
Simplifies `include` to just `includeName` now that every tier includes links.
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
> chore(website): add links to and widen Silver Supporters

- packages/ast-spec/src/unions/JSXExpression.ts
As described in the linked issue, a `JSXEmptyExpression` node is only generated as the child of a `JSXExpressionContainer` node, and so cannot appear in the same place as a `JSXExpression`.
> fix(ast-spec): a JSXEmptyExpression is not a possible JSXExpression

- packages/eslint-plugin/src/rules/key-spacing.ts
> fix(eslint-plugin): do not use .at(), Node 14 does not support it

- packages/eslint-plugin/docs/rules/key-spacing.md
This is just a small typo in the docs, so I didn't follow the PR template.
> docs(eslint-plugin): fix key-spacing core rule name

- packages/eslint-plugin/src/util/misc.ts
- packages/eslint-plugin/tests/rules/sort-type-constituents.test.ts
Fixed behavior change when sorting TSConditionalType (#6339)
> fix(eslint-plugin): [sort-type-constituents] fixed behavior change

- .eslintrc.js
- packages/eslint-plugin/src/rules/space-before-function-paren.ts
> chore: enable one-var rule 

- packages/typescript-estree/tests/ast-alignment/fixtures-to-test.ts
Noticed we've since been updated to a version of Babel that supports `satisfies`.
> chore(typescript-estree): remove unnecessary babel test exclude

- packages/eslint-plugin/src/rules/no-import-type-side-effects.ts
- packages/eslint-plugin/tests/rules/no-import-type-side-effects.test.ts
> fix(eslint-plugin): [no-import-type-side-effects] correctly ignore zero-specifier imports

- packages/eslint-plugin/src/rules/explicit-function-return-type.ts
- packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Adds a `allowFunctionsWithoutTypeParameters` option to ignore non-generic functions.
The issue is quite old but I think it makes a lot of sense to add this in. I don't often use this rule, but when I do think about it, I often mostly only want it for complex, performance-degrading types.
> feat(eslint-plugin): [explicit-function-return-type] add allowFunctionsWithoutTypeParameters option

- packages/eslint-plugin/src/rules/key-spacing.ts
- packages/eslint-plugin/tests/rules/key-spacing.test.ts
The problem was not on the align part of the rule, but the space before / after the colon part of the rule. Now it checks that the type annotation is on the same line as the key, through the `isApplicable` helper.
> fix(eslint-plugin): fix key-spacing when type starts on next line

- .github/workflows/ci.yml
Need this so we can actually check PRs sitting the merge queue.
> chore: add merge_group trigger to run ci on the merge queue

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
This PR adds a check for `void` types in the [no-unnecessary-condition] rule. It also adds a valid test case to its valid tests array.
> fix(eslint-plugin): [no-unnecessary-condition] account for optional chaining on potentially void values

- tests/integration/pack-packages.ts
Makes sure a `package.json` file exists in a `packages/*` directory before requiring the file.
> chore: check package.json existence in package-packages.ts

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
This PR fixes the issue that the `no-unnecessary-condition` rule considers unconstrainted indexed access tyoes (`Obj[Key]`) as always truthy, leading to false positives.
```ts
export function get<Obj, Key extends keyof Obj>(obj: Obj, key: Key) {
const value = obj[key];
if (value) {
//    ^^^^^
//    This is not unnecessary, but flagged as error
return value;
}
throw new Error('BOOM!')
}
get({ foo: null }, "foo");
```
The fix is as suggested in https://github.com/typescript-eslint/typescript-eslint/issues/6264#issuecomment-1362477837 by @bradzacher -- just updating the flag seems to work fine.
> fix(eslint-plugin): [no-unnecessary-condition] fix false positive when checking indexed access types

- docs/linting/Configurations.mdx
- docs/linting/Typed_Linting.mdx
- package.json
- packages/eslint-plugin/src/configs/disable-type-checked.ts
- packages/eslint-plugin/tools/generate-configs.ts
- packages/types/src/parser-options.ts
- packages/typescript-estree/src/parseSettings/getProjectConfigFiles.ts
- packages/typescript-estree/src/parseSettings/resolveProjectList.ts
- packages/typescript-estree/src/parser-options.ts
- packages/typescript-estree/tests/lib/getProjectConfigFiles.test.ts
Builds on top of the new config tooling to generate a config that disables type-aware linting.
> feat(eslint-plugin): add config that disables type-aware linting

- .gitignore
- package.json
- packages/ast-spec/package.json
- packages/parser/package.json
- packages/scope-manager/package.json
- packages/scope-manager/project.json
- packages/type-utils/package.json
- packages/types/package.json
- packages/typescript-estree/package.json
- packages/utils/package.json
- packages/visitor-keys/package.json
- yarn.lock
In #5915 we bumped our minimum supported TS version to 4.2.
This applies to both users of our packages and consumer dependents.
As such we no longer need to downlevel all the way to TS3.4 any more.
This PR updates our downlevel-dts calls to target TS4.2 and updates the folder naming and targets to match
> chore: update downlevel-dts config to target TS4.2

- packages/eslint-plugin/docs/rules/explicit-function-return-type.md
- packages/eslint-plugin/src/rules/explicit-function-return-type.ts
#6105 added the allowFunctionsWithoutTypeParameters option to explicit-function-return-type but didn't add additional documentation that would make it more useful to use; the implicit default value (`false`), and examples of correct and incorrect cases.
This documentation only PR adds the missing pieces.
> docs(eslint-plugin): explicit-function-return-type: missing allowFunctionsWithoutTypeParameters sections

- docs/Custom_Rules.mdx
The link is not matching. the link should address https://typescript-eslint.io/custom-rules#type-checking
> docs(website): fix typed rules heading link in custom rule docs

- packages/ast-spec/tests/fixtures.test.ts
- packages/shared-fixtures/fixtures/typescript/basics/type-import-type.src.ts
- packages/typescript-estree/tests/lib/getProjectConfigFiles.test.ts
- packages/typescript-estree/tests/lib/parse.project-true.test.ts
Partially fix running tests on windows machines, with this change most tests do pass with exception to
https://github.com/typescript-eslint/typescript-eslint/blob/98dec37c407717a0ff1002bf483113d15bbb4958/packages/utils/tests/eslint-utils/rule-tester/RuleTester.test.ts#L146-L188
filename is not correctly normalized in this test, this can be fixed after updating jest to 29.4 with EqualityTesters - https://jestjs.io/docs/expect#expectaddequalitytesterstesters
> test: allow to execute tests on windows

- packages/eslint-plugin/src/rules/consistent-generic-constructors.ts
- packages/eslint-plugin/tests/rules/consistent-generic-constructors.test.ts
Thanks @JoshuaKGoldberg for help with the AST selector 😄
> feat(eslint-plugin): [consistent-generic-constructors] handle default parameters

- .github/workflows/ci.yml
Not sure if this is why the job is being skipped.
If this is the right fix, we'll want to update https://typescript-eslint.io/maintenance/releases#1-pre-release-preparation too.
> chore: hardcode v6 branch name in v6 canary publish

- packages/typescript-estree/src/clear-caches.ts
Calling it exports `undefined` instead of making it an alias of `clearCaches`, which I believe was the intent.
On DefinitelyTyped, [I worked around the problem](https://github.com/microsoft/DefinitelyTyped-tools/pull/620); clearProgramCaches isn't needed now anyway.
> fix(typescript-estree): do not call export of clearProgramCache

- docs/linting/Troubleshooting.mdx
The first link is broken in the section [I get no-unsafe-* complaints for cross-file changes](https://typescript-eslint.io/linting/troubleshooting/#i-get-no-unsafe--complaints-for-cross-file-changes) from the troubleshooting page.
> docs: fix typo in troubleshooting anchor link

- packages/website/src/css/prism.css
> feat(website): change Inaccessible + text in diff codeblocks colors

- packages/website/src/components/editor/LoadedEditor.tsx
- packages/website/src/components/editor/createProvideCodeActions.ts
- packages/website/src/components/linter/WebLinter.ts
- fix for "quick fix" in newer versions of typescript sandbox
- New command that let you fix all linting issues, key command is `ctrl+s`
> chore(website): add new action to playground to fix all eslint errors 

- docs/linting/troubleshooting/Formatting.mdx
- Also relevant: https://github.com/eslint/eslint.org/issues/419
Applies a few changes to make the page more friendly for newcomers:
* Moves the _ESLint Core and Formatting_ section to the end, so that folks start with the more-relevant explanation of _Formatters vs. Linters_
* Adds an explanation of the 2-3 categories of lint rules at the start of _ESLint Core and Formatting_
* Elaborates on why you'd want to use `eslint-config-prettier`, as you don't actually need it unless you enable rules separate from the core/typescript-eslint recommended presets
cc @mattpocock @nzakas for interest 👋
> docs: clarify kinds of lint rules in formatting docs

- docs/contributing/Pull_Requests.mdx
Adds a mention about re-requesting review with a link to the GitHub docs. This way it's not ambiguous whether folks should wait for us.
> docs: mention re-requesting PR reviews

- packages/parser/src/index.ts
Adds an exported `meta` object with `name` and `version` to `@typescript-eslint/parser`.
> feat(parser): add exported meta object

- packages/website/plugins/generated-rule-docs.ts
I just realized the `optionLevel` variable was never updated to reflect #5964.
> chore(website): always generate 'error' level for suggested rule configs

- packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-function/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/legacy-fixtures/errorRecovery/fixtures/_error_/decorator-on-function/snapshots/3-Alignment-Error.shot
- packages/ast-spec/tests/fixtures-with-differences-errors.shot
- packages/eslint-plugin/src/rules/no-empty-function.ts
- packages/eslint-plugin/tests/rules/no-empty-function.test.ts
- packages/typescript-estree/src/convert.ts
> feat(typescript-estree): check for illegal decorators on function declarations

- packages/eslint-plugin/docs/rules/prefer-function-type.md
Adds a comment in the docs warning about the global augmentation edge case.
> docs(eslint-plugin): [prefer-function-type] mention global augmentation edge case in docs

- docs/linting/troubleshooting/TSLint.mdx
"... also migrated move the Typescript" read weird.
- [X ] Addresses an existing open issue: fixes [#6579](https://github.com/typescript-eslint/typescript-eslint/issues/6579)
- [ TBD] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [ X] Steps in [Contributing](https://typescript-eslint.io/contributing) were taken
> docs: fix typo in tslint docs

- .gitattributes
Per discussion with @JoshuaKGoldberg. This makes snapshots collapsed just like `yarn.lock` changes.
> chore: collapse generated snapshots in PR view by default

- packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
- packages/eslint-plugin/src/util/getWrappingFixer.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-boolean-literal-compare.test.ts
Add missing handling for removal and adding parenthesis in rule fixer
new cases covered:
```ts
if ((x instanceof Error) === false) {}
if (false === (x instanceof Error)) {}
if (x instanceof Error === false) {}
```
old fixer result
```ts
if (!(x instanceof Error) { }
if (!x instanceof Error)) { }
if (!x instanceof Error) { }
```
new fixer result
```ts
if (!(x instanceof Error)) { }
if (!(x instanceof Error)) { }
if (!(x instanceof Error)) { }
```
--------------
initially i was planning to extend range of fixer to include `)(` but after further investigation this  started generating to many edge cases
eg. `(false) === x instanceof Error`
> fix(eslint-plugin): [no-unnecessary-boolean-literal-compare] fixer should handle parentheses

- packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
- packages/eslint-plugin/tests/rules/no-confusing-void-expression.test.ts
Added a check to sequence expressions that ignores void unless it is in the last position of a SequenceExpression
> fix(eslint-plugin): [no-confusing-void-expression] check sequence expressions for void is in last position

- .github/workflows/cleanup-cache.yml
Following this doc: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
Adds a workflow that will run when a PR closes and cleanup the cache entries for that PR automatically.
This should auto-prune our cache storage to help keep it smaller and prevent possibility of accidental sharing
> chore: automatically cleanup caches when the relevant PR closes

- packages/eslint-plugin/package.json
Without this, on `npm i`:
```plaintext
joshgoldberg ~/repos/TypeScript $ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: typescript@5.1.0
npm ERR! Found: @typescript-eslint/parser@6.0.0-alpha.81
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   dev @typescript-eslint/parser@"^6.0.0-alpha.81" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @typescript-eslint/parser@"^5.0.0" from @typescript-eslint/eslint-plugin@6.0.0-alpha.81
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   dev @typescript-eslint/eslint-plugin@"^6.0.0-alpha.81" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or …
```
> fix(eslint-plugin): allow parser@^6.0.0

- packages/eslint-plugin/docs/rules/await-thenable.md
- [ x] Addresses an existing open issue: fixes #000
- [x ] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
Update from _A "Thenable" value is an object with has a..._ to **A "Thenable" value is an object which has a...**
https://github.com/typescript-eslint/typescript-eslint/issues/6629
> docs(eslint-plugin): [await-thenable] fix typo

- packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
- packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
The `allowNullableEnum: true` option for the strict-boolean-expressions rule is not respected if all enum values are explicitly set to truthy strings or truthy numbers.
> fix(eslint-plugin): [strict-boolean-expressions] handle truthy enums

- packages/eslint-plugin-internal/src/util/createRule.ts
The old code imports the whole package.json, right?
> fix(eslint-plugin-internal): version import

- package.json
- packages/website/src/components/editor/LoadedEditor.tsx
- packages/website/src/components/editor/config.ts
- packages/website/src/components/editor/useSandboxServices.ts
- patches/typescript+5.0.2.patch
- yarn.lock
TS 5.0 has been released https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/
So we can update `typescript` to 5.0.2
> chore: update to TypeScript 5.0.2

- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/tests/lib/convert.test.ts
In the node's `Object.defineProperty` _accessor descriptor_, it's now given a setter that sets it to a _data descriptor_. See terminology on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty.
> fix(typescript-estree): allow writing to deprecated node properties

- packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-boolean-literal-compare.test.ts
- simplify fixer in `no-unnecessary-boolean-literal-compare]` rule
- fixer should now produce desired results for double negation
> fix(eslint-plugin): [no-unnecessary-boolean-literal-compare] simplify fixer and add support for double negation

- packages/ast-spec/src/parameter/TSParameterProperty/fixtures/_error_/override-function-parameter/fixture.ts
- packages/ast-spec/src/parameter/TSParameterProperty/fixtures/_error_/override-function-parameter/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/parameter/TSParameterProperty/fixtures/_error_/override-function-parameter/snapshots/2-Babel-Error.shot
- packages/ast-spec/src/parameter/TSParameterProperty/fixtures/_error_/override-function-parameter/snapshots/3-Alignment-Error.shot
- packages/ast-spec/src/parameter/TSParameterProperty/fixtures/_error_/override-method-parameter/fixture.ts
- packages/ast-spec/src/parameter/TSParameterProperty/fixtures/_error_/override-method-parameter/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/parameter/TSParameterProperty/fixtures/_error_/override-method-parameter/snapshots/2-Babel-Error.shot
- packages/ast-spec/src/parameter/TSParameterProperty/fixtures/_error_/override-method-parameter/snapshots/3-Alignment-Error.shot
- packages/typescript-estree/src/convert.ts
> fix(typescript-estree): forbid `override` on non-constructor function/methods

- packages/eslint-plugin/src/rules/consistent-type-assertions.ts
- packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
Autofixes `const x = <T>{ ... }` to `const x = { ... } as T`
> feat(eslint-plugin): [consistent-type-assertions] autofix angle bracket assertions to as

- packages/website/package.json
- packages/website/plugins/generated-rule-docs.ts
- packages/website/src/components/hooks/useHashState.ts
- yarn.lock
migrate from fork of lz-string to main version as it has type definition now
change extracted from #6656
> chore(website): migrate from lzstring.ts to lz-string package

- packages/website/blog/2023-03-13-announcing-typescript-eslint-v6-beta.md
Fixes the links to point to https://v6--typescript-eslint.netlify.app/.
Also adds a `` market while I'm here, so the blog post doesn't take up the entirety of https://typescript-eslint.io/blog. 😂
> chore(website): fix v6 beta post links to point to v6 site

- packages/eslint-plugin/docs/rules/lines-around-comment.md
Adding the rules to the documentation ([#75eb5b5](https://github.com/typescript-eslint/typescript-eslint/commit/75eb5b5fa3cea7999e006819e5c4f26cbd9c48be)) seems to have introduced a typo (`interface` instead of `enum`):
- `allowEnumEnd: true` doesn't require a blank line after an **interface** body block end
- `allowEnumStart: true` doesn't require a blank line before an **interface** body block start
- `allowInterfaceEnd: true` doesn't require a blank line before an interface body block end
- `allowInterfaceStart: true` doesn't require a blank line after an interface body block start
(Emphasis mine.)
[According to Contributing](https://typescript-eslint.io/contributing/pull-requests/), at least to my understanding, the change is eligible without an open issue:
> Only send pull requests …
> docs(eslint-plugin): [lines-around-comment] fix typo

- packages/eslint-plugin/src/rules/no-misused-promises.ts
- packages/eslint-plugin/src/rules/no-unsafe-argument.ts
- packages/eslint-plugin/src/rules/require-array-sort-compare.ts
- packages/type-utils/src/isTypeReadonly.ts
Tested in playground on ts 3.5.1
```Awk
TypeError: e.getTypeArguments is not a function
Occurred while linting <input>:4
Rule: "@typescript-eslint/no-unsafe-argument"
at FunctionSignature.create (https://typescript-eslint.io/sandbox/index.js:20:1047289)
at CallExpression, NewExpression (https://typescript-eslint.io/sandbox/index.js:20:1048838)
at https://typescript-eslint.io/sandbox/index.js:20:259967
at https://typescript-eslint.io/sandbox/index.js:20:250486
at Array.forEach (<anonymous>)
at Object.emit (https://typescript-eslint.io/sandbox/index.js:20:250474)
at NodeEventGenerator$1.applySelector (https://typescript-eslint.io/sandbox/index.js:4:122618)
at NodeEventGenerator$1.applySelectors (https://typescript-eslint.io/sandbox/index.js:4:122920)
at NodeEventGenerator$1.enterNode …
```
> fix(eslint-plugin): correct crashes with getTypeArguments for ts < 3.7

- packages/website/src/components/linter/WebLinter.ts
Add missing required field `codeFullText` to v6 playground
eg. comments where not parsed correctly
```ts
/* eslint "@typescript-eslint/no-unused-vars": "error" */
const x = 2
```
[playground this branch](https://deploy-preview-6768--typescript-eslint.netlify.app/play/#ts=5.0.2&sourceType=module&code=PQKgBApgzgNglgOwC5gEQAEkE8AO0DGATnDkgLTTzLAID2ZArgg1BACZkBuAhoVKgC40EQoVqFUYEMACwAKHn5aCKCgAeYALxgATEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA)
[playground v6](https://v6--typescript-eslint.netlify.app/play/#ts=5.0.2&sourceType=module&code=PQKgBApgzgNglgOwC5gEQAEkE8AO0DGATnDkgLTTzLAID2ZArgg1BACZkBuAhoVKgC40EQoVqFUYEMACwAKHn5aCKCgAeYALxgATEA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlg …
> chore(website): [playground] regression fix for parsing comments

- packages/website/src/components/ErrorsViewer.module.css
- packages/website/src/components/ErrorsViewer.tsx
- packages/website/src/components/layout/AlertBlock.tsx
migrate error viewer changes from #6656
notable changes:
- alerts have consistent small spacing between them
- text is printed as monospace font
- text is wrapped
> chore(website): [playground] improve design of error viewer

- docs/linting/Troubleshooting.mdx
Add to the troubleshooting and FAQ that currently Typescript project references are not yet supported.
Added an entry to the troubleshooting and FAQ docs that TypeScript project references is not yet supported.
> docs: update troubleshooting to include typescript project references not being supported yet

- packages/website/blog/2023-03-13-announcing-typescript-eslint-v6-beta.md
As promised in the blog post. As PRs get merged, the ⌛s go away.
> docs: remove hourglass for types allowlist from v6 beta post

- docs/contributing/Issues.mdx
- packages/website/blog/2023-03-13-announcing-typescript-eslint-v6-beta.md
Switches all channel-specific Discord links to be the general server invite. Any specific channels are now just mentioned as text after.
> chore(website): correct Discord links to all be general invites

- packages/eslint-plugin-tslint/package.json
- packages/eslint-plugin-tslint/src/rules/config.ts
This removes the heavy lodash dep from `eslint-plugin-tslint` by implementing a simplified version of the only utility we used from the package.
> chore(eslint-plugin-tslint): remove lodash dependency

- packages/type-utils/src/TypeOrValueSpecifier.ts
- packages/type-utils/tests/TypeOrValueSpecifier.test.ts
Handle type aliases in addition to interfaces.
> fix(type-utils): checking of type aliases' type names by `typeMatchesSpecifier`

- packages/parser/src/parser.ts
Support for the `es2021.full` and `es2022.full` libs was added in #3460 and #4615, but the `getLib` function wasn’t updated to use them; if `target` is set to `"ES2021"` or `"ES2022"` in `tsconfig.json`, `getLib` would incorrectly fall back to `['lib']` rather than `['es2021.full']` or `['es2022.full']`. Add these missing cases.
> fix: update getLib for new TypeScript targets ES2021, ES2022

- docs/contributing/Pull_Requests.mdx
Added a **how to ask** section in pull request docs. I wasn't sure what the title section should be. I might be overthinking it, but labeling it ask **"How to ask for help"** felt too specific. People might not be just asking for help but wanting to ask questions (to gain insight, clarification, etc). Again I might be overthinking it. 😅
> docs: update pull requests docs to include a how to ask section

- packages/eslint-plugin/src/rules/unified-signatures.ts
- packages/eslint-plugin/tests/rules/unified-signatures.test.ts
Allows explicit different names with overloads where the number of parameters differ.
> fix(eslint-plugin): [unified-signatures] allow overloads with different named and different number of parameters

- packages/eslint-plugin/src/rules/ban-types.ts
- packages/eslint-plugin/tests/rules/ban-types.test.ts
- [/] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22) (will revert if the issue is rejected)
This PR adds `NonNullable<unknown>` to the list of alternatives for `Object` and `{}`, and introduces suggestions to automatically replace those types with `NonNullable<unknown>`.
> feat(eslint-plugin): [ban-types] add NonNullable suggestion and allow custom suggestions

- packages/website/src/components/editor/LoadedEditor.tsx
- packages/website/src/components/editor/createProvideCodeActions.ts
- packages/website/src/components/editor/useSandboxServices.ts
- packages/website/src/components/lib/jsonSchema.ts
- packages/website/src/components/linter/createLinter.ts
- packages/website/src/components/linter/utils.ts
Enable rule schema validation in playground
https://user-images.githubusercontent.com/625469/232217302-aee2b593-50e7-4abf-a83b-8eab08d2ffa9.mp4
[config with errors](https://deploy-preview-6907--typescript-eslint.netlify.app/play/#ts=5.0.4&fileType=.tsx&code=FBA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6JgQwFtmBzWsgHsmAN0QtKw9GADa4bDkTRog6JAA08hVgXZIyREjL5V0ubt2RxsLpC26AuvYgBfTRZ0X9hxMdMZzCz1rW2dsB3cgyAAzVS4OfGkmBHgwl3sI%2BzwiUmQKajoGZjYhJmRKZHxxOl5xJUoyAWFKuD9oVACwq2VTSIVIHMRaABM7BUz%2BghJyKhp6ZEYWVkQAD2JGMko6LkQuACMlWg4yMhRyvcpGIjMupRU1PuxPS2PT5HPLrcJpSDHddPGj0glGGI3EhEYlRuXjuvTCACYMo9WKwwHAkGA8gALXYcMAAdy2WLAgj2ACtfPgwMxqVUuMgslNcvk5kUlsQOMNhnxaIshgd8PjEOJaJUErtqh1ZLceg8ws9%2Bnt4BwmABrAAyzEQPw48HxHEIqDSSPsKLA%2BCxFUxWMECGGYFh0BJTHNgjAF14YA4ygNWSYglosGSBlByoO8ClgX6jo0 …
> chore(website): validate rule options in editor

- packages/website/src/components/OptionsSelector.tsx
- packages/website/src/components/Playground.tsx
- packages/website/src/components/ast/ASTViewer.tsx
- packages/website/src/components/ast/DataRenderer.tsx
- packages/website/src/components/ast/utils.ts
- packages/website/src/components/hooks/useHashState.ts
- packages/website/src/components/options.ts
- packages/website/src/components/types.ts
- always display comments in ast
- allow to display tokens by enabling flag
- allow to disable scrolling -> this is useful for mobile devices
> chore(website): [playground] option to disable scroll and display tokens

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Allow nullish coalescing for a naked type parameter because it might be nullable.
> fix(eslint-plugin): [no-unnecessary-condition] allow nullish coalescing for naked type parameter

- packages/type-utils/src/TypeOrValueSpecifier.ts
- packages/type-utils/tests/TypeOrValueSpecifier.test.ts
- Added TypeOrValueSPecifier tests for package specifiers
> fix(type-utils): fixed TypeOrValueSpecifier not accounting for scoped DT packages

- docs/Getting_Started.mdx
- docs/linting/Typed_Linting.mdx
- docs/linting/troubleshooting/Formatting.mdx
- docs/linting/typed-linting/Monorepos.mdx
For each `module.exports =` in a `.mdx` file in a code block that includes most or all of a config file, adds the `/* eslint-env node */` comment.
> docs: add /* eslint-env node */ on top of suggested configs

- packages/eslint-plugin/src/rules/array-type.ts
- packages/eslint-plugin/src/rules/ban-ts-comment.ts
- packages/eslint-plugin/src/rules/naming-convention-utils/schema.ts
- packages/eslint-plugin/src/rules/no-misused-promises.ts
- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/src/rules/require-array-sort-compare.ts
- packages/eslint-plugin/src/rules/restrict-template-expressions.ts
- packages/eslint-plugin/src/rules/sort-type-constituents.ts
- packages/eslint-plugin/src/rules/typedef.ts
- packages/eslint-plugin/tests/schema-snapshots/array-type.shot
- packages/eslint-plugin/tests/schema-snapshots/ban-ts-comment.shot
- packages/eslint-plugin/tests/schema-snapshots/naming-convention.shot
- packages/eslint-plugin/tests/schema-snapshots/no-misused-promises.shot
- packages/eslint-plugin/tests/schema-snapshots/no-unnecessary-type-assertion.shot
- packages/eslint-plugin/tests/schema-snapshots/require-array-sort-compare.shot
- packages/eslint-plugin/tests/schema-snapshots/restrict-template-expressions.shot
- packages/eslint-plugin/tests/schema-snapshots/sort-type-constituents.shot
- packages/eslint-plugin/tests/schema-snapshots/typedef.shot
- packages/rule-schema-to-typescript-types/src/generateObjectType.ts
@domdomegg's #6894 made me realise I'd incorrectly handled this case in the schema gen.
When it's missing/`undefined` it's the same as being `true` - but I treated it as `false`
> fix: correct handling of additionalProperties in object schemas

- packages/website/src/components/lib/jsonSchema.ts
while rewriting schema assign `$defs` if present in first array item to new item
this is a side effect fix for recent changes (#6899) done to rule schemas
> chore(website): correct issue with rule schema defs

- packages/eslint-plugin/src/rules/unified-signatures.ts
- packages/eslint-plugin/tests/rules/unified-signatures.test.ts
Add guard clause because b.params[i].type is not accessible when comparing to a function with no parameters
> fix(eslint-plugin): [unified-signatures] no parameters function

- docs/Getting_Started.mdx
Applies the suggested reorder, and also mentions `root: true` (since it wasn't before).
cc @jutanium - would love your eyes on this too if you have time! 😄
> docs: reorder Details & Next Steps in Getting Started

- packages/eslint-plugin/docs/rules/no-unnecessary-boolean-literal-compare.md
add missing ! (...) around comparison cases in no-unnecessary-boolean-literal-compare fixer
> docs: add missing ! (...) around comparison cases in no-unnecessary-boolean-literal-compare fixer

- package.json
- packages/utils/tests/eslint-utils/nullThrows.test.ts
- yarn.lock
Brings in the `console-fail-test` fix here.
> chore: bump console-fail-test to 0.2.3

- packages/eslint-plugin/docs/rules/ban-types.md
- Update the _Default Options_ documentation of the [ban-types](https://typescript-eslint.io/rules/ban-types) rule.  
- Documents the `suggest` option.
This was missed in #6876.
> docs: [ban-types] update documentation; suggest option and defaults

- .github/DISCUSSION_TEMPLATE/rfcs.yml
- .github/DISCUSSION_TEMPLATE/technical-discussions.yml
Addresses #7058 by adding the new checkbox to the existing `rfcs.yml` template. Then also uses a similar template for `technical-discussions.yml`.
> docs: fleshed out RFC and Technical Discussions forms

- packages/eslint-plugin/docs/rules/sort-type-constituents.md
Noticed that the string literals in the "Correct" example weren't sorted so I ran the example code through the playground and it resulted in the changes in this PR.
Preview: https://deploy-preview-7050--typescript-eslint.netlify.app/rules/sort-type-constituents/#examples
> docs(eslint-plugin): update correct code example for sort-type-constituents

- docs/contributing/Pull_Requests.mdx
Preview: https://deploy-preview-7051--typescript-eslint.netlify.app/contributing/pull-requests#raising-a-pr
Got tripped when I named my previous PR with a capitalized subject
> docs: update PR title subject example

- docs/maintenance/Pull_Requests.mdx
Added a suggestion section in the pull request docs with a section in adding gifs to PR reviews. I wasn't sure if I should add a new section called suggestions or put it below the first section. I was worried that the first section might become too verbose and that it might be better to break it up this way. I can definitely change/switch it to however is best though, no worries. Just wanted to say that I thought this was a great idea. Adding gifs to PR reviews can really make a difference, imho.
> docs: add a section suggesting gifs for pr reviews

- packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md
Updates "Correct" version to match "Incorrect" version of empty function that expects nothing and returns a string (The "Correct" version was expecting a string and returning a concatenated string)
> docs: correct explicit-module-boundary-types correct case

- .github/workflows/prettier-update.yml
If a prettier update causes formatting to change (which it usually does) then right now a maintainer has to manually update the relevant renovate PR by running `yarn format` locally and committing the results.
After this PR goes in, that `yarn format` and commit step will be done automatically on the PR without any maintainer involvement
> chore: add workflow to automatically run prettier when renovate updates it

- packages/eslint-plugin/docs/rules/restrict-plus-operands.md
- packages/eslint-plugin/src/rules/restrict-plus-operands.ts
- packages/eslint-plugin/tests/rules/restrict-plus-operands.test.ts
- packages/eslint-plugin/tests/schema-snapshots/restrict-plus-operands.shot
Renames an option for `restrict-plus-operands`
Renames the option, so that the default state of off means we lint `+=`s.
> feat(eslint-plugin): [restrict-plus-operands] change checkCompoundAssignments to skipCompoundAssignments

- docs/linting/Configurations.mdx
This pr fixes broken links in the configurations section for v6.
The links to the following configs were pointing to the main branch, since `v6` is not merged yet to main, I changed them back to point to `v6`
- strict-type-checked.ts
- stylistic.ts
- strict-type-checked.ts
- recommended-type-checked.ts
- disable-type-checked.ts
> docs: fix broken links v6 docs

- packages/eslint-plugin/src/configs/recommended-type-checked.ts
- packages/eslint-plugin/src/configs/recommended.ts
- packages/eslint-plugin/src/configs/strict-type-checked.ts
- packages/eslint-plugin/src/configs/stylistic-type-checked.ts
- packages/eslint-plugin/src/configs/stylistic.ts
- packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
- packages/eslint-plugin/src/rules/no-explicit-any.ts
- packages/eslint-plugin/src/rules/sort-type-constituents.ts
- packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
- packages/integration-tests/fixtures/recommended-does-not-require-program/index.ts
- packages/integration-tests/tests/__snapshots__/recommended-does-not-require-program.test.ts.snap
- packages/typescript-estree/src/ts-estree/ts-nodes.ts
Applies the suggested config changes from the discussion.
> feat(eslint-plugin): final final config changes for v6

- docs/linting/Typed_Linting.mdx
- packages/eslint-plugin/src/rules/class-literal-property-style.ts
- packages/eslint-plugin/tests/rules/class-literal-property-style.test.ts
This PR changes the fixer for the class literal property style rule in the eslint-plugin package from an autofixer to a suggestion fixer.
> fix(eslint-plugin): replace auto-fix of class literal property style rule with suggestion

- docs/linting/Configurations.mdx
Correct file reference for `stylistic type checked` config in the website/docs.
> docs: correct file reference for stylistic-type-checked

- packages/eslint-plugin/package.json
Remove direct dependency on grapheme-splitter.
N.B. there is still a transitive dependency on grapheme-splitter through `eslint` (this will disappear once eslint is updated past 8.41.0), so this does not actually change the contents of yarn.lock. It does, however, change the built package to no longer require grapheme-splitter.
> chore(deps): remove unnecessary dependency on grapheme-splitter

- packages/eslint-plugin/src/rules/comma-dangle.ts
- packages/eslint-plugin/tests/rules/comma-dangle.test.ts
Reverts `ignore` from `undefined` back to `() => {}`, and adds a test case for the crash. 
Shoutout+thanks to @erik-slovak for reporting in https://github.com/typescript-eslint/typescript-eslint/commit/42fe29f6912361521d551c0f629f06b54919af69#r121427176 & @sharpdressedcodes for pointing out the lack of unit test! 🙌
> fix(eslint-plugin): [comma-dangle] fixed crash from undefined predicate.ignore

- packages/eslint-plugin/docs/rules/no-floating-promises.md
- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
- packages/eslint-plugin/tests/schema-snapshots/no-floating-promises.shot
In no-floating-promises, the presence of an `onRejected` handler for `.then` or `.catch` is one of the valid ways of terminating an expression involving a promise. However, not all values supplied for `onRejected` are actually valid. Namely, anything that is not a function (looking at you, `null` and `undefined`) is simply ignored in EcmaScript. This PR adds validation to the rejection handler to verify that it is actually a function.
In short,
```
Promise.reject().then(() => {}) // previously was invalid, still is invalid
Promise.reject().then(() => {}, undefined) // previously was valid, now is invalid
```
In addition to that narrow issue, I have added the same validation for the `.catch` handler, since the same principles applies.
```
Promise.reject().catch() // previously was invalid, …
```
> fix(eslint-plugin): [no-floating-promises] false negative calling .then with second argument undefined

- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
The existing implementation treats `.finally` as though it can account for a rejected promise. It cannot prevent rejection. This PR implements the change recommended in the discussion for this issue, namely, to make `.finally` transparent to the rule and check whatever comes before it.
```
Promise.reject().finally(() => {}) // was ok, now an error
Promise.reject().catch(() => {}).finally(() => {}).finally(() => {}) // was ok - still ok
```
Note - this will have conflicts with https://github.com/typescript-eslint/typescript-eslint/pull/6881. It would be simpler to merge that PR first and then deal with the conflicts here.
> fix(eslint-plugin): [no-floating-promises] finally should be transparent to unhandled promises

- packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
Fixes the relativity issue more surgically than a full revert (#7251).
Co-authored-by: @bradzacher
> fix(typescript-estree): remove ts.sys watch program override

- packages/type-utils/tests/TypeOrValueSpecifier.test.ts
Reverts changes to `TypeOrValueSpecifier.test.ts` that were broken by #7252. @bradzacher had actually questioned them in the PR. So, great - looks like we do have test coverage for the current directory after all (accidentally).
> chore(type-utils): fixed TypeOrValueSpecifier tests relativity

- jest.config.base.js
- packages/eslint-plugin/package.json
Set worker memory limit, so CI does not run out of memory while running them.
> chore: use workerIdleMemoryLimit in jest tests

- packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
- packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
The edge case: the type of left side can be explicitly `null` or `undefined`. Then there will be no `types` property and `type` can't be treated as `ts.UnionOrIntersectionType`
> fix(eslint-plugin): [prefer-nullish-coalescing] handle case when type of left side is null or undefined

- packages/eslint-plugin/rules.d.ts
We have `skipLibCheck` turned on so we never got errors for this :sadge: (`skipLibCheck` means "do not check any `.d.ts` files)
> fix(eslint-plugin): use a default export for the rules type

- packages/typescript-estree/src/ts-estree/ts-nodes.ts
Found this when upgrading an internal codebase that's on TS4.9
Also realised we forgot to clean this up with the v6 min version bump!
> fix(typescript-estree): fix TSNode type error on old ts versions

- docs/developers/Custom_Rules.mdx
This PR fixes a typo that causes the ["Typed Rules" example on the "Custom Rules" doc page](https://typescript-eslint.io/developers/custom-rules#typed-rules) not to typecheck.
> docs: fix typo in Custom Rules doc page

- packages/eslint-plugin/docs/rules/no-floating-promises.md
Add await keyword in correct example
https://typescript-eslint.io/rules/no-floating-promises/#examples
The sample that was supposed to be correct was not actually the correct code.  
It appears that await is required.
(translated by DeepL)
Link: [https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=MYew...](https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=MYewdgzgLgBAlmUAnJBTYsC8MCGECeiMAFAJQyYB8MA3gFAwyiSwAOSIAtnBKhTGFQB3GAAUO3XsWJoIIADYA3VABoYaAFboo5KutRylqYgHJFOeQFdUJ0qQDcDGOy49Ujp3kLAYAM0uIUHDg%2BlCWSJDirlLk9IyMaGERMGYW1iaOjAC%2BTonhkRJuZAB0UAAWqGDSutQ0MFkOdE5RkqjFmtqm5lY2pMXAOFDAZWQejC1u7ahaGF1pvcW%2BCBby%2BKN0WR7M0EwgKNr8XkRkFLVO22yFvPyCIhNSMgYKymodGDX6hspzPbaNjDghDg4Jdou4mgCCER-IFgmBQvkIPdjLEnAlUEl4alfpl6rkMYjkSVypViGiSB86lkVOSTnoqTTGI1mlc2m8oD90n0BkMRnTavVme …
> docs: add await keyword in correct example of no-floating-promises.md

- docs/linting/Typed_Linting.mdx
1. I have checked that both `recommended-type-checked` and `recommended + recommended-type-checked` have same configs in the following ways
- `npx eslint --print-config target-path | jq .rules` # v6.1.0
- https://github.com/typescript-eslint/typescript-eslint/blob/9105011681514372a7e851768d83a603fa19e8f2/packages/eslint-plugin/tools/generate-configs.ts#L230-L241
2. So I created this PR because I understood that merging redundant configs is a recommended way since v6.
<details>
<summary>
rendering diff in `yarn nx run website:build && yarn start`
</summary>
Before
---
After
---
</details>
NOTE
---
- [failed CI](https://github.com/typescript-eslint/typescript-eslint/actions/runs/5631010460/job/15257576226) looks related to https://github.com/typescript-eslint/typescript-eslint/issues/7168
> docs: remove redundant configurations in `recommended` with `recommended-type-checked`

- docs/contributing/Local_Development.mdx
I ended up filing this under _Local Development_ instead of _Pull Requests_ as the latter has dealt mostly with the PR itself.
> docs: mention granular unit tests preference under Local Development

- docs/users/Versioning.mdx
- packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
Just a quick fix. In the future this should be handled appropriately as described here: https://github.com/typescript-eslint/typescript-eslint/issues/6389
> docs: update info about the supported TypeScript version range

- .eslintrc.js
- packages/eslint-plugin/src/rules/consistent-type-imports.ts
- packages/eslint-plugin/src/rules/indent.ts
- packages/eslint-plugin/src/rules/key-spacing.ts
- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/eslint-plugin/src/rules/no-shadow.ts
- packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts
- packages/eslint-plugin/src/rules/prefer-optional-chain-utils/analyzeChain.ts
- packages/eslint-plugin/src/rules/prefer-optional-chain-utils/gatherLogicalOperands.ts
- packages/eslint-plugin/src/rules/return-await.ts
- packages/eslint-plugin/src/rules/type-annotation-spacing.ts
- packages/eslint-plugin/src/util/misc.ts
- packages/type-utils/src/predicates.ts
- packages/typescript-estree/src/convert.ts
- packages/typescript-estree/src/node-utils.ts
- packages/typescript-estree/src/parseSettings/ExpiringCache.ts
Enables the rule and runs `yarn lint --fix`.
In retrospect, I probably could have labeled the issue as `good first issue`. Ah well.
> chore: enabled no-else-return internally

- packages/eslint-plugin/src/rules/no-inferrable-types.ts
- packages/eslint-plugin/tests/rules/no-inferrable-types.test.ts
`TSParameterProperty` just may contain `AssignmentPattern` in `parameter`
> fix(eslint-plugin): [no-inferrable-types] apply also for parameter properties

- packages/website/tests/index.spec.ts
One of the sponsor's logo is returning 404 (due to rebranding). This ignores that kind of errors in test setup.
Website test will fail on this branch because they fail for all non-maintainers. The same change works in this PR https://github.com/typescript-eslint/typescript-eslint/pull/7247 but submitting this as separate issue which was preferred by maintainers :)
> chore: playwright test: ignore sponsor logo returning 404

- packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
- packages/scope-manager/src/referencer/ClassVisitor.ts
- packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-inner.ts.shot
- packages/scope-manager/tests/fixtures/class/emit-metadata/nested-class-outer.ts.shot
Adds a missing `.decorators` check and updates snapshots.
I tried for a bit to get a `@typescript-eslint/consistent-type-imports` unit test to fail without the change, but couldn't.
> fix(scope-manager): correct decorators(.length) check in ClassVisitor for methods

- docs/packages/Rule_Tester.mdx
Removed `parser: '@typescript-eslint/parser'` from configurations passed to `RuleTester`'s constructor as `'@typescript-eslint/parser'` is already is the default value.
Left untouched since I believe that referencing `parser` explicitly contributes nicely to the examples in this section.
> docs: remove redundant `parser` property from examples

- docs/packages/Parser.mdx
I've updated the _TIP_ on the parser package [documentation page](https://typescript-eslint.io/packages/parser). It now points to the correct sidebar in [typescript-eslint _playground_](https://typescript-eslint.io/play#showAST=es)
_TIP_
_playground_
> docs: tip should point to the right sidebar in playground

- docs/packages/Parser.mdx
Provides a summary of how to use the option, why it's promising, and a back-link to #6754.
> docs: mention EXPERIMENTAL_useProjectService in parser package docs

- docs/contributing/Issues.mdx
- docs/contributing/Pull_Requests.mdx
This was a little tricky because our contributing guide isn't one long page. It's separated into multiple pages. I figured folks will generally need to read through at least the issues and/or PR pages.
> docs: add 'include an emoji' note in contributing guides

- docs/linting/Configurations.mdx
Adds a "`Contains +`" before each of the four configs that are supersets of others.
Aside: @sajikix's https://zenn.dev/cybozu_frontend/articles/ts-eslint-v6-guide has a really great visualization of the configs. 😄 
cc @marekdedic
> docs: include 'Contains' notes in recommended configs docs

- packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md
- packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
- packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
- packages/eslint-plugin/tests/schema-snapshots/prefer-nullish-coalescing.shot
Not sure if I need to add an invalid tests case for such a change
> feat(eslint-plugin): [prefer-nullish-coalescing] allow `ignorePrimitives` option to be `true`

- packages/eslint-plugin/package.json
- yarn.lock
Reverts typescript-eslint/typescript-eslint#7422
In `packages/eslint-plugin/tests/docs.test.ts`:
```plaintext
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("marked")' call instead.
To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.ts(1479)
module "/Users/josh/repos/typescript-eslint/node_modules/marked/lib/marked"
```
> Revert "chore(deps): update dependency marked to v6"

- .github/workflows/ci.yml
I think this is actually the only generation script we particularly need in CI?
> chore: run yarn generate-configs in CI

- packages/eslint-plugin/package.json
- yarn.lock
[natural-compare-lite](https://www.npmjs.com/package/natural-compare-lite) and [natural-compare](https://www.npmjs.com/package/natural-compare-lite) are two identical packages on the npm (They have the same tarball sha256).
`@typescript-eslint/eslint-plugin` has both `natural-compare` and `natural-compare-lite` in the `package.json`'s `dependencies`, but only `natural-compare` is actually used:
The PR removes the unused `natural-compare-lite`.
> chore(eslint-plugin): remove unused `natural-compare-lite` from dependencies

- docs/linting/Configurations.mdx
Explanation of `stylistic-type-checked` in section `Recommended Configurations` refers to `strict` instead of `stylistic`.
> docs: fix wrong explanation in `Configurations.mdx`

- packages/utils/src/ts-eslint/Rule.ts
Removes `@deprecated` tags, suggested by @bradzacher
> fix(utils): remove deprecate tag added in #7460

- .github/workflows/semantic-pr-titles.yml
In version 6.0, a new rule-tester package was added.
It's worth adding this scope to the commit validator. My other PR crashed with an error because of it:
https://github.com/typescript-eslint/typescript-eslint/pull/7467
> chore: add rule-tester commit scope

- .github/workflows/prettier-update.yml
There are two issues in this workflow:
1) By default `actions/checkout@v3` switches to detached HEAD, we need to explicitly specify `ref: ${{ github.event.pull_request.head.ref }}`
https://github.com/actions/checkout/issues/317#issuecomment-737107262
2) `actions/checkout@v3` sets `http.https://github.com/.extraheader=AUTHORIZATION: basic ***` in the git config. This prevents workflow to push to remote using `$GITHUB_TOKEN`. 
https://github.com/actions/checkout/issues/162
`persist-credentials: false` is designed to turn off this behavior
> chore: properly checkout repo in prettier-update workflow

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
This PR fixes false positives in rule `no-unnecessary-condition` caused by branded types, as described in #7293. 
Note: #7293 only talks about branded strings, but I noticed that the problem occurred for any type.
> Please include your favorite emoji at the bottom of your pull request to hint to us that you did in fact read this file.
💩
> fix(eslint-plugin): [no-unnecessary-condition] false positives with branded types

- packages/rule-tester/src/RuleTester.ts
- packages/rule-tester/tests/RuleTester.test.ts
In some cases I only need to test for valid or invalid scenarios.
For example, if I want to check that a rule for the ESLint plugin works with different code stylings. Or that a rule does not apply to a certain file extension.
Example:
```ts
ruleTester.run(
`${RULE_NAME}: works consistently with an empty array or an array with one element`,
rule,
{
valid: ['[].includes(person)', "['Decim'].includes(bartender)"],
invalid: [],
},
)
```
This test is currently crashing with an error: `Error: No test found in suite invalid`
> feat(rule-tester): allow to create empty tests

- docs/contributing/Pull_Requests.mdx
Added a part in the pull requests page to not comment in PRs that has been closed and instead to file a new issue.
> docs: add in the pull request file to not comment in closed prs

- packages/website/src/components/OptionsSelector.tsx
- packages/website/src/components/inputs/CopyButton.tsx
- packages/website/src/components/inputs/Text.module.css
- packages/website/src/components/inputs/Text.tsx
- packages/website/src/icons/check.svg
- packages/website/src/icons/close.svg
- packages/website/src/icons/copy.svg
- packages/website/src/icons/delete.svg
- packages/website/src/icons/search.svg
Reuse svgs now exported by docusaurus instead of providing copy.
Update search bar to reuse icon used in header and correct its color in dark mode.
ref facebook/docusaurus#8862
> chore(website): reuse svgs from docusaurus

- packages/ast-spec/src/jsx/JSXNamespacedName/fixtures/component-dashed/fixture.tsx
- packages/ast-spec/src/jsx/JSXNamespacedName/fixtures/component-dashed/snapshots/1-TSESTree-AST.shot
- packages/ast-spec/src/jsx/JSXNamespacedName/fixtures/component-dashed/snapshots/2-TSESTree-Tokens.shot
- packages/ast-spec/src/jsx/JSXNamespacedName/fixtures/component-dashed/snapshots/3-Babel-AST.shot
- packages/ast-spec/src/jsx/JSXNamespacedName/fixtures/component-dashed/snapshots/4-Babel-Tokens.shot
- packages/ast-spec/src/jsx/JSXNamespacedName/fixtures/component-dashed/snapshots/5-AST-Alignment-AST.shot
- packages/ast-spec/src/jsx/JSXNamespacedName/fixtures/component-dashed/snapshots/6-AST-Alignment-Tokens.shot
- packages/ast-spec/tests/fixtures.test.ts
- packages/ast-spec/tsconfig.json
- exclude tsx files from type-check
- allow tests to be executed on windows
> chore(ast-spec): exclude tsx fixtures from type-check

- packages/eslint-plugin/src/rules/no-restricted-imports.ts
- packages/eslint-plugin/tests/rules/no-restricted-imports.test.ts
Fixes #7559 by changing the logic from #7379 from "allow imports if all specifiers are types (or if no specifiers exist)" to "allow imports if specifiers exist and all specifiers are types."
✨
> fix(eslint-plugin): [no-restricted-imports] disallow side effect imports when allowTypeImports is enabled

- packages/eslint-plugin/src/rules/await-thenable.ts
- packages/eslint-plugin/tests/rules/await-thenable.test.ts
Adds a `suggestion` fixer to remove `await` from the beginning of the AwaitExpression.
While I was in the area, split up the `invalid` test cases (#6887).
> feat(eslint-plugin): [await-thenable] added suggestion fixer

- .github/renovate.json5
I updated the jest config to match the babel config, as suggested here: https://github.com/typescript-eslint/typescript-eslint/issues/7537#issuecomment-1693273153
> chore: group jest versions in renovate config

- packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md
The examples for the `ignorePrimitives` option were flipped. Setting `ignorePrimitives` to true means that any logical OR expression with a primitive operand is ignored by the lint rule.
I also made two other edits to this docs page. The first is to change "you can safely replace" to "you may consider replacing" in the lint rule's description. The reason for this change is that this lint rule suggests changes that alter the code's behavior in subtle cases where `x || y !== x ?? y`. My interpretation of "safe" for lint suggestions is they don't change the behavior of the code, please let me know if this expectation isn't correct!
There is also a small change to reword the tense in one of the sentences to help it read more smoothly.
> docs(eslint-plugin): fix ignorePrimitives examples in prefer-nullish-coalescing docs

- packages/website/package.json
- packages/website/project.json
Uses an Nx target so that we can indicate it depends on `website-eslint`'s `build`.
Locally it seemed to run build for other packages - which is probably good? To make sure they're up-to-date for `website-eslint`?
> chore(website): have start depend on website-eslint:build

- docs/linting/troubleshooting/Formatting.mdx
- docs/linting/troubleshooting/Performance.mdx
- package.json
Adds a bit of explanation around the difference between the _config_ and _plugin_.
> docs: recommend against eslint-plugin-prettier in formatting guide

- packages/utils/src/eslint-utils/RuleCreator.ts
Reproduction: https://github.com/antfu/repro-ts-eslint-utils-dts - fails on both tsup and unbuild
Reproduction with patch: https://github.com/antfu/repro-ts-eslint-utils-dts/tree/patched (the `patched` branch) - both tsup and unbuild work correctly and generated the following dts:
```ts
import { ESLintUtils } from '@typescript-eslint/utils';
declare const _default: ESLintUtils.RuleModule<"missingIfNewline", [], ESLintUtils.RuleListener>;
export { _default as default };
```
> fix(utils): type portability with `RuleCreator`, fix #7605

- packages/eslint-plugin/docs/rules/prefer-optional-chain.md
…odifyTheReturnTypeIKnowWhatImDoing in prefer-optional-chain
The example for the option allowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing seems like a copy-paste error, which has two equal lines calling `acceptsBoolean`. The second line should be using optional chain.
> docs: fix prefer-optional-chain example for the unsafe fixes option

- packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
- packages/eslint-plugin/tests/rules/prefer-string-starts-ends-with.test.ts
Avoids reporting `slice`/`substring` where the sliced range does not match the expected substring's. This may lead to false negatives, but is "safe" in the general sense.
> fix(eslint-plugin): [prefer-string-starts-ends-with] only report slice/substring with correct range

- packages/eslint-plugin/docs/rules/explicit-function-return-type.md
Fix typo in docs for rule: `explicit-function-return-type` as per [source](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/rules/explicit-function-return-type.ts#L20C5-L20C15)
> docs(eslint-plugin): [explicit-function-return-type] fix typo in option name

- .github/ISSUE_TEMPLATE/config.yml
IDK if this is the best as it adds more noise
But people can't easily find these options right now without jumping through some hoops.
> chore: add discord and stackoverflow as links to issue template

- docs/contributing/Local_Development.mdx
- [-] Addresses an existing open issue: fixes #000
- [-] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
Fixes typo
> docs: fix "Alternatively" typo

- packages/eslint-plugin/src/rules/no-useless-empty-export.ts
- packages/eslint-plugin/tests/rules/no-useless-empty-export.test.ts
> fix(eslint-plugin): [no-useless-empty-export] exempt .d.ts

- packages/eslint-plugin/src/rules/no-shadow.ts
- packages/eslint-plugin/tests/rules/no-shadow/no-shadow.test.ts
This PR adds an extra check for whether the parent of a type parameter declaration is a Class Expression
> fix(eslint-plugin): [no-shadow] fix static class generics for class expressions

- packages/eslint-plugin/src/rules/consistent-type-imports.ts
- packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
Added type assertion for json files
&nbsp;
This PR addresses the issue where `typescript-eslint/eslint-plugin` throws an error when an import statement with type imports includes an import assertions.
``` typescript
import * as aJson from './a.json' assert { type: 'json' }
const what: aJson.A;
```
`typescript-eslint` provides an invalid TypeScript code as a fix and hence had to be addressed by adding a rule that checks for such import type assertions.
Since typescript 4.5, import assertions are supported, so `No Error` or `All is Ok` is the expected output.
&nbsp;
1. Modified rule in `consistent-type-imports.ts` for type only import. Now it checks for absence of assertions and only then suggests the fix.
``` typescript
// checks for presence of import assertions
if (node.assertions.length …
```
> fix(eslint-plugin): [consistent-type-imports] import assertion checks added

- packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
- packages/eslint-plugin/tests/rules/no-confusing-void-expression.test.ts
This change will prevent autofixes in certain cases. Before the change, it worked like this
```ts
const f = function () {
let num = 1;
return num ? console.log('foo') : num;
};
// after fix
const f = function () {
let num = 1;
num ? console.log('foo') : num;
};
```
I changed to not apply fix to node which can be conditionally void.
```ts
let num = 1;
const foo = () => num ? console.log('foo') : num;
const f = function () {
let num = 1;
return num ? console.log('foo') : num;
};
```
> fix(eslint-plugin): [no-confusing-void-expression] handle unfixable cases

- packages/eslint-plugin/docs/rules/naming-convention.md
- packages/eslint-plugin/src/rules/naming-convention-utils/enums.ts
- packages/eslint-plugin/src/rules/naming-convention-utils/schema.ts
- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention/naming-convention.test.ts
- packages/eslint-plugin/tests/schema-snapshots/naming-convention.shot
Currently the `naming-convention` rule cannot be used to enforce conventions on default and namespace imports. This PR introduces that capability by introducing an `import` selector and `default` and `namespace` modifiers.
Named imports are not checked since they have to match the name from the imported file.
> feat(eslint-plugin): [naming-convention] add support for default and namespace imports

- packages/rule-tester/src/RuleTester.ts
The docs at https://typescript-eslint.io/packages/rule-tester/#type-aware-testing show that for type-aware rule testing `parserOptions` needs to be specified. However, like shown in the docs, when `parser` is omitted then an error: "The first argument to require.resolve must be a string. Received null or undefined" is thrown due to a bug in `parser` fallback behavior.
> fix(rule-tester): fix `parser` fallback logic

- packages/eslint-plugin/src/rules/no-unsafe-return.ts
- packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
I'm not sure if we should handle the following case: `const x: () => any = () => [] as any[];`
Overall the docs does not make it clear which cases are exempted, so I guess we have some room for interpretation.
> fix(eslint-plugin): [no-unsafe-return] allow returning anything if explicitly returning any

- packages/eslint-plugin/src/rules/no-unsafe-return.ts
Switches the old namespace import style to a named one.
> chore(eslint-plugin): fix post-merge issue around util namespace import

- docs/developers/Custom_Rules.mdx
Adds a caution to the docs.
I wonder if this is overkill...?
> docs: warn against progressive type enhancement in rules

- .github/workflows/ci.yml
This might help with freeing up some machines of the free github actions tier
> chore: cancel concurrent ci workflow runs

- packages/eslint-plugin/docs/rules/no-unsafe-member-access.md
Update variable declaration from const to let so that code can run. Fixes error: `Cannot assign to 'idx' because it is a constant.`
> docs(eslint-plugin): [no-unsafe-member-access] correct example idx from const to let

- .cspell.json
- packages/eslint-plugin/docs/rules/no-explicit-any.md
Adds a few sentences to the rule's docs and updates the _Further reading_ links. Continuation of #7355, so adding a co-author credit (thanks again for the discussion!).
Co-authored-by: Eric Elliot <support@paralleldrive.com>
> docs: add caveats to no-explicit-any docs

- packages/eslint-plugin/docs/rules/naming-convention.md
- packages/eslint-plugin/src/rules/naming-convention.ts
Adds `'PascalCase'` alongside `'camelCase'` to the allowed formats for imports. This should allow the majority of community standards, such as `import * as React from "react"`.
Funny that out of the >15,000 (!) generated unit tests for this rule, none were impacted by this change to defaults.
> fix(eslint-plugin): [naming-convention] allow PascalCase for imports

- packages/eslint-plugin/src/rules/ban-ts-comment.ts
- packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts
Updates error message and adds a suggestion to replace ts-ignore with ts-expect-error, as long as the option for banning ts-expect-error is not set to true.
> feat(eslint-plugin): [ban-ts-comments] suggest ts-expect-error over ts-ignore

- packages/eslint-plugin/src/rules/require-await.ts
- packages/eslint-plugin/tests/rules/require-await.test.ts
Just set `hasAwait = true` for the current scope where `await using` is used
> fix(eslint-plugin): [require-await] add support for "await using"

- docs/linting/Troubleshooting.mdx
Adds the second suggested strategy for debugging.
cc @Haprog
> docs: mention --trace-deprecation Node flag

- packages/eslint-plugin/docs/rules/restrict-plus-operands.md
Fixed https://github.com/typescript-eslint/typescript-eslint/issues/7867.
> docs: flip the flag of skipCompoundAssignments in the example

- packages/integration-tests/tests/__snapshots__/recommended-does-not-require-program.test.ts.snap
- packages/integration-tests/tests/__snapshots__/vue-sfc.test.ts.snap
Updates snapshots for the latest ESLint version deprecating formatting rules (https://github.com/eslint/eslint/issues/17522).
> chore: fix integration tests for ESLint formatting deprecations

- .github/workflows/a11y-alt-bot.yml
This PR adds a new github action/bot that checks if images in comments in issues, PRs or discussion have an alt text.
The new file is very similar to the file provided at the [original bot repo](https://github.com/github/accessibility-alt-text-bot)
> chore: add a11y-alt-text-check bot

- docs/maintenance/Dependency_Version_Upgrades.mdx
Tried the command today. -W isn't needed in our post-classic versions of Yarn.
Spotted while making #7922.
> docs: remove -W yarn flag in Dependency_Version_Upgrades.mdx

- .cspell.json
- packages/utils/src/ts-eslint/Config.ts
- packages/utils/src/ts-eslint/Linter.ts
This adds the missing fields from #7273
cc @karlhorky
> fix(utils): add missing fields to flat config types

- .github/ISSUE_TEMPLATE/01-bug-report-plugin.yaml
- .github/ISSUE_TEMPLATE/02-enhancement-rule-option.yaml
- .github/ISSUE_TEMPLATE/03-enhancement-new-rule.yaml
- .github/ISSUE_TEMPLATE/04-enhancement-new-base-rule-extension.yaml
- .github/ISSUE_TEMPLATE/05-documentation-request.yml
- .github/ISSUE_TEMPLATE/06-bug-report-other.yaml
- .github/ISSUE_TEMPLATE/07-enhancement-other.yaml
- .github/ISSUE_TEMPLATE/08-bug-report-complex.yaml
- .github/ISSUE_TEMPLATE/09-config-change.yaml
- .github/ISSUE_TEMPLATE/10-repo-maintenance.yaml
Shortens the title names - Security should still be changed, however.
> chore: shorten issue template naming

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
TypeScript's `getIndexInfoOfType` only accepts pure `string` or `number` type, so instead we extract all the index infos and compare their keyType by getting the type name of the key type.
> fix(eslint-plugin): [no-unnecessary-condition] fix false positive with computed member access and branded key type

- packages/eslint-plugin/docs/rules/class-methods-use-this.md
- packages/eslint-plugin/src/rules/class-methods-use-this.ts
- packages/eslint-plugin/tests/rules/class-methods-use-this/class-methods-use-this.test.ts
- packages/eslint-plugin/tests/rules/no-shadow/no-shadow.test.ts
- packages/eslint-plugin/tests/schema-snapshots/class-methods-use-this.shot
This fixes #7704.
TypeScript's interface feature does not have any private/protected member as a part of it.
So the rule `class-methods-use-this` enabling ignoreClassesThatImplementAnInterface=true should warn the case of that the implementation is not a part of interface.
> fix(eslint-plugin): [class-methods-use-this] detect a problematic case for private/protected members if `ignoreClassesThatImplementAnInterface` is set

- packages/website/package.json
- packages/website/src/components/Playground.tsx
- packages/website/src/components/typeDetails/TypesDetails.tsx
- yarn.lock
Reverts typescript-eslint/typescript-eslint#7937. Fixes #7962.
> chore: revert "chore(deps): update dependency react-resizable-panels to ^0.0.57"

- packages/typescript-estree/src/convert.ts
We don't have old TS version regression tests so this is a bit of a "trust me bro".
Manual test steps:
1) checkout branch
1) `yarn && yarn build`
1) copy folder `packages/typescript-estree/dist`
1) open a new folder
1) `yarn add @typescript-eslint/typescript-estree`
1) run `node` and use the repl from the issue (`require('@typescript-eslint/typescript-estree').parse('import json from "./foo.json" assert { type: "json", type: "bar" };').body[0].attributes`) --> observe the broken AST is printed.
1) paste the copied dist folder to `node_modules/@typescript-eslint/typescript-estree/`
1) run `node` and use the repl from the issue --> observe the correct AST is printed.
> fix(typescript-estree): ensure backwards compat with pre-5.3 import attributes

- docs/linting/Troubleshooting.mdx
- the package name crossenv is parked by NPM (https://www.npmjs.com/package/crossenv). cross-env is the intended one
- there's no npm command "lint" (https://docs.npmjs.com/cli/v6/commands)
> docs: fix incorrect example command

- docs/packages/Parser.mdx
- docs/packages/TypeScript_ESTree.mdx
- packages/types/src/parser-options.ts
- packages/typescript-estree/src/create-program/createDefaultProgram.ts
- packages/typescript-estree/src/create-program/createIsolatedProgram.ts
- packages/typescript-estree/src/create-program/createProjectService.ts
- packages/typescript-estree/src/create-program/createSourceFile.ts
- packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
- packages/typescript-estree/src/parseSettings/createParseSettings.ts
- packages/typescript-estree/src/parseSettings/index.ts
- packages/typescript-estree/src/parser-options.ts
- packages/typescript-estree/src/use-at-your-own-risk.ts
- packages/website-eslint/build.ts
- packages/website/src/components/linter/config.ts
In hindsight #7997 was sadly a breaking change.
There's a number of usecases that do rely on accessing JSDoc on the TS AST (eg `eslint-plugin-deprecation`).
This PR amends this change so that:
- we accept the setting via parser options so it's user-configurable.
- we default JSDoc parsing to `all` (which was the pre-5.3 behaviour) for type-aware linting.
- we default JSDoc parsing to `none` for non-type-aware-linting.
- Setting this to `none` by default for this case should provide all non-type-aware-linting users with a free perf boost.
- This is *technically* a breaking change - but the scope should be zero.
- The only usecase this impacts is "accessing JSDoc from the TS AST when not using type-aware linting".
- This usecase is possible - but I don't think it's something anyone would …
> fix: default to parse all JSDoc and provide options to configure it

- .github/ISSUE_TEMPLATE/01-bug-report-plugin.yaml
- .github/ISSUE_TEMPLATE/02-enhancement-rule-option.yaml
- .github/ISSUE_TEMPLATE/03-enhancement-new-rule.yaml
- .github/ISSUE_TEMPLATE/04-enhancement-new-base-rule-extension.yaml
- .github/ISSUE_TEMPLATE/05-documentation-request.yml
- .github/ISSUE_TEMPLATE/06-bug-report-other.yaml
- .github/ISSUE_TEMPLATE/07-enhancement-other.yaml
- .github/ISSUE_TEMPLATE/08-bug-report-complex.yaml
- .github/ISSUE_TEMPLATE/09-config-change.yaml
- .github/ISSUE_TEMPLATE/10-repo-maintenance.yaml
- .github/ISSUE_TEMPLATE/config.yml
Goes mostly with the descriptions suggested in #7856 and applies the removal of before/after from #7818 as suggested there.
Also touches up some markdown that was counted as invalid locally (`typescript` isn't a supported language name; `TypeScript` is).
> chore: streamline issue templates

- packages/website/src/components/RulesTable/index.tsx
Uses slightly smaller text for the biggest button on the page.
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
> chore(website): use less text for type checked filter

- docs/users/Dependency_Versions.mdx
There was a redirect from [`https://nodejs.org/en/about/releases`](https://nodejs.org/en/about/releases) to [`https://github.com/nodejs/release#release-schedule`](https://github.com/nodejs/release#release-schedule)
https://github.com/nodejs/nodejs.org/commit/703d66f70dabb5c4244b82fde65fd52205baff6e#diff-86afba6135d6b52234c22643d9d0395852e262279de5291e3a38b74bd9d0e1d8L31-L34
(Now https://nodejs.org/en/about/releases is 404)
> docs: fix link to Node.js release schedule

- packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
- packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Check also the `PropertyDefinition` nodes, not just the `VariableDeclarator`
> feat(eslint-plugin): [explicit-function-return-type] add support for typed class property definitions

- packages/eslint-plugin/docs/rules/no-throw-literal.md
I just accidentally opened example in the playground and noticed that there is an extra semicolon
> docs(eslint-plugin): [no-throw-literal] fix typo in example

- packages/eslint-plugin/src/rules/no-unsafe-unary-minus.ts
Followup to #7390 since I realized that the error message is wrong.
This PR corrects the error message for the `no-unsafe-unary-minus` rule.
> fix(eslint-plugin): correct message for `no-unsafe-unary-minus`

- docs/contributing/Local_Development.mdx
> docs: fix "are be"

- packages/eslint-plugin/docs/rules/require-array-sort-compare.md
- packages/eslint-plugin/src/rules/require-array-sort-compare.ts
- packages/eslint-plugin/tests/rules/require-array-sort-compare.test.ts
A simple PR that just expands the rule to check for both `sort` and `toSorted` (instead of just checking for `sort`).
For context, when the rule was originally created, `toSorted` didn't exist, as this is a new array method.
> feat: require-array-sort-compare + toSorted

- packages/eslint-plugin/docs/rules/require-array-sort-compare.md
Follow up of https://github.com/typescript-eslint/typescript-eslint/pull/8052
Sync description in docs with actual rule description
---
Without this change, tests fail on `main` branch https://github.com/typescript-eslint/typescript-eslint/actions/runs/7184836345/job/19566920340#step:6:115
> docs(eslint-plugin): [require-array-sort-compare] sync rule description

- packages/eslint-plugin/docs/rules/require-array-sort-compare.md
This is a follow-up to my previous PR to make the docs more consistent, since there are two sort methods now.
> docs(eslint-plugin): [require-array-sort-compare] generalize sort method names

- .lintstagedrc
`.mdx` is not formatted in pre-commit and may cause CI to fail.
> chore: add MDX files to precommit hook

- packages/website/src/theme/CodeBlock/Content/styles.module.css
What good timing that [Firefox supports `:has:` now](https://www.mozilla.org/en-US/firefox/121.0/releasenotes). https://caniuse.com/css-has shows we can use it. This fix was a bit easier for it!
For testing:
* Docs page that doesn't apply min-height: /linting/troubleshooting/performance-troubleshooting#eslint-plugin-prettier
* Rule page that still applies min-height: /rules/array-type
> chore(website): only min-height code blocks with playground buttons

- packages/eslint-plugin/src/rules/block-spacing.ts
- packages/eslint-plugin/src/rules/brace-style.ts
- packages/eslint-plugin/src/rules/comma-dangle.ts
- packages/eslint-plugin/src/rules/comma-spacing.ts
- packages/eslint-plugin/src/rules/func-call-spacing.ts
- packages/eslint-plugin/src/rules/indent.ts
- packages/eslint-plugin/src/rules/key-spacing.ts
- packages/eslint-plugin/src/rules/keyword-spacing.ts
- packages/eslint-plugin/src/rules/lines-around-comment.ts
- packages/eslint-plugin/src/rules/lines-between-class-members.ts
- packages/eslint-plugin/src/rules/member-delimiter-style.ts
- packages/eslint-plugin/src/rules/no-extra-parens.ts
- packages/eslint-plugin/src/rules/object-curly-spacing.ts
- packages/eslint-plugin/src/rules/padding-line-between-statements.ts
- packages/eslint-plugin/src/rules/quotes.ts
- packages/eslint-plugin/src/rules/semi.ts
- packages/eslint-plugin/src/rules/space-before-blocks.ts
- packages/eslint-plugin/src/rules/space-before-function-paren.ts
- packages/eslint-plugin/src/rules/space-infix-ops.ts
- packages/eslint-plugin/src/rules/type-annotation-spacing.ts
- packages/website/blog/2023-12-25-deprecating-formatting-rules.md
- packages/website/plugins/generated-rule-docs/insertions/insertFormattingNotice.ts
Summarizes why we're doing this and links to the ESLint blog post + ESLint Stylistic docs as well.
Also includes a fix to the rule replacements: I'd forgotten `ts/` exists as a separate namespace from `default/`.
> docs(eslint-plugin): add Deprecating Formatting Rules blog post

- .cspell.json
- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/eslint-plugin/tests/rules/unbound-method.test.ts
> fix(eslint-plugin): [unbound-method] exempt all non-Promise built-in statics

- packages/eslint-plugin/docs/rules/no-floating-promises.md
- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
- packages/eslint-plugin/typings/typescript.d.ts
This PR adds functionality to the rule to check for unawaited arrays of promises, where we might expect to use Promise.all/Promise.allSettled, etc to handle the result.
```
async function rejectIn(t: number) {
new Promise<void>((resolve) => {
setTimeout(() => {
resolve();
}, t);
});
throw new Error();
}
// Unhandled rejections. Will now flag.
[1, 2, 3].map(async (t) => {
await rejectIn(t);
});
```
I haven't attempted to add editor suggestions for fixes because the fixes seem rather complicated, depending on how you ended up with an array of promises and what you want to do with it. For example, we might fix the above code with 
```
// should we use Promise.all(), Promise.allSettled(), Promise.race(), etc? 
// it's unclear to me that picking one for the user is a good idea.
// Plus, they …
```
> feat(eslint-plugin): [no-floating-promises] flag result of .map(async)

- packages/eslint-plugin/src/rules/no-restricted-imports.ts
- packages/eslint-plugin/tests/rules/no-restricted-imports.test.ts
- packages/eslint-plugin/typings/eslint-rules.d.ts
Thanks to @mdziekon for investigation made in #8103!
Basically the extension rule didn't check if the base rule returned listeners or not (its typing was wrong, base rule may return empty object https://github.com/eslint/eslint/blob/5aa9c499da48b2d3187270d5d8ece71ad7521f56/lib/rules/no-restricted-imports.js#L192-L195)
> fix(eslint-plugin): [no-restricted-imports] prevent crash when `patterns` or `paths` in options are empty

- packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.md
The CI fails on `main`:
https://github.com/typescript-eslint/typescript-eslint/actions/runs/7358901591/job/20032930191#step:6:205
> docs(eslint-plugin): [switch-exhaustiveness-check] remove extra quotes in rule options headers

- docs/linting/Configurations.mdx
This PR fixes the link to point to the Prettier section of the Formatting page in the Troubleshooting category. The previously referenced 'Suggested Usage' header no longer exists, the closest equivalent is the current 'Suggested Usage - Prettier' header.
> chore: fix configuration link to recommended prettier usage

- tools/release/release.ts
- updates and stages yarn.lock after the versioning step takes place so that it can be auto-committed alongside the other changes
- skips the publishing step entirely if no changes are detected across any package
> chore: release script updates

- packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/fixture.ts
- packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/snapshots/1-TSESTree-AST.shot
- packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/snapshots/2-TSESTree-Tokens.shot
- packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/snapshots/3-Babel-AST.shot
- packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/snapshots/4-Babel-Tokens.shot
- packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/snapshots/5-AST-Alignment-AST.shot
- packages/ast-spec/src/expression/UpdateExpression/fixtures/valid-assignment/snapshots/6-AST-Alignment-Tokens.shot
- packages/typescript-estree/src/node-utils.ts
I tried to report this issue, but the same issue was already created. #8201 doesn't have an accepting PRS label yet, but I'm raising a PR because I think it's definitely a bug and I want it fixed quickly.
> fix(typescript-estree): fix invalid parsing error when use update expression on non-null assertion

- packages/typescript-estree/src/parseSettings/createParseSettings.ts
- packages/typescript-estree/tests/lib/createParseSettings.test.ts
I spent some time trying to investigate #8131's unit test failures. I made a bit of progress and then realized... wait, why is the project service enabled for either of these rules? We don't normally enable `parserOptions.project` for un-typed lint rules. Therefore, I don't think we'd want the presence of the environment variable to enable the project service unless `options.project` was also set.
> fix(typescript-estree): only create project service from env setting if project is enabled

- .github/workflows/a11y-alt-bot.yml
This PR adds a condition for the `accessibility_alt_text_bot` job to prevent the job from running when the username of the user that triggers the workflow ends with "[bot]".
> chore: prevent a11y-alt-text-bot workflow when author is a bot

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
This pr improves unnecessary optional chaining checking of  `no-unnecessary-condition`.
In below example, optional chain in `y()?.` is unnecessary because `y` does not return nullable value.
As described in #7912, the current `no-unnecessary-condition` does not check for the following case.
```ts
type T1 = { y: () => number } | null;
declare const x1: T1;
x1?.y()?.toExponential();
```
I added `isCallExpressionNullableOriginFromCallee` function.
This function takes a CallExpression node as an argument. It returns `true` if the call expression's nullable type is origin from callee otherwise returns `false`.
```ts
// isCallExpressionNullableOriginFromCallee will return true for given call expression `y()`
type T1 = { y: () => number } | null;
declare const x1: T1;
x1?.y()?.toExponential(); …
```
> fix(eslint-plugin): [no-unnecessary-condition] improve checking optional callee

- package.json
- tools/release/release.mts
- yarn.lock
Switches it to `yargs(process.argv.slice(2)` per https://yargs.js.org/docs/#api-reference.
> chore: fix yargs call in release script

- packages/eslint-plugin/docs/rules/no-floating-promises.md
This just tweaks the formatting for a code snippet as it appears on the rule site. 
Addresses https://github.com/typescript-eslint/typescript-eslint/pull/1799/files#r399829282. 
Workaround for https://github.com/prettier/prettier/issues/6608.
> docs: force space after await in no-floating-promises snippet

- .cspell.json
- packages/eslint-plugin/src/rules/no-useless-template-literals.ts
- packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts
> feat(eslint-plugin): [no-useless-template-literals] add fix suggestions

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
> fix(eslint-plugin): [no-unnecessary-type-assertion] detect unnecessary non-null-assertion on a call expression

- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/src/ts-estree/ts-nodes.ts
This doesn't work any better than before.
It fixes the error on >5.3, but it introduces an error on <TS5.3.
> fix(typescript-estree): fix incorrect backwards-compat augmentation in TS 5.3

- nx.json
- packages/integration-tests/tools/integration-test-base.ts
- packages/types/package.json
- Adds the `build` of `eslint-plugin` as a dependency of the lint target
- Configures the `inputs` of lint to take the `.js` files of that dependency into account when hashing for cache hits (https://nx.dev/reference/project-configuration#dependent-tasks-output)
- Also makes the `copy-ast-spec` target cacheable and makes its config more succinct
> chore: make lint use eslint-plugin outputs as inputs

- packages/eslint-plugin/tests/rules/no-unsafe-argument.test.ts
- packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
- packages/type-utils/src/isUnsafeAssignment.ts
- packages/type-utils/tests/isUnsafeAssignment.test.ts
This PR prevents infinite recursive calls to `isUnsafeAssignment` for code with circular references.
`no-unsafe-argument` ( #7298, #5014)
[playground](https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=C4TwDgpgBAKlC8UDaA7ArgWwEYQE4BpYkBdYgbgCgATCAYwBsBDXaAMzRVuAEsB7FKK168AFMABcsAJSSAbr25VKNBs2i1%2BAZ2BQJsShSGjgUykA&eslintrc=N4KABGBEAOCGBOBnApvSAuKABALgT2mUQGN4BLaHAWiIBsyA7HAejiVUgBpwp4BXWkQxhQECJFwEipCtTqMWDAPZU%2BDRLABmyKggDmfALbImwyKnhK0PAL4gbQA&tsconfig=N4XyA&tokens=false)
```ts
type T = [number, T[]];
declare function foo(t: T): void;
declare const t: T;
foo(t);
```
```
RangeError: Maximum call stack size exceeded
...
```
`no-unsafe-assignment` (unreported issue)
[playground](https://typescript-eslint.io/play/#ts=5.1.6&fileType=.tsx&code=C4TwDgpgBAKlC8UDaBnYAnAlgOwOYBpYkBdY …
> fix(type-utils): preventing isUnsafeAssignment infinite recursive calls

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Fix the following false positive cases.
- [demo](https://typescript-eslint.io/play/#ts=5.2.2&showAST=types&fileType=.ts&code=GYVwdgxgLglg9mABMOcA8AVRBTAHlbMAEwGdE4AjAK22gD4AKAKEUQEMAnAcwC5EMANC0QBrbAE8%2BY8XGD8mASj4A3ODCKIA3sIgISURFACMiALztuAbWkBdM%2BbAgANk4DcOvQagAmM4kcu9hZc1hI27qy6YPqGAMx%2BnCG2iACEDs5uHtFeACx%2BAU6p5omh4uFZMVAArAlWyabm4ETYwDBg2EQRiFGVAGx%2BTS1tHUEltl09XgDstUlhRYiDre2dFV4AHAPEQysLY2ETnoYAnLOldg3pLofZhkYADPkZ9sV1B2t3Jq9zZUVXmZEjsZfP8-sFzjdKkZ4t9zi9Fttlh1IV4jHlGojhhpLuDxh9jDVYck0hjmkjVoDbsZ%2BqSdiMSbj3qx9r8APysxAAcjJbGcUE5XRZdnZ5m5LV5Tn5grevwAPrLRTy%2BQKmABfJhAA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRRE0aB2iRwYAL4gtQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eFYDArugDTg10NM8AOXapUAYQAW6aAGsylDt160isA …
> fix(eslint-plugin): [no-unnecessary-condition] fix false positive for type variable

- packages/eslint-plugin/src/rules/no-useless-template-literals.ts
- packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts
> fix(eslint-plugin): [no-useless-template-literals] incorrect bigint autofix result

- docs/linting/troubleshooting/Performance.mdx
I added 2 rules to the page, which are the following:
- `import/no-unresolved`
- `import/unambiguous`
I believe that these are correctly handled by the TypeScript compiler, correct me if I am wrong.
> docs: add `import/no-unresolved` to perf troubleshooting docs

- packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
- packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
https://github.com/typescript-eslint/typescript-eslint/pull/8089 introduced change in the `isNullableType` function. It started treating `any` and `unknown` as nullables, it worked for `no-unnecesary-type-assertion`, but not for `prefer-nullish-coalescing`. `prefer-nullish-coalescing` expects `isNullableType` to return true only for `null` and `undefined`
> fix(eslint-plugin): [prefer-nullish-coalescing] treat any/unknown as non-nullable

- packages/eslint-plugin/src/rules/no-useless-template-literals.ts
- packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts
> fix(eslint-plugin): [no-useless-template-literals] report Infinity & NaN

- packages/eslint-plugin/src/rules/class-methods-use-this.ts
- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/tests/schema-snapshots/class-methods-use-this.shot
- packages/eslint-plugin/tests/schema-snapshots/explicit-module-boundary-types.shot
- [-] Addresses an existing open issue: fixes #000
- [-] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
This fixes typos in the schema definitions.
I've been extracting the schemas from `typescript-eslint` (using [jsonschema-extractor](https://github.com/fox-projects/jsonschema-extractor)), and submitting them upstream to [SchemaStore](https://github.com/SchemaStore/schemastore) to improve autocompletion of `.eslintrc.(json|yml|yaml)` files (at least until people switch to flat config). Typos run into build errors over there.
💖
> chore(eslint-plugin): fix typos in schema definitions

- packages/eslint-plugin/src/rules/prefer-readonly.ts
- packages/eslint-plugin/tests/rules/prefer-readonly.test.ts
Accessors don't support `readonly`, so having `prefer-readonly` apply to them doesn't make sense. The current behaviour also generates an invalid fix, as such this PR simply removes accessors from being considered in the rule.
> fix(eslint-plugin): [prefer-readonly] disable checking accessors

- packages/eslint-plugin/src/rules/no-unused-vars.ts
> chore(eslint-plugin): [no-unused-vars] remove unused nested TSModuleDeclaration rule listener

- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
- packages/scope-manager/src/referencer/ExportVisitor.ts
- packages/scope-manager/src/referencer/Referencer.ts
- packages/scope-manager/tests/fixtures/export/equals1.ts.shot
- packages/scope-manager/tests/fixtures/export/equals3-type.ts
- packages/scope-manager/tests/fixtures/export/equals3-type.ts.shot
Explicitly visit `TSExportAssignment`'s expression, so if it contains some type, that type gets a new reference
> fix(eslint-plugin): [no-unused-vars] don't report on types referenced in export assignment expression

- packages/eslint-plugin/src/rules/class-methods-use-this.ts
- packages/eslint-plugin/src/rules/no-confusing-non-null-assertion.ts
For now, I just manually remove these properties, without checking it on RuleTester level because I can't find a solution to the problem described here https://github.com/typescript-eslint/typescript-eslint/issues/8151#issuecomment-1877330302
> docs(eslint-plugin): remove `fixable` and `hasSuggestions` from rules that don't provide them

- packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
- packages/eslint-plugin/tests/rules/switch-exhaustiveness-check.test.ts
I decided to fix both issues in one pr, because it was really hard to fix the first one without fixing the second.
This PR introduces better support for all combinations of unions, intersections, infinite types. It also fix suggestions more accurate.
In addition, this PR also includes several fixes for bugs that were present on `main` but wasn't mentioned in issues:
Before ([playground](https://typescript-eslint.io/play/#ts=5.3.3&fileType=.ts&code=MYewdgzgLgBAhjAvDAygTwLYCMQBsAUA5HIQJQBQoksWSqmOBhWZ5AJgKbC5wBOHMKtBgA3OLgCuHAFwwoaAA4cQAM3gwAPnMXK1tGOXIQA7gEsowABYx8YyR1IwA3uRiC4EAXFlZ%2BcANYA3OQAvkA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6ZAd0vzIAt6AHrwCGsZPkoA3RExTJafRGQDW6MAG1w2HImjQA9tEhaIAXS0BfEBaA&tsconfig=&tokens=false)):
```diff
const a = Symbol('a')
const b = …
```
> fix(eslint-plugin): [switch-exhaustiveness-check] better support for intersections, infinite types, non-union values

- .github/ISSUE_TEMPLATE/06-bug-report-other.yaml
- .github/ISSUE_TEMPLATE/07-enhancement-other.yaml
- .github/workflows/ci.yml
- .github/workflows/semantic-pr-titles.yml
- package.json
- packages/typescript-eslint/LICENCE
- packages/typescript-eslint/README.md
- packages/typescript-eslint/package.json
- packages/typescript-eslint/project.json
- packages/typescript-eslint/src/index.ts
- packages/typescript-eslint/tsconfig.build.json
- packages/typescript-eslint/tsconfig.json
- yarn.lock
This PR just adds an private scaffold for the `typescript-eslint` package being added in #7935. I've split this out so that the automation will bump the versions with each release.
The most annoying part of the branch is every time I go back to it and rebase it on `main` I have to manually resolve and correct all of the versions or else things will use old releases from npm instead of the repo code.
> chore: add `typescript-eslint` package scaffold

- packages/eslint-plugin/src/rules/consistent-type-imports.ts
- packages/eslint-plugin/tests/rules/consistent-type-imports.test.ts
- packages/scope-manager/src/referencer/ExportVisitor.ts
- packages/scope-manager/src/referencer/Referencer.ts
- packages/scope-manager/tests/fixtures/export/equals4-type.ts
- packages/scope-manager/tests/fixtures/export/equals4-type.ts.shot
I missed that in https://github.com/typescript-eslint/typescript-eslint/pull/8265 :
In cases like `export = {} as T`, T was referenced as `isTypeReference: true` and `isValueReference: true`. Now it's only referenced as a type
> fix(eslint-plugin): [consistent-type-imports] dont report on types used in export assignment expressions

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/fixtures/tsconfig.exactOptionalPropertyTypes.json
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
This PR fixes a false positive issue that occurs when using the exactOptionalPropertyTypes option.
[Playground](https://typescript-eslint.io/play/#ts=4.9.5&fileType=.ts&code=CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPAN7wBGsA-ISgK4C2pIM8AvgNwBQuSAdOcxQoBeeAEY2QA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1tiacTJTIAhtEK0yHJgBNK%2BSpPRRE0aB2iRwYAL4gtQA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoAkNZOgB4CG0euBxTqACprIljwBPACpCBZSnkwBXdABpwEKCWnJWAORmpUAYQAW6aAGtJYaXKUBfEFaA&tokens=false)
tsconfig.json
```json
{
"compilerOptions": {
"exactOptionalPropertyTypes": true,
"strictNullChecks": true
}
}
```
code.ts
```ts
declare const foo: { bar?: number };
foo.bar ??= 1;
```
When the exactOptionalPropertyTypes option is true, typescript removes `undefined` type of the expression …
> fix(eslint-plugin): [no-unnecessary-condition] handle left-hand optional with exactOptionalPropertyTypes option

- packages/eslint-plugin/src/rules/consistent-type-imports.ts
- packages/website/src/components/config/ConfigTypeScript.tsx
- Remove the eslint-disable comment, which was made redundant by the change in #8249.
> chore: remove unnecessary eslint-disable comments

- packages/utils/src/ts-eslint/Config.ts
- packages/utils/src/ts-eslint/Linter.ts
- packages/utils/src/ts-eslint/Parser.ts
- packages/utils/src/ts-eslint/Rule.ts
More splitting out of https://github.com/typescript-eslint/typescript-eslint/pull/7935.
- Loosen parser types in flat configs to allow for non-typescript-estree parsers
- Loosen plugin types to allow for not-yet-updated plugins to be passed to flat configs
- Add some missing features added in newer v8 versions
> feat(utils): improve eslint types

- packages/eslint-plugin/docs/rules/prefer-find.md
- packages/eslint-plugin/src/configs/all.ts
- packages/eslint-plugin/src/configs/disable-type-checked.ts
- packages/eslint-plugin/src/configs/stylistic-type-checked.ts
- packages/eslint-plugin/src/rules/index.ts
- packages/eslint-plugin/src/rules/prefer-find.ts
- packages/eslint-plugin/tests/rules/prefer-find.test.ts
- packages/eslint-plugin/tests/schema-snapshots/prefer-find.shot
- packages/utils/src/eslint-utils/nullThrows.ts
Adds a rule that prefers `arr.find(...)` over `arr.filter(...)[0]`. Also adds the corresponding autofix as suggestions.
> feat(eslint-plugin): add rule prefer-find

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
I think the test cases and comments are a nice overview :)
> fix(eslint-plugin): [no-unnecessary-type-assertion] provide valid fixes for assertions with extra tokens before `as` keyword

- packages/eslint-plugin/src/rules/no-invalid-void-type.ts
This PR fixes the `Options` typing for the `no-invalid-void-type` rule so that it reflects
https://github.com/typescript-eslint/typescript-eslint/blob/70505e45bee0c2b05777a3f9e5b886a1a607d349/packages/eslint-plugin/src/rules/no-invalid-void-type.ts#L51
and also [its documentation](https://typescript-eslint.io/rules/no-invalid-void-type/#options). I think this should be considered an extremely minor typo even though it doesn't involve documentation.
:sweat_smile:
> chore(eslint-plugin): [no-invalid-void-type] fix `Options` typing to reflect `minItems: 1`

- docs/packages/Parser.mdx
- docs/packages/TypeScript_ESTree.mdx
- packages/types/src/parser-options.ts
- packages/typescript-estree/src/parseSettings/getProjectConfigFiles.ts
- packages/typescript-estree/src/parser-options.ts
- packages/typescript-estree/tests/lib/getProjectConfigFiles.test.ts
More splitting out of #7935.
This change allows us to pass `false` to `parserOptions.project`.
This allows us to work-around eslint/eslint#17820 not being in ESLint v8
> feat: allow `parserOptions.project: false`

- docs/linting/Troubleshooting.mdx
Adds a direct FAQ entry explaining why `--cache` is problematic.
> docs: add FAQ entry about ESLint's --cache

- packages/eslint-plugin/docs/rules/explicit-member-accessibility.md
Fix a missing quotation mark in docs
**Update**: The prettier linter made me add some trailing commas to the body. I suspect it didn't need them before b/c it wasn't valid JSON-C before.
> docs: fix missing quotation mark in explicit-member-accessibility.md

- packages/eslint-plugin/src/rules/prefer-find.ts
- packages/eslint-plugin/tests/rules/prefer-find.test.ts
Adds exception handling around Number conversion.
> fix(eslint-plugin): [prefer-find] stop throwing type errors when converting symbols to numbers

- packages/utils/src/eslint-utils/context.ts
Removed these in #8377 - but on second thought removing them is not good *right now*.
Our goal for this next major is that users just bump *our* peer dependencies (typescript and eslint). If we remove these functions then 3rd party plugins might break - meaning a user has to upgrade our peer deps AND 3rd party plugins. This isn't what we want - we want a isolated and painless major!
Adding them back and marking as `@deprecated` so that things keep working for now. We'll remove them in our next major.
> feat(utils): revert removal of backwards-compat functions

- packages/website/plugins/generated-rule-docs/insertions/insertFormattingNotice.ts
This pull request fixes stylistic rules deprecation links by removing the extra `/ts` prefix for redirection links.
> docs: remove /ts prefix from eslint-stylistic replacement rule link

- packages/eslint-plugin/docs/rules/restrict-plus-operands.md
I have removed the example of restrict-plus-operands
I have removed the example of restrict-plus-operands because it seems to be inaccurate and no longer relevant.
> docs: fix restrict-plus-operands example

- docs/packages/TypeScript_ESLint.mdx
- packages/website/blog/2024-02-12-announcing-typescript-eslint-v7.md
- packages/website/docusaurusConfig.ts
Adds a blog post for the v7 release to summarise the changes and announce our new package.
> docs: blog post for v7

- docs/Packages.mdx
This is what I was thinking: to direct people to think of `typescript-eslint` as the main one. And also emphasize the value of the _Getting Started_ page.
> docs: emphasize typescript-eslint in Packages page

- packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
The `defaultOptions` object in the `no-confusing-void-expression` rule documentation is currently empty:
(https://typescript-eslint.io/rules/no-confusing-void-expression/#options)
even though the rule has 2 options. Afaik, this PR makes that `defaultOptions` object explicitly state the options' default values.
Admittedly, I didn't actually generate the website locally, but
https://github.com/typescript-eslint/typescript-eslint/blob/b636baa1972e63f161cef3603d285eba128806d6/packages/website/plugins/generated-rule-docs/insertions/insertNewRuleReferences.ts#L100-L122
strongly suggests this PR will work.
This should be considered as an extremely minor documentation fix, even though changing the documentation actually requires changing code.
💖
----
<a name="update-1">__Update__</a>
I have run …
> chore(eslint-plugin): [no-confusing-void-expression] explicitly state default options in rule doc

- docs/maintenance/Releases.mdx
It's currently displayed as plain text: https://typescript-eslint.io/maintenance/releases
> chore: hide user-facing MDX comment in Releases docs

- docs/Getting_Started.mdx
- docs/linting/Configurations.mdx
- docs/linting/Legacy_ESLint_Setup.mdx
- docs/linting/Typed_Linting.mdx
- docs/linting/typed-linting/Monorepos.mdx
- packages/website/sidebars/sidebar.base.js
Splits _Getting Started_ into two pages:
* The same primary one, now with flat config information
* A new _Legacy ESLint Setup_ with the old information
I'd first tried out using tabs in the one _Getting Started_ page for simplicity, but:
- Nested tabs for configs > package managers were IMO annoying and weird to deal with as a reader
- Some of the explanations were pretty different between the two configs
See also https://github.com/typescript-eslint/typescript-eslint-examples/pull/4 for example projects using the new `typescript-eslint` package with flat config support.
> docs: updated Getting Started and related docs for flat config

- packages/website/src/components/ESQueryFilter.tsx
- packages/website/src/components/Playground.tsx
- packages/website/src/components/hooks/useHashState.ts
- packages/website/src/components/options.ts
- packages/website/src/components/types.ts
Closes #8174
Here us [a working example](https://deploy-preview-8297--typescript-eslint.netlify.app/play/#ts=5.3.3&showAST=es&fileType=.tsx&esQuerySelector=N4IgLgngDgpiBcIDGB7AtlFBXAdgExABoQBnGAGxiTBQCcSEBtUSWBEASzxhzA4DMOMWkRAA3AIbkscRAFkYYABYo8AERiCcHPihwgAvoRbRZICWDC0OAIyxg4xHBLRnJ0mADpWMAAoTaF0VhBgMAXQMgA&code=FAEwpgxgNghgTmABNGBnViDCAeAagPkQG9hFEBbMAFwAsB7EbAFQBpEBVfACgAd4ZyALkRMAlMPYBuUoh5w6PYdgAK3UYgC8hZdIC%2BQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&esQueryFilter=MethodDefinition%5Bvalue.typeParameters%5D&tokens=false)
> feat(website): add ESQuery filter to URL state

- tools/release/changelog-renderer.js
- tsconfig.json
```plaintext
/typescript-eslint/node_modules/nx/src/command-line/release/changelog.js:367
let contents = await changelogRenderer({
^
TypeError: changelogRenderer is not a function
```
I think `nx` might be trying to import the module, but since it's authored like CJS, it's not able to see the `default` export?
If that's not it then it might be a swallowed exception on the Nx side...
> chore: correct nx/(release/)changelog-renderer require path

- packages/eslint-plugin/package.json
- yarn.lock
This is breaking installing the latest plugin version.
> fix(eslint-plugin): update peer dep for parser

- docs/Getting_Started.mdx
Hey! 👋
I noticed a broken link in the "Getting Started" page, specifically in the "Details" section under the recommended configurations link. It was pointing to localhost instead of the correct public domain.
I've updated the link to direct users to the correct destination.
As far as I can tell, there are no open issues related to this, and it's likely that no one has noticed the broken link yet.
This PR resolves the issue and ensures a smoother experience for users navigating the documentation.
Thanks for reviewing! 🚀
> docs: fix broken link in getting started page details section

- docs/Getting_Started.mdx
Hey there! 👋
In the previous update to the link in the "Getting Started" page, it was pointing from the current directory, but it actually needed to go one directory up. My apologies for the mistake.
This PR fixes that issue by adjusting the link appropriately.
Thanks for reviewing! 🚀
> docs: fix invalid relative link in getting started page details section

- packages/utils/src/ts-eslint/Rule.ts
It looks like #3556 got "undone" at some point - its now a `type` which can't be merged with; sadly I only noticed this after the next next major came out so I'll still need to use a type-cast 😞
> feat(utils): use mergeable interface for `settings` property (again)

- docs/maintenance/Issues.mdx
Brad wrote a great explanation here - https://github.com/typescript-eslint/typescript-eslint/issues/8435#issuecomment-1940412549! I've tried to keep the same structure and meaning.
> docs: describe when to use `evaluating community engagement` and `wontfix` labels in Issue Flow

- packages/eslint-plugin/docs/rules/prefer-ts-expect-error.md
Typo in prefer-ts-expect-error docs fixed.
> docs(eslint-plugin): fix typo in prefer-ts-expect-error

- packages/eslint-plugin/docs/rules/no-unused-vars.md
This is a docs PR that details `no-unused-vars` usage that emulates the TypeScript style of exempting where variables are prefixed with `_`.  This grew out of: https://johnnyreilly.com/typescript-eslint-no-unused-vars
The docs preview can be seen here: https://deploy-preview-8526--typescript-eslint.netlify.app/rules/no-unused-vars
> docs: no-unused-vars demonstrate TypeScript style exemptions

- packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md
It'll be `from` instead of `source`. In the playground link warnings are also given. A test link -
https://github.com/typescript-eslint/typescript-eslint/blob/2b98ccd8672069af533002bc10978894b00eb4bc/packages/eslint-plugin/tests/rules/prefer-readonly-parameter-types.test.ts#L406-L419
> docs: from option instead of source in prefer-readonly-parameter-types

- packages/website/src/css/custom.css
> chore(website): properly align underline for children of `<a>` tag

- packages/eslint-plugin/src/rules/no-misused-promises.ts
- packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
Implements the action items detailed in https://github.com/typescript-eslint/typescript-eslint/issues/5744#issuecomment-1947717802.
Only functional change is to add test cases for the concern in the issue.
> test(eslint-plugin): [no-misused-promises] add test cases for spread args

- .github/workflows/ci.yml
- nx.json
- package.json
- packages/typescript-eslint/src/configs/all.ts
- packages/typescript-eslint/src/configs/disable-type-checked.ts
- Fixes an existing issue with stale rule configs
- Updates duplicate CI job names
- Disables the cache for linting eslint-plugin to see if the prettier sync flakiness goes away
> chore: tmp skip cache for eslint-plugin lint

- packages/typescript-eslint/src/config-helper.ts
- packages/typescript-eslint/tests/configs.test.ts
> fix(typescript-eslint): apply `ignores` to all extended configs passed to `config` helper function

- packages/eslint-plugin/src/index.ts
- packages/eslint-plugin/tests/configs.test.ts
- packages/typescript-eslint/src/index.ts
- packages/typescript-eslint/tests/configs.test.ts
This PR is a fix for #8599. I noticed that there were tests for asserting the shape of the different configs, so I extended those tests to account for `*-type-checked-only`.
I opened this PR because I believe we have some timezone differences, and it seemed nicer than just dropping an issue on your lap. If that is the wrong assumption, I apologise 😌 
Please let me know if there is any other information that I can provide!
> fix(eslint-plugin): expose *-type-checked-only configs for extension

- packages/integration-tests/tests/flat-config-types.test.ts
Now that there are no expected errors, removes the snapshot altogether.
> chore: remove now-empty failing flat-config-types integration test snapshot

- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/tests/rules/member-ordering/member-ordering-alphabetically-case-insensitive-order.test.ts
- packages/eslint-plugin/tests/rules/member-ordering/member-ordering-alphabetically-order.test.ts
- packages/eslint-plugin/tests/rules/member-ordering/member-ordering-natural-case-insensitive-order.test.ts
- packages/eslint-plugin/tests/rules/member-ordering/member-ordering-natural-order.test.ts
1. Previously, if a group of MemberType was unsorted, then it was reported ignoring the rest of the MemberTypes, now all of them are reported.
2. Previously, if the MemberTypes weren't in order wrt config, alphabetic sort was avoided, now both takes place.
> fix(eslint-plugin): [member-ordering] report alphabetical sorting for all groups instead of just the first failing group

- packages/eslint-plugin/src/rules/no-useless-template-literals.ts
- packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts
Add detect for TemplateLiteral
> fix(eslint-plugin): [no-useless-template-literals] detect TemplateLiteral

- eslint.config.mjs
- packages/typescript-eslint/src/configs/base.ts
> fix(typescript-eslint): set `sourceType: "module"` in base shared config

- packages/typescript-eslint/src/config-helper.ts
- packages/typescript-eslint/src/index.ts
+1 on https://github.com/typescript-eslint/typescript-eslint/issues/7670
> fix(typescript-eslint): export `ConfigWithExtends` type

- packages/utils/src/ast-utils/eslint-utils/astUtilities.ts
Edit getStaticValue's jsDoc description to know Symbol('k') is not static but Symbol.for('k') is static
> docs(utils): edit getStaticValue function JSDoc description

- packages/eslint-plugin/src/rules/prefer-find.ts
- packages/eslint-plugin/tests/rules/prefer-find.test.ts
Adds support for recursively checking ternary branches.
> fix(eslint-plugin): [prefer-find] support ternary branches in prefer-find

- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/eslint-plugin/tests/rules/unbound-method.test.ts
Just added the same validation to the long form method syntax as already exists for the short form, i.e.
```typescript
{
// this
f: function() {},
// is now scrutinized the same as 
g() {}
}
```
> fix(eslint-plugin): [unbound-method] check method definition in object literal using longhand form

- .github/replies.yml
- docs/maintenance/Pull_Requests.mdx
Fills out PR review flow docs.
I'm sure I missed some important things 😄. What did I miss? 
Co-authored-by: @auvred
> docs: fill out maintenance docs on PR review flow

- packages/eslint-plugin/src/rules/class-literal-property-style.ts
- packages/eslint-plugin/src/rules/prefer-for-of.ts
- packages/eslint-plugin/src/util/index.ts
- packages/eslint-plugin/src/util/isAssignee.ts
- packages/eslint-plugin/tests/rules/class-literal-property-style.test.ts
> fix(eslint-plugin): [class-literal-property-style] ignore property assigned in constructor

- eslint.config.mjs
- packages/eslint-plugin-internal/src/rules/index.ts
- packages/eslint-plugin-internal/src/rules/no-relative-paths-to-internal-packages.ts
- packages/eslint-plugin-internal/tests/rules/no-relative-paths-to-internal-packages.test.ts
Adds internal lint rule to look for flag relative imports that import code from other packages.
Found no existing violations! :)
> feat(eslint-plugin-internal): add internal lint rule no-relative-paths-to-internal-packages

- packages/eslint-plugin/src/rules/prefer-reduce-type-parameter.ts
- packages/eslint-plugin/tests/rules/prefer-reduce-type-parameter.test.ts
> feat(eslint-plugin): [prefer-reduce-type-parameter] supports tuple, union, intersection

- packages/typescript-estree/src/parseSettings/inferSingleRun.ts
Add a check for the eslint bin path in the `inferSingleRun` method within the pnpm repository.
> fix(typescript-estree): fix the issue of single run inferring in the pnpm repo (#3811)

- packages/website/src/components/editor/useSandboxServices.ts
Add eslint-disable-next-line to fix failing Lint with Build CI . (https://github.com/typescript-eslint/typescript-eslint/actions/runs/8327224129/job/22784586006)
> chore(website): disable internal/no-relative-paths-to-internal-packages rule

- packages/eslint-plugin/src/configs/strict-type-checked-only.ts
- packages/eslint-plugin/src/configs/strict-type-checked.ts
- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/repo-tools/src/postinstall.mts
- packages/rule-tester/src/utils/config-validator.ts
- packages/typescript-eslint/src/configs/strict-type-checked-only.ts
- packages/typescript-eslint/src/configs/strict-type-checked.ts
- packages/website/src/hooks/useClipboard.ts
Reverts specifically the part of #8364 that had `no-floating-promises` disable allowing `void` in the `strict-type-checked` config.
> fix(eslint-plugin): [no-floating-promises] revert disable of ignoreVoid in strict config

- packages/website/src/components/Playground.module.css
It seems like a simple task, but if there are any side effects that you might not know about, please let me know!
> fix(website): visual Editor is not scrolled

- packages/typescript-eslint/package.json
- yarn.lock
`typescript-eslint` is currently "naughty" and accesses types from `/utils` via a transitive dependency.
This means that the types we receive depend on how the package manager installs things.
pnpm and npm both do a bad job of installing dependencies in the most sane way (https://github.com/npm/cli/issues/7300) and given the current ecosystem it's possible to get an old major for `/utils` installed at the root instead of v7. This means TS will get the incorrect types for `/utils` and then the config types break.
This adds a hard dep on `/utils` to force the relationship so that all package managers do the same thing and either hoist the `/utils` dependency to the root, or at least ensure that `/utils` is nested within `typescript-eslint`.
I considered making this a peer dep - but …
> fix(typescript-eslint): declare peer dependency on `utils` to ensure npm correctly installs dependencies

- packages/website/src/components/hooks/useHashState.ts
- packages/website/src/pages/play.tsx
The docusaurus's `PendingNavigation` component rendered infinitely when the url hash changed using `useHistory`.
This causes the resize handle to not work as described in the [issue](https://github.com/typescript-eslint/typescript-eslint/issues/8731).
- PendingNavigation: `node_modules/@docusaurus/core/lib/client/PendingNavigation.js`
```ts
history.replace({
...history.location,
hash: writeStateToUrl(newState),
});
```
Here is a performance profile, which recording before and after entering the code in the editor. After entering the code, small tasks continue to come in to the main thread.
I think it's a bug in docusaurus. This PR uses the HTML5 history api to avoid this behavior.
> fix(website): fix infinite rendering when hash changed

- packages/eslint-plugin/docs/rules/restrict-template-expressions.mdx
In the `recommended` config, numbers are allowed, but so are several other types. In the `strict` config, numbers are not allowed (#8364). Either way, "string and number" might not be the right documentation for what's allowed.
N/A - small docs edit
small docs edit
> docs: restrict-template-expressions - remove mention of numbers being allowed

- packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.mdx
Fix typo `It set to` -> `If set to`
> docs: fix typo in switch-exhaustiveness-check

- packages/eslint-plugin/src/rules/prefer-optional-chain-utils/analyzeChain.ts
- packages/eslint-plugin/tests/rules/prefer-optional-chain/prefer-optional-chain.test.ts
Basically the trouble is that the rule checks "am I in a subsequence of logical operands that are candidates for optional chaining that is _more than one unit long_?", assuming that a nullish check will be the first element in that chain and subsequent elements will be chainable expressions. However, a nullish check such as `a !== null && a !== undefined` takes up more than one element in that subsequence, since it is two comparisons. When checking if the length is greater than 1, we get a false positive. 
The code change groups the subsequence so that `a !== null && a !== undefined` get treated as a single unit when checking whether to report.
my brain hurts.
> fix(eslint-plugin): [prefer-optional-chain] address multipart nullish checks false positive

- packages/eslint-plugin/src/rules/prefer-optional-chain-utils/gatherLogicalOperands.ts
- packages/eslint-plugin/tests/rules/prefer-optional-chain/prefer-optional-chain.test.ts
In #8659, we see that [the example in the docs](https://typescript-eslint.io/rules/prefer-optional-chain/#allowpotentiallyunsafefixesthatmodifythereturntypeiknowwhatimdoing) for `prefer-optional-chain`: `allowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing` is not reporting an error.
The root cause is actually _unrelated_ to `allowPotentiallyUnsafeFixesThatModifyTheReturnTypeIKnowWhatImDoing` — it is because `foo.bar` is of type `boolean`.
In the rule, there is a bypass to avoid flagging unions with falsy members, such as
```
declare const foo: { bar: boolean } | boolean | null | undefined;
foo && foo.bar;
```
since changing that to an optional chain would cause a TS error.
However, if the falsy literal is the last operand, then we _should_ report it. This is the change made …
> fix(eslint-plugin): [prefer-optional-chain] properly disambiguate between `boolean` and `false`

- packages/eslint-plugin/docs/rules/unbound-method.mdx
This fixes the  "Correct usage" example of the `unbound-method` rule.
My understanding is that the example tries to show how to bind the correct scope to the method. So the method that should be used is `logUnbound`.
Using `.bind` or an arrow function on `logBound` is useless, as it is already bound with the correct scope.
:sauropod:
> docs: fix example of binding unbound method

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
`no-unnecessary-type-assertion` now avoids to remove `const` casting from template literals when they are containing expressions.
This scenario is handled inside `isConstVariableDeclaration` which has been renamed to `isLiteralVariableDeclarationChangingTypeWithConst` to better reflect its purpose.
Edit: missed appreciation note... sorry
😅
> fix(eslint-plugin): [no-unnecessary-type-assertion] avoid remove const casting on template literals with expressions inside

- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
This PR makes "no-floating-promises" rule to raise error when floating promise is created from a tagged templates, which is essentially a function call in this context.
The motivating example is with [dax](https://github.com/dsherret/dax), which is a popular library to write shell script in TypeScript.
Its `$` API is a tagged template and it returns a Promise (with other methods on it) and we need to `await` on that.
If we forget to `await`, execution orders will be messed up and the main script might exit too early.
After this PR, "no-floating-promises" will be able to capture the mistake in the following snippet:
```typescript
import $ from 'dax-sh'
// Here we are forgetting `await` and , "no-floating-promises" cannot detect it without the PR
$`echo hello`
$`echo world`
```
I added the …
> fix(eslint-plugin): [no-floating-promises] handle TaggedTemplateExpression

- packages/parser/src/parser.ts
- packages/parser/tests/lib/parser.test.ts
This PR overrides the above property to false in `parseForESLint` and adds, modifies relevant test cases.
Continuation of https://github.com/typescript-eslint/typescript-eslint/pull/8684
> fix(parser): disallow `errorOnTypeScriptSyntacticAndSemanticIssues`

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
> fix(eslint-plugin): [no-unnecessary-type-assertion] handle exactOptionalPropertyTypes compiler option

- .github/workflows/ci.yml
This PR disables cancelling in progress workflow runs on `main` branch.
> chore: disable cancelling concurrent workflow runs on main

- docs/contributing/Pull_Requests.mdx
Adds a mention of assigning issues, and updates the search link.
> docs: mention issues being unassigned, not just open

- docs/users/Shared_Configurations.mdx
- packages/website/plugins/generated-rule-docs/insertions/insertNewRuleReferences.ts
Mentions the differences in configs in two ways:
* In the _Shared Configs_ page as plain text
* In relevant rules' docs under _Options_ with two `defaultOptions*` variables
> docs: mention strict configs' stricter default rule options

- packages/typescript-estree/package.json
- yarn.lock
#7752 installed `minimatch` on the estree package but pinned it with no explanation. This results in duplicated dependencies in some projects now that minimatch 9.0.4 is out. This PR fixes it by using `^` in its version, just like every other package.
Note that #7752 was merged in December, and 9.0.3 was the latest minimatch version back then until 9.0.4 was released 6 days ago, so the PR author probably couldn't have found an incompatibility between different patch `minimatch` versions
> chore(typescript-estree): do not pin `minimatch`

- docs/packages/Parser.mdx
- docs/packages/TypeScript_ESTree.mdx
- packages/typescript-estree/src/parser-options.ts
Mentions the `TSESTREE_SINGLE_RUN` in the aforementioned places.
💖
> docs: mention TSESTREE_SINGLE_RUN

- packages/eslint-plugin/docs/rules/member-ordering.mdx
- packages/eslint-plugin/docs/rules/naming-convention.mdx
- packages/eslint-plugin/docs/rules/sort-type-constituents.mdx
Applies a copy & pasted `:::note` to each of their docs.
> docs: feature-freeze member-ordering, naming-convention, sort-type-constituents

- packages/eslint-plugin/docs/rules/consistent-return.mdx
- yarn.lock
I have created an item in the documentation recommending the use of the noImplicitReturns option.
> docs(eslint-plugin): [consistent-return] add warning section use noImplicitReturns instead

- packages/integration-tests/tests/flat-config-types.test.ts
- packages/integration-tests/tools/integration-test-base.ts
- packages/types/src/parser-options.ts
- packages/utils/src/ts-eslint/Config.ts
- packages/utils/src/ts-eslint/Parser.ts
- packages/utils/src/ts-eslint/Processor.ts
- packages/utils/src/ts-eslint/Rule.ts
Support `exactOptionalPropertyTypes: true`
> fix(typescript-eslint): fix type errors when using `exactOptionalPropertyTypes`

- packages/repo-tools/src/generate-configs.mts
- packages/typescript-eslint/src/configs/all.ts
- packages/typescript-eslint/src/configs/base.ts
- packages/typescript-eslint/src/configs/disable-type-checked.ts
- packages/typescript-eslint/src/configs/eslint-recommended.ts
- packages/typescript-eslint/src/configs/recommended-type-checked-only.ts
- packages/typescript-eslint/src/configs/recommended-type-checked.ts
- packages/typescript-eslint/src/configs/recommended.ts
- packages/typescript-eslint/src/configs/strict-type-checked-only.ts
- packages/typescript-eslint/src/configs/strict-type-checked.ts
- packages/typescript-eslint/src/configs/strict.ts
- packages/typescript-eslint/src/configs/stylistic-type-checked-only.ts
- packages/typescript-eslint/src/configs/stylistic-type-checked.ts
- packages/typescript-eslint/src/configs/stylistic.ts
- packages/utils/src/ts-eslint/Config.ts
> feat: add `name` field to shared configs and flat config types

- packages/eslint-plugin/docs/rules/prefer-optional-chain.mdx
Some tab titles in prefer-optional-chain are displaying incorrectly.
as-is
to-be
> docs: fix incorrect tab item values in prefer-optional-chain

- docs/packages/TypeScript_ESTree.mdx
- packages/typescript-estree/src/create-program/createProjectService.ts
- packages/typescript-estree/src/parser-options.ts
- packages/typescript-estree/tests/lib/createProjectService.test.ts
Adds a `defaultProject` property to the existing `ProjectServiceOptions` config object. Folks should be able to use it like:
```js
EXPERIMENTAL_useProjectService: {
allowDefaultProjectForFiles: ["./*.js"],
defaultProject: "./tsconfig.json"
}
```
~...except, I can't find an API to use the default project in the project service. Filing as a draft for reference while I ask about it.~ Chatted with @jakebailey and @sandersn [in the TypeScript Discord](https://discord.com/channels/508357248330760243/640177429775777792/1224400225658212492). `service.setCompilerOptionsForInferredProjects` is the right API. Thanks!
❤️‍🔥
> feat(typescript-estree): add defaultProject for project service

- packages/eslint-plugin/src/configs/eslint-recommended-raw.ts
See: 
* https://github.com/typescript-eslint/typescript-eslint/issues/8211#issuecomment-2044654506
* https://github.com/eslint/eslint/issues/17446
ESLint's `no-new-symbol` rule was deprecated and replaced with `no-new-native-nonconstructor`. This PR disables `no-new-native-nonconstructor` instead of disabling `no-new-symbol`.
> feat(eslint-plugin): replace `no-new-symbol` with `no-new-native-nonconstructor`

- docs/users/Shared_Configurations.mdx
Hey, so, I noticed that docs mention a wrong glob in Shared Configs - `*.js` would only match files in root directory, it should instead be `**/*.js` if we want to match all JS files
> docs: fix bad glob in Shared_Configurations.mdx doc

- packages/typescript-estree/src/parseSettings/resolveProjectList.ts
BREAKING CHANGE: Changes the default glob settings for projects.
Enables `dot: true`.
Not sure if this should be a breaking change 🤔 but just to be safe, sending at the `v8` branch.
💖
> fix(typescript-estree): enable dot globs for project by default

- .github/workflows/ci.yml
- docs/maintenance/Releases.mdx
Sets up the `publish_canary_version_v8` job per the guide. Also touches up a couple of small typos in the guide.
> chore: add v8 canary version publishing

- packages/eslint-plugin/src/rules/no-for-in-array.ts
- packages/eslint-plugin/src/util/getForStatementHeadLoc.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-for-in-array.shot
- packages/eslint-plugin/tests/rules/no-for-in-array.test.ts
just reduces the amount of squigglies
```ts
// before
for (const i in array) { console.log(array[i]); }
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
// after
for (const i in array) { console.log(array[i]); }
^^^^^^^^^^^^^^^^^^^^^^
```
> fix(eslint-plugin): [no-for-in-array] refine report location

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
> fix(eslint-plugin): [no-unnecessary-type-assertion] allow non-null assertion for void type

- packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.mdx
- packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
- packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
Changes the default value of a rule's option.
Straightforward change of the default value from `false` to `true`.
I'd considered renaming the option to `checkConditionalTests` so we could avoid having a truthy default... but figured that was a bit more user effort than folks are likely to want. I'd be happy to make that change if requested though.
💖
> feat(eslint-plugin): [prefer-nullish-coalescing] change ignoreConditionalTests default to true

- .cspell.json
- docs/packages/TypeScript_ESTree.mdx
- docs/troubleshooting/FAQ.mdx
- packages/typescript-estree/src/clear-caches.ts
- packages/typescript-estree/src/create-program/createProjectService.ts
- packages/typescript-estree/src/create-program/validateDefaultProjectForFilesGlob.ts
- packages/typescript-estree/src/parser-options.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/src/useProgramFromProjectService.ts
- packages/typescript-estree/tests/lib/persistentParse.test.ts
- packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
- packages/typescript-estree/tests/lib/validateDefaultProjectForFilesGlob.test.ts
- packages/website/src/theme/MDXComponents/HiddenHeading.module.css
- packages/website/src/theme/MDXComponents/HiddenHeading.tsx
- packages/website/src/theme/MDXComponents/index.tsx
Adds the two safety checks for `allowDefaultProjectForFiles` as suggested in the issue:
* A new `maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING` option with a default value of `8`
* A check that `allowDefaultProjectForFiles` doesn't include `**`
* Intentionally allows slightly more permissive matches like `./*.*s`, as that's what I'd expect to be convenient & reasonable alongside the count maximum
Adds an FAQs blog post to explain them.
💖
> feat(typescript-estree): add maximumDefaultProjectFileMatchCount and wide allowDefaultProjectForFiles glob restrictions

- .github/workflows/ci.yml
- docs/maintenance/Releases.mdx
- packages/repo-tools/src/apply-canary-version.mts
~I'm ... not sure which command we should use here 😬 is it ... `nx release`?~ ✅ 
Partially overlaps #8913.
💖
> chore: fix ci.yml canary releases to use nx, not lerna

- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts
Changes the default behavior of a rule.
Roughly applies the same changes from https://github.com/eslint/eslint/pull/17932 and https://github.com/eslint/eslint/pull/18043.
💖
> feat(eslint-plugin): [no-unused-vars] align catch behavior to ESLint 9

- docs/getting-started/Legacy_ESLint_Setup.mdx
- docs/getting-started/Quickstart.mdx
- docs/getting-started/Typed_Linting.mdx
- docs/packages/Parser.mdx
- docs/users/Shared_Configurations.mdx
Adds `### Additional Configs` sections to the flat and legacy config setup guides that mention strict & stylistic, followed by `### Typed Linting` for the existing links to that page.
Applies a bit of streamlining/tightening to the pages to try to offset the added verbosity.
💖
> docs: mention strict and stylistic configs in Getting Started

- packages/utils/src/ts-eslint/ESLint.ts
BREAKING:
Changes the names of exports.
Applies just a quick export name change so importing `ESLint` gives you `FlatESLint`, not `LegacyESLint`.
Also updates the _TODO_ comment to reflect keeping the legacy class around.
💖
> feat(utils): swap LegacyESLint out for FlatESLint as ESLint export

- packages/rule-tester/src/RuleTester.ts
- packages/rule-tester/tests/eslint-base/eslint-base.test.js
- packages/rule-tester/tests/eslint-base/fixtures/suggestions.js
Brings in changes from https://github.com/eslint/eslint/pull/17532. This is pretty much a copy & paste.
> feat(rule-tester): assert suggestion messages are unique

- .github/workflows/ci.yml
- packages/integration-tests/tests/__snapshots__/flat-config-types.test.ts.snap
- packages/integration-tests/tests/__snapshots__/recommended-does-not-require-program.test.ts.snap
- packages/integration-tests/tests/__snapshots__/vue-sfc.test.ts.snap
Ran `yarn test -u` in the package.
> chore: fix v8 branch snapshots for flat-config-types

- packages/eslint-plugin/docs/rules/no-unnecessary-boolean-literal-compare.mdx
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unnecessary-boolean-literal-compare.shot
Add missing `!( ... )` around comparison cases in example for the [`allowComparingNullableBooleansToFalse` option](https://typescript-eslint.io/rules/no-unnecessary-boolean-literal-compare#allowcomparingnullablebooleanstofalse) of the [no-unnecessary-boolean-literal-compare docs](https://typescript-eslint.io/rules/no-unnecessary-boolean-literal-compare).
> docs: fix no-unnecessary-boolean-literal-compare example

- packages/typescript-estree/tests/lib/inferSingleRun.test.ts
add Testcase in typescript-estree's inferSingleRun 
※Apologies, I accidentally deleted the forked repository.  This is being re-created as a duplicate of #8710.
> test(typescript-estree): add unit tests for inferSingleRun function

- packages/typescript-estree/src/create-program/createDefaultProgram.ts
- packages/typescript-estree/src/create-program/createProjectProgram.ts
- packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
- packages/typescript-estree/src/parseSettings/createParseSettings.ts
- packages/typescript-estree/src/parseSettings/index.ts
- packages/typescript-estree/src/parseSettings/resolveProjectList.ts
- packages/typescript-estree/src/parser.ts
- packages/typescript-estree/tests/lib/semanticInfo-singleRun.test.ts
- packages/website/src/components/linter/config.ts
Without this it generates root files with incorrect casing and results in errors with casing with forceConsistentCasingInFileNames which is true by default in newer typescript versions
This came up while i was working on PR https://github.com/microsoft/TypeScript/pull/58398
cc @jakebailey i was able to turn the tsconfig cache into Map and find all places where it needed to be string and was passing canonical file path
> fix: do not pass tsconfig canonical file name to typescript API to get program details for config file

- packages/eslint-plugin/docs/rules/no-duplicate-imports.mdx
This PR fixes a broken link to `import/no-duplicates` on the `no-duplicate-imports` page.
> docs: fix broken link to `import/no-duplicates` on `no-duplicate-imports` page

- docs/developers/Custom_Rules.mdx
- packages/eslint-plugin-internal/src/rules/no-poorly-typed-ts-props.ts
- packages/eslint-plugin-internal/src/rules/no-relative-paths-to-internal-packages.ts
- packages/eslint-plugin-internal/src/rules/no-typescript-default-import.ts
- packages/eslint-plugin-internal/src/rules/no-typescript-estree-import.ts
- packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
- packages/eslint-plugin-internal/src/rules/prefer-ast-types-enum.ts
- packages/eslint-plugin-internal/src/util/createRule.ts
- packages/eslint-plugin/rules.d.ts
- packages/eslint-plugin/src/util/createRule.ts
- packages/eslint-plugin/src/util/getFunctionHeadLoc.ts
- packages/eslint-plugin/tools/generate-breaking-changes.mts
- packages/eslint-plugin/typings/eslint-rules.d.ts
- packages/repo-tools/src/generate-configs.mts
- packages/typescript-eslint/tests/configs.test.ts
- packages/utils/src/eslint-utils/RuleCreator.ts
- packages/utils/src/ts-eslint/Rule.ts
- packages/utils/src/ts-eslint/eslint/ESLintShared.ts
- packages/utils/tests/eslint-utils/RuleCreator.test.ts
- packages/website/plugins/generated-rule-docs/RuleDocsPage.ts
- packages/website/plugins/generated-rule-docs/createRuleDocsPage.ts
- packages/website/plugins/generated-rule-docs/index.ts
- packages/website/plugins/generated-rule-docs/utils.ts
- packages/website/src/components/RulesTable/index.tsx
- packages/website/src/theme/MDXComponents/RuleAttributes.tsx
Changes the default allowed types on custom rule docs.
Adds an optional `PluginDocs` type parameter to `RuleCreator` that allows adding additional properties to `meta.docs`. That allows us to move `extendsBaseRule`, `recommended`, and `requiresTypeChecking` into our own `ESLintPluginDocs` interface so that they're no longer exposed to consumers.
Adds new `RuleModuleWithMetaDocs` and `AnyRuleModuleWithMetaDocs` interfaces so that we can finally get rid of the `?.` after `meta.docs` in some of our internal tooling. And `RuleMetaDataDocs` no longer has an `Options` parameter, which simplifies some other types too.
Adds back in `"layout"` to `meta.type` as it actually is specified in https://eslint.org/docs/latest/extend/custom-rules.
💖
> feat(utils): allow specifying additional rule meta.docs in RuleCreator

- packages/rule-tester/src/RuleTester.ts
- packages/rule-tester/src/utils/interpolate.ts
- packages/rule-tester/tests/eslint-base/eslint-base.test.js
- packages/rule-tester/tests/eslint-base/fixtures/messageId.js
- packages/rule-tester/tests/eslint-base/fixtures/suggestions.js
Brings in changes from https://github.com/eslint/eslint/pull/18073. This is pretty much a copy & paste.
> feat(rule-tester): check for missing placeholder data in the message

- docs/packages/Rule_Tester.mdx
Adds an example of RuleTester with the node:test runner, which uses Node's CLI flags to import the setup file (as there's no equivalent test runner specific flag). The test file will get imported for every test, but that should be fine since we just copy some variables.
> docs: add docs for using rule tester with node:test

- packages/website/plugins/generated-rule-docs/insertions/insertNewRuleReferences.ts
This PR removes the unclosed paren linked [here](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/website/plugins/generated-rule-docs/insertions/insertNewRuleReferences.ts#L175) for links to strict, strict-type-checked anchors.
> docs: fix broken anchor links

- packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
- packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
Adds default parameter check analogous to ordinary assignment.
> fix(eslint-plugin): [explicit-function-return-types] fix false positive on default parameters

- packages/eslint-plugin/package.json
- yarn.lock
Corrects the last `^7.0.0` peer dependency that we'd missed.
💖
> fix: correct eslint-plugin's peerDependency on parser@8

- packages/eslint-plugin/package.json
- yarn.lock
A fix for #9087 was pushed in #9089 to bump the eslint-plugin's peerDependencdy on the parser to `^8.0.0`, but due to how NPM handles SemVer, it does not include pre-releases such as `8.0.0-alpha.11`, causing a "version not found" error if someone tried to install the pre-release plugin (eg on tag `rc-v8`). This PR adds another SemVer constraint to the `@typescript-eslint/parser` peerDependency to include alpha pre-releases as suggested in https://github.com/typescript-eslint/typescript-eslint/pull/9089#discussion_r1600804371
> fix(eslint-plugin): include alpha pre-releases in parser peer dependency

- packages/typescript-estree/src/useProgramFromProjectService.ts
- packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
Only add path to `defaultProjectMatchedFiles` if `opened.configFileName` is falsy.
The fix itself is pretty trivial and existing tests still pass, but I might need some help with adding a new testcase. I tried adapting the existing testcase at https://github.com/typescript-eslint/typescript-eslint/blob/77fc366aa03f3cee1ebcf91a10dc0be8b669520e/packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts#L122 but only succeeded in making *other* tests fail (maybe I mocked a result and then didn't call the function, I'm not sure).
> fix(typescript-estree): don't add in-project files to defaultProjectMatchedFiles

- packages/eslint-plugin/src/rules/prefer-regexp-exec.ts
- packages/eslint-plugin/tests/rules/prefer-regexp-exec.test.ts
Changes the heuristic to say "if we don't know what it is, it could have the global flag". Note that it could also be tricked into falsely flagging on factory functions that return a regexp, since the heuristic inspects the second argument without checking what function it's inspecting. That has been made more strict.
See [examples in the playground](https://typescript-eslint.io/play/#ts=5.4.2&fileType=.tsx&code=CYUwxgNghgTiAEYD2A7AzgF3hkAPDAXPJjAJYoDmA3AFA0D09xGArgGZvYAWCMLECYEhBp4ZCl0J0c%2BAHQBbKBjBcAFPTRck-YPDbQKAGngokWChCQAjKBHoBKWjIwKlK9Zu0RgKAORZ9KCN4UlELa1t6CkdpPBdFZTUAJRAKAFFcAAdVX08dPQNjU3NLGwhfY19fe3saZ1dE1RT0rJy87xQAHX8CoONQ%2BHCyivhfCmramlBIWARkdCx2nwwAMQMAQQA1WFIoKwEiZozMpziG9yWUVY3tsj2BScZuAYGAdx44bgQ2FhR4K1S5DQBDo02gn3mmDEIEOqWOtCeABUeIgoGhvjAkPIviE0GgWCA6mcEu4AN7ELQ6K5rIJET …
> fix(eslint-plugin): [prefer-regexp-exec] fix heuristic to check whether regex may contain global flag

- package.json
- packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/missing-value-in-using/snapshots/2-Babel-Error.shot
- packages/ast-spec/src/declaration/VariableDeclaration/fixtures/_error_/missing-value-in-using/snapshots/3-Alignment-Error.shot
- packages/ast-spec/tests/fixtures-with-differences-errors.shot
- yarn.lock
Deduplicated dependencies, and updated snapshots.
> chore(deps): dedupe dependencies and update test snapshots

- docs/Contributing.mdx
Absolute links open in a new tab. Since these are links to other docs pages, these should be relative links instead which open in the same tab.
I've checked that these are the only absolute links to `typescript-eslint.io`.
> docs: make absolute links relative

- packages/utils/src/ts-eslint/Config.ts
> fix(utils): remove function form type from flat config `files` and `ignores`

- packages/eslint-plugin/src/rules/naming-convention-utils/parse-options.ts
I replaced `map` + `reduce with concat` with single `flatMap`.
> chore(eslint-plugin): replaced map/reduce with flatMap in normalizedOptions in parse

- packages/typescript-estree/src/useProgramFromProjectService.ts
- packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
* fix(typescript-estree): truncate number of files printed
Address issue with size of error string produced causing serialization failure https://github.com/typescript-eslint/typescript-eslint/issues/9124.
* test(typescript-estree): add additional unit test for project service
Additional test for truncated error message.
- (I couldn't reproduce following the steps outlined by https://github.com/typescript-eslint/typescript-eslint/issues/9124#issuecomment-2122986459)
> fix(typescript-estree): truncate number of files printed by the maximum file error

- packages/eslint-plugin/src/rules/consistent-type-assertions.ts
- packages/eslint-plugin/src/util/getOperatorPrecedence.ts
- packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
Upon looking into this bug, I learned that there are a whole host of circumstances where the `<T>(expr)` => `(expr) as T` fix failed to put necessary parens around expr (since it was coded to _never_ put any parens around expr). A generic fix has been added, and test cases from lots of precedence categories.
Also, had to change the precedence pertaining to the `=>` operator to address the specific issue in the bug, bringing the `=>` precedence into agreement with its ranking on MDN. Feels suspicious, but didn't seem to break any test cases.
> fix(eslint-plugin): [consistent-type-assertions] prevent syntax errors on arrow functions

- packages/ast-spec/src/unions/Statement.ts
`EmptyStatement` is part of `Statement` according to ECMAScript - https://262.ecma-international.org/14.0/#prod-Statement
> fix(ast-spec): add `EmptyStatement` to `Statement`

- packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
- [] That issue was marked as [accepting prs](https://github.com/typescript-eslint/typescript-eslint/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
Add missing `output: null` causing lint failure on `main`.
> test(eslint-plugin): [consistent-type-assertions] add missing `output: null` causing lint failure on `main`

- .github/actions/breaking-pr-check/action.yml
- .github/actions/breaking-pr-check/index.js
- .github/workflows/semantic-breaking-change-pr.yml
Add CI that checks breaking change pr title and body.
- Disallows the use of exclamation mark(`!`) in PR title.
- Enforces to write “BREAKING CHANGE:” at the beginning of the PR body if the pr has breaking change label.
> chore: add breaking change pr check ci

- packages/eslint-plugin/docs/rules/prefer-ts-expect-error.mdx
- packages/eslint-plugin/src/configs/all.ts
- packages/eslint-plugin/src/configs/strict-type-checked.ts
- packages/eslint-plugin/src/configs/strict.ts
- packages/eslint-plugin/src/rules/prefer-ts-expect-error.ts
- packages/typescript-eslint/src/configs/all.ts
- packages/typescript-eslint/src/configs/strict-type-checked.ts
- packages/typescript-eslint/src/configs/strict.ts
`prefer-ts-expect-error` is just a subset of `ban-ts-comment` because `ban-ts-comment` also suggests replacing @ts-ignore with @ts-expect-error
> feat(eslint-plugin): deprecate prefer-ts-expect-error in favor of ban-ts-comment

- docs/getting-started/Quickstart.mdx
Without this, I was getting an error `Could not find a declaration file for module '@eslint/js'`. In VS Code, in the following `eslint.config.js` from the Getting Started guide:
```
// @ts-check
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
export default tseslint.config(
eslint.configs.recommended,
...tseslint.configs.recommended,
);
```
> docs: add @types/eslint__js to Quickstart.mdx

- packages/website/blog/2024-05-27-announcing-typescript-eslint-v8-beta.mdx
Small updates to the v8 beta blog post (https://main--typescript-eslint.netlify.app/blog/announcing-typescript-eslint-v8-beta) for things that have developed since it was merged.
> docs: v8 beta blog post updates for new issues and PRs

- .yarn/patches/nx-npm-18.3.5-58c0bedf91.patch
- package.json
- yarn.lock
Thanks to a tip from @JamesHenry, this:
1. Removes the TypeScript registration, as that's what's crashing
2. Fixes the changelog renderer path to work as a direct `require()`
> chore: patch nx changelog to fix releases

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
In #8740, new logic was added for template literals. This logic was wrongly added as a precondition, when it needs to be combined with the existing `const` variable declaration logic.
- Fix failing case from #8819 by re-arranging conditions
- The type assertions in the `valid` tests added in #8740 are actually unnecessary (but are too complex to be detected by the current logic). Changed `const` to `let`, so that the type assertions are truly necessary.
- Improved the name of `isLiteralVariableDeclarationChangingTypeWithConst` to `isImplicitlyNarrowedConstDeclaration`.
> fix(eslint-plugin): [no-unnecessary-type-assertion] combine template literal check with `const` variable check

- packages/eslint-plugin/src/rules/dot-notation.ts
- packages/eslint-plugin/tests/rules/dot-notation.test.ts
fix error when chaning operation is used in member acceess. thanks to #3711, i resolve this problem
additionally, the issue was not refer to protected option, but protected option also make false positive, so fix too.
> fix(eslint-plugin): [dot-notation] fix false positive when accessing private/protected property with optional chaining

- packages/eslint-plugin-internal/tsconfig.json
- packages/scope-manager/tsconfig.spec.json
- tsconfig.base.json
Changed TSConfig to target Node.js 18 since this is the minimal version we support. According to https://node.green/, Node.js 18 fully supports ES2022 and ES2023:
There is a recommended TSConfig for Node.js 18 - https://github.com/tsconfig/bases/blob/main/bases/node18.json and I followed it as a reference.
In another PR, I'm planning to enable ESLint https://eslint.org/docs/latest/rules/prefer-object-has-own rule and fix all related errors.
> chore: use recommended config for Node.js 18 in TSConfig

- packages/eslint-plugin/src/rules/prefer-literal-enum-member.ts
- packages/eslint-plugin/tests/rules/prefer-literal-enum-member.test.ts
> fix(eslint-plugin): [prefer-literal-enum-member] allow using member it self on allowBitwiseExpressions

- packages/eslint-plugin/docs/rules/no-floating-promises.mdx
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-floating-promises.shot
In my experience it is rather common to have legitimate cases to `void` a promise. The current state of the docs led me to believe that this is a "lesser preferred" option and I don't think that should be the case.
> docs(eslint-plugin): [no-floating-promises] make void a more prominent suggestion

- eslint.config.mjs
- packages/eslint-plugin-internal/src/rules/prefer-ast-types-enum.ts
- packages/eslint-plugin-internal/tsconfig.json
- packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts
- packages/eslint-plugin/src/rules/no-restricted-imports.ts
- packages/rule-tester/src/utils/cloneDeeplyExcludesParent.ts
- packages/rule-tester/src/utils/freezeDeeply.ts
- packages/rule-tester/src/utils/hasOwnProperty.ts
- packages/scope-manager/tsconfig.spec.json
- packages/type-utils/src/isTypeReadonly.ts
- packages/typescript-estree/tests/test-utils/test-utils.ts
- tsconfig.base.json
> This PR depends on https://github.com/typescript-eslint/typescript-eslint/pull/9113. See fbeede974a2dd4b0e7b123fc89f934aace7bb8cf...cf9c7ae9a39fbb1e0975719a382c1e7e0423841b for changes.
Enables [`prefer-object-has-own`](https://eslint.org/docs/latest/rules/prefer-object-has-own) ESLint rule and fixes all rule errors.
> chore: enable `prefer-object-has-own` ESLint rule

- packages/typescript-estree/src/parser-options.ts
- packages/typescript-estree/src/useProgramFromProjectService.ts
- packages/typescript-estree/tests/lib/parse.test.ts
- packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
Uses `setHostConfiguration` to pass `extraFileExtensions` to project service, when using `EXPERIMENTAL_useProjectService`. This fixes an issue where project service would not detect the appropriate tsconfig file when using non-default file extensions.
The tests are checking that the configFilePath is set in the compiler options. If it's not, it's an indication that the default inferred project is used. I duplicated the test cases used for the non-experimental projects option.
> fix(typescript-estree): pass extraFileExtensions to projectService

- docs/getting-started/Quickstart.mdx
Fix a link to the legacy (<9.0.0) config on eslint.org.
eslint.org restructured their site so the legacy config documentation is now at `https://eslint.org/docs/latest/use/configure/configuration-files-deprecated`.
> docs: update link to ESLint legacy config

- packages/rule-tester/src/RuleTester.ts
This was a regression on v8 caused by a merge from main
> fix(rule-tester): set configType to eslintrc in Linter options

- packages/eslint-plugin-internal/tests/rules/plugin-test-formatting.test.ts
- packages/eslint-plugin/tests/rules/no-useless-template-expression.test.ts
- packages/eslint-plugin/tests/rules/no-useless-template-literals.test.ts
- packages/rule-tester/src/RuleTester.ts
- packages/rule-tester/tests/RuleTester.test.ts
Re-applies changes from #8883 - essentially undoing the accidentally reverts I'd applied.
Hooray, long-lived branches! 🙌
> fix(rule-tester): re-apply updates from main

- .github/ISSUE_TEMPLATE/06-bug-report-other.yaml
Adds a quick note as described in the issue.
Also removes the `id` field that my VS Code extension is telling me is disallowed.
💖
> docs: mention needing an isolated repro in bug-report-other.yaml

- docs/maintenance/issues/Rule_Deprecations_And_Deletions.mdx
- packages/website/docusaurus.config.mts
- packages/website/sidebars/sidebar.base.js
Since the processes for deprecations / deletions / renames are pretty overlapped, I just kept them in roughly the same page.
💖
> docs: expand rule deprecation docs to also include renames

- packages/eslint-plugin/docs/rules/sort-type-union-intersection-members.mdx
- packages/eslint-plugin/tests/docs.test.ts
No other rules were nominated, and I didn't see any more deletions in the file history of the `all` configs that needed to be addressed.
💖
> docs: add missing sort-type-union-intersection-members.mdx tombstone page

- docs/packages/ESLint_Plugin.mdx
- docs/packages/ESLint_Plugin_TSLint.mdx
- docs/packages/Parser.mdx
- docs/packages/Rule_Tester.mdx
- docs/packages/Scope_Manager.mdx
- docs/packages/TypeScript_ESLint.mdx
- docs/packages/TypeScript_ESTree.mdx
- docs/packages/Utils.mdx
- packages/website/package.json
- packages/website/src/theme/MDXComponents/PackageLink.module.css
- packages/website/src/theme/MDXComponents/PackageLink.tsx
- packages/website/src/theme/MDXComponents/index.tsx
- yarn.lock
Adds a `PackageLink` component that's then used on all the package docs pages, such as `/packages/utils`. Uses https://uiwjs.github.io/react-shields for the shields themselves.
I'd wanted to use a "self-hosted" version but couldn't find one that worked well. The closest was https://www.npmjs.com/package/badge-maker but it has a runtime dependency on `fs`. Ah well - fodder for a followup.
💖
> docs: add shields.io badges to package pages

- .github/workflows/pr-labels.yml
Combines:
1. https://github.com/marketplace/actions/changed-files: to check whether the stable configs were changed
2. https://github.com/marketplace/actions/require-labels: to require the `breaking change` when any stable config was changed
For an example CI failure, see https://github.com/JoshuaKGoldberg/typescript-eslint/pull/322 -> https://github.com/JoshuaKGoldberg/typescript-eslint/pull/322#issuecomment-2146330650:
> 🤖 Beep boop! PRs that change our stable preset configs must be labeled with breaking change.
💖
> chore: ensure 'breaking change' label for PRs that touch stable configs

- packages/website/src/components/editor/useSandboxServices.ts
Enables the `acquireTypes` option as @armano2 suggested in https://github.com/typescript-eslint/typescript-eslint/issues/8696#issuecomment-2054126062. It doesn't enable preview work or better font family for the side view - that seems like ... a lot more work, which IMO would be fine as a followup.
💖
> docs(website): enable automatic types acqusition (ATA) in the playground

- packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-2/fixture.ts
- packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-2/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-2/snapshots/2-Babel-Error.shot
- packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-2/snapshots/3-Alignment-Error.shot
- packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-3/fixture.ts
- packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-3/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-3/snapshots/2-Babel-Error.shot
- packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string-3/snapshots/3-Alignment-Error.shot
- packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/declaration/TSImportEqualsDeclaration/fixtures/_error_/external-module-ref-non-string/snapshots/3-Alignment-Error.shot
- packages/ast-spec/src/special/TSExternalModuleReference/spec.ts
- packages/ast-spec/tests/fixtures-with-differences-errors.shot
- packages/eslint-plugin-internal/src/rules/no-typescript-default-import.ts
- packages/eslint-plugin/src/rules/no-restricted-imports.ts
- packages/eslint-plugin/tests/rules/no-require-imports.test.ts
- packages/typescript-estree/src/convert.ts
> feat(typescript-estree): require `import = require()` argument to be a string literal

- packages/ast-spec/src/base/UnaryExpressionBase.ts
- packages/ast-spec/src/expression/CallExpression/spec.ts
- packages/ast-spec/src/expression/ClassExpression/spec.ts
- packages/ast-spec/src/expression/NewExpression/spec.ts
- packages/ast-spec/src/expression/TaggedTemplateExpression/spec.ts
- packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
- packages/eslint-plugin/src/rules/no-implied-eval.ts
- packages/eslint-plugin/src/rules/no-unsafe-argument.ts
Also fixed two other types that are similarly too strict
> fix(ast-spec): function-call-like callee should be Expression not LeftHandSideExpression

- docs/users/Shared_Configurations.mdx
Mentions the _Quickstart_ and _typescript-eslint_ pages in the _Shared Configs_ page. They have all the docs & links-to-docs folks would need to understand the concepts and identifiers used in the config docs.
This doesn't add `import` statements to the config docs, as that would make the page a few dozen lines taller.
> docs: mention Quickstart and typescript-eslint in Shared Configs

- .github/workflows/lock.yml
Uses a new [`locked due to age`](https://github.com/typescript-eslint/typescript-eslint/labels/locked%20due%20to%20age) label I made just now per https://github.com/typescript-eslint/typescript-eslint/issues/8070#issuecomment-1858692983. It links to https://typescript-eslint.io/contributing.
> chore: add 'locked due to age' label to lock.yml workflow

- docs/Contributing.mdx
- docs/contributing/Issues.mdx
Tightens up the phrasing in the root _Contributing_ page too, now that _Issues_ has more info on the `accepting prs` et al.
💖
> docs: add a couple of starting issue queries

- packages/eslint-plugin/tests/docs.test.ts
Following #8015, this adds additional testing to ensure there's both a ✅ Correct and an ❌ Incorrect tab item for each rule option.
A lot of existing rule docs don't yet adhere to this. Rather than try to fix them all in this PR, I added an allowlist with a TODO comment.
💖
> test(eslint-plugin): add docs test for Correct and Incorrect blocks

- docs/troubleshooting/Formatting.mdx
- packages/website/blog/2023-12-25-deprecating-formatting-rules.md
I don't think we need many more places than this. It's been a while since formatting rules were deprecated, and we added more mentions of using the stylistic configs in #8823 -> #8916.
💖
> docs: note the stylistic configs as sticking around past formatting rules

- packages/eslint-plugin/docs/rules/no-misused-promises.mdx
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-misused-promises.shot
Even with ATA added (#8696), it's conceptually easier to avoid third-party packages altogether.
💖
> docs(eslint-plugin): [no-misused-promises] replace third-party EventEmitter example with native document

- docs/troubleshooting/FAQ.mdx
Pins the links back to the last commit to touch the `tsconfig.eslint.json` file: 958fecaef10a26792dc00e936e98cb19fd26d05f.
💖
> docs: correct tsconfig.eslint.json link to be permalink

- packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.mdx
Per #8932, a lot of third-party types actually do trigger the rule. So I opted to not mention them.
💖
> docs(eslint-plugin): [prefer-readonly-parameter-types] mention limitations

- docs/users/Shared_Configurations.mdx
Adds a `:::note` very similar to @bachmacintosh's phrasing to each of the configs that may change in minor or patch versions.
💖 
Co-authored-by: @bachmacintosh
> docs: mention non-semver guarantees in Shared Configs docs

- packages/website/src/components/editor/LoadedEditor.tsx
- packages/website/src/components/linter/bridge.ts
- packages/website/src/components/linter/createLinter.ts
- packages/website/src/components/linter/createParser.ts
- packages/website/src/components/linter/utils.ts
Creates and uses a helper in the website to always keep file names as `file.ts` or `react.tsx`.
> chore(website): align file names to RuleTester requirements

- packages/typescript-estree/src/withoutProjectParserOptions.ts
- packages/typescript-estree/tests/lib/withoutProjectParserOptions.test.ts
Adds the new `projectService` key to the list of removed keys.
💖
> feat(typescript-estree): also remove projectService in withoutProjectParserOptions

- packages/eslint-plugin/docs/rules/no-dynamic-delete.mdx
- packages/eslint-plugin/src/rules/no-dynamic-delete.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-dynamic-delete.shot
- packages/eslint-plugin/tests/rules/no-dynamic-delete.test.ts
Also tightened the condition for unary expressions, which I consider a bug (it allows `typeof 1`)
> feat(eslint-plugin): [no-dynamic-delete] allow all string literals as index

- packages/types/src/parser-options.ts
- packages/typescript-estree/src/parser-options.ts
Adds in the missing `| ProjectServiceOptions` to the `types` package's `ParserOptions`. That necessitates taking in the `ProjectServiceOptions` into the `types` package. 
💖
> fix(types): allow ProjectServiceOptions for projectService

- packages/eslint-plugin/src/rules/no-empty-object-type.ts
- packages/eslint-plugin/tests/schema-snapshots/no-empty-object-type.shot
I think it was just renamed at some point in #8977 (to `allowWithName`)  and didn't get cleaned up.
This is a followup to https://github.com/typescript-eslint/typescript-eslint/pull/8977/files/218d8e5fc8d63e0dd4653ac2e6aef408c22aa98a#r1597015684.
(see also https://v8--typescript-eslint.netlify.app/rules/no-empty-object-type#options)
> chore: [no-empty-object-type] remove unused option in-type-alias-with-name

- docs/packages/TypeScript_ESTree.mdx
- packages/typescript-estree/src/create-program/createProjectService.ts
- packages/typescript-estree/tests/lib/createProjectService.test.ts
Exposes the following logs populated by `ProjectService`.
```
typescript-eslint:typescript-estree:tsserver:err
typescript-eslint:typescript-estree:tsserver:info
typescript-eslint:typescript-estree:tsserver:perf
typescript-eslint:typescript-estree:tsserver:event
```
> feat(typescript-estree): exposes ProjectService logs through the plugin

- packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
const SUPPORTED_TYPESCRIPT_VERSIONS needs to be kept in sync with package.json in the typescript-eslint monorepo. However, this was not changed in #9397.
> fix: keep warnAbountTSVersion in sync with package.json

- packages/eslint-plugin/docs/rules/no-extraneous-class.mdx
- packages/eslint-plugin/src/rules/no-extraneous-class.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-extraneous-class.shot
- packages/eslint-plugin/tests/rules/no-extraneous-class.test.ts
**Description**
This PR addresses an issue with the @typescript-eslint/no-extraneous-class rule where abstract fields and methods were not being counted as instance properties. The rule implementation was missing the handling of abstract members, which have different AST nodes compared to their concrete counterparts. This fix ensures that abstract fields and methods are correctly recognized as instance properties.
**Changes**
- Updated the no-extraneous-class rule to account for `TSAbstractMethodDefinition` and `TSAbstractPropertyDefinition` nodes.
- Added tests to cover scenarios with abstract classes containing abstract members.
> fix(eslint-plugin): [no-extraneous-class] handle abstract members

- packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
- packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
For a union like `string & { __brand?: any } | undefined`, treat the intersection like a primitive; this helps cases like branded `Path` types.
> fix(eslint-plugin): [prefer-nullish-coalescing] handle intersected primitive types

- packages/eslint-plugin/src/rules/no-invalid-this.ts
- packages/eslint-plugin/tests/rules/no-invalid-this.test.ts
- packages/utils/src/ts-eslint/Rule.ts
Support auto-accessor syntax in `no-invalid-this` rule
> fix(eslint-plugin): [no-invalid-this] support AccessorProperty

- packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
- packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
The `ignorePrimitives` flag did not treat literals or enums as their underlying primitive types; for enum heavy codebases like TS, setting `ignorePrimitives` still leads to hundreds of "please use `??`" errors even when applying that fix would change behavior.
This PR instead uses the `-Like` flags variants, which also match against literals and enum values.
I have yet to test this on TS's codebase; just trying to figure out how I can even do that locally... I'll probably just hack the published package, since this change is so small.
> fix(eslint-plugin): [prefer-nullish-coalescing] treat enums and literals as their underlying primitive types

- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts
- packages/eslint-plugin/tests/schema-snapshots/no-unused-vars.shot
This was added upstream in https://github.com/eslint/eslint/pull/18170.
This syncs the changes to our implementation.
NOTE: stacked on top of #9324 - retarget to `v8` before merging
> feat(eslint-plugin): [no-unused-vars] support `ignoreClassWithStaticInitBlock`

- .github/renovate.json5
Applies three touchups to the Renovate config:
* Polishes up formatting and style
* Bases it off of [`config:recommended`](https://docs.renovatebot.com/presets-config/#configrecommended) to bring in the large set of groups, replacements, and workarounds
* Disables patch updates for the reasons in #9372
> chore: base Renovate config on config:recommended, without patch updates

- packages/type-utils/tests/getTypeName.test.ts
- packages/type-utils/tests/typeFlagUtils.test.ts
This reverts commit 2cdf240f13af938c651e5cb5970d60fa788895d3.
Okay, I finally found the cause of the issue: 
- https://github.com/typescript-eslint/typescript-eslint/pull/8922
^ after this PR, it's required to add `disallowAutomaticSingleRunInference` to tests that work with manual parsing 
---
Fun fact: it required exporting `CI=true` to reproduce the failures in the tests.
> chore: revert "test(type-utils): skip mysteriously failing type unit tests (#9427)"

- .github/workflows/close-v8-issues.yml
I tested it in my own repo. It works pretty well. See:
https://github.com/auvred/test-gha-mjolnir/issues/1 -> https://github.com/auvred/test-gha-mjolnir/pull/2
> chore: add GitHub workflow to close issues resolved in `v8` branch

- packages/eslint-plugin/rules.d.ts
In #9339, @JoshuaKGoldberg introduced a regression causing a duplicate import identifier. In a project that consumes `@typescript-eslint/eslint-plugin@8.0.0-alpha.38`, this causes two TypeScript errors in that file (if `skipLibCheck` is `false`), complaining about the duplicate import.
I'm not sure, by the way, why this is not a TS error in the repo itself, but causes a TS error when in the `node_modules` of another package.
Should we consider turning on `skipLibCheck` in this repo?
Also, I did a cursory search and was unable to find any rule in `eslint`, `typescript-eslint` or `eslint-plugin-import` that would allow us to catch issues like these 🙁
> fix(eslint-plugin): remove duplicate import `RuleModuleWithMetaDocs`

- docs/packages/TypeScript_ESLint.mdx
Pasting the last configuration at https://typescript-eslint.io/packages/typescript-eslint#flat-config-extends (under "For example in codebases with type-aware linting a config object like this is a very common way to disable TS-specific linting...") resulted in this warning:
Removing the enclosing array brackets solved the issue.
> docs: tseslint.config takes a spread argument, not an array

- packages/ast-spec/src/element/AccessorProperty/spec.ts
- packages/types/src/ts-estree.ts
Adds `parent: ClassBody` to the `AccessorPropertyComputedName` interfaces to start on #6225.
> feat(ast-spec): add parent property to AccessorProperty node types

- packages/eslint-plugin/docs/rules/no-floating-promises.mdx
- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-floating-promises.shot
- packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
- packages/eslint-plugin/tests/schema-snapshots/no-floating-promises.shot
Adds a new `checkThenables` `boolean` option to the rule that enables checking all shapes for matching the `.then()` interface. It essentially gates the existing _"does this have a `.then()` with two parameters?"_ logic behind the option.
`checkThenables` is `true` by default in this PR so as to not cause a breaking change. If this PR goes in roughly as-is, I'd like to file a followup issue for v8 to turn it to `false` by default. 
#8433 also mentioned adding in an option for adding additional types to what's flagged by default. I haven't heard anybody mention this as a strong need, so for now I'm holding off on adding that.
💖
> feat(eslint-plugin): [no-floating-promises] add checkThenables option

- packages/utils/src/eslint-utils/getParserServices.ts
- packages/utils/src/eslint-utils/parserPathSeemsToBeTSESLint.ts
- packages/utils/src/eslint-utils/parserSeemsToBeTSESLint.ts
- packages/utils/src/ts-eslint/Rule.ts
- packages/utils/tests/eslint-utils/getParserServices.test.ts
- packages/utils/tests/eslint-utils/parserSeemsToBeTSESLint.test.ts
First switches `parserPath` to `string | undefined`, then adds in handling to try to use `context.languageOptions.parser.meta.name` if it exists.
💖
> fix(utils): context.parserPath may be undefined

- packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
Adds `suggestions` property that was missing in tests from #9263 causing pipeline failures in `main`.
> fix(eslint-plugin): [no-floating-promises] add `suggestions` to tests from #9263 `checkThenables`

- packages/type-utils/tests/isSymbolFromDefaultLibrary.test.ts
> test(type-utils): disable automatic single run inference for isSymbolFromDefaultLibrary tests

- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-floating-promises.shot
> test(eslint-plugin): update outdated docs.test.ts snapshots

- packages/eslint-plugin/src/rules/restrict-template-expressions.ts
- packages/eslint-plugin/tests/rules/restrict-template-expressions.test.ts
> fix(eslint-plugin): [restrict-template-expressions] don't report tuples if `allowArray` option is enabled

- packages/eslint-plugin/src/rules/no-unnecessary-parameter-property-assignment.ts
No fixer is actually present.
Ref: https://github.com/typescript-eslint/typescript-eslint/pull/8903#discussion_r1669379472
> chore(eslint-plugin): [no-unnecessary-parameter-property-assignment] remove `fixable` from `meta`

- eslint.config.mjs
- packages/website-eslint/src/mock/path.js
Enable `prefer-arrow-callback` ([docs](https://eslint.org/docs/latest/rules/prefer-arrow-callback)).
> chore: enable prefer-arrow-callback

- packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
Mapped types have three parts: the type parameter, the template type and the constraint type:
```
> type.checker.typeToString(type)
'{ [key in K]?: V | undefined; }'
> type.checker.typeToString(type.typeParameter)
'key'
> type.checker.typeToString(type.templateType)
'V | undefined'
> type.checker.typeToString(type.constraintType)
'K'
```
The rule previously descended into the typeParameter. It doesn't need to descend into the constraintType because we get that through another code path. It does need to descend into the templateType, though.
One wrinkle is that if the mapped type is something like `{[k in 'a']: T}`, then TypeScript will treat it like `{a: T}` and we'll process it as an object type. In this case, we need to avoid _also_ processing it as a mapped type, even though …
> fix(eslint-plugin): [no-unnecessary-type-parameters] descend into all parts of mapped types in no-unnecessary-type-parameters

- packages/eslint-plugin/docs/rules/no-floating-promises.mdx
- packages/eslint-plugin/src/rules/no-floating-promises.ts
- packages/eslint-plugin/tests/rules/no-floating-promises.test.ts
Changes a rule's default option.
Changes the option's default from `true` to `false` and updates docs + tests.
💖
> feat(eslint-plugin): [no-floating-promises] disable checkThenables by default for v8

- packages/typescript-eslint/src/config-helper.ts
The interface docs were missing the ellipsis.
```ts
tseslint.config({ extends: [tseslint.configs.recommended] })
-> [
{
'0': {
name: 'typescript-eslint/base',
languageOptions: [Object],
plugins: [Object]
},
'1': {
files: [Array],
rules: [Object],
name: 'typescript-eslint/eslint-recommended'
},
'2': { name: 'typescript-eslint/recommended', rules: [Object] }
},
{}
]
```
> docs(typescript-eslint): add missing ellipsis in ConfigWithExtends

- eslint.config.mjs
- packages/eslint-plugin/src/rules/prefer-find.ts
Enable `no-useless-computed-key` ([docs](https://eslint.org/docs/latest/rules/no-useless-computed-key)).
> chore: enable no-useless-computed-key

- packages/typescript-estree/src/parseSettings/inferSingleRun.ts
- packages/typescript-estree/tests/lib/inferSingleRun.test.ts
Does a straightforward check for `'--fix'` in `process.argv`.
I'd have loved to use something more ... not-hacky, i.e. some explicit indication from ESLint itself. But our old friend https://github.com/eslint/rfcs/pull/102 was rejected.
💖
> fix(typescript-estree): don't infer single-run when --fix is in proces.argv

- packages/typescript-estree/src/parseSettings/inferSingleRun.ts
- packages/typescript-estree/tests/lib/inferSingleRun.test.ts
There's no way to set extra file extensions on the classic standalone `ts.Host`. So we don't do that here.
Folks using `.svelte`, `.vue`, etc. can still use the project _service_.
💖
> fix(typescript-estree): disable single-run inference with extraFileExtensions

- packages/website/docusaurus.config.mts
- packages/website/src/components/OptionsSelector.tsx
- packages/website/webpack.plugin.js
Hardcodes the version to `'v8'`. The root issue is that our versioning infra doesn't touch the `package.json`s directly, so they still say the latest v7 version in them & get imported into components with that...
💖
> chore(website): correct version to be v8, not latest merged v7

- eslint.config.mjs
- packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
- packages/eslint-plugin/src/rules/unified-signatures.ts
- packages/typescript-estree/tests/lib/convert.test.ts
- packages/typescript-estree/tests/lib/persistentParse.test.ts
Enable `@typescript-eslint/no-unused-expressions` ([docs](https://typescript-eslint.io/rules/no-unused-expressions/)). This allows for more dogfooding, as well.
> chore: enable @typescript-eslint/no-unused-expressions

- packages/typescript-estree/src/create-program/createProjectService.ts
- packages/typescript-estree/tests/lib/createProjectService.test.ts
Per https://github.com/microsoft/TypeScript/issues/59338#issuecomment-2236857239, disable this so that the auto import projects are not used.
> fix(typescript-estree): disable includePackageJsonAutoImports in ProjectService

- docs/packages/Parser.mdx
- docs/troubleshooting/typed-linting/index.mdx
Adds an _"if this then ... else ..."_ style list for `parserOptions.projectService` out-of-program files. It's similar to the existing list for `parserOptions.project`.
Extracts out the shared _"How do I disable type-checked linting for a file?"_ instructions into a separate FAQ heading that can be linked. That means no more odd nested mdx code blocks breaking Prettier! 🧹
💖
> docs: clarify projectService out-of-project remediation steps

- packages/typescript-estree/src/create-program/useProvidedPrograms.ts
- packages/typescript-estree/tests/lib/semanticInfo.test.ts
- packages/website/src/hooks/useClipboard.ts
When `parseSettings.projects` is populated, `useProvidedPrograms` nows refer to `parserOptions.project` and `project(s)` instead of `parserOptions.programs` and `program(s)`.
Also applies a mild refactor to reduce nesting in the function.
I think after this I'd like to holistically revamp the error messages around invalid 
💖
> fix(typescript-estree): specific error for parserOptions.project not including a file

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
This PR accounts for private identifiers when checking if a member expression is nullable
Not sure if/which additional test cases I should add here, so I'm open for suggestions 😄
> fix(eslint-plugin): [no-unnecessary-condition] false positive on optional private field

- packages/website/src/components/editor/useSandboxServices.ts
- packages/website/src/vendor/sandbox.d.ts
- packages/website/src/vendor/typescript-vfs.d.ts
this solves most of issues with ATA types not beeing visible to eslint, but sadly `node:*` is still not fully supported
ref: https://github.com/typescript-eslint/typescript-eslint/issues/9594
> fix(website): expose ATA types to eslint instance

- packages/eslint-plugin/src/configs/strict-type-checked-only.ts
- packages/eslint-plugin/src/configs/strict-type-checked.ts
- packages/eslint-plugin/src/rules/return-await.ts
- packages/typescript-eslint/src/configs/strict-type-checked-only.ts
- packages/typescript-eslint/src/configs/strict-type-checked.ts
- packages/utils/src/ts-eslint/Rule.ts
~BREAKING CHANGE~ Technically _not_ a breaking change, since it's only going to the strict config, but targeting v8 anyway to batch it in with the rest of our config changes.
Nothin but a config change
Note, also, followup to #9595, thanks @JoshuaKGoldberg for the tip on the config generation infra
***
Co-authored-by: @JoshuaKGoldberg
> feat(eslint-plugin): [return-await] add return-await to strict-type-checked preset

- packages/repo-tools/src/generate-sponsors.mts
`twitterHandle` was added to the TypeScript type when `generate-sponsors` was initially built, but it was never used and also never added to the GraphQL query, so it never existed.
[9bb88e55](https://github.com/typescript-eslint/typescript-eslint/pull/4105/commits/9bb88e557a1758a66201f77176f2bfdc231eb1f3)
> chore(website): remove incorrect `twitterHandle` from type

- packages/type-utils/src/typeOrValueSpecifiers/specifierNameMatches.ts
- packages/type-utils/tests/TypeOrValueSpecifier.test.ts
Changes `specifierNameMatches` to:
1. Always check alias names of the types, to support directly matching type aliases
2. For intersection types, also check `type.types.some(...)` recursively
Sending this to the `v8` branch because it's based on some `TypeOrValueSpecifier` changes in `v8`. But it doesn't block shipping v8 and isn't a part of the v8 milestone.
💖
> feat(type-utils): support intersection types in TypeOrValueSpecifier

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
As Kirk mentioned in https://github.com/typescript-eslint/typescript-eslint/issues/9268#issuecomment-2148437137, we can't rely on ESTree because the variable can be declared in the TS default lib, so we don't even have a corresponding ESTree AST.
> fix(eslint-plugin): [no-unnecessary-type-assertion] prevent runtime error when asserting a variable declared in default TS lib

- packages/eslint-plugin/docs/rules/no-unnecessary-type-parameters.mdx
- packages/eslint-plugin/src/configs/strict-type-checked-only.ts
- packages/eslint-plugin/src/configs/strict-type-checked.ts
- packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
- packages/typescript-eslint/src/configs/strict-type-checked-only.ts
- packages/typescript-eslint/src/configs/strict-type-checked.ts
Bumps the rule's `meta.docs.recommended` and removes its docs page's admonition.
💖
> feat(eslint-plugin): [no-unnecessary-type-parameters] promote to strict

- docs/getting-started/Typed_Linting.mdx
Fixes broken link during mass update in #9024. Looking at #9024, all other occurrences seem to have been updated correctly — this is the only wrongly updated occurrence.
> chore(website): fix broken link about typed linting

- eslint.config.mjs
- package.json
- packages/eslint-plugin/tsconfig.json
- yarn.lock
Simplifies our `eslint.config.mjs` a bit by using `parserOptions.projectService: true` instead of a larger `parserOptions.project` array. There was one `packages/eslint-plugin/eslint-recommended-raw.d.ts` file missing from its `tsconfig.json`.
This is an example of the need for `additionalNodeTypeFiles` from https://github.com/eslint-community/eslint-plugin-eslint-plugin/pull/484. Switching to the project service meant we got project references support for free, which switched the linted files from `dist/*/.d.ts` to the source `ast-spec.ts`.
💖
> chore: use parserOptions.projectService internally

- packages/typescript-estree/src/useProgramFromProjectService.ts
- packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
The _"does this file's path match the allowed list of files"_ needed to be relative to `tsconfigRootDir`, not the absolute path.
💖
> fix(typescript-estree): factor tsconfigRootDir into allowDefaultProject

- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
If `usedOnlyAsType`, then ignore the variable if it came from an import definition. This showed that there were existing tests which encoded the old behavior, which I updated.
The second commit moves some code slightly to avoid extra work now that this loop can `continue`.
Due to #9688, I had to commit with `--no-verify`, so hopefully this passes CI.
> fix(eslint-plugin): [no-unused-vars] ignore imports used only as types

- docs/packages/Parser.mdx
- packages/typescript-estree/tests/lib/validateDefaultProjectForFilesGlob.test.ts
- packages/website/blog/2024-05-27-announcing-typescript-eslint-v8-beta.mdx
- packages/website/blog/2024-07-31-announcing-typescript-eslint-v8.md
Fixes up the docs - I'd missed this discrepancy in the initial launch.
💖
> docs: correct allowDefaultProject references to not start with ./

- packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/strict-boolean-expressions.shot
https://typescript-eslint.io/rules/strict-boolean-expressions/#examples
fixes incorrect example for nullable numbers not actually raising lint error due to [typescript type narrowing](https://github.com/typescript-eslint/typescript-eslint/issues/9699#issuecomment-2264352992)
> docs: [strict-boolean-expressions] fix nullable number/string example

- eslint.config.mjs
- packages/typescript-eslint/src/index.ts
- packages/typescript-estree/tests/lib/convert.test.ts
- packages/utils/src/ts-eslint/ESLint.ts
Now, unused disable directives will block the pipeline. I cannot think of any reason not to have this, and per the linked comment, @auvred and @JoshuaKGoldberg support it 👍
> chore: set `reportUnusedDisableDirectives` level to `error`

- packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
Prevents checking of references inside a function body, or if one doesn't exist, generally after the return type.
This might give a little speed boost for not checking function bodies... but:
* Since that's just AST iteration, it probably won't be noticeable for any real world cases
* Inferred return types will now have to go to the type checker, which might slow things down anyway
💖
> fix(eslint-plugin): [no-unnecessary-type-parameters] skip checking function bodies for AST references

- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
- packages/eslint-plugin/src/util/misc.ts
- packages/eslint-plugin/tests/rules/member-ordering/member-ordering-alphabetically-order.test.ts
> fix(eslint-plugin): [member-ordering] get accessor member name & take into account `abstract` and decorator

- packages/rule-tester/package.json
- packages/rule-tester/typings/eslint.d.ts
- yarn.lock
This dep is unused in the package; removing it seems to have no effect. (Not that it much matters, `eslint` itself directly depends on it.)
> chore(rule-tester): remove unused dep on @eslint/eslintrc

- docs/packages/TypeScript_ESLint.mdx
josh-cena said that this was a bug, so I am filing a PR to fix it.
A core team member should review the rest of the docs for additional mistakes of this nature.
> docs: fix outdated project setting

- docs/getting-started/Legacy_ESLint_Setup.mdx
In the [Legacy ESLint Setup](https://typescript-eslint.io/getting-started/legacy-eslint-setup) page, the following link...
> We also provide a plethora of powerful rules that utilize the power of TypeScript's type information. [Visit the next page for a typed rules setup guide](https://typescript-eslint.io/troubleshooting/typed-linting).
...points to the [Typed Linting page under Troubleshooting](https://typescript-eslint.io/troubleshooting/typed-linting). However, it seems that the intent was to link to the [Linting with Type Information](https://typescript-eslint.io/getting-started/typed-linting) page, which describes how to set up typed linting.
Compare the corresponding passage in the [Quickstart](https://typescript-eslint.io/getting-started/) which correctly links to "Linting with …
> docs: fix link in Legacy ESLint Setup page

- packages/website/blog/2024-07-31-announcing-typescript-eslint-v8.md
docs: add @typescript-eslint/no-unnecessary-type-parameters to strict-type-checked diff
The `@typescript-eslint/no-unnecessary-type-parameters` was added to `strict-type-checked` in v8 (related pr 
https://github.com/typescript-eslint/typescript-eslint/pull/9662), but was not described in the release docs.
The description was added because without it, it would be difficult to find out the reason when the version is upgraded.
> docs: add @typescript-eslint/no-unnecessary-type-parameters to strict-type-checked diff

- packages/type-utils/tests/containsAllTypesByName.test.ts
Added test case for containsAllTypesByName function.
> test(type-utils): add tests for containsAllTypesByName

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/fixtures/tsconfig.json
- packages/eslint-plugin/tests/fixtures/var-declaration.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
This PR makes the rule ignore var declared in child scopes.
> fix(eslint-plugin): [no-unnecessary-type-assertion] conflict with TS for variables used before assignment

- packages/eslint-plugin/src/rules/no-redundant-type-constituents.ts
- packages/eslint-plugin/tests/rules/no-redundant-type-constituents.test.ts
> fix(eslint-plugin): [no-redundant-type-constituents] differentiate a types-error any from a true any

- packages/eslint-plugin/src/rules/no-unsafe-enum-comparison.ts
- packages/eslint-plugin/tests/rules/no-unsafe-enum-comparison.test.ts
Added additional logic for the rule to "see through" intersections, allowing the rule to work properly in the case outlined in the linked issue.
> fix(eslint-plugin): [no-unsafe-enum-comparison] add logic to see through intersections

- packages/typescript-estree/src/create-program/createProjectService.ts
- packages/typescript-estree/src/parseSettings/createParseSettings.ts
- packages/typescript-estree/tests/lib/createProjectService.test.ts
Not sure what a good test would be for this; I'm also not sure if adding this param is a break? I can make it optional.
> fix(typescript-estree): pass in tsconfigRootDir as cwd to getParsedConfigFile

- packages/type-utils/tests/containsAllTypesByName.test.ts
#9711 added a lint failure on main because of my lint rule being enabled (`prefer-node-protocol`)
> chore: fix `prefer-node-protocol` lint failure on main

- packages/utils/src/ts-eslint/Rule.ts
> fix(utils): add missing `TSSatisfiesExpression` in `RuleListenerBaseSelectors`

- docs/packages/Rule_Tester.mdx
node test-runner doesn’t have `afterAll` function, so fixed to `after`. ([Node.js Test runner doc](https://nodejs.org/api/test.html#afterfn-options))
> docs: fix setup example for node:test in RuleTester

- packages/website/tsconfig.json
- tools/scripts/generate-sponsors.mts
- tsconfig.json
Remove `lib: ES2023` from `tsconfig`s
> chore: remove lib: esnext

- eslint.config.mjs
- packages/visitor-keys/src/get-keys.ts
- packages/visitor-keys/src/visitor-keys.ts
Enables sorting on `packages/visitor-keys`.
💖
> chore: enable eslint-plugin-perfectionist on visitor-keys package

- eslint.config.mjs
- packages/eslint-plugin/src/rules/consistent-type-imports.ts
- packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
- packages/eslint-plugin/src/rules/no-empty-interface.ts
- packages/eslint-plugin/src/rules/no-magic-numbers.ts
- packages/eslint-plugin/src/rules/no-misused-new.ts
- packages/eslint-plugin/src/rules/no-misused-promises.ts
- packages/eslint-plugin/src/rules/no-type-alias.ts
- packages/eslint-plugin/src/rules/no-unnecessary-parameter-property-assignment.ts
- packages/eslint-plugin/src/rules/prefer-optional-chain-utils/gatherLogicalOperands.ts
- packages/eslint-plugin/src/util/collectUnusedVariables.ts
- packages/eslint-plugin/src/util/getWrappingFixer.ts
- packages/rule-tester/src/utils/serialization.ts
- packages/typescript-estree/src/convert.ts
- packages/website/src/components/ast/selectedRange.ts
- packages/website/src/components/ast/tsUtils.ts
- packages/website/tools/typedoc-plugin-no-inherit-fork.mjs
Since we already enable `no-lonely-if` in #9547 (which handles `else { if (a) }` => `else if (a) {}`, this is the next logic step to enable `unicorn/no-lonely-if` ([docs](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-lonely-if.md)), which handles `if (a) { if (b) {} }` => `if (a && b) {}`.
Tests failed due to CI flake.
> chore: enable unicorn/no-lonely-if

- packages/typescript-estree/src/create-program/createProjectService.ts
- packages/typescript-estree/src/useProgramFromProjectService.ts
- packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
If a file isn't found by `parserOptions.projectService`, then this will attempt to reload the project service. Doing so refreshes how it sees TSConfigs on disk. This should fix most -but not all- cases mentioned in #9731 -> https://github.com/microsoft/vscode-eslint/issues/1911 of a new file being created & ESLint not knowing to update parser information.
This includes several limits on it to avoid slowing down unrelated situations:
* It won't happen in single-run mode at all (i.e. CLI calls without `--fix`)
* It's throttled to 250ms so it shouldn't slow down editors if multiple files have this issue
💖
> feat(typescript-estree): reload project service once when file config isn't found

- docs/packages/Parser.mdx
- docs/troubleshooting/typed-linting/index.mdx
- packages/typescript-estree/tests/lib/createProjectService.test.ts
- packages/website/blog/2024-05-27-announcing-typescript-eslint-v8-beta.mdx
- packages/website/blog/2024-07-31-announcing-typescript-eslint-v8.md
- packages/website/src/css/custom.css
Steals some of the docs from #8031 so we can get them in sooner.
Also adds in FAQs around the most common mishaps we've seen from users. Largely:
* Questions around files not being included in their nearest `tsconfig.json` (e.g. `.js` files without `allowJs`/`checkJs`)
* You can't use non-`tsconfig.json` files as the main file path; if you're using TSConfigs to build with a separate system, building should be the custom non-`tsconfig.json` paths (e.g. `tsconfig.build.json`)
💖
> docs: add more project service docs and FAQs

- docs/packages/Rule_Tester.mdx
I couldn't think of anything to say for each of them beyond their existing one-line JSDoc descriptions. 🤷 
Also moves the Node(.js (`node:test`)) heading so that the named test frameworks are in alphabetical order. I couldn't help myself.
💖
> docs: mention RuleTester static properties

- .github/workflows/pr-review-requested.yml
- docs/maintenance/Issues.mdx
- docs/maintenance/Pull_Requests.mdx
Summarizing scattered conversations I've had over the last few months. This PR is very much a proposal, I'm expecting some discussions in it. 😄 
💖
> docs: formalized '1 approval' and 'team assigned' labels

- eslint.config.mjs
As per the comment, completely disables sorting on enums. We tend to use them in ways where our own ordering makes more sense than alphabetical/natural.
💖
> chore: disable eslint-plugin-perfectionist on enums

- packages/typescript-estree/src/withoutProjectParserOptions.ts
- packages/typescript-estree/tests/lib/withoutProjectParserOptions.test.ts
Adds an `<Options extends TSESTreeOptions>` to `withoutProjectParserOptions` so it can use types that happen to match it.
💖
> feat(typescript-estree): make withoutProjectParserOptions generic

- packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
- packages/eslint-plugin-internal/tests/rules/plugin-test-formatting.test.ts
- packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts
- packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
- packages/eslint-plugin/tests/rules/method-signature-style.test.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
- packages/eslint-plugin/tests/rules/no-unused-expressions.test.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
- packages/eslint-plugin/tests/rules/prefer-for-of.test.ts
- packages/eslint-plugin/tests/rules/prefer-literal-enum-member.test.ts
- packages/eslint-plugin/tests/rules/return-await.test.ts
- packages/eslint-plugin/tests/rules/typedef.test.ts
I followed the proposal in https://github.com/typescript-eslint/typescript-eslint/issues/6128 and added a check for unnecessary NoFormat occurrences, with a test.
Reopen: https://github.com/typescript-eslint/typescript-eslint/pull/6853
Co-authored-by: @Jolg42
> chore(eslint-plugin-internal): noUnnecessaryNoFormat

- docs/troubleshooting/typed-linting/Performance.mdx
More explicitly mentions in the docs that most perf issues are from calling to TypeScript's APIs.
💖
> docs: add Troubleshooting entry for debugging slow lint rules

- packages/eslint-plugin/docs/rules/no-redeclare.mdx
Removed repeated word `variable` twice
> docs(eslint-plugin): [no-redeclare] remove repeated word

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Updates the fixer to remove the range of the `!` token.
> fix(eslint-plugin): [no-unnecessary-type-assertion] fix TSNonNullExpression fixer

- eslint.config.mjs
- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/website/tools/typedoc-plugin-no-inherit-fork.mjs
Enable `unicorn/prefer-array-some` ([docs](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-array-some.md)).
This rule might have been added to `typescript-eslint`, but was recently closed in #8378 .
> chore: enable `unicorn/prefer-array-some`

- docs/developers/Custom_Rules.mdx
- docs/packages/Parser.mdx
- docs/packages/Rule_Tester.mdx
- docs/packages/TypeScript_ESTree.mdx
- packages/types/src/parser-options.ts
- packages/typescript-estree/jest.config.js
- packages/typescript-estree/src/create-program/createProjectService.ts
- packages/typescript-estree/src/create-program/getParsedConfigFile.ts
- packages/typescript-estree/src/create-program/validateDefaultProjectForFilesGlob.ts
- packages/typescript-estree/tests/lib/createProjectService.test.ts
- packages/typescript-estree/tests/lib/parse.project-true.test.ts
- packages/typescript-estree/tests/lib/validateDefaultProjectForFilesGlob.test.ts
Now, `getParsedConfigFile` will always be called, even if the user hasn't explicitly provided `projectService.defaultProject` manually. This is actually good, I think: it'll make sure the project's `tsconfig.json` is valid.
💖
> feat(typescript-estree): default projectService.defaultProject to 'tsconfig.json'

- packages/website/blog/2022-09-18-automated-rule-docs-with-docusaurus-and-remark.md
- packages/website/blog/2022-12-05-asts-and-typescript-eslint.md
- packages/website/blog/2023-02-24-consistent-type-exports-and-imports-why-and-how.md
- packages/website/blog/2023-03-13-announcing-typescript-eslint-v6-beta.md
- packages/website/blog/2023-07-09-announcing-typescript-eslint-v6.md
- packages/website/blog/2023-09-18-parser-options-project-true.md
- packages/website/blog/2023-12-25-deprecating-formatting-rules.md
- packages/website/blog/2024-02-12-announcing-typescript-eslint-v7.md
- packages/website/blog/2024-03-25-changes-to-consistent-type-imports-with-decorators.md
- packages/website/blog/2024-05-27-announcing-typescript-eslint-v8-beta.mdx
- packages/website/blog/2024-07-31-announcing-typescript-eslint-v8.md
- packages/website/blog/authors.yml
Per https://docusaurus.io/docs/blog#global-authors. I like this feature, it's a nice bit of deduplication!
💖
> chore: add blog/authors.yml for Docusaurus

- packages/eslint-plugin/docs/rules/no-unnecessary-condition.mdx
- packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.mdx
- packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx
Adds a `:::danger` admonition to each docs page.
💖
> docs: mark allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing options as deprecated

- packages/eslint-plugin/docs/rules/no-unsafe-argument.mdx
- packages/eslint-plugin/src/rules/no-unsafe-argument.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unsafe-argument.shot
- packages/eslint-plugin/tests/rules/no-unsafe-argument.test.ts
Uses the same _"error typed"_ phrasing as other `no-unsafe-*` rules.
💖
> feat(eslint-plugin): [no-unsafe-argument] differentiate error types

- packages/eslint-plugin/src/rules/no-misused-promises.ts
- packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
> fix(eslint-plugin): [no-misused-promises] handle static method

- eslint.config.mjs
- package.json
- packages/eslint-plugin-internal/src/rules/plugin-test-formatting.ts
- packages/rule-tester/src/utils/flat-config-schema.ts
- packages/rule-tester/src/utils/interpolate.ts
- packages/scope-manager/tests/fixtures.test.ts
- packages/typescript-estree/tests/lib/parse.test.ts
- packages/website-eslint/src/mock/path.js
- yarn.lock
Enables several small basic rules in `eslint-plugin-regexp` that can mostly be autofixed to simplify regexps.
> chore: enable `eslint-plugin-regexp`

- packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
The existing code was inspecting the `references` on the `Scope` itself, but we want to be inspecting the `references` on the corresponding `Variable`.
* [docs for `references` property on `Scope`](https://eslint.org/docs/latest/extend/scope-manager-interface#references)
* [docs for `references` property on `Variable`](https://eslint.org/docs/latest/extend/scope-manager-interface#references-1)
Coauthor credit to Josh for the breadcrumbs in https://github.com/typescript-eslint/typescript-eslint/issues/9889#issuecomment-2313374807
Co-authored-by: @JoshuaKGoldberg
> fix(eslint-plugin): [no-unnecessary-type-parameters] fix AST quick path scope analysis

- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/rules/consistent-type-assertions.ts
- packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
- yarn.lock
Adds `espree` as a `devDependency` to be able to use it as a parser in the unit test.
💖
> fix(eslint-plugin): [consistent-type-assertions] access parser services lazily

- packages/integration-tests/fixtures/flat-config-types-@types__eslint-v8/package.json
The v9 integration test also uses latest. I believe any issues on eslint.stylistic around v8 / flat config types should be fixed now?
💖
> chore: pin eslint version in `@types/eslint@v8` integration test

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
- packages/type-utils/src/predicates.ts
Since there are two rules using this utility function, I removed the same logic from the rule and added test code.
And I tried to add a unit test for isNullableType, but I couldn't find the original unit test file. Is it true that unit tests are not originally written for this utility file?
> feat(type-utils): isNullableType add Void logic

- packages/eslint-plugin/src/rules/no-deprecated.ts
- packages/eslint-plugin/tests/rules/no-deprecated.test.ts
> fix(eslint-plugin): [no-deprecated] report on deprecated variables used in destructuring assignment

- packages/eslint-plugin/src/rules/no-deprecated.ts
- packages/eslint-plugin/tests/rules/no-deprecated.test.ts
- packages/utils/tests/ts-eslint/ESLint.test.ts
```ts
declare interface SomeInterface {
/** @deprecated */
property: () => void;
/** @deprecated */
method(): void;
}
declare const someInterface: SomeInterface;
someInterface.property(); // ❌ missing error
someInterface.method(); // ✅ errors
```
Both `property` and `method` identifiers have call signatures, but:
- `method` has `"deprecated"` jsdoc tag on its **signature**
- `property` has `"deprecated"` jsdoc tag on its **symbol**
> fix(eslint-plugin): [no-deprecated] report on deprecated properties with function-like types

- docs/developers/ESLint_Plugins.mdx
Explain, that there is not need to define the parser and therefore include `typescript-eslint` as peer dependency.
> docs: add note about typescript-eslint as peer dependency

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
Properly reflect the truthiness or falsiness of a value after multiple negations, and expand the reporting range to include the negation operator(s).
> fix(eslint-plugin): [no-unnecessary-condition] properly reflect multiple negations in message

- packages/typescript-estree/src/create-program/createProjectService.ts
- packages/typescript-estree/tests/lib/createProjectService.test.ts
Changes error throwing to only occur if the user explicitly provides a `parserOptions.defaultProject`.
💖
> fix(typescript-estree): don't throw on missing tsconfig.json by default in project service

- docs/packages/Parser.mdx
- docs/packages/TypeScript_ESTree.mdx
- packages/types/src/parser-options.ts
- packages/typescript-estree/src/create-program/createProjectService.ts
- packages/typescript-estree/tests/lib/createProjectService.test.ts
Adds an off-by-default `projectService.loadTypeScriptPlugins` option to configure whether plugins are loaded. This is a bugfix in that plugins were previously always loaded. It's a feature in that it's held behind an option.
💖
> feat(typescript-estree): disable plugin loading by default in project service

- packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
> test(eslint-plugin): [no-unnecessary-type-parameters] add tests with intrinsic `NoInfer`

- CHANGELOG.md
- packages/website/blog/2024-07-31-announcing-typescript-eslint-v8.md
Adds quick notices positioning blog posts as the upgrade guides for major versions.
💖
> docs: explicitly indicate blog posts are major version upgrade guides

- knip.ts
- packages/utils/src/ts-eslint/Rule.ts
- packages/utils/tests/ts-eslint/Rule.type-test.ts
I added some tests, and it turns out there were 10 selectors missing!
> fix(utils): add missing entries to the RuleListener selectors list

- packages/eslint-plugin/TSLINT_RULE_ALTERNATIVES.md
Hello @JoshuaKGoldberg,
Quick little typo I spotted. `no-throw-literal` was renamed to `only-throw-error` here (https://github.com/typescript-eslint/typescript-eslint/pull/8701). There is no such thing as `only-throw-literal`..!
> docs: fix typo for `only-throw-error` rule

- packages/types/src/ts-estree.ts
`new` expressions may contain a spread, e.g. `new Array(...[])`.
Adds `TSESTree.NewExpression` as an allowed parent type of `SpreadElement`, since `SpreadElement` can contain `NewExpression`s. This regressed in https://github.com/typescript-eslint/typescript-eslint/pull/9560.
> fix(types): add `NewExpression` as a parent of `SpreadElement`

- CHANGELOG.md
Misnamed `no-deprecation`/`no-deprecated` in CHANGELOG.md
Same in the release description for https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.3.0
> docs: misnamed `no-deprecation`/`no-deprecated` in CHANGELOG.md

- packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx
See https://typescript-eslint.io/rules/strict-boolean-expressions/#allowruletorunwithoutstrictnullchecksiknowwhatiamdoing 😬
> docs: [strict-boolean-expressions] fix adominition

- packages/eslint-plugin/src/rules/class-literal-property-style.ts
- packages/eslint-plugin/src/rules/class-methods-use-this.ts
- packages/eslint-plugin/src/util/isArrayMethodCallWithPredicate.ts
- packages/eslint-plugin/src/util/misc.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
- packages/eslint-plugin/tests/rules/prefer-promise-reject-errors.test.ts
#9836 had some bugs with how various data types are coerced to strings when used in a computed `MemberAccess`; this PR fixes those bugs.
> fix(eslint-plugin): properly coerce all types to string in `getStaticMemberAccessValue`

- packages/eslint-plugin/src/rules/no-deprecated.ts
- packages/eslint-plugin/tests/fixtures/class.ts
- packages/eslint-plugin/tests/fixtures/deprecated.ts
- packages/eslint-plugin/tests/fixtures/tsconfig.json
- packages/eslint-plugin/tests/fixtures/tsconfig.moduleResolution-node16.json
- packages/eslint-plugin/tests/rules/no-deprecated.test.ts
JSDoc tags are attached to the original symbols, not to symbol aliases. But symbols of imported variables are aliases, so we need to resolve those aliases, that's it!
> fix(eslint-plugin): [no-deprecated] report on imported deprecated variables

- packages/eslint-plugin/docs/rules/no-confusing-non-null-assertion.mdx
- packages/eslint-plugin/src/rules/no-confusing-non-null-assertion.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-confusing-non-null-assertion.shot
- packages/eslint-plugin/tests/rules/no-confusing-non-null-assertion.test.ts
Basically just shares the logic from the other operators. The only difference is that, since it's not _always_ safe to remove the non-null assertion before an `in` or `instanceof`, I additionally added the wrapping suggestion for `a! in b` -> `(a!) in b` and `a! instanceof b` -> `(a!) instanceof b`.
> fix(eslint-plugin): [no-confusing-non-null-assertion] check !in and !instanceof

- packages/eslint-plugin/docs/rules/no-unsafe-call.mdx
- packages/eslint-plugin/docs/rules/no-unsafe-function-type.mdx
- packages/eslint-plugin/src/rules/no-unsafe-call.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unsafe-call.shot
- packages/eslint-plugin/tests/rules/no-unsafe-call.test.ts
- packages/eslint-plugin/tests/rules/no-unsafe-function-type.test.ts
- packages/website/src/components/lib/parseConfig.ts
- Simply check for `Function` type in existing rule.
- Minor cleanup of some sloppiness in the report messages, to ensure that they can say "`Function` typed" rather than "`any` typed"
> feat(eslint-plugin): [no-unsafe-call] check calls of Function

- packages/eslint-plugin/docs/rules/no-unnecessary-type-parameters.mdx
- packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
Add FAQ section to rule's doc page.
Tried to mention all/most of the issues linked to #9680 in some capacity.
> docs: [no-unnecessary-type-parameters] add FAQ section

- packages/eslint-plugin/tests/rules/only-throw-error.test.ts
- packages/eslint-plugin/tests/rules/prefer-promise-reject-errors.test.ts
- packages/type-utils/src/builtinSymbolLikes.ts
This PR addresses #9882 along with a similar issue for `@typescript-eslint/prefer-promise-reject-errors`:
```typescript
// @typescript-eslint/only-throw-error
function fun1<T extends Error>(t: T): void {
throw t;
}
// @typescript-eslint/prefer-promise-reject-errors
function fun2<T extends Error>(t: T): void {
Promise.reject(t);
}
```
Since this changes a function that's being used in a lot of other places (`isBuiltinSymbolLikeRecurser()`), this can affect other rules (for better or worse).
Please let me know if you think this isn't the correct way to approach this.
> fix(type-utils): check for type parameters on `isBuiltinSymbolLikeRecurser()`

- packages/utils/src/eslint-utils/getParserServices.ts
- packages/utils/tests/eslint-utils/getParserServices.test.ts
Updates the error message to be less precise, be more accurate, and point at the docs.
> fix(utils): update missing type information message

- packages/eslint-plugin/src/rules/no-deprecated.ts
- packages/eslint-plugin/tests/rules/no-deprecated.test.ts
wraps `getJsDocTags` call in a try-catch
> fix(eslint-plugin): [no-deprecated] max callstack exceeded when class implements itself

- eslint.config.mjs
- packages/eslint-plugin/docs/rules/no-unnecessary-condition.mdx
- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/src/rules/prefer-optional-chain.ts
- packages/eslint-plugin/src/rules/prefer-string-starts-ends-with.ts
- packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
- packages/eslint-plugin/src/util/assertionFunctionUtils.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unnecessary-condition.shot
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
- packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
- packages/eslint-plugin/tests/schema-snapshots/no-unnecessary-condition.shot
- packages/type-utils/src/getTypeName.ts
- packages/typescript-estree/tests/lib/semanticInfo.test.ts
- packages/typescript-estree/tests/lib/source-files.test.ts
- packages/typescript-estree/tests/test-utils/test-utils.ts
- packages/website/src/components/typeDetails/SimplifiedTreeView.tsx
- fixes #9076, 
- fixes #10007
- Basically completely rewrite the existing method `findAssertedArgument` in SBE to use `checker.getResolvedSignature()` and `checker.getTypePredicateOfSignature()`, and move it into shared location
- Put new behavior behind option "checkTypePredicates" - see [this discord conversation](https://discord.com/channels/508357248330760243/1287101496269213778) for the thought process on naming
- Add docs
- Enable internally and suppress violations
> feat(eslint-plugin): [no-unnecessary-condition] add checkTypePredicates

- packages/eslint-plugin/docs/rules/await-thenable.mdx
- packages/eslint-plugin/src/rules/await-thenable.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/await-thenable.shot
- packages/eslint-plugin/tests/rules/await-thenable.test.ts
Just ask the type checker if a `Symbol.asyncIterator` is present, ezpz. Add tests and docs (less ezpz).
> feat(eslint-plugin): [return-await] check for-await loop iteree

- packages/typescript-estree/src/parseSettings/inferSingleRun.ts
I just ran into this at work.
Our codebase runs ESLint via a script that is eval'd.
So we run `node --eval "code goes here"`
In this instance `process.argv.length === 1` -- so our single run infer code crashes!
> fix(typescript-estree): fix crash when running from a `node --eval` script

- packages/eslint-plugin/src/rules/ban-ts-comment.ts
- packages/eslint-plugin/tests/rules/ban-ts-comment.test.ts
This PR resolves #8753 and stops warning on `// @ts-nocheck` comments which are not at the beginning of the file:
```ts
const a = 1;
// @ts-nocheck - should not be reported
// TS error is not actually suppressed
const b: string = a;
```
> fix(eslint-plugin): stop warning on @ts-nocheck comments which aren't at the beginning of the file

- packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-parameters.test.ts
I thought it was something in the scope manager but it turned out to be really simple: in `setItem<T>(T): T`, the variable `T` has two declarations, and it's both a type and a value. Therefore we can't assume that the type parameters declared aren't also available as values.
> fix(eslint-plugin): [no-unnecessary-type-parameters] cannot assume variables are either type or value

- packages/eslint-plugin/tests/rules/no-use-before-define.test.ts
- packages/scope-manager/src/referencer/Referencer.ts
- packages/scope-manager/tests/fixtures/ts-module/nested-namespace-alias.ts
- packages/scope-manager/tests/fixtures/ts-module/nested-namespace-alias.ts.shot
`A.X.Y` is `TSQualifiedName`
Before:
Visit `A.X` (another `TSQualifiedName`), this will create extra reference for `X` variable. Therefore, the `const X` variable has two references instead of one.
```ts
import Z = A.X.Y
//         ^^^
```
Now:
Visit only `A` (`Identifier`)
```ts
import Z = A.X.Y
//         ^
```
> fix(scope-manager): [no-use-before-define] do not treat nested namespace aliases as variable references

- packages/typescript-estree/src/create-program/createProjectProgramError.ts
- packages/typescript-estree/src/create-program/shared.ts
- packages/typescript-estree/src/useProgramFromProjectService.ts
- packages/typescript-estree/tests/lib/parse.test.ts
- packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
> fix(typescript-estree): improve project service error message when file extension missing from extraFileExtensions

- packages/eslint-plugin/src/rules/no-unused-vars.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
Ensure that `no-unused-vars` never complains about the naming of an enum member, whether it is used or unused.
> fix(eslint-plugin): [no-unused-vars] never report the naming of an enum member

- packages/eslint-plugin/eslint-recommended-raw.d.ts
- packages/eslint-plugin/package.json
- packages/eslint-plugin/rules.d.ts
- packages/eslint-plugin/src/configs/eslint-recommended-raw.ts
- packages/eslint-plugin/src/index.ts
- packages/eslint-plugin/src/rules/index.ts
> fix(eslint-plugin): correct use-at-your-own-risk type definitions

- packages/eslint-plugin/src/rules/await-thenable.ts
- packages/eslint-plugin/tests/rules/await-thenable.test.ts
Handle Union types in in the for-statement of the `await-thenable` rule.
If type is Union, we loop through each types to check if it contains an async Iterator.
If that's the case, we don't report an error.
> fix(eslint-plugin): handle unions in await...for

- packages/rule-tester/src/RuleTester.ts
I don't really get the circular JSON problem but looks like we can suppress it by just rethrowing the exception 🤷‍♂️
> chore(rule-tester): rethrow exceptions in RuleTester to avoid circular JSON issue

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
I put this in to debug during development and accidentally left it in, see https://github.com/typescript-eslint/typescript-eslint/pull/10009/files#diff-3cc43b506517aba406ae3a31d7998b116c4b09db76b632c6cb3c2e54fc71d66cR144
> chore(eslint-plugin): [no-unnecessary-condition] remove dead suggestion id

- packages/typescript-eslint/src/config-helper.ts
- packages/typescript-eslint/tests/configs.test.ts
> fix(typescript-eslint): propagate `name` field to extended configs in `config` helper

- docs/getting-started/Typed_Linting.mdx
Hello, this is just small PR to fix typo in the documentation, I've stumbled upon this when I was trying to setup typescript eslint with eslint v9, I didn't find any issue addressing it and I didn't find any PR also.
> docs: fix typo

- packages/eslint-plugin-internal/jest.config.js
- packages/eslint-plugin/jest.config.js
Change [`coveragePathIgnorePatterns`](https://jestjs.io/docs/configuration#coveragepathignorepatterns-arraystring) to [`modulePathIgnorePatterns`](https://jestjs.io/docs/configuration#modulepathignorepatterns-arraystring) to fix #10146.
> chore: coverage issues caused by using `export` assignments

- packages/eslint-plugin/src/rules/class-literal-property-style.ts
- packages/eslint-plugin/tests/rules/class-literal-property-style.test.ts
Note that this affects both the 'getters' and 'fields' style.
> fix(eslint-plugin): [class-literal-property-style] don't report nodes with `override` keyword

- docs/users/Dependency_Versions.mdx
eslint's supported version range information has been modified to refer to peerDependencies in package.json of the eslint-plugin package.
> docs: fix the Dependency Versions lists

- docs/users/Shared_Configurations.mdx
`tsconfigDirName` seems to be a mistake, because this property is mentioned only in one place and does not exist anywhere in the codebase
> docs: fix property name

- packages/type-utils/tests/getConstrainedTypeAtLocation.test.ts
Added tests for getConstrainedTypeAtLocation function.
> test(type-utils): add tests for getConstrainedTypeAtLocation

- packages/rule-tester/src/RuleTester.ts
- packages/rule-tester/tests/filename.test.ts
Allowing custom filenames outside the current directory in `RuleTester`.
Fix is similar to the one in ESLint [fix: handle absoulte file paths in RuleTester #17989](https://github.com/eslint/eslint/pull/17989).
Since we cannot directly use `FlatConfigArray`, I mock it with an Object containing a `basePath` property.
> fix(rule-tester): allow custom filename outside directory

- packages/eslint-plugin/tests/rules/no-unsafe-argument.test.ts
I was making some changes as part of another PR and noticed this. I didn't open an issue with how small this is, I hope this is OK.
Errors like this will surface once https://github.com/typescript-eslint/typescript-eslint/issues/8298 is tackled.
> test(eslint-plugin): fix a typo in a test, causing it to test the `error` type rather than the `unknown` type

- packages/type-utils/src/predicates.ts
Prevents the whole type from being looped through `isThenableType` once for each part of the type.
> fix(eslint-plugin): [no-unsafe-return] don't reiterate through all type parts for each part

- eslint.config.mjs
- packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
- packages/website-eslint/src/mock/path.js
- packages/website/src/theme/prism-include-languages.js
- packages/website/tools/typedoc-plugin-no-inherit-fork.mjs
Purely switches the ESLint config and some necessary inline comments. Doesn't attempt to remove existing annotations.
💖
> chore: switch from explicit-function-return-type to explicit-module-boundary-types internally

- packages/rule-tester/src/RuleTester.ts
- packages/rule-tester/tests/filename.test.ts
If the `filename` specified in a test is absolute or steps up at least one directory, then the `Linter`'s `cwd` option is used to specify the base path.
When creating a `FlatConfigArray`, ESLint uses the linter's `cwd` option to specify the base path:
https://github.com/eslint/eslint/blob/725962731538eaa38d5d78b9e82ce3fccc9762d0/lib/linter/linter.js#L1524
The `cwd` option is specified when creating the `Linter` object:
https://github.com/eslint/eslint/blob/3a4eaf921543b1cd5d1df4ea9dec02fab396af2a/lib/linter/linter.js#L1304
That means the `RuleTester` may need to create multiple `Linter` objects. I've created a Map of `Linter` objects keyed by their base path. 
For absolute paths and paths that step up a directory, the base path is calculated by resolving the file name relative to either …
> fix(rule-tester): use cwd option to set base path for tests with file name

- packages/eslint-plugin/docs/rules/switch-exhaustiveness-check.mdx
- packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/switch-exhaustiveness-check.shot
- packages/eslint-plugin/tests/rules/switch-exhaustiveness-check.test.ts
> fix(eslint-plugin): [switch-exhaustiveness-check] invert `considerDefaultExhaustiveForUnions`

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
This adds a utility function to check for a falseyBigInt. I implemented functions to convert `type.value` to BigInt when necessary, yet this still required the extra condition in `checkNode` for the specific edge case.
> fix(eslint-plugin): [no-unnecessary-condition] falsey bigint should be falsey

- docs/troubleshooting/faqs/General.mdx
This doesn't address an issue, but I thought it was too small of a change to make an issue out of it 💯 
This simply fixes a small typo in the docs
> docs: fix typo in docs

- docs/troubleshooting/faqs/General.mdx
This a documentation change. It makes the General FAQ less confusing
> docs: fix "the a" typo in FAQ

- packages/types/src/ts-estree.ts
This PR fixes the `ImportAttribute#parent` type.
> fix(types): parent property type annotation in the ImportAttribute node

- packages/utils/src/ts-eslint/Config.ts
According to the docs for ESLint an array should be allowed here, and the type used by ESLint in their `ESLint.Plugin` interface is:
Record<string, Linter.LegacyConfig | Linter.Config | Linter.Config[]> | undefined
So we should also allow an array. The helper function `tseslint.config` returns an array so without this you're not allowed to use a config returned by this function as a value in this record.
Fixes #10213
💖
> fix(utils): allow an array for the values of SharedConfig

- packages/eslint-plugin/src/rules/consistent-type-definitions.ts
- packages/eslint-plugin/tests/rules/consistent-type-definitions.test.ts
rewrite the fixer to be more robust
> fix(eslint-plugin): [consistent-type-definitions] don't leave trailing parens when fixing type to interface

- packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
- packages/eslint-plugin/tests/rules/switch-exhaustiveness-check.test.ts
This PR resolves #10228. Apparently, TypeScript has a different type [when a property could be missing](https://github.com/microsoft/TypeScript/blob/cb44488fcec4348a448434afbf2ebcbf2b423c61/src/compiler/checker.ts/#L2059) rather than the standard `undefined` type. Both types have the same object flags but different `debugIntrinsicName`, making them not match for the current equality check (along with a different `id` key). 
This issue isn't related to the recent fix in https://github.com/typescript-eslint/typescript-eslint/pull/10223 and can be tracked a while back. I didn't bother checking that the type is actually the missing type (it would require checking the currently untyped `debugIntrinsicName`) and just comparing for the standard undefined object flags (which match both the …
> fix(eslint-plugin): [switch-exhaustiveness-check] add support for covering a missing property with `undefined`

- packages/eslint-plugin/docs/rules/await-thenable.mdx
- packages/eslint-plugin/src/rules/await-thenable.ts
- packages/eslint-plugin/src/rules/prefer-optional-chain-utils/analyzeChain.ts
- packages/eslint-plugin/src/rules/return-await.ts
- packages/eslint-plugin/src/util/getFixOrSuggest.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/await-thenable.shot
- packages/eslint-plugin/tests/docs.test.ts
- packages/eslint-plugin/tests/rules/await-thenable.test.ts
Basically just checks whether the RHS of an `await using` statement _might_ have a `[Symbol.asyncDispose]()`, otherwise reports. 
Added in docs and a couple minor refactors. Also modified the `getFixOrSuggest()` method to allow providing _no_ fix or suggestion.
> feat(eslint-plugin): [await-thenable] report unnecessary `await using` statements

- eslint.config.mjs
- packages/eslint-plugin/docs/rules/no-confusing-void-expression.mdx
- packages/eslint-plugin/tests/docs.test.ts
- Fix lint errors 
- Fix website build error
> chore: fix lint and build website errors

- packages/eslint-plugin/docs/rules/no-deprecated.mdx
TypeScript can't visualize deprecated code, editors can.
> docs: [no-deprecated] awkward wording about TypeScript visualizing deprecated code

- packages/eslint-plugin/src/rules/await-thenable.ts
- packages/eslint-plugin/src/rules/return-await.ts
- packages/eslint-plugin/src/util/index.ts
- packages/eslint-plugin/src/util/needsToBeAwaited.ts
- packages/eslint-plugin/tests/rules/await-thenable.test.ts
- packages/eslint-plugin/tests/rules/return-await.test.ts
This PR resolves #10311 and stops reporting on some type constraints (see [playground link](https://typescript-eslint.io/play/#ts=5.6.2&fileType=.ts&code=PTAEBcE8AcFNWgQwE6ILa3LZoDuBLcAC1ADsB7UAY3NIGdxV9TwAoROyUq0AMwFdu4fLQiwGARgA8AFQB8ACgBuiADb9YALlAyAlKADerUKGSZ%2ByUqES5EhUCvWwA3KwC%2BrViAgx4SVBhYOATEoAAGiKSQYaDkOGGCANYUuKQxNPSMdizsnNx8glTColgMAEyyoLAAHlikACZ0oEkppIqOGtp6hsam5pbWtvYdLu6eHFw8AkIiVqXgAMyVNXWN1lHtap06%2BkYmZuAWVjZ24A5box5eYPX4ZkXhkdGx8S3kqTFQcAgcdOK5kwKMxK4nAABZlBdtG9UrtegcjoNTucnK4rhN8tMirMxAwAKyQpzaJ5w-b9Y5DM4jNGsIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AQwHd3K78ALRE3YAjJOiiJo0APbRI4MAF8QSoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)).
As per @kirkwaiblinger's …
> fix(eslint-plugin): [await-thenable, return-await] don't flag awaiting unconstrained type parameter as unnecessary

- packages/utils/src/ts-eslint/Config.ts
Added optional `language` field.
> feat(utils): add new optional `language` field to `FlatConfig.Config` type

- packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts
- packages/eslint-plugin/tests/rules/explicit-function-return-type.test.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
This PR resolves #10231 and adjusts both `explicit-module-boundary-types` and `explicit-function-return-type` to not fail on the following when `allowDirectConstAssertionInArrowFunctions` is enabled:
```ts
type Foo = {
foo: string,
bar: number,
};
export const a = () => ({
foo: "FOOO",
bar: 123,
}as const); // <-- This works as expected.
export const b = () => ({
foo: "FOOO",
bar: 123,
} as const satisfies Foo); // <-- This unexpectedly causes the rules to report.
```
> fix(eslint-plugin): [explicit-module-boundary-types] and [explicit-function-return-type] don't report on `as const satisfies`

- packages/rule-tester/src/RuleTester.ts
- packages/rule-tester/tests/RuleTester.test.ts
- packages/utils/src/ts-utils/NoInfer.ts
- packages/utils/src/ts-utils/index.ts
> [!CAUTION]
> The issue is not marked with the label "accepting prs" right now but [there is a comment about making this change](https://github.com/typescript-eslint/typescript-eslint/issues/10321#issuecomment-2469603873)
Added `NoInfer` on `RuleTester#run` `tests` parameter. 
This change prevent to infer `MessageIds` and `Options` type parameters from the `tests` parameter which may cause  incorrect types when using helper functions.
> [!NOTE]
> [Currently typescript version range (`>=4.8.4 <5.7.0`)](https://typescript-eslint.io/users/dependency-versions/#typescript) supports versions that do not have the `NoInfer` utility type included ([`>= 5.4`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-4/#the-noinfer-utility-type)).
> To solve the problem I added a `NoInfer` …
> feat(rule-tester): run method - avoid to infer type parameter from `tests` param

- packages/eslint-plugin/src/rules/no-deprecated.ts
- packages/eslint-plugin/tests/rules/no-deprecated.test.ts
Report deprecations which are used in default exports - this is the way typescript compiler reports deprecations.
> fix(eslint-plugin): report deprecations used in default export

- packages/eslint-plugin/src/rules/no-confusing-void-expression.ts
My ooops on #10067.
Would it make sense to use a generic ([here](https://github.com/typescript-eslint/typescript-eslint/blob/746560aab8b8df6fed02219f03e866795cdc58c6/packages/utils/src/eslint-utils/RuleCreator.ts#L29)) to enforce that every rule provides default values for every one of its options (so that mistakes like this don't repeat)?
> docs(eslint-plugin): [no-confusing-void-expression] add a default value for `ignoreVoidReturningFunctions`

- docs/getting-started/Quickstart.mdx
This PR removed `@types/eslint__js` from install script in quickstart steps.
For it has been built-in supported since https://github.com/eslint/eslint/pull/19010.
> docs: remove `@types/eslint__js` from quickstart step

- packages/typescript-estree/src/parseSettings/warnAboutTSVersion.ts
I don't really know what I'm doing (this is my first PR to this repository), but I think that in https://github.com/typescript-eslint/typescript-eslint/pull/10372 , the update to version list in `typescript-estree` might have slipped through, `typescript-estree` was still declaring that it only supports TS versions below 5.7.0 (so users of TS 5.7 are currently still getting warnings about unsupported TS version even on the latest typescript-eslint at 8.15.1-alpha.6).
Seeing how for previous TS versions, const SUPPORTED_TYPESCRIPT_VERSIONS was updated in the same "feat: support TypeScript X.Y" pull requests as everything else, it seems that it should have went there, but it didn't, so I'm creating a separate PR for it.
I also took a liberty of upgrading the lowest supported version from …
> fix(typescript-estree): update conditions for unsupported version warning

- packages/eslint-plugin/src/rules/no-unnecessary-template-expression.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-template-expression.test.ts
- packages/eslint-plugin/tests/rules/no-useless-constructor.test.ts
Basically just checks for an unescaped new line literal following the expression, and checks whether the expression is a whitespace literal
I used as a guiding principle "If the user has explicitly provided whitespace to end a line we won't report". This is different from "we won't ever write report on an interpolation fixing which would result in terminal whitespace". For example, this code
```ts
`this has ${'whitespace after fixing       '}
`;
```
fixes to
```
`this has whitespace after fixing       
`;
```
and that is intentional.
It's up to a user to explicitly specify 
```ts
`this has whitespace after fixing${'       '}
`;
// or
`this has whitespace after fixing       ${''}
`;
```
if that's what they want to do
🫡
> fix(eslint-plugin): [no-unnecessary-template-expressions] allow template expressions used to make trailing whitespace visible

- packages/eslint-plugin/docs/rules/no-restricted-types.mdx
- packages/eslint-plugin/src/rules/no-restricted-types.ts
It seems like the `extendDefaults` setting from `ban-types` was ported into `no-restricted-types`, but that setting isn't part of the new rule's documentation nor it's used in its implementation.
> fix(eslint-plugin): remove references to "extendDefaults" in no-restricted-types

- packages/eslint-plugin/src/rules/promise-function-async.ts
- packages/eslint-plugin/tests/rules/promise-function-async.test.ts
This PR resolves #5709 and takes function overloading into consideration.
Currently, the rule flags the following as an issue and auto-fixes it with `async`, even though the actual return type of the function is `Promise<number> | number`:
```ts
function b(): Promise<number>
function b(a: boolean): number
function b(a?: boolean): Promise<number> | number {
return Promise.resolve(1);
}
```
This PR changes the rule to treat the above similarly to how it treats the following:
```ts
function b(a?: boolean): Promise<number> | number {
return Promise.resolve(1);
}
```
> fix(eslint-plugin): [promise-function-async] handle function overloading

- packages/eslint-plugin/package.json
- packages/parser/package.json
- packages/type-utils/package.json
- packages/typescript-eslint/package.json
- packages/typescript-estree/package.json
- packages/utils/package.json
- yarn.lock
`typescript` is a mandatory peer dependency (_peerDepedency_ of `ts-api-utils`) and not optional peer dependency (it needs to be removed from _peerDepedencyMeta_).
- `ts-api-utils` has `typescript` as peer dependency:
```json5
// ts-api-utils/package.json
{
"peerDependencies": {
"typescript": ">=4.2.0"
}
}
```
- `@typescript-eslint/typescript-estree` uses `ts-api-utils` dependency that has `typescript` as peer dependency (see _Info_)
- `@typescript-eslint/utils` uses `@typescript-eslint/typescript-estree` dependency that uses `ts-api-utils` dependency. It needs `typescript` peer dependency
- `@typescript-eslint/parser` uses `@typescript-eslint/typescript-estree` dependency that uses `ts-api-utils` dependency. It needs `typescript` peer dependency
- `@typescript-eslint/type-utils` uses …
> fix: typescript peer dependency

- packages/eslint-plugin/src/rules/no-base-to-string.ts
- packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
- fixes #10431 - ~~⌛ not yet accepting PRs~~ ✅ 
- fixes #8585 - ✅  accepting PRs
#8585 only repros in TS < 5.4, so you'll want to use [the branch playground](https://deploy-preview-10432--typescript-eslint.netlify.app/play/#ts=5.3.3&fileType=.ts&code=C4TwDgpgBAwg9gOwM7AE4FcDGwCGAjAGwgB4BRBYAS1AD4oBeKfFVHbKBCAdygAoA6QTlQBzJAC4mCEAG0AugEoGdclVABuAFCbKFCKgBmbaAHF0lAgBMYACxwJOBKAG9NUKMDgBlNLpG8FSQADYgBiABJnFj8AXxogzRjtSwhMAmFoTEQUJhxJMwtrOwcIAmTU9NRM7OAoAzg4SXhkNCxcQhICq1t7RygAMhcoPGFJAEYoOK00nCQkKFIAD2AIBBTLLqLe0qgIZdXLefq4IaSUmaqoLJbhvEkllbWIDfNu4sdtHBx%2BTx9UPwCUAA9ECoHAANaaPB4H7eXwIfxKEEcOC1CGaIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oCMBDZRLXxdk%2BKkwDm6KImjQO0SODABfECqA&tsconfig=&tokens=false) to verify that the repro in the issue is actually fixed for TS < …
> fix(eslint-plugin): [no-base-to-string] handle more robustly when multiple `toString()` declarations are present for a type

- packages/eslint-plugin/src/rules/use-unknown-in-catch-callback-variable.ts
- packages/eslint-plugin/tests/rules/use-unknown-in-catch-callback-variable.test.ts
Since we're no longer generally flagging expressions that have type `(e: any) => whatever`, I added in recursion to catch function literals not passed directly, but whose type is still inferred. So, `promise.catch(e => condition ? (e) => {} : (e) => {});` still can and does trigger the rule, since `e` is inferred as `any` in both locations. Plus, the rule reports them each individually and consequently offers a suggestion now.
> fix(eslint-plugin): [use-unknown-in-catch-callback-variable] only flag function literals

- packages/eslint-plugin/src/rules/no-unnecessary-template-expression.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-template-expression.test.ts
This PR addresses #10434 and stops the rule from reporting on expressions that include comments:
```ts
`
${/* intentional comment */ 'foo'}
...`;
```
> fix(eslint-plugin): [no-unnecessary-template-expression] don't report when an expression includes comment

- packages/eslint-plugin/src/rules/no-unnecessary-boolean-literal-compare.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-boolean-literal-compare.test.ts
This PR follows-up #10443 and reports on values with a boolean type parameter that are being compared to a boolean literal:
```ts
// fails
const test1: (someCondition: boolean) => void = someCondition => {
if (someCondition === true) {}
};
// should fail
const test2: <T extends boolean>(someCondition: T) => void = someCondition => {
if (someCondition === true) {}
};
```
> fix(eslint-plugin): [no-unnecessary-boolean-literal-compare] flag values of a type parameter with boolean type constraints

- packages/eslint-plugin/docs/rules/explicit-function-return-type.mdx
- packages/eslint-plugin/docs/rules/explicit-module-boundary-types.mdx
- packages/eslint-plugin/docs/rules/non-nullable-type-assertion-style.mdx
- packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.mdx
- packages/eslint-plugin/docs/rules/prefer-reduce-type-parameter.mdx
- packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx
- packages/eslint-plugin/src/rules/no-unsafe-type-assertion.ts
- packages/eslint-plugin/src/rules/non-nullable-type-assertion-style.ts
- packages/eslint-plugin/src/rules/prefer-reduce-type-parameter.ts
- packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/explicit-function-return-type.shot
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/explicit-module-boundary-types.shot
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/prefer-reduce-type-parameter.shot
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/strict-boolean-expressions.shot
This PR addresses #10458 and makes consistent use of asserting vs casting.
There is some inconsistency for casting values: to cast ([`no-extra-boolean-cast`](https://eslint.org/docs/latest/rules/no-extra-boolean-cast)), to coerce (e.g. [`no-implicit-coercion`](https://eslint.org/docs/latest/rules/no-implicit-coercion), [MDN](https://developer.mozilla.org/en-US/docs/Glossary/Type_coercion)), to convert (upcoming [`no-unnecessary-type-conversion`](https://github.com/typescript-eslint/typescript-eslint/pull/10182#issuecomment-2453282643)). To my understanding, these all mean the same thing.
I've used consistent language for casting a value (currently using `to cast`). Please let me know if this sounds OK or if I should change it back.
> fix(eslint-plugin): use consistent naming for asserting types and casting values

- packages/typescript-eslint/src/config-helper.ts
- packages/typescript-eslint/src/index.ts
Names and exports the types so that projects using `declaration: true` will not see errors
> fix(typescript-eslint): export types so that declarations can be named for dts files

- packages/eslint-plugin/src/rules/no-deprecated.ts
- packages/eslint-plugin/tests/rules/no-deprecated.test.ts
I have fixed the bug in the title.
🐝
> fix(eslint-plugin): [no-deprecated] not reporting usages of deprecated declared constants as object value

- packages/eslint-plugin/src/rules/prefer-reduce-type-parameter.ts
- packages/eslint-plugin/tests/rules/prefer-reduce-type-parameter.test.ts
This PR tackles #3440 and makes the rule skip cases where the type assertion is necessary and auto-fixing to using `reduce()`'s type parameter will result in a type error.
Alternatively, as code that does this isn't exactly safe, the rule can still report such cases but use a suggestion instead of an auto-fix (although `no-unsafe-type-assertion` will report the assertion as unsafe).
> fix(eslint-plugin): [prefer-reduce-type-parameter] don't report cases in which the fix results in a type error

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
This PR addresses #10442 and handles a potential return type being a type constraint.
The PR suffers from the same issues around `getConstrainedTypeAtLocation` described by @kirkwaiblinger on #10438 and requires a small workaround.
Note that `no-unnecessary-condition` makes a lot of use of `getConstrainedTypeAtLocation`, but going over them roughly, I couldn't find additional bugs around unconstrained type parameters.
> fix(eslint-plugin): [no-unnecessary-condition] don't flag values of an unconstrained or valid type parameter

- packages/eslint-plugin/src/rules/consistent-type-assertions.ts
- packages/eslint-plugin/tests/schema-snapshots/consistent-type-assertions.shot
Removes the schema requirement for `assertionStyle` to be provided, on the basis that when the `defaultOptions` are merged, an `assertionStyle` value of "as" will be used if none was provided.
This allows a user to supply partial options in their config, for example to override `objectLiteralTypeAssertions: 'never'` but retain the default `assertionStyle: 'as'`, e.g. the following now works:
```js
{
'@typescript-eslint/consistent-type-assertions: [
'error',
{ objectLiteralTypeAssertions: 'never' }
]
}
```
Note: I had intended to include a test case that omits the `assertionStyle` option, but I have a suspicion that the rule tester doesn't merge defaults, as I was unable to get the test to pass schema validation despite the fact that I had manually tested the change and can confirm that it …
> fix(eslint-plugin): [consistent-type-assertions] allow default assertionStyle option

- packages/eslint-plugin/src/rules/array-type.ts
- packages/eslint-plugin/tests/rules/array-type.test.ts
I added 3 new test cases that cover the auto-fix of the array-filter rule when used with conditional types. Afterwards I used the hint in the issue and added the typescript AST node "TSConditionalType" to the switch case which made the test case succeed.
I also linked my local typescript-eslint version using my package manager and check that it handles the original case in my code base, which made me open the issue, correctly.
Please feel free to provide feedback, this is my first contribution to typescript-eslint or such a big project at all for that matter.
> fix(eslint-plugin): [array-type] autofix with conditional types needs parentheses

- packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
- packages/eslint-plugin/src/util/isNodeEqual.ts
- packages/eslint-plugin/tests/rules/consistent-indexed-object-style.test.ts
- packages/utils/src/json-schema.ts
This PR tackles #7863 and replaces the current logic for detecting circular references with one that also checks for indirect cycles:
```ts
export type ExampleUnion = boolean | number;
export type ExampleRoot = ExampleUnion | ExampleObject;
export interface ExampleObject {
[key: string]: ExampleRoot;
}
```
The PR also flags some recursive patterns that are valid as a type reference (and can be fixed into a `Record<...>` form), which currently the rule doesn't flag ([playground link](https://typescript-eslint.io/play/#ts=5.7.2&fileType=.ts&code=JYOwLgpgTgZghgYwgAgCoQM5gIzIN4BQyyA2gNYQCeAXMllKAOYC6teyMA9p7elrgF8A3AQEECAegnIwACxRwARpwBuKYBmQB5ANLI4muDMoAHFFAgxoEEEmSKArmGQaQAcmcWTnKJAAmBGCmKHxgAEzIALzIAEoQCD5%2BADz0TAA0%2BBzcvJjhyAIAfCIEoJCwiCG5AMz4RKQUNHRgDCAsOVhVJMwiYpLScgrKai6auvqGxmbIFlYWt …
> fix(eslint-plugin): [consistent-indexed-object-style] don't report on indirect circular references

- packages/eslint-plugin/src/rules/member-ordering.ts
- packages/eslint-plugin/tests/rules/member-ordering.test.ts
Change this rule to ignore overloading method definitions that do not have an implementation. https://github.com/typescript-eslint/typescript-eslint/issues/2409#issuecomment-678837924
```ts
class Foo {
myMethod(a: string); // skip
myMethod(a: number); // skip
myMethod(a: number, b: string); // skip
myMethod(a: string | number, b?: string) { // check
alert(a.toString());
}
}
```
> fix(eslint-plugin): [member-ordering] ignore method overloading

- packages/eslint-plugin/src/rules/no-shadow.ts
- packages/eslint-plugin/tests/rules/no-shadow/no-shadow.test.ts
This PR addresses #10539 and adjusts the rule to include the following ways of defining functions (and their parameters) behind the `ignoreFunctionTypeParameterNameValueShadow` flag: 
```ts
const arg1 = 0;
declare function test1(arg1: string): typeof arg1;
const arg2 = 0;
declare class Test3 {
p2(arg2: string): typeof arg2;
}
```
> fix(eslint-plugin): [no-shadow] report correctly on parameters of functions declared with the `declare` keyword

- packages/eslint-plugin/package.json
- packages/eslint-plugin/src/rules/no-base-to-string.ts
- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/src/rules/no-unnecessary-type-parameters.ts
- packages/type-utils/package.json
- packages/type-utils/src/builtinSymbolLikes.ts
- packages/typescript-estree/package.json
- yarn.lock
Bump the version. Also remove workarounds for several fixed bugs (they were all fixed by v1.4.3 already).
> chore: upgrade to ts-api-utils 2.0

- packages/eslint-plugin/docs/rules/strict-boolean-expressions.mdx
- packages/eslint-plugin/src/rules/strict-boolean-expressions.ts
- packages/eslint-plugin/tests/rules/strict-boolean-expressions.test.ts
Changed fixes to suggestions, ezpz.
Also removed the fix/suggestion section from the rule docs since it was an eyesore and it's no longer useful, now that there are _no_ autofixes.
> fix(eslint-plugin): [strict-boolean-expressions] remove remaining (unsafe) autofixes

- packages/eslint-plugin/src/rules/no-deprecated.ts
- packages/eslint-plugin/tests/rules/no-deprecated.test.ts
I have fixed the bug in the title.
🐛
> fix(eslint-plugin): [no-deprecated] doesn't report on shorthand property in an object expression

- packages/eslint-plugin/src/rules/no-unnecessary-template-expression.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-template-expression.test.ts
Switches the `no-unnecessary-template-expression` rule to use `getConstraintInfo` internally.
Related #10569
Assuming I've done the right thing here, let me know and i'll happily do most of the others. I'm just using this as a way to get my head back into the codebase
> chore(eslint-plugin): use `getConstraintInfo` in no-unnecessary-template-expression

- packages/website/docusaurus.config.mts
Hi there👋
I've noticed the code blocks with the languages `bash` and `diff` were missing syntax highlighting in the docs. These languages need to be manually added in the `docusaurus` config file. This PR fixes this issue.
Let me know if I should create an issue ticket, I thought this is a minor enough change^^
Getting started page before & after:
Troubleshooting before & after:
> docs: add syntax highlighting for bash and diff blocks

- packages/eslint-plugin/docs/rules/no-unnecessary-condition.mdx
A small change to fix an incorrect variable name used in a comment in one of the code examples
> docs: fix incorrect variable name in a comment in code example

- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unnecessary-condition.shot
Looks like https://github.com/typescript-eslint/typescript-eslint/pull/10613 was just missing the associated snapshot
> chore: fix CI snapshot failure

- packages/eslint-plugin/tests/rules/class-methods-use-this/class-methods-use-this.test.ts
- packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
- packages/eslint-plugin/tests/rules/no-array-delete.test.ts
Adds a couple of extra test cases for these rules:
- `class-methods-use-this`
- `consistent-type-assertions`
- `no-array-delete`
wasn't sure why you have a `core` tests file for `class-methods-use-this`. so let me know which one this test belongs in
> test(eslint-plugin): add extra tests

- packages/eslint-plugin/src/rules/no-empty-interface.ts
- tools/scripts/generate-configs.mts
I keep forgetting to do this quick little fixup...
💖
> chore: throw error in generate-configs if rule is deprecated and recommended

- packages/eslint-plugin/docs/rules/no-deprecated.mdx
- packages/eslint-plugin/src/rules/no-deprecated.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-deprecated.shot
- packages/eslint-plugin/tests/rules/no-deprecated.test.ts
- packages/eslint-plugin/tests/schema-snapshots/no-deprecated.shot
This PR addresses issue #9899.
Add an `allow` option of type [TypeOrValueSpecifier](https://typescript-eslint.io/packages/type-utils/type-or-value-specifier/). The types/values specified in the `allow` option are allowed to be used even if deprecated.
> feat(eslint-plugin): [no-deprecated] add allow options

- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
This PR resolves #10600 and removes some duplicated logic for checking special-case types in a union (`any`, `unknown`, or types with the `TypeVariable` type flag).
The current implementation seems to pick up unconstrained type parameters by checking the presence of the `TypeVariable` type flag. I think this is necessary (over `getConstraintInfo`) as the check needs to detect types such as the following:
```ts
function test<T>(arg: T, key: keyof T) {
if (arg[key]) {
//
}
}
```
> fix(eslint-plugin): [no-unnecessary-condition] don't flag optional chaining for union types with an unconstrained type parameters

- packages/typescript-eslint/src/config-helper.ts
Update jsdoc of config helper function to non-spread form so that its consistent with the docs on the website.
> docs(typescript-eslint): make jsdoc for config helper function consistent

- eslint.config.mjs
- packages/eslint-plugin-internal/src/rules/debug-namespace.ts
- packages/eslint-plugin-internal/src/rules/index.ts
- packages/eslint-plugin-internal/tests/rules/debug-namespace.test.ts
- packages/type-utils/src/predicates.ts
- packages/typescript-estree/src/create-program/createIsolatedProgram.ts
- packages/typescript-estree/src/create-program/createProjectProgram.ts
- packages/typescript-estree/src/create-program/createProjectService.ts
- packages/typescript-estree/src/create-program/createSourceFile.ts
- packages/typescript-estree/src/create-program/getWatchProgramsForProjects.ts
- packages/typescript-estree/src/create-program/useProvidedPrograms.ts
- packages/typescript-estree/src/parseSettings/createParseSettings.ts
- packages/typescript-estree/src/parseSettings/getProjectConfigFiles.ts
- packages/typescript-estree/src/parseSettings/resolveProjectList.ts
Adds a new `@typescript-eslint/internal/debug-namespace` lint rule that makes sure any `const log = debug('...')` uses a namespace equivalent to the package name, file directory, and file path. 
This caught several discrepancies in existing namespaces. I don't think we need to count this as a breaking change as those namespaces really aren't part of the public API. But this does constitute a `feat:` I think.
💖
> feat: standardize debug namespaces to file paths

- packages/eslint-plugin/docs/rules/consistent-type-assertions.mdx
- packages/eslint-plugin/src/rules/consistent-type-assertions.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/consistent-type-assertions.shot
- packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
- packages/eslint-plugin/tests/schema-snapshots/consistent-type-assertions.shot
This pr addresses #6374 and adds `arrayLiteralTypeAssertions` option to the `consistent-type-assertions` rule.
It starts from #6749, which was previously closed, and adds `allow-as-parameter` to the `arrayLiteralTypeAssertions` option. (https://github.com/typescript-eslint/typescript-eslint/pull/6749#discussion_r1161060475)
Co-authored-by: @danvk
> feat(eslint-plugin): [consistent-type-assertions] add arrayLiteralTypeAssertions options

- packages/eslint-plugin-internal/src/rules/debug-namespace.ts
- packages/rule-tester/src/RuleTester.ts
Resolves an issue caused by #10599.
> fix(eslint-plugin-internal): [debug-namespace] on windows

- packages/eslint-plugin/src/rules/no-unnecessary-type-arguments.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-arguments.test.ts
> fix(eslint-plugin): [no-unnecessary-type-arguments] handle type args on jsx

- packages/eslint-plugin/src/rules/no-misused-spread.ts
- packages/eslint-plugin/tests/rules/no-misused-spread.test.ts
This PR addresses #10648 and adjusts the rule to check `JSXSpreadAttribute` nodes for being valid object-spread.
I didn't add any check for the other type of JSX spread node, `JSXSpreadChild`, as it seems TypeScript always flags it if it isn't an array:
```ts
<div>{...x}</div>
```
Even if the type being spread is a `string`, it still gets reported by TypeScript ([playground link](https://typescript-eslint.io/play/#ts=4.8.4&fileType=.tsx&code=CYUwxgNghgTiAEYD2A7AzgF3gDwFz0xgEsUBzAbgChKAeYIgNwD4BvAOg%2BwF8aB6e5lSA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6Jge1oFtLlZkiACa1kxaIgCGQ9FETRoHaJHBgAviDVA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)). I've checked this is reported on the lowest version of TypeScript …
> fix(eslint-plugin): check JSX spread elements for misused spread usage

- packages/scope-manager/src/referencer/Referencer.ts
- packages/scope-manager/tests/fixtures/jsx/children.tsx.shot
- packages/scope-manager/tests/fixtures/jsx/namespaced-attribute.tsx.shot
Addresses #9790 and registers a reference for the closing JSX element if it exists.
> fix(scope-manager): add a reference for JSX closing element if it exists

- packages/rule-tester/src/RuleTester.ts
While testing, I accidentally raised the wrong PRs to this repository. Sorry for the unnecessary notifications. 😢 
Eventually, I figured out the cause using a PC with window OS that I hadn't used in a long time. 😄
> fix(rule-tester): handle window root path

- packages/eslint-plugin/src/rules/no-for-in-array.ts
- packages/eslint-plugin/tests/eslint-rules/no-undef.test.ts
- packages/eslint-plugin/tests/fixtures/tsconfig.lib-dom.json
- packages/eslint-plugin/tests/rules/no-for-in-array.test.ts
See https://github.com/typescript-eslint/typescript-eslint/pull/10535#issuecomment-2564044282 for the updated contents of this PR.
~~This PR tackles #10534 and reports on cases such as:~~
```ts
declare const maybeArr: string[] | undefined;
declare const arr: string[];
// fails correctly
for (const item in arr) {}
// should fail, same with `T[] | null`
for (const item in maybeArr) {}
```
> fix(eslint-plugin): [no-for-in-array] report on any type which may be an array or array-like

- packages/eslint-plugin/src/rules/no-base-to-string.ts
- packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
This PR addresses #10632 and fixes the rule so it does not fail on recursive array or tuple types. It looks like this regression has been introduced in #10437.
---
Not directly related: It seems not intentional, but since #10437, the rule reports invalid nested array types (which it didn't previously):
```ts
declare const s: { foo: 'bar' }[][];
// [object Object]
s.join();
```
Previously, the array check (which used to run only on `array.join()`) never checked for nested array types. This changed on #10437, and the recursive check also runs as part of `array.join()` (which means the crash reproduces on recursive `array.join()` too, [playground link](https://typescript-eslint.io/play/#ts=5.7.2&fileType=.tsx&code=KYDwDg9gTgLgBDAnmYcBqBDANgV1QXgCg44AfOHAOwBNgAzAS0uGuLLgCMIItgNK25SjgC2HYFEFwAz …
> fix(eslint-plugin): [no-base-to-string] don't crash for recursive array or tuple types

- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
I've noticed this while reviewing https://github.com/typescript-eslint/typescript-eslint/pull/10618.
To my understanding, these tests should make sure the rule [doesn't report on template literals with expressions](https://github.com/typescript-eslint/typescript-eslint/blob/31be0532065491d9141cbddfe42dd771eadc0a82/packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts#L171-L175).
It seems that even if this check is removed, these tests still pass. I think it's related to "fresh literals" ([more on this here](https://github.com/typescript-eslint/typescript-eslint/pull/10631)), as is shown below ([playground link](https://typescript-eslint.io/play/#ts=5.7.3&fileType=.ts&code=MYewdgzgLgBAZiEMC8MDkCRoNwChcD0BMUAFgKYwAGFANrUgCQDemAvlTOQB4AOATuQgQAluBgATEEJigArmFgBDCDCUxaIqOX5LauUJFjb …
> test(eslint-plugin): adjust tests to verify `no-unnecessary-type-assertion` doesn't report template literals with expressions

- packages/type-utils/src/TypeOrValueSpecifier.ts
- packages/type-utils/src/typeOrValueSpecifiers/specifierNameMatches.ts
- packages/type-utils/tests/TypeOrValueSpecifier.test.ts
This PR attempts to tackle #10665 and adds support for matching intersection types with `TypeOrValueSpecifier` with a [`PackageSpecifier`](https://typescript-eslint.io/packages/type-utils/type-or-value-specifier/#packagespecifier).
I've written my thoughts about this issue on https://github.com/typescript-eslint/typescript-eslint/issues/10665#issuecomment-2596137452.
---
Some more thoughts:
- This also affects [`LibSpecifier`](https://typescript-eslint.io/packages/type-utils/type-or-value-specifier/#libspecifier) (which I think is correct), though I couldn't find an actual type on TypeScript's built-in lib types to test this on.
- It seems that for nested intersections the specifier won't match (I think this is [mentioned here too](https://github.com/typescript-eslint/typescript-eslint/blo …
> fix(type-utils): support matching intersection types in `TypeOrValueSpecifier` with a `PackageSpecifier`

- packages/eslint-plugin/docs/rules/no-unused-vars.mdx
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unused-vars.shot
Explains the broad overview of type-only variables being extra code + runtime complexity.
Adds a couple of straightforward examples in tags. I'm up for adding more on request, just didn't want to overload the page at first.
Uses a blank `## Options` section to push the FAQs to after `## How to Use` and `## Options`. Especially given https://github.com/eslint/eslint.org/pull/664 likely releasing soon, I feel less pressure than a few years ago to prioritize emphasizing why to use the rule over TS options.
💖
> docs(eslint-plugin): [no-unused-vars] add types-only values FAQ

- packages/eslint-plugin/src/rules/no-duplicate-type-constituents.ts
- packages/eslint-plugin/tests/rules/no-duplicate-type-constituents.test.ts
It addresses #9496.
Changed to recursively traverse constituents to find nested duplicate types.
> fix(eslint-plugin): [no-duplicate-type-constituents] handle nested types

- packages/eslint-plugin/docs/rules/no-unnecessary-template-expression.mdx
- packages/eslint-plugin/src/rules/no-unnecessary-template-expression.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unnecessary-template-expression.shot
- packages/eslint-plugin/tests/rules/no-unnecessary-template-expression.test.ts
This pr addresses #9971.
I didn't apply all the tests written for `TemplateLiteral`s to `TemplateLiteralType`s because it shares most of its logic with `TemplateLiteral`s.
This includes tests for basic behavior similar to `TemplateLiteral` and some behavior that must be handled separately for `TemplateLiteralType`.
```ts
type Type = `${"aa"}`; // error
type Type = `a${"aa"}`; // error
type Type = `a${"aa" /* comments */}`;; // no-error
// enum
enum MyEnum { A = "A", B = "B"}
type Type = `${MyEnum}`; //  no-error
type Type = `${MyEnum.A}`; // error
// TSNullKeyword & TSUndefinedKeyword
type Type = `${null}`; // error
type Type = `${undefined}`; // error
```
> fix(eslint-plugin): [no-unnecessary-template-expression] handle template literal type

- packages/types/src/ts-estree.ts
This PR addresses #10682, follows #9560 up, and adds strict `parent` types for the proposed changes.
> feat(types): add strict `parent` types for function-declaration, default-export and named-export nodes

- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
Fixed the bug described in the title.
🐛
> fix(eslint-plugin): [no-unnecessary-type-assertion] should report readonly class properties with a literal initializer 

- packages/eslint-plugin/src/rules/switch-exhaustiveness-check.ts
- packages/eslint-plugin/tests/fixtures/switch-exhaustiveness-check.ts
- packages/eslint-plugin/tests/fixtures/tsconfig.json
- packages/eslint-plugin/tests/rules/switch-exhaustiveness-check.test.ts
This pr addresses #7747.
The default `TypeFormatFlags` for the `typeToString` method is `AllowUniqueESSymbolType | UseAliasDefinedOutsideCurrentScope`.
This pr adds `UseFullyQualifiedType` to change the type to a qualified name.
- [TypeScript/src/compiler/checker.ts](https://github.com/microsoft/TypeScript/blame/main/src/compiler/checker.ts)
```ts
function typeToString(
type: Type,
enclosingDeclaration?: Node,
flags: TypeFormatFlags = TypeFormatFlags.AllowUniqueESSymbolType | TypeFormatFlags.UseAliasDefinedOutsideCurrentScope,
// ...
): string {
const noTruncation =
```
https://github.com/microsoft/TypeScript/blob/1c4083f4edc71cb1744a62013732e3c95d05a035/src/compiler/types.ts#L5538-L5540
```ts
UseFullyQualifiedType                   = 1 << 6,  // Write out the fully qualified type name …
```
> fix(eslint-plugin): [switch-exhaustiveness-check] suggest with qualified name

- packages/eslint-plugin/docs/rules/no-unnecessary-template-expression.mdx
- packages/eslint-plugin/src/rules/no-unnecessary-template-expression.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unnecessary-template-expression.shot
- packages/eslint-plugin/tests/rules/no-unnecessary-template-expression.test.ts
It addresses https://github.com/typescript-eslint/typescript-eslint/issues/10738.
Just as we allowed interpolation to convert an enum to a union, make it allow for the type parameter also.
> fix(eslint-plugin): [no-unnecessary-template-expression] allow interpolating type parameter in type context

- packages/eslint-plugin/package.json
- packages/type-utils/package.json
- packages/typescript-estree/package.json
- yarn.lock
Consumers can already fix #10747 on their own by running `npm update ts-api-utils` or equivalent. But this forces folks to be on the fixed version.
💖
> fix: bump ts-api-utils to ^2.0.1

- packages/eslint-plugin/src/rules/no-shadow.ts
- packages/eslint-plugin/tests/rules/no-shadow/no-shadow.test.ts
I added an additional guard clause checking if a variable has a `declare` tag and removing it from consideration under no-shadow if it does. The code may look very clunky because the conditional statements were derived through experimentation, so they may not catch all cases. Apologies for the mess, and do let me know how I may improve it.
There's one thing I couldn't figure out how to handle: The test case on `no-shadow.test.ts`, line `953` demonstrates the current behaviour when there is a `declare` keyword variable being shadowed by another in an inner scope. Should we have the error point to the `declare` variable or the global variable? 🧼
> fix(eslint-plugin): [no-shadow] ignore declare variables in definition files shadowing global variables

- packages/utils/src/ts-eslint/Config.ts
Follows https://github.com/eslint/eslint/pull/19201, released in https://github.com/eslint/eslint/releases/tag/v9.19.0. Currently, that flag is not yet usable with `typescriptEslint.config(…)` because of the missing type.
See also https://eslint.org/docs/latest/use/configure/configuration-files#configuration-objects.
> feat(utils): add `reportUnusedInlineConfigs` to LinterOptions

- packages/eslint-plugin/docs/rules/restrict-plus-operands.mdx
- packages/eslint-plugin/src/rules/restrict-plus-operands.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/restrict-plus-operands.shot
- packages/eslint-plugin/tests/rules/restrict-plus-operands.test.ts
If `allowNumberAndString` is set to `false`, `restrict-plus-operands` now reports when a `bigint` and a `string` are added, instead of just reporting for `number` and `string`. This is inline with the docs for `allowNumberAndString`:
> Whether to allow bigint/number typed values and string typed values to be added together.
`eslintrc`:
```json
{
"rules": {
"@typescript-eslint/restrict-plus-operands": [
"error",
{
"allowNumberAndString": false
}
]
}
}
```
Code snippet:
```ts
let fnBigint = (a: bigint, b: string) => a + b;
```
> [!WARNING]
> Operands of '+' operations must be a number or string, allowing a string + any of: `any`, `boolean`, `null`, `RegExp`, `undefined`. Got `bigint` + `string`.
> fix(eslint-plugin): [restrict-plus-operands] report adding bigints to strings when `allowNumberAndString` is `false`

- docs/getting-started/Typed_Linting.mdx
- docs/troubleshooting/typed-linting/index.mdx
- packages/website/src/theme/MDXComponents/RuleAttributes.tsx
Adds almost no new content, instead emphasizing or reorganizing existing content:
* Adds the suggested _"which comes with performance tradeoffs"_ note to the auto-added cards on top of rules pages
* Moves FAQs from `/getting-started/typed-linting` to the actual typed linting FAQs, promoting the _Performance_ heading to an h2
💖
> docs: emphasize performance tradeoffs of typed linting

- packages/eslint-plugin/docs/rules/no-unnecessary-condition.mdx
- packages/eslint-plugin/src/rules/no-unnecessary-condition.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unnecessary-condition.shot
- packages/eslint-plugin/tests/rules/no-unnecessary-condition.test.ts
- packages/eslint-plugin/tests/schema-snapshots/no-unnecessary-condition.shot
This PR attempts to tackle #7047 and changes `allowConstantLoopConditions` from a `boolean` to the following `enum`:
- `'never'`: same as the current `false`
- `'neverExceptWhileTrue'`: disallows constant conditions in all loops except `while` loops with the literal `true`.
- `'always'`: same as the current `true`
This is a non-breaking change as the existing options map to the new option (minus `neverExceptWhileTrue`).
---
Some thoughts:
I've used a similar option name for `'neverExceptWhileTrue'` as [`no-constant-condition`'s `checkLoops`](https://eslint.org/docs/latest/rules/no-constant-condition#checkloops). The option name is somewhat limiting because it's so specific, it may be better to have an option name that's a bit less specific to allow future changes(?).
The original issue …
> feat(eslint-plugin): [no-unnecessary-condition] make `allowConstantLoopConditions` more granular

- packages/ast-spec/src/expression/YieldExpression/spec.ts
Update YieldExpression.argument type to `Expression | null`
> fix(ast-spec): correct YieldExpression.argument type

- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
This PR follows up on the discussion in https://github.com/typescript-eslint/typescript-eslint/issues/7652#issuecomment-2622676298 and adds the relevant missing tests. This is a bit different than what the issue describes, as the issue seems to have been resolved in https://github.com/typescript-eslint/typescript-eslint/pull/8558.
I'll add that there are some inconsistencies with how the rule treats literals (enums included), I wrote some thoughts about this in https://github.com/typescript-eslint/typescript-eslint/pull/10631.
> test(eslint-plugin): [no-unnecessary-type-assertion] add missing tests for asserting enums

- packages/eslint-plugin/docs/rules/no-unnecessary-template-expression.mdx
- packages/eslint-plugin/src/rules/no-unnecessary-template-expression.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unnecessary-template-expression.shot
- packages/eslint-plugin/tests/rules/no-unnecessary-template-expression.test.ts
This pr allows the use of template literal type expression if any part of the type (union, intersection) has at least one enum member.
> fix(eslint-plugin): [no-unnecessary-template-expression] ignore enum and enum members

- packages/eslint-plugin/src/rules/no-unsafe-assignment.ts
- packages/eslint-plugin/tests/rules/no-unsafe-assignment.test.ts
This PR addresses #10784 and adds checks for `accessor` properties.
> fix(eslint-plugin): [no-unsafe-assignment] report on an `any` value assigned as an initializer of an `accessor` property

- packages/eslint-plugin/src/rules/consistent-generic-constructors.ts
- packages/eslint-plugin/tests/rules/consistent-generic-constructors.test.ts
This PR addresses #10786 and adjusts the rule to check `accessor` class properties.
> fix(eslint-plugin): [consistent-generic-constructors] check `accessor` class properties 

- packages/eslint-plugin/src/rules/prefer-return-this-type.ts
- packages/eslint-plugin/tests/rules/prefer-return-this-type.test.ts
This PR addresses #10791 and adds checks for `accessor` properties.
> fix(eslint-plugin): [prefer-return-this-type] check `accessor` properties with a function initializer

- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/src/util/misc.ts
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
This PR addresses #10802 and adds checks for `accessor` properties.
> fix(eslint-plugin): [explicit-module-boundary-types] check `accessor` class properties with a function initializer

- packages/eslint-plugin/src/rules/explicit-member-accessibility.ts
- packages/eslint-plugin/src/util/getMemberHeadLoc.ts
- packages/eslint-plugin/tests/rules/explicit-member-accessibility.test.ts
This PR addresses #10803 and adds checks for `accessor` properties.
> fix(eslint-plugin): [explicit-member-accessibility] check `accessor` class properties for missing accessibility modifier

- packages/eslint-plugin/src/rules/no-deprecated.ts
- packages/eslint-plugin/tests/rules/no-deprecated.test.ts
This PR addresses #10811 and adds handling of `accessor` properties.
I've added a couple of tests to check `accessor` properties generally work (not just the false-positive of declaring them). Please let me know if this shouldn't be included.
> fix(eslint-plugin): [no-deprecated] don't report on deprecated `accessor` property declaration

- packages/eslint-plugin/src/rules/no-misused-promises.ts
- packages/eslint-plugin/tests/rules/no-misused-promises.test.ts
This PR addresses #10812 and adds logic to handle `static` `accessor` properties.
I've added a couple of tests to check `accessor` properties generally work, regardless of being `static`. Please let me know if this shouldn't be included.
> fix(eslint-plugin): [no-misused-promises] don't report on `static` `accessor` properties

- docs/users/Releases.mdx
We on the maintenance team are spread around the world, so are our users, and our release automations don't respect DST, so let's just use UTC and call it a day?
> docs: give release time in UTC and local time

- docs/getting-started/Quickstart.mdx
- docs/packages/TypeScript_ESLint.mdx
Primarily applies two refactors on the page:
* Moves `config(...)` docs much higher, so people are more likely to see them
* The eslintrc migration section is moved to the very end - there are still folks who need it but it's not quite as commonplace as it was half a year ago
* Rewords the description of `extends` to what's suggested in the issue, rather than the now-no-longer-technically-true variadic function concept
Also touches up on some other phrasings:
* Slightly longer descriptions introductory table, to explain more about the exports
* `// ...` instead of the 2nd+ rule in `rules: { ... }`s, for brevity
* Switched from `no-unsafe-*` to `no-floating-promises` since it's more commonly known on its own
💖
> docs: refreshed typescript-eslint package docs, especially tseslint.config

- docs/troubleshooting/typed-linting/index.mdx
Fix a broken link
The old link https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/parser#parseroptionsproject has no content.
> docs: fix broken parserOptions.project link

- packages/eslint-plugin/project.json
- packages/rule-schema-to-typescript-types/package.json
Removes a couple of unused/broken scripts from
`rule-schema-to-typescript-types`.
Also adds a missing nx target such that `generate-breaking-changes` works again.
> chore: remove unused scripts

- packages/rule-tester/package.json
Refer to the related issue:https://github.com/typescript-eslint/typescript-eslint/issues/10908
> fix(rule-tester): Add missing `parser` dependency

- packages/rule-tester/src/types/index.ts
`TestLanguageOptions` is now exported from the `rule-tester` package, allowing that type to be used directly instead of accessing it via `ValidTestCase['languageOptions']`
> feat(rule-tester): export `TestLanguageOptions`

- packages/eslint-plugin/docs/rules/explicit-module-boundary-types.mdx
- packages/eslint-plugin/src/rules/explicit-module-boundary-types.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/explicit-module-boundary-types.shot
- packages/eslint-plugin/tests/rules/explicit-module-boundary-types.test.ts
- packages/eslint-plugin/tests/schema-snapshots/explicit-module-boundary-types.shot
This PR addresses #4586 and add an option to ignore overload implementations:
```ts
export function test(a: string): string;
export function test(a: number): number;
export function test(a: unknown) {
return a;
}
```
---
Some thoughts:
Would it make sense to apply the same option to `explicit-function-return-type` too?
It seems both rules share several options (e.g. `allowHigherOrderFunctions`, `allowDirectConstAssertionInArrowFunctions`, `allowTypedFunctionExpressions`) and also have [common code for handling these options](https://github.com/typescript-eslint/typescript-eslint/blob/c910ac1553e517ebc534d3271e84b51e4ac23f5d/packages/eslint-plugin/src/util/explicitReturnTypeUtils.ts).
I think the motivation for having this option in `explicit-function-return-type` is the same for …
> feat(eslint-plugin): [explicit-module-boundary-types] add an option to ignore overload implementations

- packages/eslint-plugin/tests/rules/no-unsafe-return.test.ts
- packages/type-utils/src/discriminateAnyType.ts
- packages/type-utils/src/index.ts
- packages/type-utils/src/predicates.ts
- packages/type-utils/tests/discriminateAnyType.test.ts
> fix(eslint-plugin): [no-unsafe-return] handle recursive type

- packages/rule-tester/src/index.ts
Take two! This was previously done in #10892, but I only exported `TestLanguageOptions` from `src/types/index.ts` 🤦‍♂️ 
This change exports it from the `src/index.ts` as well so that it's actually exported from the package.
> fix(rule-tester): export `TestLanguageOptions`

- packages/eslint-plugin/src/rules/no-empty-interface.ts
- packages/eslint-plugin/src/rules/no-loss-of-precision.ts
- packages/eslint-plugin/src/rules/no-type-alias.ts
- packages/eslint-plugin/src/rules/no-var-requires.ts
- packages/eslint-plugin/src/rules/prefer-ts-expect-error.ts
- packages/eslint-plugin/src/rules/sort-type-constituents.ts
- packages/utils/src/ts-eslint/Rule.ts
- packages/website/rulesMeta.ts
This PR does:
- Add type `DeprecatedInfo` support to field `Rule.meta.deprecated`
- Deprecated filed `Rule.meta.replacedBy`
- Add basic deprecated info to deprecated rules
> feat(utils): support `DeprecatedInfo` for `rule.meta.deprecated`

- packages/ast-spec/src/parameter/AssignmentPattern/fixtures/decorated-assignment-pattern-parameter/fixture.ts
- packages/ast-spec/src/parameter/AssignmentPattern/fixtures/decorated-assignment-pattern-parameter/snapshots/1-TSESTree-AST.shot
- packages/ast-spec/src/parameter/AssignmentPattern/fixtures/decorated-assignment-pattern-parameter/snapshots/2-TSESTree-Tokens.shot
- packages/ast-spec/src/parameter/AssignmentPattern/fixtures/decorated-assignment-pattern-parameter/snapshots/3-Babel-AST.shot
- packages/ast-spec/src/parameter/AssignmentPattern/fixtures/decorated-assignment-pattern-parameter/snapshots/4-Babel-Tokens.shot
- packages/ast-spec/src/parameter/AssignmentPattern/fixtures/decorated-assignment-pattern-parameter/snapshots/5-AST-Alignment-AST.shot
- packages/ast-spec/src/parameter/AssignmentPattern/fixtures/decorated-assignment-pattern-parameter/snapshots/6-AST-Alignment-Tokens.shot
- packages/ast-spec/tests/fixtures-with-differences-ast.shot
- packages/typescript-estree/src/convert.ts
This PR addresses #10937 and adjusts the range for decorated `AssignmentPattern` function parameter to match other binding patterns.
I've added a test for this since the change didn't cause any tests to fail (and so this was probably missing a test).
> fix(typescript-estree): fix span start for decorated `AssignmentPattern` function parameter

- tools/release/release.mts
Adds a flag that will allow us to do manual releases that bypass this check.
For example right now the [v8.27.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.27.0) release didn't go to npm due to a token issue -- but all of the GH stuff was done. This will allow us to rectify this situation in future with a few clicks!
> chore: allow releases without changes

- tsconfig.repo-config-files.json
Is this what you meant @kirkwaiblinger?
we can't enable it at repo level since the ast-types use enums still
> chore: enable erasableSyntaxOnly in tools

- packages/eslint-plugin/src/rules/no-unsafe-function-type.ts
Rule [no-unsafe-function-type](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/rules/no-unsafe-function-type.ts) has an unneeded `fixable : 'code'` property. 
There is no 'fix' or 'suggestion' in rule.
Each `invalid` code tests return a `null` output. That doesn't mean anything, I know, but if I'm right, I should probably remove these outputs. 🤔
> fix(eslint-plugin): [no-unsafe-function-type] remove fixable property

- packages/eslint-plugin/src/util/isAssignee.ts
- packages/eslint-plugin/tests/rules/prefer-for-of.test.ts
Fixed `isAssignee` function to handle erasable type syntax.
> fix(eslint-plugin): [prefer-for-of] fix false positive when using erasable type syntax within update expressions

- packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.mdx
- packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/prefer-nullish-coalescing.shot
- packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
- packages/eslint-plugin/tests/schema-snapshots/prefer-nullish-coalescing.shot
> feat(eslint-plugin): [prefer-nullish-coalescing] create `ignoreIfStatements` option

- packages/integration-tests/fixtures/flat-config-types-@types__eslint-v8/eslint.config.js
- packages/integration-tests/fixtures/flat-config-types-@types__eslint-v9/eslint.config.js
- packages/integration-tests/tests/__snapshots__/flat-config-types-@types__eslint-v8.test.ts.snap
- packages/integration-tests/tests/__snapshots__/flat-config-types-@types__eslint-v9.test.ts.snap
Fix test failures by marking eslint-plugin-deprecation usage as expecting ts failures
Co-authored-by: @aryaemami59
> chore: fix failing integration tests on deprecation plugin

- packages/eslint-plugin/docs/rules/no-unsafe-argument.mdx
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unsafe-argument.shot
Some lines in example code are incorrect.
> docs: fix typos in no-unsafe-argument examples

- packages/eslint-plugin/src/util/misc.ts
- packages/eslint-plugin/tests/util/misc.test.ts
This PR #10911 adds support for TypeScript's `allowArbitraryExtensions` feature in the `isDefinitionFile` utility.
> fix(eslint-plugin): support arbitrary extensions in definition files

- packages/eslint-plugin/src/rules/no-array-constructor.ts
- packages/eslint-plugin/tests/rules/no-array-constructor.test.ts
remove optional chaining logic and change test case
> fix(eslint-plugin): [no-array-constructor] remove optional chaining exemption

- packages/eslint-plugin/TSLINT_RULE_ALTERNATIVES.md
- packages/eslint-plugin/src/configs/eslint-recommended-raw.ts
Original tickets suggests removing references to `no-with`, since `with` statements are already not allowed by Typescript compiler.
This is the only mention I could find.
> feat(eslint-plugin): disable core rule no-with in eslint-recommended

- packages/eslint-plugin/src/rules/no-explicit-any.ts
- packages/eslint-plugin/tests/rules/no-explicit-any.test.ts
Enhanced the `no-explicit-any` rule to suggest replacing `keyof any` with PropertyKey. added detection, helpful suggestion messages, auto-fix support, and test coverage.
> feat(eslint-plugin): [no-explicit-any] suggest to replace keyof any with PropertyKey

- .vscode/settings.json
Flat config is no longer experimental, of course. Also we get this in the eslint output: 
```
ESLint version 9.22.0 supports flat config without experimental opt-in. 
The 'eslint.experimental.useFlatConfig' setting can be removed.
```
> chore: remove eslint vscode extension flat config experimental flag

- packages/eslint-plugin/src/configs/eslintrc/all.ts
- packages/eslint-plugin/src/configs/eslintrc/recommended-type-checked-only.ts
- packages/eslint-plugin/src/configs/eslintrc/recommended-type-checked.ts
- packages/eslint-plugin/src/configs/eslintrc/recommended.ts
- packages/eslint-plugin/src/configs/eslintrc/strict-type-checked-only.ts
- packages/eslint-plugin/src/configs/eslintrc/strict-type-checked.ts
- packages/eslint-plugin/src/configs/eslintrc/strict.ts
- packages/eslint-plugin/src/configs/eslintrc/stylistic-type-checked-only.ts
- packages/eslint-plugin/src/configs/eslintrc/stylistic-type-checked.ts
- packages/eslint-plugin/src/configs/eslintrc/stylistic.ts
- tools/scripts/generate-configs.mts
To repro: Create a minimal _eslintrc_ setup using `"extends": ["plugin:@typescript-eslint/recommended"]`, and execute `ESLINT_USE_FLAT_CONFIG=false eslint .`.
Tested, and this fixes the issue for me locally. Can follow up with an integration test or something if we want.
> fix(eslint-plugin): fix mistake with eslintrc config generation

- packages/eslint-plugin/docs/rules/no-unnecessary-type-assertion.mdx
- packages/eslint-plugin/src/rules/no-unnecessary-type-assertion.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-unnecessary-type-assertion.shot
- packages/eslint-plugin/tests/rules/no-unnecessary-type-assertion.test.ts
- packages/eslint-plugin/tests/schema-snapshots/no-unnecessary-type-assertion.shot
Add new ignoreStringConstAssertion that ignores const assertions on string literals to as it is a common use case to force typescript to not widen type to string
> feat(eslint-plugin): [no-unnecessary-type-assertion] add option to ignore string const assertions

- packages/typescript-eslint/src/config-helper.ts
- packages/typescript-eslint/tests/config-helper.test.ts
continuation of https://github.com/typescript-eslint/typescript-eslint/pull/10576
Co-authored-by: @abrahamguo
> fix(typescript-eslint): gracefully handle invalid flat config objects in config helper

- packages/eslint-plugin/docs/rules/no-unsafe-declaration-merging.mdx
This PR fixes a simple typo on https://typescript-eslint.io/rules/no-unsafe-declaration-merging.
> fix(website): fix typo

- packages/ast-spec/tsconfig.spec.json
- packages/eslint-plugin/tsconfig.spec.json
- packages/integration-tests/tsconfig.spec.json
- packages/rule-schema-to-typescript-types/tsconfig.spec.json
- packages/rule-tester/tsconfig.spec.json
- packages/scope-manager/tsconfig.spec.json
- packages/type-utils/tsconfig.spec.json
- packages/types/tsconfig.spec.json
- packages/typescript-estree/tsconfig.spec.json
same fix as https://github.com/typescript-eslint/typescript-eslint/pull/11067 for same problem again in CI? (I have no idea why this fixes the failure)
(failure on main: https://cloud.nx.app/runs/jK7P2iHuD6/task/types%3Atypecheck)
```
vitest.config.mts(4,34): error TS6305: 
Output file '/home/runner/work/typescript-eslint/typescript-eslint/dist/out-tsc/root/vitest/vitest.config.base.d.mts' 
has not been built from source file '/home/runner/work/typescript-eslint/typescript-eslint/vitest.config.base.mts'.
```
> chore: fix more vitest config CI failures

- packages/website/src/pages/index.tsx
I couldn't find any other places that use `<code>typescript-eslint</code>` or refer to the project as <code>\`typescript-eslint`</code>.
💖
> docs: use plain text for project name, not code, in homepage

- packages/typescript-eslint/tests/configs.test.ts
Just a quick rename. The test code is a little confusing because it refers to `plugin.configs`, but we canonically would refer to this as `tseslint.configs`, and it is _not_ equal to `tseslint.plugin.configs`.
> chore(typescript-eslint): correct naming of import of typescript-eslint in test

- packages/eslint-plugin/src/rules/consistent-indexed-object-style.ts
- packages/eslint-plugin/tests/rules/consistent-indexed-object-style.test.ts
This PR addresses #11179 and adjusts the auto-fixer to fix the following:
```ts
type Bar = {
[k in string];
};
```
Into:
```ts
type Bar = Record<string, any>;
```
> fix(eslint-plugin): [consistent-indexed-object-style] adjust auto-fixer to generate valid syntax for `TSMappedType` with no type annotation

- docs/maintenance/Releases.mdx
- docs/users/Releases.mdx
- packages/website/docusaurus.config.mts
- packages/website/src/css/custom.css
Relies on an `CURRENT_MAJOR_VERSION` env variable I've set in Netlify. You can preview it with a different version locally with:
```shell
CURRENT_MAJOR_VERSION=9001 yarn start
```
💖
> docs: add big announcement notice for old major versions

- packages/eslint-plugin/docs/rules/typedef.mdx
- packages/eslint-plugin/src/configs/eslintrc/all.ts
- packages/eslint-plugin/src/configs/flat/all.ts
- packages/eslint-plugin/src/rules/typedef.ts
At long last! We haven't recommended this rule in _years_. It's mostly been kept around as a legacy support point. But it's been less and less useful over the years.
Primarily a docs change + addition of `meta.deprecated` to the rule.
Moves the `:::caution` note to be the first added content in the rule's docs file, and adds a note to it that the rule is deprecated.
Note that this does include a behavioral change: the rule is no longer in the `all` configs. Per https://typescript-eslint.io/users/configs#all, the contents of `all` are _not_ considered semver-stable. This is not a breaking change.
💖
> docs(eslint-plugin): [typedef] deprecate the rule

- docs/getting-started/Typed_Linting.mdx
- docs/packages/Parser.mdx
- Fixes the links at https://typescript-eslint.io/getting-started/typed-linting#troubleshooting. 
- Fixes the link to the project service section at the `project` section: https://typescript-eslint.io/packages/parser#project
> chore: fix project service links

- packages/eslint-plugin/package.json
This PR excludes `docs/` directory from the published `@typescript-eslint/eslint-plugin` package.
I converted from `README.md` to `./README.md` in [`files`](https://docs.npmjs.com/cli/v11/configuring-npm/package-json#files) of `package.json`.  This is because [docs/rules/README.md](https://github.com/roottool/typescript-eslint/blob/db9e2c553e306880b7de7bb27e216f4c26a5ec9f/packages/eslint-plugin/docs/rules/README.md) is included in the eslint-plugin package after `docs/` directory is excluded. I checked it with [`yarn pack --dry-run`](https://v3.yarnpkg.com/cli/pack).
As an aside, I think that `README.md`  in `files` can be deleted. `README` is always included in this `files` config.
> Certain files are always included, regardless of settings:
> 
> - `package.json`
> - `README`
> - …
> fix: exclude docs/ directory from eslint-plugin package

- packages/eslint-plugin/docs/rules/ban-ts-comment.mdx
- packages/eslint-plugin/src/util/astUtils.ts
- packages/scope-manager/src/variable/ESLintScopeVariable.ts
- packages/utils/src/ts-eslint/Config.ts
- packages/utils/src/ts-eslint/eslint/ESLintShared.ts
This PR only renames "directive comments" into "comment directives" in documentation.
The wording is rather similar, indeed. It seems to me that "comment directives" is the preferred naming in the ecosystem:
- when support for the `// @ts-expect-error` was added to TypeScript, several internal types use the "comment directives" naming: https://github.com/microsoft/TypeScript/pull/36014
- the Learning TypeScript book has a whole chapter named Comment Directives (but not Directive Comments): https://www.learningtypescript.com/articles/comment-directives
> docs: rename "directive comments" to "comment directives"

- docs/users/Shared_Configurations.mdx
Affects https://typescript-eslint.io/users/configs
Addresses 2 issues.
1. https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslintrc/eslint-recommended.ts is a bad link to use for `eslint-recommended`. It's technically true but doesn't show its contents. So, I've changed it to https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended-raw.ts
2. The wording "See  `configs/<config-name>.ts` for the exact contents of this config" doesn't really work because those configs are now at `configs/eslintrc/<config-name>.ts` (with the exception of bullet point 1, which is at `configs/eslint-recommended-raw.ts`). Since putting `eslintrc` and `*-raw` in the link text is IMO distracting, I've …
> docs: fix up config links

- packages/visitor-keys/package.json
- yarn.lock
Fix #11293 by bumping dependency of `eslint-visitor-keys` to v4.2.1.
As mentioned in #11293, as far as I can see, this is the only substantive change made in v4.2.1, so I think it should be possible to bump `eslint-visitor-keys` dependency in isolation, without breaking anything else.
No-one has had a chance to respond on #11293 yet, so I'm jumping the gun by submitting a PR. However, judging by #11279, I assume this will be considered a bug, and I thought a PR would help verify that this fix doesn't break anything.
If I'm out of line, please feel free to close this!
> chore(visitor-keys): bump `eslint-visitor-keys` dependency

- packages/types/src/parser-options.ts
I didn't open an issue because it's just for updating a single type for 2026.
I was happening to be manually updating my dependencies and was very confused when I suddenly started getting this error:
```ts
Argument of type 'Config<RulesRecord>' is not assignable to parameter of type 'InfiniteDepthConfigWithExtends'.
Type 'Config<RulesRecord>' is not assignable to type 'ConfigWithExtends'.
Types of property 'languageOptions' are incompatible.
Type 'import("/home/david/Projects/My Price Health/mono/node_modules/eslint/lib/types/index").Linter.LanguageOptions | undefined' is not assignable to type 'import("/home/david/Projects/My Price Health/mono/node_modules/@typescript-eslint/utils/dist/ts-eslint/Config").FlatConfig.LanguageOptions | undefined'.
Type 'import("/home/david/Projects/My Price …
```
> fix(types): add 2026/17 to EcmaVersion

- packages/ast-spec/src/element/MethodDefinition/fixtures/constructor-string-literal/fixture.ts
- packages/ast-spec/src/element/MethodDefinition/fixtures/constructor-string-literal/snapshots/1-TSESTree-AST.shot
- packages/ast-spec/src/element/MethodDefinition/fixtures/constructor-string-literal/snapshots/2-TSESTree-Tokens.shot
- packages/ast-spec/src/element/MethodDefinition/fixtures/constructor-string-literal/snapshots/3-Babel-AST.shot
- packages/ast-spec/src/element/MethodDefinition/fixtures/constructor-string-literal/snapshots/4-Babel-Tokens.shot
- packages/ast-spec/src/element/MethodDefinition/fixtures/constructor/fixture.ts
- packages/ast-spec/src/element/MethodDefinition/fixtures/constructor/snapshots/1-TSESTree-AST.shot
- packages/ast-spec/src/element/MethodDefinition/fixtures/constructor/snapshots/2-TSESTree-Tokens.shot
- packages/ast-spec/src/element/MethodDefinition/fixtures/constructor/snapshots/3-Babel-AST.shot
- packages/ast-spec/src/element/MethodDefinition/fixtures/constructor/snapshots/4-Babel-Tokens.shot
- packages/typescript-estree/src/convert.ts
cases:
```ts
// Literal
class A {
"constructor"() { }
}
// Identifier
class B {
constructor() { }
}
```
💖
> fix(typescript-estree): align constructor literal with eslint

- packages/website/src/components/editor/useSandboxServices.ts
- packages/website/src/components/linter/bridge.ts
- packages/website/src/components/linter/createLinter.ts
- packages/website/src/components/linter/createParser.ts
- packages/website/src/components/linter/types.ts
I think this issue occurs because of differences in the properties used when creating a ts.Program between Monaco and TypeScript-VFS.
> https://github.com/typescript-eslint/typescript-eslint/blob/e57126a23e3f9b0ec67665d47e37a429d7755753/packages/website/src/components/linter/createParser.ts#L29
The modules like [monaco](https://github.com/microsoft/monaco-editor), [typescript](https://github.com/microsoft/TypeScript), and [typescript-website](https://github.com/microsoft/TypeScript-Website) are scattered, so it’s a bit confusing
**1. create `ts.program` by monace**
**When monaco-editor creating this code will excute**   [link](https://github.com/microsoft/monaco-editor/blob/dd6bdfe8dae1b3c134fa7bc7b176b43fd294916e/src/language/typescript/tsWorker.ts#L35-L41)
`private _languageService = …
> fix(website): acquired types are shown in the editor but not reflected in linting

- packages/eslint-plugin/tests/rules/consistent-type-assertions.test.ts
Change dynamic test cases using spread and map to handwritten ones.
🚀
> chore(eslint-plugin): switch auto-generated test cases to hand-written in consistent-type-assertions.test.ts

- packages/eslint-plugin/docs/rules/no-base-to-string.mdx
- packages/eslint-plugin/src/rules/no-base-to-string.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/no-base-to-string.shot
- packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
- packages/eslint-plugin/tests/schema-snapshots/no-base-to-string.shot
- packages/eslint-plugin/vitest.config.mts
add checkUnknown option.
One thing I'm curious about is, is it correct to treat generic types as unknown?
```ts
function foo<T>(x: T) {
String(x);
}
```
> feat(eslint-plugin): [no-base-to-string] add checkUnknown Option

- docs/getting-started/Quickstart.mdx
- docs/packages/TypeScript_ESLint.mdx
Adds an aside under _Quickstart_ explaining the transient `defineConfig()` situation, along with a similar note under the `typescript-eslint` package docs.
I experimented for a bit splitting existing `tseslint.config` code blocks into tabs as suggested by the issue. That felt more confusing to me: that it was almost suggesting writing to files. Explaining the difference would have taken up even more previous docs space.
💖
> docs: mention ESLint's defineConfig()

- packages/website/src/components/linter/createParser.ts
Sorry, I didn’t consider that case either. @JoshuaKGoldberg 
When `fileType` doesn't exist in the URL hash, the following hook is executed:
> https://github.com/typescript-eslint/typescript-eslint/blob/db32b8a82d58eddb29be207a5f4476644973abbf/packages/website/src/components/editor/LoadedEditor.tsx#L93-L110
As a result, `system.write` is called.
After that, this code runs.
> https://github.com/typescript-eslint/typescript-eslint/blob/db32b8a82d58eddb29be207a5f4476644973abbf/packages/website/src/components/linter/createParser.ts#L49-L51
At this point, `system` has the file, but `compilerHost` does not.
At the result "cannot find source file" error occur in [typescript-website](https://github.com/microsoft/TypeScript-Website/blob/1019cfc8f96ded4729e8ccd342742534a9826a9d/packages/typescript-vf …
> fix(website): did not find a source file error if url hash doesn't contain fileType

- nx.json
We were using legacy settings for Nx Cloud. I have updated both our account and configuration to the more secure and reliable setup.
> chore: migrate to nx-cloud-id

- packages/types/package.json
The `types:copy-ast-spec` task could hit the remote cache when the `ast-spec` build outputs were changing. This change ensures that is now impossible by making it so that `copy-ast-spec` will always run. It's a very cheap operation anyway.
> chore: make copy-ast-spec non cacheable

- packages/website/package.json
Sets the website's `build` task as a dependency for its `lint` task.
💖
> chore: fix website lint task to rely on build

- packages/utils/src/ts-eslint/Config.ts
The default value of the `reportUnusedDisableDirectives` linter option is `'warn'`, not `'off'` (see [ESLint docs](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-objects)). This PR fixes the JSDoc comment of that option to reflect this.
> chore: fix default value in JSDoc for reportUnusedDisableDirectives

- packages/typescript-eslint/src/getTSConfigRootDirFromStack.ts
- packages/typescript-eslint/src/index.ts
- packages/typescript-eslint/tests/configs.test.ts
- packages/typescript-eslint/tests/getTsconfigRootDirFromStack.test.ts
- packages/typescript-eslint/tests/path-test-fixtures/tsconfigRootDirInference-normal/normal-folder/eslint.config.cts
- packages/typescript-eslint/tests/path-test-fixtures/tsconfigRootDirInference-not-eslint-config/not-an-eslint.config.cts
- packages/typescript-eslint/tests/path-test-fixtures/tsconfigRootDirInference-space/folder that has a space/eslint.config.cts
- fixes #11398 
- fixes #11407 
Alternative option or followup to https://github.com/typescript-eslint/typescript-eslint/pull/11408
See discord discussion around this: https://discord.com/channels/1026804805894672454/1395485881334366361
https://v8.dev/docs/stack-trace-api#customizing-stack-traces
> fix(typescript-eslint): infer tsconfigRootDir with v8 API

- packages/integration-tests/fixtures/flat-config-types-@types__eslint-v9/eslint.config.js
- packages/integration-tests/tests/__snapshots__/flat-config-types-@types__eslint-v9.test.ts.snap
Integration tests have been failing lately, due to a deprecation warning with `stylistic.configs['recommended-flat']` ([example](https://cloud.nx.app/runs/JDM1jutRpo?utm_source=pull-request&utm_medium=comment)). Maybe this is related to their recent [v5 release](https://github.com/eslint-stylistic/eslint-stylistic/releases/tag/v5.0.0)? Unsure 🤷‍♂️.
> chore: fix integration test failure with eslint stylistic plugin deprecation warning

- packages/eslint-plugin-internal/package.json
- yarn.lock
Seems like the failure has to do with some performance-y problems in `make-synchronized`. Upgrading `@prettier/sync` may solve this (since it uses a more recent version of `make-synchronized`) 🤷 
Locally, I haven't been able to reproduce the failure with this commit
> chore: upgrade @prettier/sync to fix CI lint failures

- packages/eslint-plugin/src/rules/naming-convention.ts
- packages/eslint-plugin/tests/rules/naming-convention/naming-convention.test.ts
Reverts #11127 which was a breaking change merged by mistake.
See https://github.com/typescript-eslint/typescript-eslint/issues/7879#issuecomment-3148636019
---
This reverts commit b872e2b2f5b07762e2ab5615e57a11fcf6603f16.
> fix(eslint-plugin): revert #11127

- packages/eslint-plugin/src/rules/only-throw-error.ts
- packages/eslint-plugin/tests/rules/only-throw-error.test.ts
It seems we can actually support yield and await as the type checker will already resolve the yielded/awaited type.
When yielding, it is possible a generator can be typed such that the `yield` resolves to an `Error`.
> feat(eslint-plugin): [only-throw-error] support yield/await expressions

- .cspell.json
- packages/typescript-eslint/src/getTSConfigRootDirFromStack.ts
- packages/typescript-eslint/tests/getTsconfigRootDirFromStack.test.ts
I haven't written an automated test for this, since... it's not super clear how without mocking the v8 stack trace API (which seems really yucky) or writing a full integration test (tedious).
But it's very easy to clone down the repo in https://github.com/typescript-eslint/typescript-eslint/issues/11429, `yarn link`, and observe the bug being fixed. 
Maybe more comprehensive automated testing of the `tsconfigRootDir` can be a follow-on if we want to invest in that effort?
> fix(typescript-eslint): handle `file://` urls in stack trace when inferring `tsconfigRootDir`

- packages/typescript-eslint/package.json
- packages/typescript-eslint/src/compatibility-types.ts
- packages/typescript-eslint/src/index.ts
- packages/typescript-eslint/tests/type-compatibility.test-d.ts
- packages/typescript-eslint/vitest.config.mts
Third time's the charm 🙃 
I realized that, if we're extremely vague about what the parser, plugin, and configs are, we can easily satisfy both the expected types from `defineConfig()` and `tseslint.config()`, without running into the many incompatibilities I experienced during previous attempts. While this sacrifices precision, the exact shapes of those objects aren't actually important at all to users; it's only important that they be usable within their configs. So, I think this is a worthwhile tradeoff. 
It's possible that some plugin authors, or downstream consumers that use our tools in some way other than in their lint configuration might experience some type errors as a result of this. Fixing these errors should be quite simple, since one can use type assertions to get the previous …
> fix(typescript-eslint): export `plugin`, `parser`, and `configs` that are compatible with both `defineConfig()` and `tseslint.config()`

- docs/getting-started/Quickstart.mdx
- docs/getting-started/Typed_Linting.mdx
- docs/packages/TypeScript_ESLint.mdx
- docs/troubleshooting/faqs/ESLint.mdx
- docs/troubleshooting/faqs/Frameworks.mdx
- docs/troubleshooting/faqs/General.mdx
- docs/troubleshooting/typed-linting/Monorepos.mdx
- docs/troubleshooting/typed-linting/Performance.mdx
- docs/troubleshooting/typed-linting/index.mdx
- docs/users/Shared_Configurations.mdx
- docs/users/What_About_Formatting.mdx
- eslint.config.mjs
- packages/typescript-eslint/src/config-helper.ts
- packages/typescript-eslint/tests/config-helper.test.ts
- packages/typescript-eslint/tests/type-compatibility.test-d.ts
- Replaces `tseslint.config()` in the docs everywhere with `defineConfig()`
- adds `/** @deprecated */` to `tseslint.config()`.
- adds deprecation/migration info to the docs.
- switches our eslint config to use `defineConfig()`
- Should we use the `defineConfig(a, b, c)` or `defineConfig([a, b, c])` style? The eslint docs (inexplicably) use `defineConfig([a, b, c])` throughout, but `defineConfig(a, b, c)` is much better in a TS context since each argument's type is checked individually. I've gone with that approach for now, but we can change to match their style if we want.
> feat: deprecate tseslint.config()

- packages/typescript-estree/src/useProgramFromProjectService.ts
- packages/typescript-estree/tests/lib/useProgramFromProjectService.test.ts
Use minimatch dot option to take file starting with a dot into account when configuring allowDefaultProject using globs
> fix(typescript-estree): match filenames starting with a period when using glob in allowDefaultProject

- eslint.config.mjs
- packages/typescript-estree/src/useProgramFromProjectService.ts
Enable eslint no-useless-rename rule on project, see [discussion](https://github.com/typescript-eslint/typescript-eslint/pull/11537#discussion_r2320126182)
> chore: enable ESLint no-useless-rename rule on project

- packages/eslint-plugin/src/rules/no-unsafe-enum-comparison.ts
- packages/eslint-plugin/tests/rules/no-unsafe-enum-comparison.test.ts
The problem was not about which type was the switch argument and which was the case, and more so about the fact that the rule didn't consider unions of number literals to be numbers (and ditto for strings).
> fix(eslint-plugin): [no-unsafe-enum-comparison] support unions of literals

- packages/eslint-plugin/src/rules/await-thenable.ts
- packages/eslint-plugin/tests/rules/await-thenable.test.ts
This PR addresses #11609 and adjusts `await-thenable` to allow passing values which may be promises to promise aggregator methods, specifically in an array literal:
```ts
declare const maybePromise: Promise<number> | number;
Promise.all([
maybePromise,
Promise.resolve(1),
Promise.resolve(2),
Promise.resolve(3),
]);
```
Note that this special cases array literals, and the code below will still be reported:
```ts
declare const maybePromise: Promise<number> | number;
const arr = [
maybePromise,
Promise.resolve(1),
Promise.resolve(2),
Promise.resolve(3),
];
// Unexpected iterable of non-Promise (non-"Thenable") values passed to promise aggregator. 
Promise.all(arr);
```
> fix(eslint-plugin): [await-thenable] should not report passing values to promise aggregators which may be a promise in an array literal

- eslint.config.mjs
- packages/website/src/components/editor/createProvideTwoslashInlay.ts
While looking into other website issues, I noticed that @kirkwaiblinger's work in #11558 introduced a runtime error, because it removed a `g` flag from a regular expression that is passed to `String#matchAll`, which does require a `g` flag.
This PR fixes this issue, as well as enabling `regexp/no-missing-g-flag` (which did successfully identify this issue) to prevent this from occurring again.
> chore(website): lint for missing `g` flag

- packages/eslint-plugin/src/rules/no-base-to-string.ts
- packages/eslint-plugin/tests/rules/no-base-to-string.test.ts
Added isIgnoredTypeOrBase to ensure that a type’s superclass or extended interfaces are properly checked against the ignored types list.
> fix(eslint-plugin): [no-base-to-string] check if superclass is ignored

- packages/ast-spec/src/element/AccessorProperty/fixtures/_error_/key-constructor-string-escaped/fixture.ts
- packages/ast-spec/src/element/AccessorProperty/fixtures/_error_/key-constructor-string-escaped/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/element/AccessorProperty/fixtures/_error_/key-constructor-string-escaped/snapshots/2-Babel-Error.shot
- packages/ast-spec/src/element/PropertyDefinition/fixtures/_error_/key-constructor-string-escaped/fixture.ts
- packages/ast-spec/src/element/PropertyDefinition/fixtures/_error_/key-constructor-string-escaped/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/element/PropertyDefinition/fixtures/_error_/key-constructor-string-escaped/snapshots/2-Babel-Error.shot
- packages/ast-spec/src/element/TSAbstractAccessorProperty/fixtures/_error_/key-constructor-string-escaped/fixture.ts
- packages/ast-spec/src/element/TSAbstractAccessorProperty/fixtures/_error_/key-constructor-string-escaped/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/element/TSAbstractAccessorProperty/fixtures/_error_/key-constructor-string-escaped/snapshots/2-Babel-Error.shot
- packages/ast-spec/src/element/TSAbstractPropertyDefinition/fixtures/_error_/key-constructor-string-escaped/fixture.ts
- packages/ast-spec/src/element/TSAbstractPropertyDefinition/fixtures/_error_/key-constructor-string-escaped/snapshots/1-TSESTree-Error.shot
- packages/ast-spec/src/element/TSAbstractPropertyDefinition/fixtures/_error_/key-constructor-string-escaped/snapshots/2-Babel-Error.shot
When I [update @​typescript-eslint/typescript-estree](https://github.com/prettier/prettier/pull/17931) with changes from #​11590 in Prettier, I found that CSpell reports on original fixtures, use  `'construct\u{6f}r'` instead of `'\u{63}onstructor'` fixed it.
> chore: update test fixtures to avoid spellcheck error

- packages/typescript-estree/src/convert-comments.ts
The `textEnd` is actually the length of the value text of the comment, but `textEnd` is what we needed.
> chore: slightly improve `convertComments`

- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars-eslint.test.ts
- packages/eslint-plugin/tests/rules/no-unused-vars/no-unused-vars.test.ts
- packages/rule-tester/tests/RuleTester.test.ts
- packages/rule-tester/tests/filename.test.ts
- packages/utils/src/eslint-utils/RuleCreator.ts
- packages/utils/src/ts-eslint/Rule.ts
This PR introduces an `name` property to the `RuleModule` interface.
🚀
> feat(eslint-plugin): expose rule name via RuleModule interface

- packages/eslint-plugin/src/rules/prefer-nullish-coalescing.ts
- packages/eslint-plugin/tests/rules/prefer-nullish-coalescing.test.ts
Report this case when ignoreBooleanCoercion is true:
```
declare const a: string | true | undefined;
declare const b: string | boolean | undefined;
const x = Boolean(a ? a : b);
```
but do not report this case:
```
declare const a: string | true | undefined;
declare const b: string | boolean | undefined;
declare const c: string | boolean | undefined;
const x = Boolean(c || (a ? a : b));
```
> fix(eslint-plugin): [prefer-nullish-coalescing] ignoreBooleanCoercion should not apply to top-level ternary expressions

- packages/eslint-plugin/src/rules/unbound-method.ts
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/unbound-method.shot
Generally applies the phrasing suggested in https://github.com/typescript-eslint/typescript-eslint/issues/10056#issuecomment-2374507181. I also tweaked the `unboundWithoutThisAnnotation` to speak generally, rather than suggest user action on the specific function.
Co-authored-by: @kirkwaiblinger
💖
> fix(eslint-plugin): [unbound-method] improve wording around `this: void` and binding

- packages/eslint-plugin/docs/rules/prefer-optional-chain.mdx
- packages/eslint-plugin/tests/docs-eslint-output-snapshots/prefer-optional-chain.shot
Since only the `foo.a` part is relevant, I removed the rest.
💖
> docs(eslint-plugin): [prefer-optional-chain] remove unnecessary docs chainings

- docs/packages/ESLint_Plugin.mdx
Adds a note just to the docs in `eslint-plugin`. `parser` is used in more places, so I left it alone.
💖
> docs: mention eslint-plugin is implicit with flat config

- packages/eslint-plugin/docs/rules/prefer-for-of.mdx
As a nice side effect, this reduces the _"Intentionally Omitted: When Not To Use It"_ comments from 7 to 6.
💖
> docs(eslint-plugin): [prefer-for-of] mention DOM elements and lib: dom.iterable

- packages/eslint-plugin/src/rules/no-deprecated.ts
- packages/eslint-plugin/tests/rules/no-deprecated.test.ts
PR enhances the `no-deprecated` ESLint rule to better handle `TSImportEqualsDeclaration`, specifically cases like `export import Bar = Foo;`
> fix(eslint-plugin): [no-deprecated] ignore deprecated `export import`s

- packages/ast-spec/src/expression/UnaryExpression/spec.ts
- packages/ast-spec/src/type/TSLiteralType/spec.ts
From @bradzacher's proposal in #11587:
- Remove `UpdateExpression` from the type
- Refine the `Literal` union to just the valid literals
- Refine the `UnaryExpression` to just the valid operators
> fix(ast-spec): cleanup `TSLiteralType`
